In [1]:
import os
import numpy as np
import pandas as pd

# Paths: notebook is in zavala_electricity_market, data in dataset/IM-3-GO-WEST
# Run from project root (prj_market) or from zavala_electricity_market
_cwd = os.getcwd()
if os.path.basename(_cwd) == "zavala_electricity_market":
    BASE_DIR = os.path.dirname(_cwd)
else:
    BASE_DIR = _cwd
DATA_DIR = os.path.join(BASE_DIR, "dataset", "IM-3-GO-WEST")
if not os.path.isdir(DATA_DIR):
    DATA_DIR = os.path.join(_cwd, "dataset", "IM-3-GO-WEST")

# Ensure zavala_electricity_market is on path (when running from project root)
import sys
ZAVALA_DIR = os.path.join(BASE_DIR, "zavala_electricity_market")
if os.path.isdir(ZAVALA_DIR) and ZAVALA_DIR not in sys.path:
    sys.path.insert(0, ZAVALA_DIR)

# --- Minimal customization for current repo layout ---

# 1) If the original DATA_DIR doesn't exist, try archive/dataset/IM-3-GO-WEST
if not os.path.isdir(DATA_DIR):
    alt_data_dir = os.path.join(BASE_DIR, "archive", "dataset", "IM-3-GO-WEST")
    if os.path.isdir(alt_data_dir):
        DATA_DIR = alt_data_dir

# 2) If ZAVALA_DIR isn't a valid dir (e.g. code is at repo root),
#    fall back to BASE_DIR itself when it has zavala_funcs.py
if not os.path.isdir(ZAVALA_DIR):
    repo_root_candidate = BASE_DIR
    if os.path.isfile(os.path.join(repo_root_candidate, "zavala_funcs.py")):
        if repo_root_candidate not in sys.path:
            sys.path.insert(0, repo_root_candidate)
        ZAVALA_DIR = repo_root_candidate

print("Using DATA_DIR:", DATA_DIR)
print("Using ZAVALA_DIR:", ZAVALA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

from zavala_funcs import (
    zavala,
    zavala_cvar,
    zavala_deterministic_da,
    zavala_rt_energy_only,
    expected_caps_from_scenarios,
    price_distortion,
    probability_feasible,
    expected_cumulative_regret,
    compute_social_surplus,
    tail_worst_indices_by_value,
    _stack_rt,
)

print("Data dir:", DATA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

Using DATA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Using ZAVALA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']
Data dir: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']

In [2]:
# Load nodal time series (rows = time, columns = bus_XXXXX)
solar = pd.read_csv(os.path.join(DATA_DIR, "nodal_solar.csv"))
wind = pd.read_csv(os.path.join(DATA_DIR, "nodal_wind.csv"))
load_df = pd.read_csv(os.path.join(DATA_DIR, "nodal_load.csv"))
thermal_df = pd.read_csv(os.path.join(DATA_DIR, "thermal_gens.csv"))

T = len(solar)
assert len(wind) == T and len(load_df) == T, "Solar, wind, load must have same length"
print(f"Time steps: {T}")
print(f"Solar columns: {solar.shape[1]}, Wind: {wind.shape[1]}, Load: {load_df.shape[1]}")
print(f"Thermal generators: {len(thermal_df)}")

Time steps: 8760
Solar columns: 125, Wind: 125, Load: 125
Thermal generators: 280

In [3]:
# Choose buses with non-trivial solar: columns with max > threshold
solar_cols = [c for c in solar.columns if solar[c].max() > 50]
wind_cols = [c for c in wind.columns if wind[c].max() > 50]
# Pick x solar and y wind (unreliable)
num_solar, num_wind = 9, 9
num_thermal = 9
solar_buses = solar_cols[:num_solar] if len(solar_cols) >= num_solar else list(solar.columns[:num_solar])
wind_buses = wind_cols[:num_wind] if len(wind_cols) >= num_wind else list(wind.columns[:num_wind])

# Reliable: aggregate thermal by bus, pick 4 buses with largest capacity
thermal_by_bus = thermal_df.groupby("Bus")["Max_Cap"].sum().sort_values(ascending=False)
thermal_buses_numeric = list(thermal_by_bus.head(num_thermal).index)  # e.g. [408441, 135041, ...]
thermal_bus_cols = [f"bus_{b}" for b in thermal_buses_numeric]  # for load alignment if needed

# Load: use total system load (sum over all buses)
load_total = load_df.sum(axis=1).values  # (T,)

print("Solar buses (unreliable):", solar_buses)
print("Wind buses (unreliable):", wind_buses)
print("Thermal buses (reliable):", thermal_buses_numeric)
print("Load: system total (sum over all buses)")

Solar buses (unreliable): ['bus_100931', 'bus_200261', 'bus_201361', 'bus_204901', 'bus_211211', 'bus_230601', 'bus_232301', 'bus_232631', 'bus_251601']
Wind buses (unreliable): ['bus_100931', 'bus_102281', 'bus_105701', 'bus_106771', 'bus_134461', 'bus_135041', 'bus_211211', 'bus_211651', 'bus_251601']
Thermal buses (reliable): [500991, 605141, 408441, 261001, 403691, 261331, 606631, 280991, 102281]
Load: system total (sum over all buses)

In [4]:
# Filter thermal_df for the selected buses
selected_buses = [500991, 605141, 408441, 261001]
thermal_selected = thermal_df[thermal_df['Bus'].isin(selected_buses)]
display(thermal_selected)

,Name,Bus,Fuel,Max_Cap,Min_Cap,Heat_Rate
0,PHOENIX_Nuc,408441,NUC (Nuclear),4209.60,1046.90,8.530000
1,TONOPAH_NG,408441,NG (Natural Gas),1325.10,393.07,4.177264
2,PHOENIX_NG,408441,NG (Natural Gas),1207.38,449.72,3.622784
28,BRUSH_C,605141,BIT (Bituminous Coal),552.30,78.79,8.941106
29,WELLINGTON_C,605141,BIT (Bituminous Coal),800.40,247.36,8.242654
30,DENVER_C,605141,BIT (Bituminous Coal),586.31,164.07,7.933221
31,KEENESBURG_NG,605141,NG (Natural Gas),685.11,246.77,5.015047
32,BOULDER_C,605141,BIT (Bituminous Coal),251.00,55.58,8.227582
33,PLATTEVILLE_NG,605141,NG (Natural Gas),1185.48,481.17,2.758167
34,AURORA_NG,605141,NG (Natural Gas),397.80,147.60,4.898308
35,COMMERCECITY_NG,605141,NG (Natural Gas),154.20,29.25,4.799750
36,DENVER_NG,605141,NG (Natural Gas),269.01,54.48,3.526185
37,FORTLUPTON_NG,605141,NG (Natural Gas),497.70,120.82,4.718237
38,BURLINGTON_C,605141,BIT (Bituminous Coal),129.40,47.19,7.651625
39,FREDERICK_NG,605141,NG (Natural Gas),394.00,136.49,2.436760
40,BRUSH_NG,605141,NG (Natural Gas),597.22,156.56,3.038616
41,LIMON_NG,605141,NG (Natural Gas),154.20,37.06,4.622871
42,LAMAR_C,605141,BIT (Bituminous Coal),43.50,17.89,7.974531
43,CHEYENNE_NG,605141,NG (Natural Gas),139.99,33.48,4.731375
55,CASTLEDALE_C,500991,BIT (Bituminous Coal),1577.19,296.35,8.900558
56,HUNTINGTON_C,500991,BIT (Bituminous Coal),1037.30,382.51,8.612997
57,OREM_NG,500991,NG (Natural Gas),1392.48,370.22,3.543914
58,MONA_NG,500991,NG (Natural Gas),648.99,208.10,5.030309
59,KEMMERER_C,500991,BIT (Bituminous Coal),831.99,304.11,8.195294
60,HELPER_C,500991,BIT (Bituminous Coal),208.60,49.90,8.192120
61,SALTLAKECITY_NG,500991,NG (Natural Gas),783.49,218.84,3.554682
62,PAYSON_NG,500991,NG (Natural Gas),140.00,43.07,3.959980
63,SUNNYSIDE_C,500991,BIT (Bituminous Coal),58.10,6.34,8.114105
64,MAGNA_C,500991,BIT (Bituminous Coal),213.80,41.00,7.651219
65,BOUNTIFUL_NG,500991,NG (Natural Gas),30.39,8.90,2.977745
77,SUNCITY_NG,261001,NG (Natural Gas),819.00,228.42,2.720162
78,REDONDOBEACH_NG,261001,NG (Natural Gas),1316.40,454.78,5.271419
79,LONGBEACH_NG,261001,NG (Natural Gas),2173.98,657.33,4.487376
80,PLAYADELREY_NG,261001,NG (Natural Gas),823.20,271.80,5.154075
81,HUNTINGTONBEACH_NG,261001,NG (Natural Gas),436.00,100.93,2.516905
82,WILMINGTON_NG,261001,NG (Natural Gas),548.11,163.17,5.168842
83,CARSON_NG,261001,NG (Natural Gas),405.00,135.72,3.373920

Debug Logs

In [5]:
# For diagnostics: breakdown of DA and RT allocations
def _log(msg, logfile=None):
    if logfile is None:
        print(msg)
    else:
        with open(logfile, "a", encoding="utf-8") as f:
            f.write(str(msg) + "\n")

def _tech_breakdown_da(g_da):
    g_da = np.asarray(g_da, dtype=float)
    return {
        "solar": g_da[:3].sum(),
        "wind": g_da[3:6].sum(),
        "thermal": g_da[6:10].sum(),
        "total": g_da.sum(),
    }

def _tech_breakdown_rt(G_rt, probs=None):
    G_rt = np.asarray(G_rt, dtype=float)  # shape (S, 10)
    solar = G_rt[:, :3].sum(axis=1)
    wind = G_rt[:, 3:6].sum(axis=1)
    thermal = G_rt[:, 6:10].sum(axis=1)
    total = G_rt.sum(axis=1)

    if probs is None:
        return {
            "solar": solar.mean(),
            "wind": wind.mean(),
            "thermal": thermal.mean(),
            "total": total.mean(),
        }

    probs = np.asarray(probs, dtype=float)
    return {
        "solar": np.dot(probs, solar),
        "wind": np.dot(probs, wind),
        "thermal": np.dot(probs, thermal),
        "total": np.dot(probs, total),
    }

def _print_case_diag(name, probs, g_da, d_da, G_rt, D_rt, pi, Pi,
                     n_solar, n_wind, n_thermal, logfile=None):
    g_da = np.asarray(g_da, dtype=float)
    d_da = np.asarray(d_da, dtype=float)
    G_rt = np.asarray(G_rt, dtype=float)
    D_rt = np.asarray(D_rt, dtype=float)
    probs = np.asarray(probs, dtype=float)
    Pi = np.asarray(Pi, dtype=float)

    exp_rt = np.dot(probs, G_rt)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    da_alloc = {
        "solar": g_da[solar_slice].sum(),
        "wind": g_da[wind_slice].sum(),
        "thermal": g_da[thermal_slice].sum(),
        "total": g_da.sum(),
    }
    rt_alloc = {
        "solar": exp_rt[solar_slice].sum(),
        "wind": exp_rt[wind_slice].sum(),
        "thermal": exp_rt[thermal_slice].sum(),
        "total": exp_rt.sum(),
    }

    da_load = float(d_da.sum())
    exp_rt_load = float(np.dot(probs, D_rt.sum(axis=1)))

    _log(f"\n===== {name} =====", logfile)
    _log(f"DA price pi: {float(pi):.6f}", logfile)
    _log(f"E[RT price]: {float(np.dot(probs, Pi)):.6f}", logfile)
    _log(f"DA load: {da_load:.6f}", logfile)
    _log(f"E[RT load]: {exp_rt_load:.6f}", logfile)
    _log("DA allocation by tech: " + str({k: round(v, 4) for k, v in da_alloc.items()}), logfile)
    _log("Expected RT allocation by tech: " + str({k: round(v, 4) for k, v in rt_alloc.items()}), logfile)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "DA": g_da,
        "E_RT": exp_rt,
        "RT_minus_DA": exp_rt - g_da,
    })
    _log(df.to_string(index=False), logfile)
    
def _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i, n_solar, n_wind, n_thermal, logfile=None):
    z = np.asarray(z_g_i, dtype=float)
    c = np.asarray(cvar_g_i, dtype=float)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "stoch_DA": z,
        "cvar_DA": c,
        "cvar_minus_stoch": c - z,
    })

    _log("\n===== CVaR - Stochastic DA difference =====", logfile)
    _log(df.to_string(index=False), logfile)
    _log("Tech-level difference: " + str({
        "solar": round((c[solar_slice] - z[solar_slice]).sum(), 4),
        "wind": round((c[wind_slice] - z[wind_slice]).sum(), 4),
        "thermal": round((c[thermal_slice] - z[thermal_slice]).sum(), 4),
        "total": round((c - z).sum(), 4),
    }), logfile)

In [6]:
# Initialize log files
log_dir = "logs"
os.makedirs(log_dir, exist_ok=True)

debug_log = os.path.join(log_dir, "zavala_debug_log.txt")
with open(debug_log, "w", encoding="utf-8") as f:
    f.write("Zavala diagnostics log\n")

Build Real Data

In [7]:
def build_real_data_instance(solar_df, wind_df, load_total_vec, thermal_by_bus, thermal_buses_numeric,
                              solar_buses, wind_buses, start_idx, num_scenarios, rng=None):
    """
    Build (probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar) from real data for one time window.
    - start_idx: first time index
    - num_scenarios: number of consecutive time steps (scenarios)
    """
    if rng is None:
        rng = np.random.default_rng()
    end_idx = start_idx + num_scenarios
    S = num_scenarios

    # Scenario probabilities: near-uniform (same idea as s_real10_mix)
    kappa = 1500.0
    alpha = np.full(S, kappa / S)
    probs = rng.dirichlet(alpha)
    probs = probs / probs.sum()

    # Marginal costs: cheap for unreliable (solar/wind), higher for reliable (thermal)
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_unrel = n_solar + n_wind
    n_rel = len(thermal_buses_numeric)

    mc_unrel = rng.uniform(8.0, 14.0, size=n_unrel)
    mc_rel = rng.uniform(35.0, 55.0, size=n_rel)
    mc_g_i = np.concatenate([mc_unrel, mc_rel]).astype(float)

    # Single inelastic load (VOLL)
    mv_d_j = np.array([1000.0], dtype=float)

    # Generator capacities per scenario (S x 10)
    # Columns 0..2: solar, 3..5: wind, 6..9: thermal (constant)
    solar_vals = solar_df.loc[start_idx:end_idx - 1, solar_buses].values  # (S, 3)
    wind_vals = wind_df.loc[start_idx:end_idx - 1, wind_buses].values    # (S, 3)
    unrel_caps = np.clip(np.hstack([solar_vals, wind_vals]), 0.0, None)  # (S, 6)

    rel_caps = np.array([thermal_by_bus[b] for b in thermal_buses_numeric], dtype=float)
    rel_caps = np.broadcast_to(rel_caps, (S, len(thermal_buses_numeric)))  # (S, 4) constant across scenarios

    g_i_bar = np.hstack([unrel_caps, rel_caps])  # (S, 10)

    # Demand: system total load for each scenario (S x 1)
    d_j_bar = load_total_vec[start_idx:end_idx].reshape(-1, 1).astype(float)
    d_j_bar = np.clip(d_j_bar, 1e-6, None)  # avoid zeros

    return probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar

In [8]:
# Quick sanity check: one small window
NUM_SCENARIOS = 500
rng = np.random.default_rng(42)
probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
    solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
    solar_buses, wind_buses, start_idx=0, num_scenarios=min(NUM_SCENARIOS, T), rng=rng
)
print("probs.shape:", probs.shape, "sum:", probs.sum())
print("g_i_bar.shape:", g_i_bar.shape)
print("d_j_bar.shape:", d_j_bar.shape)
print("Unreliable (solar+wind) sample mean:", g_i_bar[:, :6].mean(axis=0))
print("Reliable (thermal) constant:", g_i_bar[0, 6:])
print("Load sample:", d_j_bar[:5].ravel())

probs.shape: (500,) sum: 1.0
g_i_bar.shape: (500, 27)
d_j_bar.shape: (500, 1)
Unreliable (solar+wind) sample mean: [ 67.33335058  17.28        28.36311076 390.34965713 131.82143061
  24.22398934]
Reliable (thermal) constant: [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.26796677e+03
 2.58000000e+02 4.17920476e+02 2.42095982e+01 2.93740174e+02
 4.60995965e+02 6.63495200e+01 1.68442245e+01 6.00000000e-01
 6.92233000e+03 6.83762000e+03 6.74208000e+03 6.52169000e+03
 4.90857000e+03 4.80050000e+03 4.64808000e+03 4.38565000e+03
 4.24913000e+03]
Load sample: [75073. 72985. 71226. 70105. 69772.]

In [9]:
def run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=None):
    """Run stochastic, CVaR, and deterministic Zavala for one instance. Returns dict of metrics.
    Same logic as run_zavala.py, no changes to external files.
    """
    # ----- Stochastic Zavala -----
    z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi = zavala(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    prob_f = probability_feasible(probs, z_g_i, z_d_j, g_i_bar, d_j_bar)
    z_dist = price_distortion(probs, z_pi, z_Pi)
    z_reg = expected_cumulative_regret(probs, z_g_i, z_d_j, z_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_stoch = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=z_g_i, d_da=z_d_j, G_rt=Z_G, D_rt=Z_D)

    # # ----- CVaR Zavala -----
    cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi, _ = zavala_cvar(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    cvar_dist = price_distortion(probs, cvar_pi, cvar_Pi)
    cvar_reg = expected_cumulative_regret(probs, cvar_g_i, cvar_d_j, cvar_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_cvar = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=cvar_g_i, d_da=cvar_d_j, G_rt=C_G, D_rt=C_D)

    # ----- Deterministic (expected capacities) -----
    gbar_det, dbar_det = expected_caps_from_scenarios(probs, g_i_bar, d_j_bar)
    g_det, d_det, pi_det = zavala_deterministic_da(mc_g_i, mv_d_j, gbar_det, dbar_det)
    G_det_list, D_det_list, Pi_det_list = [], [], []
    for p in range(len(probs)):
        Gp, Dp, Pi_p = zavala_rt_energy_only(mc_g_i, mv_d_j, g_det, d_det, g_i_bar[p], d_j_bar[p])
        G_det_list.append(Gp)
        D_det_list.append(Dp)
        Pi_det_list.append(Pi_p)
    G_det_rt, D_det_rt = _stack_rt(G_det_list, D_det_list)
    Pi_det = np.array(Pi_det_list)
    det_dist = price_distortion(probs, pi_det, Pi_det)
    det_reg = expected_cumulative_regret(probs, g_det, d_det, pi_det, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_det = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=g_det, d_da=d_det, G_rt=G_det_rt, D_rt=D_det_rt)

    # ----- Tail metrics (5% worst by high neg-surplus) -----
    tail = 0.05
    stoch_tail_idx = tail_worst_indices_by_value(ss_stoch["ss_per_scenario"], probs, tail=tail, worst="high")
    cvar_tail_idx = tail_worst_indices_by_value(ss_cvar["ss_per_scenario"], probs, tail=tail, worst="high")
    det_tail_idx = tail_worst_indices_by_value(ss_det["ss_per_scenario"], probs, tail=tail, worst="high")

    stoch_tail_welfare = -np.mean(ss_stoch["ss_per_scenario"][stoch_tail_idx])
    cvar_tail_welfare = -np.mean(ss_cvar["ss_per_scenario"][cvar_tail_idx])
    det_tail_welfare = -np.mean(ss_det["ss_per_scenario"][det_tail_idx])

    stoch_tail_dist = np.mean(np.abs(z_pi - np.array(z_Pi)[stoch_tail_idx]))
    cvar_tail_dist = np.mean(np.abs(cvar_pi - np.array(cvar_Pi)[cvar_tail_idx]))
    det_tail_dist = np.mean(np.abs(pi_det - Pi_det[det_tail_idx]))

    # Log diagnostics/output results analysis
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_thermal = len(thermal_buses_numeric)

    _print_case_diag("Stochastic", probs, z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("CVaR", probs, cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("Deterministic", probs, g_det, d_det, G_det_rt, D_det_rt, pi_det, Pi_det,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i,
                            n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)

    return {
        "prob_feasible": prob_f,
        "stoch_distortion": z_dist, "stoch_regret": z_reg, "stoch_ss": ss_stoch["E_social_surplus"],
        "stoch_tail_welfare": stoch_tail_welfare, "stoch_tail_distortion": stoch_tail_dist,
        "cvar_distortion": cvar_dist, "cvar_regret": cvar_reg, "cvar_ss": ss_cvar["E_social_surplus"],
        "cvar_tail_welfare": cvar_tail_welfare, "cvar_tail_distortion": cvar_tail_dist,
        "det_distortion": det_dist, "det_regret": det_reg, "det_ss": ss_det["E_social_surplus"],
        "det_tail_welfare": det_tail_welfare, "det_tail_distortion": det_tail_dist,
    }

In [10]:
NUM_INSTANCES = 10
NUM_SCENARIOS = 500
rng = np.random.default_rng(2025)

max_start = T - NUM_SCENARIOS
if max_start <= 0:
    raise ValueError(f"Need at least {NUM_SCENARIOS} time steps; have {T}")

# Random start indices for each instance (non-overlapping or random)
start_indices = rng.integers(0, max_start + 1, size=NUM_INSTANCES)

results_list = []
for i in range(NUM_INSTANCES):
    start = int(start_indices[i])
    probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
        solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
        solar_buses, wind_buses, start_idx=start, num_scenarios=NUM_SCENARIOS, rng=rng
    )
    print(f"the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are {probs.shape}, {mc_g_i.shape}, {mv_d_j.shape}, {g_i_bar.shape}, {d_j_bar.shape}")
    res = run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=debug_log)
    results_list.append(res)
    print(f"Instance {i+1}/{NUM_INSTANCES} (start={start}) done.")

the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:18:18 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:18:22 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:18:22 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:18:22 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:18:22 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:18:24 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:18:24 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:18:24 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:18:24 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:18:31 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:19:16 PM: Applying reduction GUROBI
(CVXPY) May 03 05:19:17 PM: Finished problem compilation (took 5.469e+01 seconds).
(CVXPY) May 03 05:19:17 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter Username
Set parameter LicenseID to value 2797952
Academic license - for non-commercial use only - expires 2027-03-25
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0xe0df2598
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2142 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39886 columns, 105602 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.760e+04
 Factor NZ  : 1.122e+05 (roughly 30 MB of memory)
 Factor Ops : 1.164e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.20469411e+07 -4.94275391e+08  1.15e+06 6.21e+02  6.12e+05     0s
   1  -2.87178824e+07 -2.87720447e+08  5.82e+04 3.57e+01  3.90e+04     0s
   2  -2.94285202e+07 -9.37163809e+07  2.69e+03 7.52e+00  3.62e+03     0s
   3  -4.26084601e+07 -5.46578445e+07  2.05e+02 2.10e+00  4.00e+02     0s
   4  -4.26084601e+07 -5.46578445e+07  2.05e+02 2.10e+00  4.00e+02     0s
   5  -3.20487628e+07 -3.45183109e+10  1.15e+06 1.13e-13  4.51e+07     0s
   6  -1.04470909e+07 -3.83750794e+10  1.96e+04 2.93e+01  3.11e+06     0s
   7  -6.05835847e+06 -2.73250537e+09  2.87e+02 3.86e+00  9.96e+04     0s
   8  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.56e+03     0s
   9  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.56e+03     0s
  10  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.56e+03     0s
  11  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.56e+03     0s
  12  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.55e+03     0s
  13  -1.80337072e+07 -1.02132176e+08  1.35e-08 3.71e+00  2.55e+03     0s

Barrier performed 13 iterations in 0.38 seconds (0.35 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10256   -5.1441678e+07   0.000000e+00   0.000000e+00      1s

Solved in 10256 iterations and 1.12 seconds (1.92 work units)
Optimal objective -5.144167783e+07

(CVXPY) May 03 05:19:19 PM: Problem status: optimal
(CVXPY) May 03 05:19:19 PM: Optimal value: -5.144e+07
(CVXPY) May 03 05:19:19 PM: Compilation took 5.469e+01 seconds
(CVXPY) May 03 05:19:19 PM: Solver (including time spent in interface) took 1.348e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:19:27 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:19:31 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:19:31 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:19:31 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:19:31 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:19:35 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:19:35 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:19:35 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:19:42 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:19:57 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:21:50 PM: Applying reduction GUROBI
(CVXPY) May 03 05:21:50 PM: Finished problem compilation (took 1.388e+02 seconds).
(CVXPY) May 03 05:21:50 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0xc2afaecd
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2142 columns
Presolve time: 0.09s
Presolved: 57001 rows, 68387 columns, 226176 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.413e+05
 Factor NZ  : 3.133e+05 (roughly 50 MB of memory)
 Factor Ops : 2.490e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.97399654e+08 -1.01402702e+09  2.31e+07 1.47e+01  4.61e+06     0s
   1   2.65246672e+08 -4.31932896e+08  8.44e+04 3.02e+01  2.47e+05     0s
   2   2.65246043e+08 -4.31934977e+08  8.44e+04 3.13e+01  2.47e+05     0s
   3   2.65246043e+08 -4.31934977e+08  8.44e+04 3.13e+01  2.47e+05     0s
   4   3.97358736e+08 -3.62658650e+11  2.31e+07 6.40e+00  1.73e+09     0s
   5   6.43150332e+08 -3.12656893e+11  1.15e+05 1.51e+01  5.67e+07     0s
   6   6.41624547e+08 -2.08986345e+10  2.63e+03 1.38e+00  1.11e+06     0s
   7   6.41665257e+08 -2.08986022e+10  2.63e+03 7.69e+02  1.11e+06     0s
   8   6.41665257e+08 -2.08986022e+10  2.63e+03 7.69e+02  1.11e+06     0s
   9   6.41665257e+08 -2.08986022e+10  2.63e+03 7.69e+02  1.11e+06     0s
  10   6.41665257e+08 -2.08986022e+10  2.63e+03 7.69e+02  1.11e+06     1s
  11   3.97358736e+08 -3.62658650e+11  2.31e+07 6.40e+00  1.73e+09     1s
  12   1.25528062e+08 -3.98697339e+10  2.68e+05 7.06e+01  7.55e+07     1s
  13   5.12379426e+07 -1.00117400e+09  5.83e+03 2.84e+00  6.66e+05     1s
  14   2.45459912e+06 -9.83593227e+07  2.76e+02 5.61e+00  3.61e+04     1s
  15   2.45564662e+06 -9.83586466e+07  2.76e+02 6.78e+01  3.58e+04     1s
  16   2.45564662e+06 -9.83586466e+07  2.76e+02 6.78e+01  3.58e+04     1s
  17   2.46576884e+06 -9.83480916e+07  2.76e+02 2.42e+03  3.26e+04     1s
  18  -3.05738797e+07 -6.53508646e+07  8.37e+01 7.42e+02  6.87e+03     1s
  19  -3.05705194e+07 -6.53469657e+07  8.37e+01 7.89e+02  6.65e+03     1s
  20  -3.05714864e+07 -6.53477503e+07  8.37e+01 7.76e+02  6.61e+03     1s
  21  -3.05699168e+07 -6.53451615e+07  8.37e+01 6.10e+02  6.46e+03     1s
  22  -3.05595654e+07 -6.53451615e+07  8.37e+01 6.10e+02  6.29e+03     1s
  23  -3.05595654e+07 -6.53451615e+07  8.37e+01 6.10e+02  6.29e+03     1s
  24  -3.05595654e+07 -6.53451615e+07  8.37e+01 6.10e+02  6.29e+03     1s
  25  -3.05592722e+07 -6.53446919e+07  8.37e+01 5.67e+02  6.16e+03     1s
  26  -3.05596657e+07 -6.53450954e+07  8.37e+01 5.97e+02  6.02e+03     1s
  27  -3.05589593e+07 -6.53447171e+07  8.37e+01 6.11e+02  5.88e+03     1s
  28  -3.05589593e+07 -6.53447171e+07  8.37e+01 6.11e+02  5.88e+03     1s
  29  -3.05589593e+07 -6.53447171e+07  8.37e+01 6.11e+02  5.88e+03     1s
  30  -3.05590532e+07 -6.53447171e+07  8.37e+01 6.11e+02  5.82e+03     1s
  31  -3.05601708e+07 -6.53452674e+07  8.37e+01 6.75e+02  5.74e+03     1s
  32  -3.05601708e+07 -6.53452674e+07  8.37e+01 6.75e+02  5.74e+03     1s

Barrier performed 32 iterations in 1.48 seconds (1.83 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   30222   -5.6256593e+07   0.000000e+00   0.000000e+00      4s

Solved in 30222 iterations and 4.39 seconds (9.85 work units)
Optimal objective -5.625659345e+07

(CVXPY) May 03 05:21:56 PM: Problem status: optimal
(CVXPY) May 03 05:21:56 PM: Optimal value: -5.626e+07
(CVXPY) May 03 05:21:56 PM: Compilation took 1.388e+02 seconds
(CVXPY) May 03 05:21:56 PM: Solver (including time spent in interface) took 4.717e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 1/10 (start=3696) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:22:02 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:22:04 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:22:04 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:22:04 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:22:04 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:22:06 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:22:06 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:22:06 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:22:06 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:22:11 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:22:59 PM: Applying reduction GUROBI
(CVXPY) May 03 05:22:59 PM: Finished problem compilation (took 5.515e+01 seconds).
(CVXPY) May 03 05:22:59 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0xca670f1b
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2801 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39227 columns, 103625 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.562e+04
 Factor NZ  : 1.103e+05 (roughly 30 MB of memory)
 Factor Ops : 1.153e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.04153231e+07 -4.90922118e+08  9.25e+05 6.19e+02  5.06e+05     0s
   1  -2.87282711e+07 -2.81290584e+08  3.67e+04 6.02e+01  4.25e+04     0s
   2  -2.93199903e+07 -7.53738617e+07  2.47e+03 1.11e+01  3.07e+03     0s
   3  -4.38112431e+07 -5.31644656e+07  9.37e+01 1.05e+01  3.62e+02     0s
   4  -4.38112431e+07 -5.31644656e+07  9.37e+01 1.05e+01  3.62e+02     0s
   5  -3.04172750e+07 -3.34296388e+10  9.26e+05 1.10e-13  3.63e+07     0s
   6  -1.30734000e+07 -3.51455885e+10  1.22e+04 2.26e+01  2.24e+06     0s
   7  -1.06040075e+07 -1.29626607e+09  1.61e+02 1.47e+00  4.13e+04     0s
   8  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s
   9  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s
  10  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s
  11  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s
  12  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s
  13  -2.60531425e+07 -1.44323549e+08  2.68e-01 1.71e+01  3.51e+03     0s

Barrier performed 13 iterations in 0.40 seconds (0.34 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11640   -5.0046442e+07   0.000000e+00   0.000000e+00      1s

Solved in 11640 iterations and 1.21 seconds (2.27 work units)
Optimal objective -5.004644156e+07

(CVXPY) May 03 05:23:01 PM: Problem status: optimal
(CVXPY) May 03 05:23:01 PM: Optimal value: -5.005e+07
(CVXPY) May 03 05:23:01 PM: Compilation took 5.515e+01 seconds
(CVXPY) May 03 05:23:01 PM: Solver (including time spent in interface) took 1.406e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:23:09 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:23:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:23:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:23:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:23:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:23:18 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:23:18 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:23:18 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:23:23 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:23:36 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:25:32 PM: Applying reduction GUROBI
(CVXPY) May 03 05:25:32 PM: Finished problem compilation (took 1.381e+02 seconds).
(CVXPY) May 03 05:25:32 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0x33a23d9c
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [8e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2801 columns
Presolve time: 0.10s
Presolved: 57001 rows, 67728 columns, 222222 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.334e+05
 Factor NZ  : 3.054e+05 (roughly 50 MB of memory)
 Factor Ops : 2.424e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.96295820e+08 -9.97767960e+08  1.80e+07 1.28e+01  7.44e+06     0s
   1   1.96383981e+08 -3.81651062e+08  7.86e+04 5.01e+00  3.91e+05     0s
   2   1.96383981e+08 -3.81651062e+08  7.86e+04 5.01e+00  3.91e+05     0s
   3   2.96295820e+08 -1.75368975e+11  1.80e+07 1.28e+01  1.36e+09     0s
   4   4.35429821e+08 -1.38202972e+11  1.89e+05 1.09e+02  2.36e+08     0s
   5   4.39733195e+08 -2.01719784e+10  1.24e+04 1.02e+01  2.24e+07     0s
   6   4.39735042e+08 -2.01719647e+10  1.24e+04 2.79e+02  2.24e+07     0s
   7   5.02195940e+08 -2.07555635e+10  9.88e+03 2.35e+02  2.29e+07     0s
   8   4.83928403e+08 -8.36604624e+08  1.42e+02 4.66e+00  4.19e+05     0s
   9   4.83928403e+08 -8.36604624e+08  1.42e+02 4.66e+00  4.19e+05     0s
  10   4.83928403e+08 -8.36604624e+08  1.42e+02 4.66e+00  4.19e+05     0s
  11   2.96295820e+08 -1.75368975e+11  1.80e+07 1.28e+01  1.36e+09     1s
  12   1.08715656e+08 -1.31625715e+10  2.92e+05 6.94e+01  4.81e+07     1s
  13   3.04776899e+07 -3.42317982e+08  5.10e+03 5.38e+00  3.51e+05     1s
  14   2.14439948e+06 -1.01896230e+08  7.19e+02 3.57e+00  6.66e+04     1s
  15  -2.39208196e+07 -7.22320856e+07  2.82e+02 1.91e+01  2.06e+04     1s
  16  -2.39205334e+07 -7.22300780e+07  2.82e+02 5.27e+01  2.04e+04     1s
  17  -2.39205334e+07 -7.22300780e+07  2.82e+02 5.27e+01  2.04e+04     1s
  18  -2.39212934e+07 -7.22273008e+07  2.82e+02 3.61e+01  2.03e+04     1s
  19  -2.39212934e+07 -7.22273008e+07  2.82e+02 3.61e+01  2.03e+04     1s
  20  -2.39212934e+07 -7.22273008e+07  2.82e+02 3.61e+01  2.03e+04     1s

Barrier performed 20 iterations in 0.88 seconds (0.99 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   58566   -5.4837688e+07   0.000000e+00   0.000000e+00      5s

Solved in 58566 iterations and 4.72 seconds (9.93 work units)
Optimal objective -5.483768849e+07

(CVXPY) May 03 05:25:39 PM: Problem status: optimal
(CVXPY) May 03 05:25:39 PM: Optimal value: -5.484e+07
(CVXPY) May 03 05:25:39 PM: Compilation took 1.381e+02 seconds
(CVXPY) May 03 05:25:39 PM: Solver (including time spent in interface) took 5.049e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 2/10 (start=8215) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:25:46 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:25:47 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:25:47 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:25:47 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:25:47 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:25:49 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:25:49 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:25:49 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:25:49 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:25:58 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:26:45 PM: Applying reduction GUROBI
(CVXPY) May 03 05:26:45 PM: Finished problem compilation (took 5.769e+01 seconds).
(CVXPY) May 03 05:26:45 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x7a99e3be
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2822 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39206 columns, 103562 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.556e+04
 Factor NZ  : 1.102e+05 (roughly 30 MB of memory)
 Factor Ops : 1.153e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.20045523e+07 -5.45534730e+08  9.25e+05 6.20e+02  5.66e+05     0s
   1  -2.80654163e+07 -2.96473265e+08  3.87e+04 3.96e+01  3.72e+04     0s
   2  -2.89760683e+07 -8.20699810e+07  2.16e+03 2.00e+01  3.22e+03     0s
   3  -4.32028294e+07 -5.24822780e+07  7.49e+01 7.12e+00  2.95e+02     0s
   4  -4.43290757e+07 -5.08177509e+07  6.16e+01 4.87e+00  1.78e+02     0s
   5  -4.43290757e+07 -5.08177509e+07  6.16e+01 4.87e+00  1.78e+02     0s
   6  -3.20067982e+07 -3.33825232e+10  9.26e+05 1.13e-13  3.63e+07     0s
   7  -1.37511803e+07 -3.51358509e+10  1.23e+04 2.22e+01  2.22e+06     0s
   8  -1.12628361e+07 -9.79332894e+08  1.25e+02 1.64e+00  2.64e+04     0s
   9  -1.12628361e+07 -9.79332894e+08  1.25e+02 1.64e+00  2.64e+04     0s
  10  -1.12628361e+07 -9.79332894e+08  1.25e+02 1.64e+00  2.64e+04     0s

Barrier performed 10 iterations in 0.29 seconds (0.27 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11532   -5.0281550e+07   0.000000e+00   0.000000e+00      1s

Solved in 11532 iterations and 1.19 seconds (2.26 work units)
Optimal objective -5.028154989e+07

(CVXPY) May 03 05:26:47 PM: Problem status: optimal
(CVXPY) May 03 05:26:47 PM: Optimal value: -5.028e+07
(CVXPY) May 03 05:26:47 PM: Compilation took 5.769e+01 seconds
(CVXPY) May 03 05:26:47 PM: Solver (including time spent in interface) took 1.392e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:26:54 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:26:58 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:26:58 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:26:58 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:26:58 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:27:01 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:27:01 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:27:01 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:27:08 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:27:22 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:29:21 PM: Applying reduction GUROBI
(CVXPY) May 03 05:29:21 PM: Finished problem compilation (took 1.436e+02 seconds).
(CVXPY) May 03 05:29:21 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0x37e7b60c
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [8e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2822 columns
Presolve time: 0.10s
Presolved: 57001 rows, 67707 columns, 222096 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.332e+05
 Factor NZ  : 3.051e+05 (roughly 50 MB of memory)
 Factor Ops : 2.422e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.20327314e+08 -1.05763671e+09  1.98e+07 1.28e+01  8.67e+06     0s
   1   2.19645750e+08 -4.23495843e+08  8.83e+04 4.49e+00  4.35e+05     0s
   2   2.19645750e+08 -4.23495843e+08  8.83e+04 4.49e+00  4.35e+05     0s
   3   3.20327314e+08 -1.75009229e+11  1.98e+07 1.28e+01  1.49e+09     0s
   4   4.97520079e+08 -1.44766582e+11  1.85e+05 1.10e+02  2.87e+08     0s
   5   5.00366738e+08 -2.10254736e+10  1.29e+04 1.05e+01  2.78e+07     0s
   6   4.82202025e+08 -6.67921202e+08  3.71e+02 8.92e+00  3.44e+05     0s
   7   4.82202025e+08 -6.67921202e+08  3.71e+02 8.92e+00  3.44e+05     0s
   8   4.82202025e+08 -6.67921202e+08  3.71e+02 8.92e+00  3.44e+05     0s
   9   4.82202025e+08 -6.67921202e+08  3.71e+02 8.92e+00  3.44e+05     0s
  10   4.82202025e+08 -6.67921202e+08  3.71e+02 8.92e+00  3.44e+05     0s
  11   3.20327314e+08 -1.75009229e+11  1.98e+07 1.28e+01  1.49e+09     1s
  12   1.14792193e+08 -1.47770707e+10  3.02e+05 6.80e+01  5.43e+07     1s
  13   3.93311975e+07 -6.07344583e+08  8.60e+03 5.97e+00  6.70e+05     1s
  14  -3.77606424e+06 -8.69693880e+07  5.80e+02 4.31e+00  4.74e+04     1s
  15  -3.60614649e+07 -6.10159286e+07  1.09e+02 2.59e+01  7.25e+03     1s
  16  -4.81157294e+07 -5.65513727e+07  4.00e+01 1.20e+01  1.45e+03     1s
  17  -5.12269670e+07 -5.57346111e+07  2.22e+01 6.62e+00  6.23e+02     1s
  18  -5.12269670e+07 -5.57346111e+07  2.22e+01 6.62e+00  6.23e+02     1s
  19  -5.12269670e+07 -5.57346111e+07  2.22e+01 6.62e+00  6.23e+02     1s

Barrier performed 19 iterations in 0.89 seconds (0.99 work units)
Sub-optimal termination - objective -5.12269670e+07

Crossover log...

   56717 DPushes remaining with DInf 0.0000000e+00                 1s
       0 DPushes remaining with DInf 0.0000000e+00                 3s

   66560 PPushes remaining with PInf 2.0242303e+01                 3s
       0 PPushes remaining with PInf 0.0000000e+00                 3s

  Push phase complete: Pinf 0.0000000e+00, Dinf 3.7343362e+03      3s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
  117454   -5.5053469e+07   0.000000e+00   3.734336e+03      3s

Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   61850   -5.5091434e+07   0.000000e+00   0.000000e+00      5s

Solved in 61850 iterations and 4.73 seconds (8.40 work units)
Optimal objective -5.509143401e+07

(CVXPY) May 03 05:29:27 PM: Problem status: optimal
(CVXPY) May 03 05:29:27 PM: Optimal value: -5.509e+07
(CVXPY) May 03 05:29:27 PM: Compilation took 1.436e+02 seconds
(CVXPY) May 03 05:29:27 PM: Solver (including time spent in interface) took 5.055e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 3/10 (start=8199) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:29:34 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:29:35 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:29:35 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:29:35 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:29:35 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:29:37 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:29:37 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:29:37 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:29:37 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:29:42 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:30:27 PM: Applying reduction GUROBI
(CVXPY) May 03 05:30:27 PM: Finished problem compilation (took 5.181e+01 seconds).
(CVXPY) May 03 05:30:27 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0xf75b7ed7
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [9e-02, 1e+05]
Presolve removed 56000 rows and 2217 columns
Presolve time: 0.08s
Presolved: 28501 rows, 39811 columns, 105377 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.738e+04
 Factor NZ  : 1.120e+05 (roughly 30 MB of memory)
 Factor Ops : 1.163e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -2.79635020e+07 -4.46607554e+08  1.08e+06 6.20e+02  5.46e+05     0s
   1  -2.61579422e+07 -2.66738740e+08  4.11e+04 3.95e+01  3.52e+04     0s
   2  -2.85344408e+07 -7.37166830e+07  3.57e+03 1.11e+01  2.98e+03     0s
   3  -4.43395114e+07 -5.34969221e+07  2.60e+02 3.80e+00  2.93e+02     0s
   4  -4.43395114e+07 -5.34969221e+07  2.60e+02 3.80e+00  2.93e+02     0s
   5  -2.79647524e+07 -3.27262369e+10  1.08e+06 1.10e-13  4.22e+07     0s
   6  -8.80707061e+06 -3.70673862e+10  1.72e+04 3.00e+01  2.96e+06     0s
   7  -5.95778556e+06 -2.25148813e+09  2.48e+02 2.78e+00  8.12e+04     0s
   8  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.76e+03     0s
   9  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.76e+03     0s
  10  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.76e+03     0s
  11  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.76e+03     0s
  12  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.75e+03     0s
  13  -1.83585482e+07 -1.35453003e+08  4.20e-02 9.67e+00  3.75e+03     0s

Barrier performed 13 iterations in 0.36 seconds (0.34 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10343   -5.0932947e+07   0.000000e+00   0.000000e+00      1s

Solved in 10343 iterations and 1.11 seconds (2.12 work units)
Optimal objective -5.093294665e+07

(CVXPY) May 03 05:30:29 PM: Problem status: optimal
(CVXPY) May 03 05:30:29 PM: Optimal value: -5.093e+07
(CVXPY) May 03 05:30:29 PM: Compilation took 5.181e+01 seconds
(CVXPY) May 03 05:30:29 PM: Solver (including time spent in interface) took 1.287e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:30:36 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:30:41 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:30:41 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:30:41 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:30:41 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:30:44 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:30:44 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:30:44 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:30:48 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:31:05 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:32:55 PM: Applying reduction GUROBI
(CVXPY) May 03 05:32:55 PM: Finished problem compilation (took 1.347e+02 seconds).
(CVXPY) May 03 05:32:55 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0xf6488b15
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [9e-02, 1e+05]
Presolve removed 84000 rows and 2217 columns
Presolve time: 0.10s
Presolved: 57001 rows, 68312 columns, 225726 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.404e+05
 Factor NZ  : 3.124e+05 (roughly 50 MB of memory)
 Factor Ops : 2.482e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.88548491e+08 -1.28589709e+09  2.08e+07 1.28e+01  5.82e+06     0s
   1   2.63655005e+08 -5.37832558e+08  8.97e+04 2.35e+01  2.94e+05     0s
   2   2.63655005e+08 -5.37832558e+08  8.97e+04 2.35e+01  2.94e+05     0s
   3   3.88548491e+08 -3.35401814e+11  2.08e+07 1.28e+01  1.56e+09     0s
   4   5.77715328e+08 -2.90149131e+11  1.86e+05 1.07e+02  2.66e+08     0s
   5   5.80910158e+08 -4.75176897e+10  1.30e+04 1.16e+01  2.91e+07     0s
   6   5.69243458e+08 -1.35186076e+09  5.53e+02 6.90e-02  2.21e+05     0s
   7   5.69243712e+08 -1.35186071e+09  5.53e+02 1.02e-01  2.21e+05     0s
   8   5.69243712e+08 -1.35186071e+09  5.53e+02 1.02e-01  2.21e+05     0s
   9   5.69243712e+08 -1.35186071e+09  5.53e+02 1.02e-01  2.21e+05     0s
  10   5.69243712e+08 -1.35186071e+09  5.53e+02 1.02e-01  2.21e+05     0s
  11   3.88548491e+08 -3.35401814e+11  2.08e+07 1.28e+01  1.56e+09     1s
  12   1.25880300e+08 -3.51003546e+10  1.96e+05 6.75e+01  6.41e+07     1s
  13   4.96552158e+07 -7.03918370e+08  3.31e+03 4.30e+00  4.45e+05     1s
  14   1.10781582e+07 -1.38412569e+08  4.72e+02 3.13e+00  6.22e+04     1s
  15  -2.17482393e+07 -7.87592830e+07  1.63e+02 8.42e+01  1.56e+04     1s
  16  -2.17487603e+07 -7.87569665e+07  1.63e+02 7.74e+01  1.52e+04     1s
  17  -2.17487603e+07 -7.87571013e+07  1.63e+02 8.87e+01  1.52e+04     1s
  18  -2.17498543e+07 -7.87580994e+07  1.63e+02 4.53e+01  1.51e+04     1s
  19  -2.17523951e+07 -7.88320513e+07  1.64e+02 7.20e+09  1.43e+04     1s
  20  -3.43748577e+07 -7.30435723e+07  7.91e+01 5.87e+09  8.90e+03     1s
  21  -3.43748577e+07 -7.30458966e+07  7.91e+01 5.87e+09  8.89e+03     1s
  22  -3.48350603e+07 -7.16053380e+07  7.04e+01 5.64e+09  7.56e+03     1s
  23  -3.48339352e+07 -7.16041653e+07  7.04e+01 5.64e+09  7.34e+03     1s
  24  -3.48339352e+07 -7.16041653e+07  7.04e+01 5.64e+09  7.34e+03     1s
  25  -3.48339352e+07 -7.16041653e+07  7.04e+01 5.64e+09  7.34e+03     1s

Barrier performed 25 iterations in 1.04 seconds (1.26 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   32988   -5.5720354e+07   0.000000e+00   0.000000e+00      5s

Solved in 32988 iterations and 4.93 seconds (11.81 work units)
Optimal objective -5.572035351e+07

(CVXPY) May 03 05:33:02 PM: Problem status: optimal
(CVXPY) May 03 05:33:02 PM: Optimal value: -5.572e+07
(CVXPY) May 03 05:33:02 PM: Compilation took 1.347e+02 seconds
(CVXPY) May 03 05:33:02 PM: Solver (including time spent in interface) took 5.252e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 4/10 (start=3155) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:33:10 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:33:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:33:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:33:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:33:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:33:15 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:33:15 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:33:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:33:15 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:33:21 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:34:11 PM: Applying reduction GUROBI
(CVXPY) May 03 05:34:11 PM: Finished problem compilation (took 5.823e+01 seconds).
(CVXPY) May 03 05:34:11 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x0f664742
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2866 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39162 columns, 103430 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.543e+04
 Factor NZ  : 1.101e+05 (roughly 30 MB of memory)
 Factor Ops : 1.152e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -2.97231791e+07 -4.41820253e+08  9.24e+05 6.19e+02  4.57e+05     0s
   1  -2.90019403e+07 -2.55228248e+08  4.10e+04 4.74e+01  3.66e+04     0s
   2  -3.02160472e+07 -7.56055312e+07  3.33e+03 1.17e+01  3.25e+03     0s
   3  -4.37274216e+07 -5.17031164e+07  1.02e+02 1.17e+01  2.71e+02     0s
   4  -4.73872085e+07 -5.00271168e+07  3.08e+01 3.53e+00  7.25e+01     0s
   5  -4.73872085e+07 -5.00271168e+07  3.08e+01 3.53e+00  7.25e+01     0s
   6  -2.97251878e+07 -3.30463008e+10  9.24e+05 1.13e-13  3.62e+07     0s
   7  -1.25143134e+07 -3.49243766e+10  1.13e+04 2.21e+01  2.19e+06     0s
   8  -1.02964968e+07 -8.64324910e+08  1.08e+02 1.20e+00  2.39e+04     0s
   9  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s
  10  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s
  11  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s
  12  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s
  13  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s
  14  -2.93235281e+07 -1.12422084e+08  5.53e+00 3.01e+01  2.19e+03     0s

Barrier performed 14 iterations in 0.39 seconds (0.36 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11518   -4.9717626e+07   0.000000e+00   0.000000e+00      1s

Solved in 11518 iterations and 1.17 seconds (2.26 work units)
Optimal objective -4.971762614e+07

(CVXPY) May 03 05:34:13 PM: Problem status: optimal
(CVXPY) May 03 05:34:13 PM: Optimal value: -4.972e+07
(CVXPY) May 03 05:34:13 PM: Compilation took 5.823e+01 seconds
(CVXPY) May 03 05:34:13 PM: Solver (including time spent in interface) took 1.352e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:34:21 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:34:25 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:34:25 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:34:25 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:34:25 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:34:28 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:34:28 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:34:28 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:34:35 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:34:48 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:36:36 PM: Applying reduction GUROBI
(CVXPY) May 03 05:36:36 PM: Finished problem compilation (took 1.314e+02 seconds).
(CVXPY) May 03 05:36:36 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0x63c6a92b
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2866 columns
Presolve time: 0.09s
Presolved: 57001 rows, 67663 columns, 221832 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.326e+05
 Factor NZ  : 3.046e+05 (roughly 50 MB of memory)
 Factor Ops : 2.417e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.24089343e+08 -1.30975597e+09  1.87e+07 1.28e+01  5.19e+06     0s
   1   2.20888101e+08 -5.03350280e+08  8.26e+04 1.06e+01  2.55e+05     0s
   2   2.20888101e+08 -5.03350280e+08  8.26e+04 1.06e+01  2.55e+05     0s
   3   3.24089343e+08 -3.45491243e+11  1.87e+07 1.28e+01  1.41e+09     0s
   4   4.98416088e+08 -2.80815123e+11  1.69e+05 1.08e+02  2.45e+08     0s
   5   5.02311586e+08 -3.59453734e+10  1.01e+04 8.58e+00  1.99e+07     0s
   6   4.87621412e+08 -9.37382988e+08  2.47e+02 1.03e-01  2.04e+05     0s
   7   4.87621412e+08 -9.37382988e+08  2.47e+02 1.03e-01  2.04e+05     0s
   8   4.87621412e+08 -9.37382988e+08  2.47e+02 1.03e-01  2.04e+05     0s
   9   4.87621412e+08 -9.37382988e+08  2.47e+02 1.03e-01  2.04e+05     0s
  10   4.87621412e+08 -9.37382988e+08  2.47e+02 1.03e-01  2.04e+05     0s
  11   3.24089343e+08 -3.45491243e+11  1.87e+07 1.28e+01  1.41e+09     1s
  12   1.17683078e+08 -2.65689516e+10  2.62e+05 7.16e+01  4.80e+07     1s
  13   3.74334471e+07 -5.63230619e+08  3.77e+03 3.49e+00  2.91e+05     1s
  14   3.79972980e+06 -1.32240783e+08  3.38e+02 3.75e+01  4.72e+04     1s
  15  -9.63565972e+06 -1.04813032e+08  2.15e+02 6.79e+01  3.01e+04     1s
  16  -3.77880459e+07 -6.23897915e+07  2.99e+01 1.71e+01  4.34e+03     1s
  17  -3.77870957e+07 -6.23875480e+07  2.99e+01 1.66e+01  4.29e+03     1s
  18  -3.77872031e+07 -6.23876901e+07  2.99e+01 3.29e+01  4.27e+03     1s
  19  -3.77877185e+07 -6.23883118e+07  2.99e+01 4.96e+01  4.25e+03     1s
  20  -3.77872902e+07 -6.23878094e+07  2.99e+01 5.78e+01  4.21e+03     1s
  21  -3.77874840e+07 -6.23880544e+07  2.99e+01 7.12e+01  4.19e+03     1s
  22  -3.77875836e+07 -6.23875435e+07  2.99e+01 6.39e+01  4.17e+03     1s
  23  -3.77878733e+07 -6.23878671e+07  2.99e+01 7.31e+01  4.16e+03     1s
  24  -3.77878733e+07 -6.23878671e+07  2.99e+01 7.31e+01  4.16e+03     1s
  25  -3.77878733e+07 -6.23878671e+07  2.99e+01 7.31e+01  4.16e+03     1s
  26  -3.77878733e+07 -6.23878671e+07  2.99e+01 7.31e+01  4.16e+03     1s

Barrier performed 26 iterations in 1.12 seconds (1.31 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   64732   -5.4493933e+07   0.000000e+00   0.000000e+00      4s

Solved in 64732 iterations and 3.67 seconds (5.82 work units)
Optimal objective -5.449393294e+07

(CVXPY) May 03 05:36:49 PM: Problem status: optimal
(CVXPY) May 03 05:36:49 PM: Optimal value: -5.449e+07
(CVXPY) May 03 05:36:49 PM: Compilation took 1.314e+02 seconds
(CVXPY) May 03 05:36:49 PM: Solver (including time spent in interface) took 1.206e+01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 5/10 (start=7877) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:36:55 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:36:57 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:36:57 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:36:57 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:36:57 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:36:59 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:36:59 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:36:59 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:36:59 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:37:04 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:37:46 PM: Applying reduction GUROBI
(CVXPY) May 03 05:37:46 PM: Finished problem compilation (took 4.925e+01 seconds).
(CVXPY) May 03 05:37:46 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x30413798
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 56000 rows and 2796 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39232 columns, 103640 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.564e+04
 Factor NZ  : 1.103e+05 (roughly 30 MB of memory)
 Factor Ops : 1.153e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.06776613e+07 -4.62965686e+08  9.77e+05 1.24e+03  1.03e+06     0s
   1  -2.73578981e+07 -2.65049447e+08  3.64e+04 6.52e+01  6.02e+04     0s
   2  -3.03488443e+07 -7.61502271e+07  2.11e+03 2.47e+01  6.06e+03     0s
   3  -4.39393132e+07 -5.37010823e+07  1.50e+02 1.98e+01  7.76e+02     0s
   4  -4.66015790e+07 -5.08309037e+07  8.03e+01 4.61e+01  2.77e+02     0s
   5  -4.83493278e+07 -5.07966948e+07  4.35e+01 1.86e+01  1.48e+02     0s
   6  -4.83493278e+07 -5.07966948e+07  4.35e+01 1.86e+01  1.48e+02     0s
   7  -3.06800100e+07 -1.62551149e+10  9.77e+05 1.14e-13  3.82e+07     0s
   8  -9.86866317e+06 -1.79618119e+10  7.79e+03 8.20e+00  1.52e+06     0s
   9  -1.19210839e+07 -9.02744369e+08  4.71e+01 1.28e+02  5.93e+04     0s
  10  -2.09807739e+07 -2.32730306e+08  1.59e+01 1.86e+01  1.37e+04     0s
  11  -2.09807739e+07 -2.32730306e+08  1.59e+01 1.86e+01  1.37e+04     0s
  12  -2.09807739e+07 -2.32730306e+08  1.59e+01 1.86e+01  1.37e+04     0s
  13  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.79e+03     0s
  14  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.58e+03     0s
  15  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.58e+03     0s
  16  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.58e+03     0s
  17  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     0s
  18  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     0s
  19  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     1s
  20  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     1s
  21  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     1s
  22  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     1s
  23  -1.26882199e+07 -1.13288879e+08  1.91e-01 1.60e+01  7.57e+03     1s

Barrier performed 23 iterations in 0.59 seconds (0.63 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11419   -5.0685493e+07   0.000000e+00   0.000000e+00      1s

Solved in 11419 iterations and 1.22 seconds (2.39 work units)
Optimal objective -5.068549327e+07

(CVXPY) May 03 05:37:48 PM: Problem status: optimal
(CVXPY) May 03 05:37:48 PM: Optimal value: -5.069e+07
(CVXPY) May 03 05:37:48 PM: Compilation took 4.925e+01 seconds
(CVXPY) May 03 05:37:48 PM: Solver (including time spent in interface) took 1.402e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:37:56 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:38:00 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:38:00 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:38:00 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:38:00 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:38:04 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:38:04 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:38:04 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:38:09 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:38:22 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:40:18 PM: Applying reduction GUROBI
(CVXPY) May 03 05:40:18 PM: Finished problem compilation (took 1.376e+02 seconds).
(CVXPY) May 03 05:40:18 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0x367918b0
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [5e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 84000 rows and 2796 columns
Presolve time: 0.11s
Presolved: 57001 rows, 67733 columns, 222252 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.335e+05
 Factor NZ  : 3.054e+05 (roughly 50 MB of memory)
 Factor Ops : 2.424e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.36746330e+08 -9.34716492e+08  2.01e+07 1.28e+01  8.15e+06     0s
   1   2.30116775e+08 -3.96259915e+08  1.83e+05 1.16e+02  4.59e+05     0s
   2   2.30116775e+08 -3.96259915e+08  1.83e+05 1.16e+02  4.59e+05     0s
   3   3.36746330e+08 -1.66727274e+11  2.01e+07 1.28e+01  1.51e+09     0s
   4   5.24591673e+08 -1.42690394e+11  1.71e+05 1.21e+02  3.15e+08     0s
   5   5.26338041e+08 -2.02741565e+10  1.14e+04 1.09e+01  2.88e+07     0s
   6   5.03792688e+08 -6.74650459e+08  3.03e+02 1.32e+01  4.28e+05     0s
   7   5.03792688e+08 -6.74650459e+08  3.03e+02 1.32e+01  4.28e+05     0s
   8   5.03792688e+08 -6.74650459e+08  3.03e+02 1.32e+01  4.28e+05     0s
   9   5.03792688e+08 -6.74650459e+08  3.03e+02 1.32e+01  4.28e+05     0s
  10   5.03792688e+08 -6.74650459e+08  3.03e+02 1.32e+01  4.28e+05     0s
  11   3.36746330e+08 -1.66727274e+11  2.01e+07 1.28e+01  1.51e+09     1s
  12   1.15546087e+08 -1.30798978e+10  2.11e+05 6.31e+01  4.83e+07     1s
  13   3.85512074e+07 -3.29757171e+08  4.92e+03 1.77e+00  4.05e+05     1s
  14  -5.98179315e+06 -8.96565371e+07  6.77e+02 1.36e+00  5.48e+04     1s
  15  -4.21043187e+07 -5.82020263e+07  1.07e+02 3.59e+00  4.61e+03     1s
  16  -4.21043187e+07 -5.82020263e+07  1.07e+02 3.59e+00  4.61e+03     1s
  17  -4.21043187e+07 -5.82020263e+07  1.07e+02 3.59e+00  4.61e+03     1s
  18  -4.21043187e+07 -5.82020263e+07  1.07e+02 3.59e+00  4.61e+03     1s

Barrier performed 18 iterations in 0.84 seconds (0.93 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   25476   -5.5478589e+07   0.000000e+00   0.000000e+00      4s

Solved in 25476 iterations and 3.62 seconds (7.63 work units)
Optimal objective -5.547858870e+07

(CVXPY) May 03 05:40:23 PM: Problem status: optimal
(CVXPY) May 03 05:40:23 PM: Optimal value: -5.548e+07
(CVXPY) May 03 05:40:23 PM: Compilation took 1.376e+02 seconds
(CVXPY) May 03 05:40:23 PM: Solver (including time spent in interface) took 3.947e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 6/10 (start=6833) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:40:30 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:40:32 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:40:32 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:40:32 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:40:32 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:40:34 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:40:34 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:40:34 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:40:34 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:40:42 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:41:28 PM: Applying reduction GUROBI
(CVXPY) May 03 05:41:28 PM: Finished problem compilation (took 5.652e+01 seconds).
(CVXPY) May 03 05:41:28 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x24c2cf4f
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-02, 1e+05]
Presolve removed 56000 rows and 2178 columns
Presolve time: 0.10s
Presolved: 28501 rows, 39850 columns, 105494 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.749e+04
 Factor NZ  : 1.121e+05 (roughly 30 MB of memory)
 Factor Ops : 1.164e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.80925721e+07 -4.78470340e+08  1.35e+06 6.21e+02  6.10e+05     0s
   1  -3.59083378e+07 -2.80868014e+08  6.83e+04 4.88e+01  4.93e+04     0s
   2  -2.92415525e+07 -1.10645905e+08  4.00e+03 5.98e+00  6.75e+03     0s
   3  -3.53167509e+07 -8.99108738e+07  1.96e+03 8.78e+01  4.00e+03     0s
   4  -4.31003060e+07 -5.27861343e+07  1.28e+02 2.57e+01  3.69e+02     0s
   5  -4.31003060e+07 -5.27861343e+07  1.28e+02 2.57e+01  3.69e+02     0s
   6  -3.80950712e+07 -3.87621825e+10  1.36e+06 1.13e-13  5.29e+07     0s
   7  -1.22426524e+07 -4.09335961e+10  2.69e+04 2.80e+01  3.53e+06     0s
   8  -2.85119287e+06 -2.69795150e+09  3.29e+02 2.38e+00  7.54e+04     0s
   9  -2.51679059e+07 -1.62424045e+08  1.15e+01 4.50e+00  3.62e+03     0s
  10  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  11  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  12  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  13  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  14  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  15  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  16  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  17  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  18  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     0s
  19  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     1s
  20  -4.33845286e+07 -5.53840340e+07  1.00e+00 5.94e+00  3.05e+02     1s

Barrier performed 20 iterations in 0.54 seconds (0.49 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10521   -5.0677080e+07   0.000000e+00   0.000000e+00      1s

Solved in 10521 iterations and 1.22 seconds (2.31 work units)
Optimal objective -5.067707975e+07

(CVXPY) May 03 05:41:31 PM: Problem status: optimal
(CVXPY) May 03 05:41:31 PM: Optimal value: -5.068e+07
(CVXPY) May 03 05:41:31 PM: Compilation took 5.652e+01 seconds
(CVXPY) May 03 05:41:31 PM: Solver (including time spent in interface) took 1.423e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:41:38 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:41:43 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:41:43 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:41:43 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:41:43 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:41:46 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:41:46 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:41:46 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:41:51 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:42:05 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:44:05 PM: Applying reduction GUROBI
(CVXPY) May 03 05:44:05 PM: Finished problem compilation (took 1.423e+02 seconds).
(CVXPY) May 03 05:44:05 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0x5a28f915
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-02, 1e+05]
Presolve removed 84000 rows and 2178 columns
Presolve time: 0.10s
Presolved: 57001 rows, 68351 columns, 225960 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.409e+05
 Factor NZ  : 3.128e+05 (roughly 50 MB of memory)
 Factor Ops : 2.486e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   4.68087134e+08 -1.12705776e+09  2.70e+07 6.40e+00  5.05e+06     0s
   1   3.07638516e+08 -4.66833964e+08  1.22e+05 6.31e+00  2.68e+05     0s
   2   3.07638516e+08 -4.66833964e+08  1.22e+05 6.31e+00  2.68e+05     0s
   3   4.68087134e+08 -4.33280017e+11  2.70e+07 6.40e+00  2.03e+09     0s
   4   6.74377603e+08 -3.61501929e+11  2.62e+05 1.09e+02  3.49e+08     0s
   5   6.83260009e+08 -7.75913925e+10  2.63e+04 1.96e+01  6.27e+07     0s
   6   6.82971115e+08 -3.08622104e+09  1.52e+03 6.39e-01  5.39e+05     0s
   7   6.82959916e+08 -3.08622717e+09  1.52e+03 4.95e+00  5.39e+05     0s
   8   6.82959916e+08 -3.08622717e+09  1.52e+03 4.95e+00  5.39e+05     0s
   9   6.82959916e+08 -3.08622717e+09  1.52e+03 4.95e+00  5.39e+05     0s
  10   6.82959916e+08 -3.08622717e+09  1.52e+03 4.95e+00  5.39e+05     0s
  11   4.68087134e+08 -4.33280017e+11  2.70e+07 6.40e+00  2.03e+09     1s
  12   1.57713897e+08 -4.43696251e+10  3.35e+05 7.39e+01  8.68e+07     1s
  13   8.03747669e+07 -2.05454527e+09  1.18e+04 3.57e+00  1.47e+06     1s
  14   2.63649907e+07 -1.51629081e+08  5.15e+01 3.68e+00  7.36e+04     1s
  15   2.63633003e+07 -1.51629409e+08  5.15e+01 7.01e+01  7.27e+04     1s
  16  -9.86264933e+06 -8.40728553e+07  1.78e+01 4.28e+02  2.20e+04     1s
  17  -9.86272182e+06 -8.40731565e+07  1.78e+01 4.39e+02  2.17e+04     1s
  18  -9.86445343e+06 -8.40735758e+07  1.78e+01 4.75e+02  2.10e+04     1s
  19  -9.86445343e+06 -8.40735758e+07  1.78e+01 4.75e+02  2.10e+04     1s
  20  -9.86445343e+06 -8.40735758e+07  1.78e+01 4.75e+02  2.10e+04     1s

Barrier performed 20 iterations in 0.94 seconds (1.01 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   63831   -5.5460688e+07   0.000000e+00   0.000000e+00      5s

Solved in 63831 iterations and 4.84 seconds (9.28 work units)
Optimal objective -5.546068849e+07

(CVXPY) May 03 05:44:12 PM: Problem status: optimal
(CVXPY) May 03 05:44:12 PM: Optimal value: -5.546e+07
(CVXPY) May 03 05:44:12 PM: Compilation took 1.423e+02 seconds
(CVXPY) May 03 05:44:12 PM: Solver (including time spent in interface) took 5.170e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 7/10 (start=5282) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:44:19 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:44:21 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:44:21 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:44:21 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:44:21 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:44:23 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:44:23 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:44:23 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:44:23 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:44:30 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:45:16 PM: Applying reduction GUROBI
(CVXPY) May 03 05:45:16 PM: Finished problem compilation (took 5.459e+01 seconds).
(CVXPY) May 03 05:45:16 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x84830bf6
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 56000 rows and 2797 columns
Presolve time: 0.10s
Presolved: 28501 rows, 39231 columns, 103637 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.564e+04
 Factor NZ  : 1.103e+05 (roughly 30 MB of memory)
 Factor Ops : 1.153e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -2.81682030e+07 -4.59776968e+08  9.71e+05 6.18e+02  5.14e+05     0s
   1  -2.63616758e+07 -2.61620552e+08  3.85e+04 2.91e+01  2.68e+04     0s
   2  -2.95539076e+07 -7.49875626e+07  1.23e+03 1.63e+01  2.55e+03     0s
   3  -4.38973156e+07 -5.22011239e+07  1.20e+02 1.74e+01  2.54e+02     0s
   4  -4.38973156e+07 -5.22011239e+07  1.20e+02 1.74e+01  2.54e+02     0s
   5  -2.81697071e+07 -3.22389410e+10  9.71e+05 1.13e-13  3.80e+07     0s
   6  -1.05595884e+07 -3.55870865e+10  1.13e+04 2.43e+01  2.38e+06     0s
   7  -8.70714397e+06 -1.25730830e+09  1.43e+02 1.74e+00  4.09e+04     0s
   8  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s
   9  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s
  10  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s
  11  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s
  12  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s
  13  -2.41499823e+07 -7.89180384e+07  4.65e+00 1.20e+01  1.58e+03     0s

Barrier performed 13 iterations in 0.39 seconds (0.34 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11058   -5.0292851e+07   0.000000e+00   0.000000e+00      1s

Solved in 11058 iterations and 1.21 seconds (2.28 work units)
Optimal objective -5.029285109e+07

(CVXPY) May 03 05:45:18 PM: Problem status: optimal
(CVXPY) May 03 05:45:18 PM: Optimal value: -5.029e+07
(CVXPY) May 03 05:45:18 PM: Compilation took 5.459e+01 seconds
(CVXPY) May 03 05:45:18 PM: Solver (including time spent in interface) took 1.400e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:45:27 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:45:30 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:45:30 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:45:30 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:45:30 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:45:33 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:45:33 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:45:33 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:45:41 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:45:54 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:47:56 PM: Applying reduction GUROBI
(CVXPY) May 03 05:47:57 PM: Finished problem compilation (took 1.468e+02 seconds).
(CVXPY) May 03 05:47:57 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0xe0d9561b
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 84000 rows and 2797 columns
Presolve time: 0.10s
Presolved: 57001 rows, 67732 columns, 222246 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.335e+05
 Factor NZ  : 3.054e+05 (roughly 50 MB of memory)
 Factor Ops : 2.424e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.35459969e+08 -1.30221291e+09  1.87e+07 1.28e+01  5.41e+06     0s
   1   2.29302732e+08 -5.17722516e+08  8.01e+04 4.04e+00  2.67e+05     0s
   2   2.29302732e+08 -5.17722516e+08  8.01e+04 4.04e+00  2.67e+05     0s
   3   3.35459969e+08 -3.30179520e+11  1.87e+07 1.28e+01  1.41e+09     0s
   4   5.09144697e+08 -2.75578043e+11  1.63e+05 1.07e+02  2.43e+08     0s
   5   5.12504186e+08 -3.97863878e+10  9.19e+03 1.00e+01  2.30e+07     0s
   6   4.99650792e+08 -9.54558049e+08  2.63e+02 8.68e-02  2.15e+05     0s
   7   4.99657949e+08 -9.54548028e+08  2.63e+02 2.14e+02  2.15e+05     0s
   8   4.99657949e+08 -9.54548028e+08  2.63e+02 2.14e+02  2.15e+05     0s
   9   4.99657949e+08 -9.54548028e+08  2.63e+02 2.14e+02  2.15e+05     0s
  10   4.99657949e+08 -9.54548028e+08  2.63e+02 2.14e+02  2.15e+05     0s
  11   3.35459969e+08 -3.30179520e+11  1.87e+07 1.28e+01  1.41e+09     1s
  12   1.15856726e+08 -2.77539071e+10  2.32e+05 6.42e+01  4.98e+07     1s
  13   4.03449147e+07 -5.91331841e+08  3.98e+03 1.78e+00  3.25e+05     1s
  14   1.75978933e+06 -1.21160790e+08  4.55e+02 1.03e+01  4.29e+04     1s
  15  -3.68165921e+07 -6.27634938e+07  5.67e+01 7.89e+00  4.38e+03     1s
  16  -3.68165921e+07 -6.27634938e+07  5.67e+01 7.89e+00  4.38e+03     1s
  17  -3.68165921e+07 -6.27634938e+07  5.67e+01 7.89e+00  4.38e+03     1s
  18  -3.68165858e+07 -6.27634945e+07  5.67e+01 6.32e+00  4.38e+03     1s
  19  -3.68168713e+07 -6.27637161e+07  5.67e+01 3.82e+01  4.37e+03     1s
  20  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s
  21  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s
  22  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s
  23  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s
  24  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s
  25  -3.68167697e+07 -6.27635866e+07  5.67e+01 4.24e+01  4.36e+03     1s

Barrier performed 25 iterations in 1.17 seconds (1.29 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   27293   -5.5054366e+07   0.000000e+00   0.000000e+00      4s

Solved in 27293 iterations and 4.18 seconds (8.84 work units)
Optimal objective -5.505436623e+07

(CVXPY) May 03 05:48:02 PM: Problem status: optimal
(CVXPY) May 03 05:48:02 PM: Optimal value: -5.505e+07
(CVXPY) May 03 05:48:02 PM: Compilation took 1.468e+02 seconds
(CVXPY) May 03 05:48:02 PM: Solver (including time spent in interface) took 4.502e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 8/10 (start=6916) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:48:09 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:48:10 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:48:10 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:48:10 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:48:10 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:48:12 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:48:12 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:48:12 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:48:12 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:48:19 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:49:04 PM: Applying reduction GUROBI
(CVXPY) May 03 05:49:04 PM: Finished problem compilation (took 5.373e+01 seconds).
(CVXPY) May 03 05:49:04 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0xa0f733d7
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2662 columns
Presolve time: 0.10s
Presolved: 28501 rows, 39366 columns, 104042 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.604e+04
 Factor NZ  : 1.107e+05 (roughly 30 MB of memory)
 Factor Ops : 1.155e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -2.97413677e+07 -4.38009590e+08  1.10e+06 6.18e+02  5.25e+05     0s
   1  -2.87124230e+07 -2.52971947e+08  4.89e+04 2.91e+01  2.93e+04     0s
   2  -3.04561475e+07 -7.49703816e+07  4.02e+03 1.85e+01  2.52e+03     0s
   3  -4.31439840e+07 -5.32911112e+07  3.50e+02 4.77e+00  3.57e+02     0s
   4  -4.31439840e+07 -5.32911112e+07  3.50e+02 4.77e+00  3.57e+02     0s
   5  -2.97428555e+07 -3.38355505e+10  1.10e+06 1.13e-13  4.30e+07     0s
   6  -9.86128786e+06 -3.72554700e+10  2.01e+04 2.92e+01  3.03e+06     0s
   7  -5.74301435e+06 -2.52499827e+09  2.92e+02 5.11e+00  9.39e+04     0s
   8  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.29e+03     0s
   9  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.29e+03     0s
  10  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.29e+03     0s
  11  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.29e+03     0s
  12  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.28e+03     0s
  13  -1.71585592e+07 -9.23623167e+07  1.26e-08 8.57e+00  2.28e+03     0s

Barrier performed 13 iterations in 0.38 seconds (0.34 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10969   -5.0370096e+07   0.000000e+00   0.000000e+00      1s

Solved in 10969 iterations and 1.25 seconds (2.44 work units)
Optimal objective -5.037009566e+07

(CVXPY) May 03 05:49:06 PM: Problem status: optimal
(CVXPY) May 03 05:49:06 PM: Optimal value: -5.037e+07
(CVXPY) May 03 05:49:06 PM: Compilation took 5.373e+01 seconds
(CVXPY) May 03 05:49:06 PM: Solver (including time spent in interface) took 1.444e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:49:14 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:49:19 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:49:19 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:49:19 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:49:19 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:49:22 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:49:22 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:49:22 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:49:29 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:49:42 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:51:36 PM: Applying reduction GUROBI
(CVXPY) May 03 05:51:36 PM: Finished problem compilation (took 1.371e+02 seconds).
(CVXPY) May 03 05:51:36 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0xba16015a
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2662 columns
Presolve time: 0.10s
Presolved: 57001 rows, 67867 columns, 223056 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.351e+05
 Factor NZ  : 3.070e+05 (roughly 50 MB of memory)
 Factor Ops : 2.438e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.81222660e+08 -9.53960775e+08  2.13e+07 6.40e+00  4.14e+06     0s
   1   2.52922864e+08 -3.97898567e+08  1.09e+05 1.51e+01  2.24e+05     0s
   2   2.52922864e+08 -3.97898567e+08  1.09e+05 1.51e+01  2.24e+05     0s
   3   3.81222660e+08 -3.55255182e+11  2.13e+07 6.40e+00  1.60e+09     0s
   4   5.46136503e+08 -2.98009825e+11  2.33e+05 1.09e+02  2.76e+08     0s
   5   5.51264831e+08 -4.98073772e+10  1.91e+04 1.27e+01  3.08e+07     0s
   6   5.47167631e+08 -1.57744308e+09  7.93e+02 6.90e-01  1.65e+05     0s
   7   5.47167631e+08 -1.57744308e+09  7.93e+02 6.90e-01  1.65e+05     0s
   8   5.47167631e+08 -1.57744308e+09  7.93e+02 6.90e-01  1.65e+05     0s
   9   5.47167631e+08 -1.57744308e+09  7.93e+02 6.90e-01  1.65e+05     0s
  10   5.47167631e+08 -1.57744308e+09  7.93e+02 6.90e-01  1.65e+05     0s
  11   3.81222660e+08 -3.55255182e+11  2.13e+07 6.40e+00  1.60e+09     1s
  12   1.25799314e+08 -3.88117659e+10  2.99e+05 7.40e+01  7.30e+07     1s
  13   5.15250864e+07 -1.15874947e+09  7.03e+03 2.37e+00  7.49e+05     1s
  14   2.39432724e+07 -1.67038677e+08  4.21e+02 1.24e+00  8.60e+04     1s
  15   4.82825561e+06 -8.57798427e+07  2.39e+02 6.34e+01  3.10e+04     1s
  16   4.82825561e+06 -8.57798427e+07  2.39e+02 6.34e+01  3.10e+04     1s
  17   4.82825561e+06 -8.57798427e+07  2.39e+02 6.34e+01  3.10e+04     1s
  18   4.82557434e+06 -8.57812658e+07  2.39e+02 9.49e+01  2.82e+04     1s
  19   4.81991384e+06 -8.57690517e+07  2.39e+02 2.20e+02  2.70e+04     1s
  20  -3.39693644e+07 -6.13938773e+07  6.52e+01 8.40e+01  4.48e+03     1s
  21  -3.39693644e+07 -6.13938773e+07  6.52e+01 8.40e+01  4.48e+03     1s
  22  -3.39693644e+07 -6.13938773e+07  6.52e+01 8.40e+01  4.48e+03     1s
  23  -3.39691272e+07 -6.13935444e+07  6.52e+01 1.49e+02  4.35e+03     1s
  24  -3.39691272e+07 -6.13935444e+07  6.52e+01 1.49e+02  4.33e+03     1s
  25  -3.39691272e+07 -6.13935444e+07  6.52e+01 1.49e+02  4.33e+03     1s
  26  -3.39691272e+07 -6.13935444e+07  6.52e+01 1.49e+02  4.32e+03     1s
  27  -3.39679454e+07 -6.13921617e+07  6.52e+01 2.53e+02  4.29e+03     1s
  28  -3.39675589e+07 -6.13918886e+07  6.52e+01 2.54e+02  4.22e+03     1s
  29  -3.39675589e+07 -6.13918886e+07  6.52e+01 2.54e+02  4.21e+03     1s
  30  -3.39675589e+07 -6.13918886e+07  6.52e+01 2.54e+02  4.21e+03     1s

Barrier performed 30 iterations in 1.32 seconds (1.56 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   29602   -5.5119723e+07   0.000000e+00   0.000000e+00      5s

Solved in 29602 iterations and 4.96 seconds (13.54 work units)
Optimal objective -5.511972285e+07

(CVXPY) May 03 05:51:42 PM: Problem status: optimal
(CVXPY) May 03 05:51:42 PM: Optimal value: -5.512e+07
(CVXPY) May 03 05:51:42 PM: Compilation took 1.371e+02 seconds
(CVXPY) May 03 05:51:42 PM: Solver (including time spent in interface) took 5.270e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 9/10 (start=6330) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (27,), (1,), (500, 27), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:51:52 PM: Your problem has 14028 variables, 28501 constraints, and 0 parameters.
(CVXPY) May 03 05:51:55 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:51:55 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:51:55 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:51:55 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:51:57 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:51:57 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:51:57 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 03 05:51:57 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:52:03 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:52:53 PM: Applying reduction GUROBI
(CVXPY) May 03 05:52:53 PM: Finished problem compilation (took 5.862e+01 seconds).
(CVXPY) May 03 05:52:53 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 84501 rows, 42028 columns and 168028 nonzeros
Model fingerprint: 0x7ece02c2
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 56000 rows and 2889 columns
Presolve time: 0.09s
Presolved: 28501 rows, 39139 columns, 103361 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 28
 Free vars  : 28
 AA' NZ     : 7.536e+04
 Factor NZ  : 1.100e+05 (roughly 30 MB of memory)
 Factor Ops : 1.152e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.19212072e+07 -4.59479988e+08  9.24e+05 6.19e+02  4.71e+05     0s
   1  -2.95282619e+07 -2.60383094e+08  4.17e+04 4.66e+01  3.45e+04     0s
   2  -3.02007211e+07 -7.30321947e+07  3.05e+03 1.85e+01  3.04e+03     0s
   3  -4.48151201e+07 -5.21558426e+07  7.84e+01 2.06e+01  2.54e+02     0s
   4  -4.48151201e+07 -5.21558426e+07  7.84e+01 2.06e+01  2.54e+02     0s
   5  -3.19239097e+07 -3.34152318e+10  9.24e+05 1.13e-13  3.62e+07     0s
   6  -1.35482999e+07 -3.50985305e+10  1.13e+04 2.12e+01  2.16e+06     0s
   7  -1.11597090e+07 -1.18631929e+09  1.43e+02 1.85e+00  3.73e+04     0s
   8  -1.21535493e+07 -1.15301286e+09  1.37e+02 2.94e+02  3.52e+04     0s
   9  -2.45935400e+07 -1.46521823e+08  1.80e+01 2.73e+01  3.59e+03     0s
  10  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  11  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  12  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  13  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  14  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  15  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  16  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  17  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  18  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  19  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s
  20  -4.03009401e+07 -5.31445324e+07  1.75e+00 5.80e+00  3.24e+02     0s

Barrier performed 20 iterations in 0.49 seconds (0.49 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11501   -4.9953839e+07   0.000000e+00   0.000000e+00      1s

Solved in 11501 iterations and 1.21 seconds (2.33 work units)
Optimal objective -4.995383857e+07

(CVXPY) May 03 05:52:56 PM: Problem status: optimal
(CVXPY) May 03 05:52:56 PM: Optimal value: -4.995e+07
(CVXPY) May 03 05:52:56 PM: Compilation took 5.862e+01 seconds
(CVXPY) May 03 05:52:56 PM: Solver (including time spent in interface) took 1.399e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 03 05:53:02 PM: Your problem has 14529 variables, 29001 constraints, and 0 parameters.
(CVXPY) May 03 05:53:06 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 03 05:53:06 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 03 05:53:06 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 03 05:53:06 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 03 05:53:09 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 03 05:53:09 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 03 05:53:09 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 03 05:53:17 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 03 05:53:30 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 03 05:55:36 PM: Applying reduction GUROBI
(CVXPY) May 03 05:55:36 PM: Finished problem compilation (took 1.499e+02 seconds).
(CVXPY) May 03 05:55:36 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 141001 rows, 70529 columns and 323028 nonzeros
Model fingerprint: 0xf683e14e
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 84000 rows and 2889 columns
Presolve time: 0.10s
Presolved: 57001 rows, 67640 columns, 221694 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 29
 Free vars  : 29
 AA' NZ     : 2.324e+05
 Factor NZ  : 3.043e+05 (roughly 50 MB of memory)
 Factor Ops : 2.415e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.14410590e+08 -1.35654710e+09  1.94e+07 1.28e+01  5.49e+06     0s
   1   2.19826629e+08 -5.25346010e+08  8.43e+04 1.12e+01  2.66e+05     0s
   2   2.19826629e+08 -5.25346010e+08  8.43e+04 1.12e+01  2.66e+05     0s
   3   3.14410590e+08 -3.50561108e+11  1.94e+07 1.28e+01  1.46e+09     0s
   4   4.97705591e+08 -2.87451346e+11  1.67e+05 1.07e+02  2.53e+08     0s
   5   5.01737421e+08 -3.61484491e+10  9.77e+03 8.47e+00  2.03e+07     0s
   6   5.01737240e+08 -3.61484767e+10  9.77e+03 4.50e+02  2.03e+07     0s
   7   6.27003316e+08 -4.92215517e+10  7.51e+03 6.72e+02  9.54e+06     0s
   8   5.67351464e+08 -5.00228139e+09  9.88e-01 4.85e+00  2.20e+05     0s
   9   5.69637822e+08 -5.00230405e+09  9.88e-01 7.75e+02  2.19e+05     0s
  10   5.69637822e+08 -5.00230405e+09  9.88e-01 7.75e+02  2.19e+05     0s
  11   3.14410590e+08 -3.50561108e+11  1.94e+07 1.28e+01  1.46e+09     1s
  12   1.14938478e+08 -2.64539867e+10  2.51e+05 7.06e+01  4.81e+07     1s
  13   3.71216426e+07 -5.96846127e+08  4.39e+03 3.33e+00  3.13e+05     1s
  14  -5.13975924e+06 -8.55391373e+07  3.32e+02 3.18e+00  2.14e+04     1s
  15  -5.13990104e+06 -8.55379509e+07  3.32e+02 7.37e+01  2.13e+04     1s
  16  -5.13990104e+06 -8.55379509e+07  3.32e+02 7.37e+01  2.13e+04     1s
  17  -5.13990104e+06 -8.55379509e+07  3.32e+02 7.37e+01  2.12e+04     1s
  18  -5.13990104e+06 -8.55379509e+07  3.32e+02 7.37e+01  2.12e+04     1s

Barrier performed 18 iterations in 0.84 seconds (0.91 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   64293   -5.4737937e+07   0.000000e+00   0.000000e+00      5s

Solved in 64293 iterations and 4.55 seconds (8.10 work units)
Optimal objective -5.473793695e+07

(CVXPY) May 03 05:55:42 PM: Problem status: optimal
(CVXPY) May 03 05:55:42 PM: Optimal value: -5.474e+07
(CVXPY) May 03 05:55:42 PM: Compilation took 1.499e+02 seconds
(CVXPY) May 03 05:55:42 PM: Solver (including time spent in interface) took 4.883e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 10/10 (start=8061) done.

In [11]:
# Aggregate and average
keys = list(results_list[0].keys())
means = {k: np.mean([r[k] for r in results_list]) for k in keys}
stds = {k: np.std([r[k] for r in results_list]) for k in keys}

print("============== Real-data results (averaged over {} instances) ================".format(NUM_INSTANCES))
print("Distortion (DA vs E[RT price]):")
print("  Stochastic:", means["stoch_distortion"], "±", stds["stoch_distortion"])
print("  CVaR:", means["cvar_distortion"], "±", stds["cvar_distortion"])
print("  Deterministic:", means["det_distortion"], "±", stds["det_distortion"])
print("E[Social Surplus]:")
print("  Stochastic:", means["stoch_ss"], "±", stds["stoch_ss"])
print("  CVaR:", means["cvar_ss"], "±", stds["cvar_ss"])
print("  Deterministic:", means["det_ss"], "±", stds["det_ss"])
print("Tail (5%) welfare (mean positive SS in worst tail):")
print("  Stochastic:", means["stoch_tail_welfare"], "±", stds["stoch_tail_welfare"])
print("  CVaR:", means["cvar_tail_welfare"], "±", stds["cvar_tail_welfare"])
print("  Deterministic:", means["det_tail_welfare"], "±", stds["det_tail_welfare"])
print("Tail (5%) price distortion:")
print("  Stochastic:", means["stoch_tail_distortion"], "±", stds["stoch_tail_distortion"])
print("  CVaR:", means["cvar_tail_distortion"], "±", stds["cvar_tail_distortion"])
print("  Deterministic:", means["det_tail_distortion"], "±", stds["det_tail_distortion"])
print("Probability feasible:", means["prob_feasible"], "±", stds["prob_feasible"])

============== Real-data results (averaged over 10 instances) ================
Distortion (DA vs E[RT price]):
  Stochastic: 0.2417335294489135 ± 0.07545903738203191
  CVaR: 110.31372964009522 ± 0.06349479263490834
  Deterministic: 403.84139765569336 ± 18.56224819337082
E[Social Surplus]:
  Stochastic: 50439960.04080574 ± 482445.81605449645
  CVaR: 50438313.99019052 ± 482662.2239405528
  Deterministic: 49708871.90922298 ± 462336.8313540358
Tail (5%) welfare (mean positive SS in worst tail):
  Stochastic: 47831771.58097801 ± 181299.2923707616
  CVaR: 47865233.65880746 ± 181328.01298853
  Deterministic: 47801680.89850707 ± 178538.57796445588
Tail (5%) price distortion:
  Stochastic: 100.00000000000027 ± 8.597625825036818e-13
  CVaR: 9.146114949937464e-13 ± 7.117282853320532e-13
  Deterministic: 100.0 ± 0.0
Probability feasible: 0.020450221882226713 ± 0.010027050792888847

In [12]:
summary = pd.DataFrame({
    "Method": ["Stochastic", "CVaR", "Deterministic"] * 3,
    "Metric": ["Distortion", "Distortion", "Distortion", "E[SS]", "E[SS]", "E[SS]", "Tail welfare", "Tail welfare", "Tail welfare"],
    "Mean": [
        means["stoch_distortion"], means["cvar_distortion"], means["det_distortion"],
        means["stoch_ss"], means["cvar_ss"], means["det_ss"],
        means["stoch_tail_welfare"], means["cvar_tail_welfare"], means["det_tail_welfare"],
    ],
    "Std": [
        stds["stoch_distortion"], stds["cvar_distortion"], stds["det_distortion"],
        stds["stoch_ss"], stds["cvar_ss"], stds["det_ss"],
        stds["stoch_tail_welfare"], stds["cvar_tail_welfare"], stds["det_tail_welfare"],
    ],
})
summary["Std/Mean"] = summary["Std"] / summary["Mean"]
display(summary)

          Method        Metric          Mean            Std  Std/Mean
0     Stochastic    Distortion  2.417335e-01       0.075459  0.312158
1           CVaR    Distortion  1.103137e+02       0.063495  0.000576
2  Deterministic    Distortion  4.038414e+02      18.562248  0.045964
3     Stochastic         E[SS]  5.043996e+07  482445.816054  0.009565
4           CVaR         E[SS]  5.043831e+07  482662.223941  0.009569
5  Deterministic         E[SS]  4.970887e+07  462336.831354  0.009301
6     Stochastic  Tail welfare  4.783177e+07  181299.292371  0.003790
7           CVaR  Tail welfare  4.786523e+07  181328.012989  0.003788
8  Deterministic  Tail welfare  4.780168e+07  178538.577964  0.003735

In [13]:
from pathlib import Path

LOG_DIR = Path("outputs/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

print("\n=== Summary dataframe ===")
print(summary.to_string(index=False))

with open(LOG_DIR / "summary_dataframe.log", "w") as f:
    f.write(summary.to_string(index=False))
    f.write("\n")

=== Summary dataframe ===
       Method       Metric         Mean           Std  Std/Mean
   Stochastic   Distortion 2.417335e-01      0.075459  0.312158
         CVaR   Distortion 1.103137e+02      0.063495  0.000576
Deterministic   Distortion 4.038414e+02     18.562248  0.045964
   Stochastic        E[SS] 5.043996e+07 482445.816054  0.009565
         CVaR        E[SS] 5.043831e+07 482662.223941  0.009569
Deterministic        E[SS] 4.970887e+07 462336.831354  0.009301
   Stochastic Tail welfare 4.783177e+07 181299.292371  0.003790
         CVaR Tail welfare 4.786523e+07 181328.012989  0.003788
Deterministic Tail welfare 4.780168e+07 178538.577964  0.003735