In [2]:
import os
import numpy as np
import pandas as pd

# Paths: notebook is in zavala_electricity_market, data in dataset/IM-3-GO-WEST
# Run from project root (prj_market) or from zavala_electricity_market
_cwd = os.getcwd()
if os.path.basename(_cwd) == "zavala_electricity_market":
    BASE_DIR = os.path.dirname(_cwd)
else:
    BASE_DIR = _cwd
DATA_DIR = os.path.join(BASE_DIR, "dataset", "IM-3-GO-WEST")
if not os.path.isdir(DATA_DIR):
    DATA_DIR = os.path.join(_cwd, "dataset", "IM-3-GO-WEST")

# Ensure zavala_electricity_market is on path (when running from project root)
import sys
ZAVALA_DIR = os.path.join(BASE_DIR, "zavala_electricity_market")
if os.path.isdir(ZAVALA_DIR) and ZAVALA_DIR not in sys.path:
    sys.path.insert(0, ZAVALA_DIR)

# --- Minimal customization for current repo layout ---

# 1) If the original DATA_DIR doesn't exist, try archive/dataset/IM-3-GO-WEST
if not os.path.isdir(DATA_DIR):
    alt_data_dir = os.path.join(BASE_DIR, "archive", "dataset", "IM-3-GO-WEST")
    if os.path.isdir(alt_data_dir):
        DATA_DIR = alt_data_dir

# 2) If ZAVALA_DIR isn't a valid dir (e.g. code is at repo root),
#    fall back to BASE_DIR itself when it has zavala_funcs.py
if not os.path.isdir(ZAVALA_DIR):
    repo_root_candidate = BASE_DIR
    if os.path.isfile(os.path.join(repo_root_candidate, "zavala_funcs.py")):
        if repo_root_candidate not in sys.path:
            sys.path.insert(0, repo_root_candidate)
        ZAVALA_DIR = repo_root_candidate

print("Using DATA_DIR:", DATA_DIR)
print("Using ZAVALA_DIR:", ZAVALA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

from zavala_funcs import (
    zavala,
    zavala_cvar,
    zavala_deterministic_da,
    zavala_rt_energy_only,
    expected_caps_from_scenarios,
    price_distortion,
    probability_feasible,
    expected_cumulative_regret,
    compute_social_surplus,
    tail_worst_indices_by_value,
    _stack_rt,
)

print("Data dir:", DATA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

Using DATA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Using ZAVALA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']
Data dir: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']

In [3]:
# Load nodal time series (rows = time, columns = bus_XXXXX)
solar = pd.read_csv(os.path.join(DATA_DIR, "nodal_solar.csv"))
wind = pd.read_csv(os.path.join(DATA_DIR, "nodal_wind.csv"))
load_df = pd.read_csv(os.path.join(DATA_DIR, "nodal_load.csv"))
thermal_df = pd.read_csv(os.path.join(DATA_DIR, "thermal_gens.csv"))

T = len(solar)
assert len(wind) == T and len(load_df) == T, "Solar, wind, load must have same length"
print(f"Time steps: {T}")
print(f"Solar columns: {solar.shape[1]}, Wind: {wind.shape[1]}, Load: {load_df.shape[1]}")
print(f"Thermal generators: {len(thermal_df)}")

Time steps: 8760
Solar columns: 125, Wind: 125, Load: 125
Thermal generators: 280

In [4]:
# Choose buses with non-trivial solar: columns with max > threshold
solar_cols = [c for c in solar.columns if solar[c].max() > 50]
wind_cols = [c for c in wind.columns if wind[c].max() > 50]
# Pick 3 solar and 3 wind (unreliable)
num_solar, num_wind = 3, 3
solar_buses = solar_cols[:num_solar] if len(solar_cols) >= num_solar else list(solar.columns[:num_solar])
wind_buses = wind_cols[:num_wind] if len(wind_cols) >= num_wind else list(wind.columns[:num_wind])

# Reliable: aggregate thermal by bus, pick 4 buses with largest capacity
thermal_by_bus = thermal_df.groupby("Bus")["Max_Cap"].sum().sort_values(ascending=False)
thermal_buses_numeric = list(thermal_by_bus.head(4).index)  # e.g. [408441, 135041, ...]
thermal_bus_cols = [f"bus_{b}" for b in thermal_buses_numeric]  # for load alignment if needed

# Load: use total system load (sum over all buses)
load_total = load_df.sum(axis=1).values  # (T,)

print("Solar buses (unreliable):", solar_buses)
print("Wind buses (unreliable):", wind_buses)
print("Thermal buses (reliable):", thermal_buses_numeric)
print("Load: system total (sum over all buses)")

Solar buses (unreliable): ['bus_100931', 'bus_200261', 'bus_201361']
Wind buses (unreliable): ['bus_100931', 'bus_102281', 'bus_105701']
Thermal buses (reliable): [500991, 605141, 408441, 261001]
Load: system total (sum over all buses)

In [5]:
# Filter thermal_df for the selected buses
selected_buses = [500991, 605141, 408441, 261001]
thermal_selected = thermal_df[thermal_df['Bus'].isin(selected_buses)]
display(thermal_selected)

,Name,Bus,Fuel,Max_Cap,Min_Cap,Heat_Rate
0,PHOENIX_Nuc,408441,NUC (Nuclear),4209.60,1046.90,8.530000
1,TONOPAH_NG,408441,NG (Natural Gas),1325.10,393.07,4.177264
2,PHOENIX_NG,408441,NG (Natural Gas),1207.38,449.72,3.622784
28,BRUSH_C,605141,BIT (Bituminous Coal),552.30,78.79,8.941106
29,WELLINGTON_C,605141,BIT (Bituminous Coal),800.40,247.36,8.242654
30,DENVER_C,605141,BIT (Bituminous Coal),586.31,164.07,7.933221
31,KEENESBURG_NG,605141,NG (Natural Gas),685.11,246.77,5.015047
32,BOULDER_C,605141,BIT (Bituminous Coal),251.00,55.58,8.227582
33,PLATTEVILLE_NG,605141,NG (Natural Gas),1185.48,481.17,2.758167
34,AURORA_NG,605141,NG (Natural Gas),397.80,147.60,4.898308
35,COMMERCECITY_NG,605141,NG (Natural Gas),154.20,29.25,4.799750
36,DENVER_NG,605141,NG (Natural Gas),269.01,54.48,3.526185
37,FORTLUPTON_NG,605141,NG (Natural Gas),497.70,120.82,4.718237
38,BURLINGTON_C,605141,BIT (Bituminous Coal),129.40,47.19,7.651625
39,FREDERICK_NG,605141,NG (Natural Gas),394.00,136.49,2.436760
40,BRUSH_NG,605141,NG (Natural Gas),597.22,156.56,3.038616
41,LIMON_NG,605141,NG (Natural Gas),154.20,37.06,4.622871
42,LAMAR_C,605141,BIT (Bituminous Coal),43.50,17.89,7.974531
43,CHEYENNE_NG,605141,NG (Natural Gas),139.99,33.48,4.731375
55,CASTLEDALE_C,500991,BIT (Bituminous Coal),1577.19,296.35,8.900558
56,HUNTINGTON_C,500991,BIT (Bituminous Coal),1037.30,382.51,8.612997
57,OREM_NG,500991,NG (Natural Gas),1392.48,370.22,3.543914
58,MONA_NG,500991,NG (Natural Gas),648.99,208.10,5.030309
59,KEMMERER_C,500991,BIT (Bituminous Coal),831.99,304.11,8.195294
60,HELPER_C,500991,BIT (Bituminous Coal),208.60,49.90,8.192120
61,SALTLAKECITY_NG,500991,NG (Natural Gas),783.49,218.84,3.554682
62,PAYSON_NG,500991,NG (Natural Gas),140.00,43.07,3.959980
63,SUNNYSIDE_C,500991,BIT (Bituminous Coal),58.10,6.34,8.114105
64,MAGNA_C,500991,BIT (Bituminous Coal),213.80,41.00,7.651219
65,BOUNTIFUL_NG,500991,NG (Natural Gas),30.39,8.90,2.977745
77,SUNCITY_NG,261001,NG (Natural Gas),819.00,228.42,2.720162
78,REDONDOBEACH_NG,261001,NG (Natural Gas),1316.40,454.78,5.271419
79,LONGBEACH_NG,261001,NG (Natural Gas),2173.98,657.33,4.487376
80,PLAYADELREY_NG,261001,NG (Natural Gas),823.20,271.80,5.154075
81,HUNTINGTONBEACH_NG,261001,NG (Natural Gas),436.00,100.93,2.516905
82,WILMINGTON_NG,261001,NG (Natural Gas),548.11,163.17,5.168842
83,CARSON_NG,261001,NG (Natural Gas),405.00,135.72,3.373920

Debug Logs

In [6]:
# For diagnostics: breakdown of DA and RT allocations
def _log(msg, logfile=None):
    if logfile is None:
        print(msg)
    else:
        with open(logfile, "a", encoding="utf-8") as f:
            f.write(str(msg) + "\n")

def _tech_breakdown_da(g_da):
    g_da = np.asarray(g_da, dtype=float)
    return {
        "solar": g_da[:3].sum(),
        "wind": g_da[3:6].sum(),
        "thermal": g_da[6:10].sum(),
        "total": g_da.sum(),
    }

def _tech_breakdown_rt(G_rt, probs=None):
    G_rt = np.asarray(G_rt, dtype=float)  # shape (S, 10)
    solar = G_rt[:, :3].sum(axis=1)
    wind = G_rt[:, 3:6].sum(axis=1)
    thermal = G_rt[:, 6:10].sum(axis=1)
    total = G_rt.sum(axis=1)

    if probs is None:
        return {
            "solar": solar.mean(),
            "wind": wind.mean(),
            "thermal": thermal.mean(),
            "total": total.mean(),
        }

    probs = np.asarray(probs, dtype=float)
    return {
        "solar": np.dot(probs, solar),
        "wind": np.dot(probs, wind),
        "thermal": np.dot(probs, thermal),
        "total": np.dot(probs, total),
    }

def _print_case_diag(name, probs, g_da, d_da, G_rt, D_rt, pi, Pi, logfile=None):
    g_da = np.asarray(g_da, dtype=float)
    d_da = np.asarray(d_da, dtype=float)
    G_rt = np.asarray(G_rt, dtype=float)
    D_rt = np.asarray(D_rt, dtype=float)

    da = _tech_breakdown_da(g_da)
    rt = _tech_breakdown_rt(G_rt, probs=probs)

    da_load = float(d_da.sum())
    exp_rt_load = float(np.dot(np.asarray(probs, dtype=float), D_rt.sum(axis=1)))

    da_supply = float(g_da.sum())
    exp_rt_supply = float(np.dot(np.asarray(probs, dtype=float), G_rt.sum(axis=1)))

    _log(f"\n===== {name} =====", logfile)
    _log(f"DA price pi: {float(pi):.6f}", logfile)
    _log(f"E[RT price]: {float(np.dot(np.asarray(probs, dtype=float), np.asarray(Pi, dtype=float))):.6f}", logfile)
    _log("DA allocation by tech: " + str({k: round(v, 4) for k, v in da.items()}), logfile)
    _log("Expected RT allocation by tech: " + str({k: round(v, 4) for k, v in rt.items()}), logfile)

    gen_names = [f"solar_{i+1}" for i in range(3)] + [f"wind_{i+1}" for i in range(3)] + [f"thermal_{i+1}" for i in range(4)]
    g_da = np.asarray(g_da, dtype=float)
    exp_rt = np.dot(np.asarray(probs, dtype=float), np.asarray(G_rt, dtype=float))

    df = pd.DataFrame({
        "gen": gen_names,
        "DA": g_da,
        "E_RT": exp_rt,
        "RT_minus_DA": exp_rt - g_da,
    })
    _log(df.to_string(index=False), logfile)
    _log(f"DA load: {da_load:.6f}", logfile)
    _log(f"E[RT load]: {exp_rt_load:.6f}", logfile)
    _log(f"DA supply - DA load: {da_supply - da_load:.6f}", logfile)
    _log(f"E[RT supply] - E[RT load]: {exp_rt_supply - exp_rt_load:.6f}", logfile)

def _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i, logfile=None):
    gen_names = [f"solar_{i+1}" for i in range(3)] + [f"wind_{i+1}" for i in range(3)] + [f"thermal_{i+1}" for i in range(4)]
    z = np.asarray(z_g_i, dtype=float)
    c = np.asarray(cvar_g_i, dtype=float)
    df = pd.DataFrame({
        "gen": gen_names,
        "stoch_DA": z,
        "cvar_DA": c,
        "cvar_minus_stoch": c - z,
    })
    _log("\n===== CVaR - Stochastic DA difference =====", logfile)
    _log(df.to_string(index=False), logfile)
    _log("Tech-level difference: " + str({
        "solar": round((c[:3] - z[:3]).sum(), 4),
        "wind": round((c[3:6] - z[3:6]).sum(), 4),
        "thermal": round((c[6:10] - z[6:10]).sum(), 4),
        "total": round((c - z).sum(), 4),
    }), logfile)

In [7]:
# Initialize log files
log_dir = "logs"
os.makedirs(log_dir, exist_ok=True)

debug_log = os.path.join(log_dir, "zavala_debug_log.txt")
with open(debug_log, "w", encoding="utf-8") as f:
    f.write("Zavala diagnostics log\n")

Cost Metric

In [8]:
def realized_cost_per_scenario(mc_g_i, g_da, G_rt, d_cap_rt, D_rt, voll=1000.0):
    mc_g_i = np.asarray(mc_g_i, dtype=float)
    g_da = np.asarray(g_da, dtype=float)
    G_rt = np.asarray(G_rt, dtype=float)
    d_cap_rt = np.asarray(d_cap_rt, dtype=float).reshape(-1)
    D_rt = np.asarray(D_rt, dtype=float).reshape(-1)

    mc_delta = mc_g_i / 10.0

    energy_cost = (G_rt * mc_g_i[None, :]).sum(axis=1)
    mismatch_cost = (np.abs(G_rt - g_da[None, :]) * mc_delta[None, :]).sum(axis=1)
    unserved_energy = np.maximum(d_cap_rt - D_rt, 0.0)
    load_shed_cost = voll * unserved_energy

    return energy_cost + mismatch_cost + load_shed_cost

def cvar_from_samples(values, probs, beta=0.95):
    values = np.asarray(values, dtype=float)
    probs = np.asarray(probs, dtype=float)

    order = np.argsort(values)
    v = values[order]
    p = probs[order]
    c = np.cumsum(p)

    var_idx = np.searchsorted(c, beta, side="left")
    var = v[var_idx]

    tail_mask = values >= var
    tail_probs = probs[tail_mask]
    tail_probs = tail_probs / tail_probs.sum()
    cvar = np.dot(tail_probs, values[tail_mask])

    return var, cvar

def risk_adjusted_total_cost(cost_scenarios, probs, beta=0.95):
    E_cost = float(np.dot(probs, cost_scenarios))
    VaR, CVaR = cvar_from_samples(cost_scenarios, probs, beta=beta)
    return {
        "E_cost": E_cost,
        "VaR": VaR,
        "CVaR": CVaR,
        "RiskAdjustedTotalCost": E_cost + CVaR,
    }

Build Real Data

In [9]:
def build_real_data_instance(solar_df, wind_df, load_total_vec, thermal_by_bus, thermal_buses_numeric,
                              solar_buses, wind_buses, start_idx, num_scenarios, rng=None):
    """
    Build (probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar) from real data for one time window.
    - start_idx: first time index
    - num_scenarios: number of consecutive time steps (scenarios)
    """
    if rng is None:
        rng = np.random.default_rng()
    end_idx = start_idx + num_scenarios
    S = num_scenarios

    # Scenario probabilities: near-uniform (same idea as s_real10_mix)
    kappa = 1500.0
    alpha = np.full(S, kappa / S)
    probs = rng.dirichlet(alpha)
    probs = probs / probs.sum()

    # Marginal costs: cheap for unreliable (solar/wind), higher for reliable (thermal)
    mc_unrel = rng.uniform(8.0, 14.0, size=6)
    mc_rel = rng.uniform(35.0, 55.0, size=4)
    mc_g_i = np.concatenate([mc_unrel, mc_rel]).astype(float)

    # Single inelastic load (VOLL)
    mv_d_j = np.array([1000.0], dtype=float)

    # Generator capacities per scenario (S x 10)
    # Columns 0..2: solar, 3..5: wind, 6..9: thermal (constant)
    solar_vals = solar_df.loc[start_idx:end_idx - 1, solar_buses].values  # (S, 3)
    wind_vals = wind_df.loc[start_idx:end_idx - 1, wind_buses].values    # (S, 3)
    unrel_caps = np.clip(np.hstack([solar_vals, wind_vals]), 0.0, None)  # (S, 6)

    rel_caps = np.array([thermal_by_bus[b] for b in thermal_buses_numeric], dtype=float)
    rel_caps = np.broadcast_to(rel_caps, (S, 4))  # (S, 4) constant across scenarios

    g_i_bar = np.hstack([unrel_caps, rel_caps])  # (S, 10)

    # Demand: system total load for each scenario (S x 1)
    d_j_bar = load_total_vec[start_idx:end_idx].reshape(-1, 1).astype(float)
    d_j_bar = np.clip(d_j_bar, 1e-6, None)  # avoid zeros

    return probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar

In [10]:
# Quick sanity check: one small window
NUM_SCENARIOS = 500
rng = np.random.default_rng(42)
probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
    solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
    solar_buses, wind_buses, start_idx=0, num_scenarios=min(NUM_SCENARIOS, T), rng=rng
)
print("probs.shape:", probs.shape, "sum:", probs.sum())
print("g_i_bar.shape:", g_i_bar.shape)
print("d_j_bar.shape:", d_j_bar.shape)
print("Unreliable (solar+wind) sample mean:", g_i_bar[:, :6].mean(axis=0))
print("Reliable (thermal) constant:", g_i_bar[0, 6:])
print("Load sample:", d_j_bar[:5].ravel())

probs.shape: (500,) sum: 1.0
g_i_bar.shape: (500, 10)
d_j_bar.shape: (500, 1)
Unreliable (solar+wind) sample mean: [ 67.33335058  17.28        28.36311076 660.0882676  133.714
 215.59573142]
Reliable (thermal) constant: [6922.33 6837.62 6742.08 6521.69]
Load sample: [75073. 72985. 71226. 70105. 69772.]

In [11]:
def run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=None):
    """Run stochastic, CVaR, and deterministic Zavala for one instance. Returns dict of metrics.
    Same logic as run_zavala.py, no changes to external files.
    """
    # ----- Stochastic Zavala -----
    z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi = zavala(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    prob_f = probability_feasible(probs, z_g_i, z_d_j, g_i_bar, d_j_bar)
    z_dist = price_distortion(probs, z_pi, z_Pi)
    z_reg = expected_cumulative_regret(probs, z_g_i, z_d_j, z_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_stoch = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=z_g_i, d_da=z_d_j, G_rt=Z_G, D_rt=Z_D)

    # Cost metrics for stochastic case
    stoch_cost_scen = realized_cost_per_scenario(
        mc_g_i, z_g_i, Z_G, d_j_bar[:, 0], Z_D[:, 0], voll=mv_d_j[0]
    )
    stoch_cost_summary = risk_adjusted_total_cost(stoch_cost_scen, probs, beta=0.95)

    # # ----- CVaR Zavala -----
    cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi, _ = zavala_cvar(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    cvar_dist = price_distortion(probs, cvar_pi, cvar_Pi)
    cvar_reg = expected_cumulative_regret(probs, cvar_g_i, cvar_d_j, cvar_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_cvar = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=cvar_g_i, d_da=cvar_d_j, G_rt=C_G, D_rt=C_D)

    # Cost metrics for CVaR case
    cvar_cost_scen = realized_cost_per_scenario(
        mc_g_i, cvar_g_i, C_G, d_j_bar[:, 0], C_D[:, 0], voll=mv_d_j[0]
    )
    cvar_cost_summary = risk_adjusted_total_cost(cvar_cost_scen, probs, beta=0.95)

    # ----- Deterministic (expected capacities) -----
    gbar_det, dbar_det = expected_caps_from_scenarios(probs, g_i_bar, d_j_bar)
    g_det, d_det, pi_det = zavala_deterministic_da(mc_g_i, mv_d_j, gbar_det, dbar_det)
    G_det_list, D_det_list, Pi_det_list = [], [], []
    for p in range(len(probs)):
        Gp, Dp, Pi_p = zavala_rt_energy_only(mc_g_i, mv_d_j, g_det, d_det, g_i_bar[p], d_j_bar[p])
        G_det_list.append(Gp)
        D_det_list.append(Dp)
        Pi_det_list.append(Pi_p)
    G_det_rt, D_det_rt = _stack_rt(G_det_list, D_det_list)
    Pi_det = np.array(Pi_det_list)
    det_dist = price_distortion(probs, pi_det, Pi_det)
    det_reg = expected_cumulative_regret(probs, g_det, d_det, pi_det, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_det = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=g_det, d_da=d_det, G_rt=G_det_rt, D_rt=D_det_rt)

    # Cost metrics for deterministic case
    det_cost_scen = realized_cost_per_scenario(
        mc_g_i, g_det, G_det_rt, d_j_bar[:, 0], D_det_rt[:, 0], voll=mv_d_j[0]
    )
    det_cost_summary = risk_adjusted_total_cost(det_cost_scen, probs, beta=0.95)

    # ----- Tail metrics (5% worst by high neg-surplus) -----
    tail = 0.05
    stoch_tail_idx = tail_worst_indices_by_value(ss_stoch["ss_per_scenario"], probs, tail=tail, worst="high")
    cvar_tail_idx = tail_worst_indices_by_value(ss_cvar["ss_per_scenario"], probs, tail=tail, worst="high")
    det_tail_idx = tail_worst_indices_by_value(ss_det["ss_per_scenario"], probs, tail=tail, worst="high")

    stoch_tail_welfare = -np.mean(ss_stoch["ss_per_scenario"][stoch_tail_idx])
    cvar_tail_welfare = -np.mean(ss_cvar["ss_per_scenario"][cvar_tail_idx])
    det_tail_welfare = -np.mean(ss_det["ss_per_scenario"][det_tail_idx])

    stoch_tail_dist = np.mean(np.abs(z_pi - np.array(z_Pi)[stoch_tail_idx]))
    cvar_tail_dist = np.mean(np.abs(cvar_pi - np.array(cvar_Pi)[cvar_tail_idx]))
    det_tail_dist = np.mean(np.abs(pi_det - Pi_det[det_tail_idx]))

    # Log diagnostics/output results analysis
    _print_case_diag("Stochastic", probs, z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi, logfile=logfile)
    _print_case_diag("CVaR", probs, cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi, logfile=logfile)
    _print_case_diag("Deterministic", probs, g_det, d_det, G_det_rt, D_det_rt, pi_det, Pi_det, logfile=logfile)
    _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i, logfile=logfile)

    _log("\n===== COST SUMMARY =====", logfile)
    _log(
        f"Stochastic | E_cost={stoch_cost_summary['E_cost']:.2f}, "
        f"VaR={stoch_cost_summary['VaR']:.2f}, "
        f"CVaR={stoch_cost_summary['CVaR']:.2f}, "
        f"RiskAdjustedTotalCost={stoch_cost_summary['RiskAdjustedTotalCost']:.2f}",
        logfile
    )
    _log(
        f"CVaR       | E_cost={cvar_cost_summary['E_cost']:.2f}, "
        f"VaR={cvar_cost_summary['VaR']:.2f}, "
        f"CVaR={cvar_cost_summary['CVaR']:.2f}, "
        f"RiskAdjustedTotalCost={cvar_cost_summary['RiskAdjustedTotalCost']:.2f}",
        logfile
    )
    _log(
        f"Deterministic | E_cost={det_cost_summary['E_cost']:.2f}, "
        f"VaR={det_cost_summary['VaR']:.2f}, "
        f"CVaR={det_cost_summary['CVaR']:.2f}, "
        f"RiskAdjustedTotalCost={det_cost_summary['RiskAdjustedTotalCost']:.2f}",
        logfile
    )

    return {
        "prob_feasible": prob_f,
        "stoch_distortion": z_dist, "stoch_regret": z_reg, "stoch_ss": ss_stoch["E_social_surplus"],
        "stoch_tail_welfare": stoch_tail_welfare, "stoch_tail_distortion": stoch_tail_dist,
        "cvar_distortion": cvar_dist, "cvar_regret": cvar_reg, "cvar_ss": ss_cvar["E_social_surplus"],
        "cvar_tail_welfare": cvar_tail_welfare, "cvar_tail_distortion": cvar_tail_dist,
        "det_distortion": det_dist, "det_regret": det_reg, "det_ss": ss_det["E_social_surplus"],
        "det_tail_welfare": det_tail_welfare, "det_tail_distortion": det_tail_dist,
    }

In [12]:
NUM_INSTANCES = 10
NUM_SCENARIOS = 500
rng = np.random.default_rng(2025)

max_start = T - NUM_SCENARIOS
if max_start <= 0:
    raise ValueError(f"Need at least {NUM_SCENARIOS} time steps; have {T}")

# Random start indices for each instance (non-overlapping or random)
start_indices = rng.integers(0, max_start + 1, size=NUM_INSTANCES)

results_list = []
for i in range(NUM_INSTANCES):
    start = int(start_indices[i])
    probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
        solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
        solar_buses, wind_buses, start_idx=start, num_scenarios=NUM_SCENARIOS, rng=rng
    )
    print(f"the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are {probs.shape}, {mc_g_i.shape}, {mv_d_j.shape}, {g_i_bar.shape}, {d_j_bar.shape}")
    res = run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=debug_log)
    results_list.append(res)
    print(f"Instance {i+1}/{NUM_INSTANCES} (start={start}) done.")

the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:44:34 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:44:35 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:44:35 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:44:35 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:44:35 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:44:36 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:44:36 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:44:36 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:44:36 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:44:38 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:44:50 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:44:50 PM: Finished problem compilation (took 1.518e+01 seconds).
(CVXPY) Apr 25 08:44:50 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter Username
Set parameter LicenseID to value 2797952
Academic license - for non-commercial use only - expires 2027-03-25
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xd9df9dec
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 681 columns
Presolve time: 0.04s
Presolved: 11501 rows, 15830 columns, 41968 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.097e+04
 Factor NZ  : 1.125e+05 (roughly 12 MB of memory)
 Factor Ops : 1.709e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.74337938e+07 -3.90382156e+08  3.83e+05 5.79e+02  5.75e+05     0s
   1  -2.73512714e+07 -1.76110305e+08  4.29e+04 2.09e+01  3.90e+04     0s
   2  -1.61248432e+07 -5.98020382e+07  1.40e+03 7.74e-01  3.78e+03     0s
   3  -2.37836424e+07 -2.77608005e+07  2.24e+01 6.12e-01  2.58e+02     0s
   4  -2.37836424e+07 -2.77608005e+07  2.24e+01 6.12e-01  2.58e+02     0s
   5  -4.74560394e+07 -2.80745356e+10  3.84e+05 1.14e-13  4.40e+07     0s
   6  -1.14973661e+07 -2.55745043e+10  1.93e+04 4.86e+01  5.42e+06     0s
   7  -3.19902612e+05 -3.46297133e+09  3.48e+02 1.65e+00  3.22e+05     0s
   8  -4.88963638e+06 -6.87378245e+07  6.41e-08 8.11e-01  4.33e+03     0s
   9  -2.41976860e+07 -2.99960510e+07  1.69e-09 1.50e-01  3.78e+02     0s
  10  -2.41976860e+07 -2.99960510e+07  1.69e-09 1.50e-01  3.78e+02     0s
  11  -2.41976860e+07 -2.99960510e+07  1.69e-09 1.50e-01  3.78e+02     0s
  12  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  13  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  14  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  15  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  16  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  17  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  18  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  19  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  20  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  21  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s
  22  -2.57900813e+07 -2.73289681e+07  2.91e-11 1.30e-02  9.73e+01     0s

Barrier performed 22 iterations in 0.24 seconds (0.24 work units)
Sub-optimal termination - objective -2.57900813e+07

Crossover log...

   11353 DPushes remaining with DInf 0.0000000e+00                 0s

Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4144   -2.6914229e+07   0.000000e+00   0.000000e+00      0s

Solved in 4144 iterations and 0.25 seconds (0.49 work units)
Optimal objective -2.691422873e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:44:51 PM: Problem status: optimal
(CVXPY) Apr 25 08:44:51 PM: Optimal value: -2.691e+07
(CVXPY) Apr 25 08:44:51 PM: Compilation took 1.518e+01 seconds
(CVXPY) Apr 25 08:44:51 PM: Solver (including time spent in interface) took 3.471e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:44:55 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:44:56 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:44:56 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:44:56 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:44:56 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:44:58 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:44:58 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:44:58 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:45:00 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:45:05 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:45:31 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:45:31 PM: Finished problem compilation (took 3.484e+01 seconds).
(CVXPY) Apr 25 08:45:31 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0xd104a270
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 681 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27331 columns, 90425 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.734e+04
 Factor NZ  : 1.582e+05 (roughly 20 MB of memory)
 Factor Ops : 1.481e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.31672799e+08 -1.38392432e+09  1.02e+07 1.28e+01  8.06e+06     0s
   1   1.93124063e+08 -6.14053715e+08  1.32e+05 2.29e+00  4.46e+05     0s
   2   1.93142760e+08 -6.14098548e+08  1.32e+05 7.87e+01  4.43e+05     0s
   3   1.93142760e+08 -6.14098548e+08  1.32e+05 7.87e+01  4.43e+05     0s
   4   2.31672799e+08 -3.49770561e+11  1.02e+07 1.28e+01  2.10e+09     0s
   5   4.77390744e+08 -3.14982706e+11  9.01e+04 6.63e+00  4.55e+07     0s
   6   4.77400344e+08 -3.14982880e+11  9.01e+04 9.54e+02  4.50e+07     0s
   7   1.29912548e+09 -9.01917066e+10  2.23e+04 9.22e+01  1.56e+07     0s
   8   1.29912548e+09 -9.01917066e+10  2.23e+04 9.22e+01  1.56e+07     0s
   9   1.29912548e+09 -9.01917066e+10  2.23e+04 9.22e+01  1.56e+07     0s
  10   1.29912548e+09 -9.01917066e+10  2.23e+04 9.22e+01  1.56e+07     0s
  11   2.31672799e+08 -3.49770561e+11  1.02e+07 1.28e+01  2.10e+09     0s
  12   8.34694923e+07 -2.58922896e+10  1.41e+05 5.61e+01  5.73e+07     0s
  13   7.75969163e+07 -3.20394680e+09  1.09e+04 6.93e+00  3.95e+06     0s
  14   4.30428606e+07 -1.27374997e+08  8.91e+01 1.45e+00  1.46e+05     0s
  15  -1.52174547e+07 -3.13528423e+07  6.83e+00 1.29e+00  4.92e+03     0s
  16  -1.52180455e+07 -3.13534748e+07  6.83e+00 2.35e+00  4.91e+03     0s
  17  -1.52173836e+07 -3.13556983e+07  6.83e+00 7.18e+01  4.79e+03     0s
  18  -1.52174899e+07 -3.13558741e+07  6.83e+00 8.42e+01  4.65e+03     0s
  19  -1.56010704e+07 -3.12530015e+07  6.62e+00 2.92e+02  4.32e+03     0s
  20  -1.56010704e+07 -3.12530015e+07  6.62e+00 2.92e+02  4.32e+03     0s
  21  -1.56010704e+07 -3.12530015e+07  6.62e+00 2.92e+02  4.32e+03     0s
  22  -1.56010704e+07 -3.12530015e+07  6.62e+00 2.92e+02  4.31e+03     1s
  23  -1.56049612e+07 -3.12578702e+07  6.62e+00 8.14e+02  4.28e+03     1s
  24  -1.56256847e+07 -3.12594075e+07  6.62e+00 1.22e+03  4.28e+03     1s
  25  -1.56256847e+07 -3.12594075e+07  6.62e+00 1.22e+03  4.27e+03     1s
  26  -1.56256847e+07 -3.12594075e+07  6.62e+00 1.22e+03  4.27e+03     1s

Barrier performed 26 iterations in 0.60 seconds (0.59 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10450   -2.9491278e+07   0.000000e+00   0.000000e+00      1s

Solved in 10450 iterations and 0.98 seconds (2.14 work units)
Optimal objective -2.949127773e+07

(CVXPY) Apr 25 08:45:33 PM: Problem status: optimal
(CVXPY) Apr 25 08:45:33 PM: Optimal value: -2.949e+07
(CVXPY) Apr 25 08:45:33 PM: Compilation took 3.484e+01 seconds
(CVXPY) Apr 25 08:45:33 PM: Solver (including time spent in interface) took 1.122e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 1/10 (start=3696) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:45:37 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:45:37 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:45:37 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:45:37 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:45:37 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:45:38 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:45:38 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:45:38 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:45:38 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:45:40 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:45:52 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:45:52 PM: Finished problem compilation (took 1.507e+01 seconds).
(CVXPY) Apr 25 08:45:52 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xf19ec54b
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 22000 rows and 902 columns
Presolve time: 0.03s
Presolved: 11501 rows, 15609 columns, 41305 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.030e+04
 Factor NZ  : 1.119e+05 (roughly 12 MB of memory)
 Factor Ops : 1.705e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.16067175e+07 -3.64094000e+08  3.04e+05 5.75e+02  4.39e+05     0s
   1  -2.64372322e+07 -1.55020327e+08  3.09e+04 3.06e+01  3.53e+04     0s
   2  -1.71663583e+07 -4.98699018e+07  5.82e+02 2.83e+00  3.54e+03     0s
   3  -2.40076066e+07 -2.76091369e+07  2.63e+01 1.89e+00  2.76e+02     0s
   4  -2.47784121e+07 -2.66995993e+07  1.79e+01 6.04e-01  1.26e+02     0s
   5  -2.47784121e+07 -2.66995993e+07  1.79e+01 6.04e-01  1.26e+02     0s
   6  -4.16296832e+07 -2.73040739e+10  3.04e+05 1.14e-13  3.52e+07     0s
   7  -1.18928478e+07 -2.28974360e+10  1.24e+04 3.88e+01  3.89e+06     0s
   8  -4.50266419e+06 -1.43806537e+09  1.79e+02 1.60e+00  9.96e+04     0s
   9  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s
  10  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s
  11  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s
  12  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s
  13  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s
  14  -1.79523138e+07 -7.35001998e+07  7.59e-01 1.31e+01  3.62e+03     0s

Barrier performed 14 iterations in 0.21 seconds (0.15 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4174   -2.6614685e+07   0.000000e+00   0.000000e+00      0s

Solved in 4174 iterations and 0.29 seconds (0.52 work units)
Optimal objective -2.661468530e+07

(CVXPY) Apr 25 08:45:53 PM: Problem status: optimal
(CVXPY) Apr 25 08:45:53 PM: Optimal value: -2.661e+07
(CVXPY) Apr 25 08:45:53 PM: Compilation took 1.507e+01 seconds
(CVXPY) Apr 25 08:45:53 PM: Solver (including time spent in interface) took 3.651e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:45:56 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:45:57 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:45:57 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:45:57 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:45:57 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:45:58 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:45:58 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:45:58 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:46:01 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:46:06 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:46:31 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:46:32 PM: Finished problem compilation (took 3.435e+01 seconds).
(CVXPY) Apr 25 08:46:32 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0xcb0deb49
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 33000 rows and 902 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27110 columns, 89099 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.469e+04
 Factor NZ  : 1.587e+05 (roughly 20 MB of memory)
 Factor Ops : 1.522e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.79652910e+08 -1.30087863e+09  8.21e+06 1.28e+01  6.33e+06     0s
   1   1.47415713e+08 -5.65219789e+08  2.73e+05 9.87e+01  6.19e+05     0s
   2   1.47415713e+08 -5.65219789e+08  2.73e+05 9.87e+01  6.19e+05     0s
   3   1.79652910e+08 -3.38446908e+11  8.21e+06 1.28e+01  1.69e+09     0s
   4   3.67690191e+08 -2.84581179e+11  1.55e+05 1.08e+02  3.03e+08     0s
   5   3.76201185e+08 -4.23642026e+10  2.21e+04 1.45e+01  4.11e+07     0s
   6   3.76200744e+08 -4.23642176e+10  2.21e+04 7.92e+02  4.09e+07     0s
   7   4.33361341e+08 -4.09873528e+10  1.85e+04 9.86e+02  3.78e+07     0s
   8   4.18523620e+08 -1.59210593e+09  3.17e+02 3.23e+00  3.06e+05     0s
   9   4.18523620e+08 -1.59210593e+09  3.17e+02 3.23e+00  3.06e+05     0s
  10   4.18523620e+08 -1.59210593e+09  3.17e+02 3.23e+00  3.06e+05     0s
  11   1.79652910e+08 -3.38446908e+11  8.21e+06 1.28e+01  1.69e+09     0s
  12   7.68253064e+07 -2.15859164e+10  1.56e+05 6.03e+01  4.81e+07     0s
  13   3.72844840e+07 -9.88329816e+08  3.28e+03 3.09e+00  7.33e+05     0s
  14   1.96488624e+07 -6.36821464e+07  3.51e+01 5.71e-01  4.68e+04     0s
  15  -1.73694427e+07 -3.14167355e+07  2.24e+00 8.03e-01  2.71e+03     0s
  16  -1.73702207e+07 -3.14175159e+07  2.24e+00 3.26e+01  2.69e+03     0s
  17  -1.73700413e+07 -3.14173261e+07  2.24e+00 3.43e+01  2.69e+03     0s
  18  -1.73700413e+07 -3.14173261e+07  2.24e+00 3.43e+01  2.68e+03     0s
  19  -1.73700413e+07 -3.14173261e+07  2.24e+00 3.43e+01  2.68e+03     0s

Barrier performed 19 iterations in 0.38 seconds (0.39 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   13759   -2.9189824e+07   0.000000e+00   0.000000e+00      1s

Solved in 13759 iterations and 0.92 seconds (2.21 work units)
Optimal objective -2.918982384e+07

(CVXPY) Apr 25 08:46:33 PM: Problem status: optimal
(CVXPY) Apr 25 08:46:33 PM: Optimal value: -2.919e+07
(CVXPY) Apr 25 08:46:33 PM: Compilation took 3.435e+01 seconds
(CVXPY) Apr 25 08:46:33 PM: Solver (including time spent in interface) took 1.053e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 2/10 (start=8215) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:46:37 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:46:38 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:46:38 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:46:38 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:46:38 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:46:39 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:46:39 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:46:39 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:46:39 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:46:41 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:46:54 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:46:54 PM: Finished problem compilation (took 1.608e+01 seconds).
(CVXPY) Apr 25 08:46:54 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xf4d095de
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [9e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 909 columns
Presolve time: 0.04s
Presolved: 11501 rows, 15602 columns, 41284 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.028e+04
 Factor NZ  : 1.119e+05 (roughly 12 MB of memory)
 Factor Ops : 1.705e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.19479808e+07 -4.43206704e+08  3.04e+05 5.75e+02  5.42e+05     0s
   1  -2.49299028e+07 -1.88159345e+08  2.92e+04 3.72e+01  4.79e+04     0s
   2  -1.58803098e+07 -5.28471772e+07  5.29e+02 3.26e+00  4.17e+03     0s
   3  -2.32352957e+07 -2.80104803e+07  2.29e+01 4.49e+00  3.69e+02     0s
   4  -2.32352957e+07 -2.80104803e+07  2.29e+01 4.49e+00  3.69e+02     0s
   5  -4.19670427e+07 -2.72621972e+10  3.04e+05 1.14e-13  3.51e+07     0s
   6  -1.20427727e+07 -2.28979412e+10  1.24e+04 3.92e+01  3.91e+06     0s
   7  -4.58881077e+06 -1.73818820e+09  2.13e+02 2.41e+00  1.32e+05     0s
   8  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s
   9  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s
  10  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s
  11  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s
  12  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s
  13  -1.35383773e+07 -4.72990127e+07  6.44e-01 1.87e+00  2.25e+03     0s

Barrier performed 13 iterations in 0.16 seconds (0.14 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4066   -2.6678351e+07   0.000000e+00   0.000000e+00      0s

Solved in 4066 iterations and 0.26 seconds (0.48 work units)
Optimal objective -2.667835059e+07

(CVXPY) Apr 25 08:46:55 PM: Problem status: optimal
(CVXPY) Apr 25 08:46:55 PM: Optimal value: -2.668e+07
(CVXPY) Apr 25 08:46:55 PM: Compilation took 1.608e+01 seconds
(CVXPY) Apr 25 08:46:55 PM: Solver (including time spent in interface) took 3.335e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:46:57 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:46:59 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:46:59 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:46:59 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:46:59 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:47:00 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:47:00 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:47:00 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:47:02 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:47:07 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:47:34 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:47:34 PM: Finished problem compilation (took 3.525e+01 seconds).
(CVXPY) Apr 25 08:47:34 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0xca33c375
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [9e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 909 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27103 columns, 89057 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.460e+04
 Factor NZ  : 1.588e+05 (roughly 20 MB of memory)
 Factor Ops : 1.525e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.76220578e+08 -1.43324874e+09  8.33e+06 1.28e+01  7.10e+06     0s
   1   1.48501954e+08 -6.30179749e+08  3.03e+05 1.15e+02  7.24e+05     0s
   2   1.48498695e+08 -6.30168871e+08  3.03e+05 3.24e+02  7.16e+05     0s
   3   1.48498695e+08 -6.30168871e+08  3.03e+05 3.24e+02  7.16e+05     0s
   4   1.76220578e+08 -3.37738027e+11  8.33e+06 1.28e+01  1.72e+09     0s
   5   3.78656117e+08 -2.81669338e+11  7.80e+04 9.97e+00  4.14e+07     0s
   6   3.76291680e+08 -3.46858560e+10  2.88e+03 6.25e+01  3.17e+06     0s
   7   3.76254442e+08 -3.46858617e+10  2.88e+03 1.81e+02  3.16e+06     0s
   8   3.76165378e+08 -3.46858600e+10  2.88e+03 7.74e+02  3.14e+06     0s
   9   3.76165378e+08 -3.46858600e+10  2.88e+03 7.74e+02  3.14e+06     0s
  10   3.76165378e+08 -3.46858600e+10  2.88e+03 7.74e+02  3.14e+06     0s
  11   1.76220578e+08 -3.37738027e+11  8.33e+06 1.28e+01  1.72e+09     0s
  12   7.51915525e+07 -2.13202716e+10  1.49e+05 5.97e+01  4.75e+07     0s
  13   3.66619559e+07 -9.60873245e+08  3.12e+03 3.48e+00  7.19e+05     0s
  14   1.33716581e+07 -6.41910816e+07  1.75e+01 8.57e-01  4.17e+04     0s
  15   1.33712875e+07 -6.41896302e+07  1.75e+01 5.78e+01  4.13e+04     0s
  16   1.33712875e+07 -6.41896302e+07  1.75e+01 5.78e+01  4.13e+04     0s
  17   1.33698064e+07 -6.41912319e+07  1.75e+01 1.72e+02  4.07e+04     0s
  18   1.33698064e+07 -6.41912319e+07  1.75e+01 1.72e+02  4.07e+04     0s
  19   1.33698064e+07 -6.41912319e+07  1.75e+01 1.72e+02  4.07e+04     0s

Barrier performed 19 iterations in 0.44 seconds (0.44 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   14525   -2.9259282e+07   0.000000e+00   0.000000e+00      1s

Solved in 14525 iterations and 0.95 seconds (2.40 work units)
Optimal objective -2.925928175e+07

(CVXPY) Apr 25 08:47:36 PM: Problem status: optimal
(CVXPY) Apr 25 08:47:36 PM: Optimal value: -2.926e+07
(CVXPY) Apr 25 08:47:36 PM: Compilation took 3.525e+01 seconds
(CVXPY) Apr 25 08:47:36 PM: Solver (including time spent in interface) took 1.083e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 3/10 (start=8199) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:47:39 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:47:40 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:47:40 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:47:40 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:47:40 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:47:41 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:47:41 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:47:41 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:47:41 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:47:43 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:47:54 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:47:54 PM: Finished problem compilation (took 1.442e+01 seconds).
(CVXPY) Apr 25 08:47:54 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0x1bcb6221
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 693 columns
Presolve time: 0.03s
Presolved: 11501 rows, 15818 columns, 41932 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.093e+04
 Factor NZ  : 1.125e+05 (roughly 12 MB of memory)
 Factor Ops : 1.708e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.42893380e+07 -3.50025133e+08  3.59e+05 5.80e+02  5.14e+05     0s
   1  -2.53133183e+07 -1.64972843e+08  3.22e+04 2.32e+01  3.46e+04     0s
   2  -1.66130717e+07 -5.65301180e+07  1.09e+03 2.32e+00  3.44e+03     0s
   3  -2.41962713e+07 -2.82217006e+07  1.76e+01 6.06e-01  2.71e+02     0s
   4  -2.58214067e+07 -2.71150758e+07  6.09e+00 1.34e+00  8.33e+01     0s
   5  -2.62657411e+07 -2.70348760e+07  3.36e+00 6.59e-01  4.93e+01     0s
   6  -2.63499828e+07 -2.69574026e+07  2.84e+00 4.38e-01  3.89e+01     0s
   7  -2.65217290e+07 -2.69249440e+07  1.83e+00 1.32e-01  2.58e+01     0s
   8  -2.67130984e+07 -2.68702466e+07  7.39e-01 3.29e-01  1.00e+01     0s
   9  -2.67799242e+07 -2.68647109e+07  3.82e-01 1.13e-01  5.39e+00     0s
  10  -2.68248447e+07 -2.68608961e+07  1.54e-01 4.02e-02  2.29e+00     0s
  11  -2.68418997e+07 -2.68603778e+07  7.37e-02 1.02e-02  1.17e+00     0s
  12  -2.68569366e+07 -2.68598993e+07  8.08e-03 2.77e-02  1.88e-01     0s
  13  -2.68592114e+07 -2.68595146e+07  2.28e-04 6.45e-04  1.93e-02     0s
  14  -2.68593065e+07 -2.68594452e+07  1.03e-04 2.88e-04  8.84e-03     0s
  15  -2.68593293e+07 -2.68594312e+07  7.25e-05 2.23e-04  6.49e-03     0s
  16  -2.68593506e+07 -2.68594144e+07  4.49e-05 1.33e-04  4.07e-03     0s
  17  -2.68593597e+07 -2.68594084e+07  3.37e-05 9.59e-05  3.10e-03     0s
  18  -2.68593766e+07 -2.68594029e+07  1.28e-05 7.15e-05  1.68e-03     0s
  19  -2.68593823e+07 -2.68593975e+07  5.69e-06 4.88e-05  9.76e-04     0s
  20  -2.68593835e+07 -2.68593962e+07  3.96e-06 4.23e-05  8.12e-04     0s
  21  -2.68593844e+07 -2.68593944e+07  2.84e-06 3.38e-05  6.38e-04     0s
  22  -2.68593849e+07 -2.68593923e+07  2.22e-06 2.40e-05  4.73e-04     0s
  23  -2.68593862e+07 -2.68593904e+07  5.61e-07 1.63e-05  2.68e-04     0s
  24  -2.68593865e+07 -2.68593889e+07  2.97e-07 9.90e-06  1.56e-04     0s
  25  -2.68593867e+07 -2.68593885e+07  1.09e-07 7.95e-06  1.19e-04     0s
  26  -2.68593868e+07 -2.68593873e+07  7.34e-08 1.64e-06  3.46e-05     0s
  27  -2.68593869e+07 -2.68593869e+07  5.94e-09 3.21e-08  7.33e-07     0s
  28  -2.68593869e+07 -2.68593869e+07  7.28e-12 1.61e-08  3.11e-08     0s
  29  -2.68593869e+07 -2.68593869e+07  1.13e-10 3.24e-09  3.71e-10     0s

Barrier solved model in 29 iterations and 0.23 seconds (0.23 work units)
Optimal objective -2.68593869e+07

Crossover log...

    4023 DPushes remaining with DInf 0.0000000e+00                 0s

Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4188   -2.6859387e+07   0.000000e+00   0.000000e+00      0s

Solved in 4188 iterations and 0.25 seconds (0.52 work units)
Optimal objective -2.685938688e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:47:55 PM: Problem status: optimal
(CVXPY) Apr 25 08:47:55 PM: Optimal value: -2.686e+07
(CVXPY) Apr 25 08:47:55 PM: Compilation took 1.442e+01 seconds
(CVXPY) Apr 25 08:47:55 PM: Solver (including time spent in interface) took 3.303e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:47:58 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:48:00 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:48:00 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:48:00 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:48:00 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:48:01 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:48:01 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:48:01 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:48:03 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:48:08 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:48:34 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:48:34 PM: Finished problem compilation (took 3.456e+01 seconds).
(CVXPY) Apr 25 08:48:34 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0x2de10ae9
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 693 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27319 columns, 90353 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.720e+04
 Factor NZ  : 1.582e+05 (roughly 20 MB of memory)
 Factor Ops : 1.483e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.16671350e+08 -1.23396539e+09  9.63e+06 1.28e+01  7.36e+06     0s
   1   1.81869712e+08 -5.61175394e+08  1.07e+05 1.93e+00  4.16e+05     0s
   2   1.81871805e+08 -5.61172230e+08  1.07e+05 3.17e+02  4.14e+05     0s
   3   1.93075060e+08 -2.13235446e+08  4.03e+04 5.72e+01  1.43e+05     0s
   4   1.93044423e+08 -2.13236205e+08  4.03e+04 6.54e+02  1.37e+05     0s
   5   1.93207245e+08 -2.13139258e+08  4.03e+04 8.54e+02  1.34e+05     0s
   6   1.92697559e+08 -2.13197316e+08  4.03e+04 2.12e+03  1.29e+05     0s
   7   1.92697559e+08 -2.13197316e+08  4.03e+04 2.12e+03  1.29e+05     0s
   8   2.16671350e+08 -3.22647503e+11  9.63e+06 1.28e+01  1.98e+09     0s
   9   4.49101877e+08 -2.95939579e+11  8.39e+04 4.42e+00  4.27e+07     0s
  10   4.35957078e+08 -2.95814372e+10  2.73e+03 4.68e+00  2.48e+06     0s
  11   4.36010478e+08 -2.95814380e+10  2.73e+03 2.10e+02  2.47e+06     0s
  12   4.36581716e+08 -2.95814524e+10  2.73e+03 2.81e+02  2.47e+06     0s
  13   2.16671350e+08 -3.22647503e+11  9.63e+06 1.28e+01  1.98e+09     0s
  14   7.67873375e+07 -2.39097188e+10  1.22e+05 5.48e+01  5.31e+07     0s
  15   6.87010368e+07 -2.60027721e+09  9.23e+03 5.98e+00  3.19e+06     0s
  16   3.65560206e+07 -1.08035447e+08  6.23e+01 4.37e-01  1.23e+05     0s
  17   3.65466894e+07 -1.08028190e+08  6.23e+01 1.43e+02  1.19e+05     0s
  18  -1.67950949e+07 -3.41925025e+07  6.86e+00 2.01e+01  6.89e+03     0s
  19  -1.67953421e+07 -3.41915868e+07  6.86e+00 2.19e+01  6.71e+03     0s
  20  -1.67993054e+07 -3.41889645e+07  6.85e+00 2.77e+01  6.58e+03     0s
  21  -1.67990854e+07 -3.41897123e+07  6.85e+00 6.52e+02  6.57e+03     0s
  22  -1.69069052e+07 -3.41049468e+07  6.76e+00 7.62e+02  6.41e+03     0s
  23  -1.69027158e+07 -3.41097149e+07  6.76e+00 7.99e+02  6.18e+03     0s
  24  -1.69029326e+07 -3.41098638e+07  6.76e+00 8.26e+02  5.89e+03     0s
  25  -2.83230747e+07 -2.96273257e+07  4.37e-01 4.96e+01  9.71e+01     1s
  26  -2.83231462e+07 -2.96274086e+07  4.37e-01 5.07e+01  9.44e+01     1s
  27  -2.83231431e+07 -2.96273964e+07  4.37e-01 5.16e+01  9.44e+01     1s
  28  -2.84277594e+07 -2.95800518e+07  3.93e-01 4.29e+01  7.66e+01     1s
  29  -2.82724373e+07 -2.95322561e+07  3.72e-01 1.67e+01  7.54e+01     1s
  30  -2.86782430e+07 -2.94981838e+07  2.36e-01 1.40e+01  4.00e+01     1s
  31  -2.89287560e+07 -2.94984995e+07  1.72e-01 1.40e+01  2.78e+01     1s

Barrier performed 31 iterations in 0.67 seconds (0.75 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    8964   -2.9438790e+07   0.000000e+00   0.000000e+00      1s

Solved in 8964 iterations and 0.68 seconds (1.58 work units)
Optimal objective -2.943878962e+07

(CVXPY) Apr 25 08:48:36 PM: Problem status: optimal
(CVXPY) Apr 25 08:48:36 PM: Optimal value: -2.944e+07
(CVXPY) Apr 25 08:48:36 PM: Compilation took 3.456e+01 seconds
(CVXPY) Apr 25 08:48:36 PM: Solver (including time spent in interface) took 8.092e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 4/10 (start=3155) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:48:39 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:48:40 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:48:40 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:48:40 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:48:40 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:48:40 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:48:40 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:48:40 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:48:40 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:48:43 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:48:55 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:48:55 PM: Finished problem compilation (took 1.569e+01 seconds).
(CVXPY) Apr 25 08:48:55 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0x4fcc2b61
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 920 columns
Presolve time: 0.04s
Presolved: 11501 rows, 15591 columns, 41251 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.025e+04
 Factor NZ  : 1.118e+05 (roughly 12 MB of memory)
 Factor Ops : 1.705e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.15705164e+07 -3.41380157e+08  3.03e+05 5.74e+02  4.15e+05     0s
   1  -2.65655032e+07 -1.46335350e+08  3.40e+04 2.91e+01  3.28e+04     0s
   2  -1.74338458e+07 -4.66335462e+07  1.04e+03 2.02e+00  2.91e+03     0s
   3  -2.42128110e+07 -2.71725462e+07  1.82e+01 2.33e+00  2.08e+02     0s
   4  -2.42128110e+07 -2.71725462e+07  1.82e+01 2.33e+00  2.08e+02     0s
   5  -4.15945770e+07 -2.69331767e+10  3.04e+05 1.14e-13  3.51e+07     0s
   6  -1.18465638e+07 -2.27063620e+10  1.23e+04 3.84e+01  3.85e+06     0s
   7  -4.48990261e+06 -1.67715495e+09  2.32e+02 1.88e+00  1.29e+05     0s
   8  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s
   9  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s
  10  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s
  11  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s
  12  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s
  13  -1.35470058e+07 -5.11331823e+07  3.55e+00 1.53e+00  2.53e+03     0s

Barrier performed 13 iterations in 0.15 seconds (0.14 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4333   -2.6497524e+07   0.000000e+00   0.000000e+00      0s

Solved in 4333 iterations and 0.27 seconds (0.61 work units)
Optimal objective -2.649752399e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:48:56 PM: Problem status: optimal
(CVXPY) Apr 25 08:48:56 PM: Optimal value: -2.650e+07
(CVXPY) Apr 25 08:48:56 PM: Compilation took 1.569e+01 seconds
(CVXPY) Apr 25 08:48:56 PM: Solver (including time spent in interface) took 3.442e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:48:59 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:49:00 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:49:00 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:49:00 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:49:00 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:49:01 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:49:01 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:49:01 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:49:04 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:49:09 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:49:35 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:49:35 PM: Finished problem compilation (took 3.484e+01 seconds).
(CVXPY) Apr 25 08:49:35 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0x79028f9a
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 920 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27092 columns, 88991 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.447e+04
 Factor NZ  : 1.593e+05 (roughly 20 MB of memory)
 Factor Ops : 1.542e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.78993548e+08 -1.25741938e+09  8.30e+06 1.28e+01  6.27e+06     0s
   1   1.49036404e+08 -5.13183703e+08  1.23e+05 5.34e+00  3.49e+05     0s
   2   1.49049459e+08 -5.13217739e+08  1.23e+05 7.94e+01  3.47e+05     0s
   3   1.49055840e+08 -5.13228019e+08  1.23e+05 1.89e+02  3.46e+05     0s
   4   1.49046568e+08 -5.13098912e+08  1.23e+05 1.79e+02  3.44e+05     0s
   5   1.49202819e+08 -5.13109837e+08  1.23e+05 1.11e+02  3.42e+05     0s
   6   1.49202819e+08 -5.13089511e+08  1.23e+05 1.22e+02  3.41e+05     0s
   7   1.78993548e+08 -3.33264161e+11  8.30e+06 1.28e+01  1.71e+09     0s
   8   3.83474013e+08 -2.79415435e+11  8.06e+04 5.74e+00  4.08e+07     0s
   9   3.79350650e+08 -3.15297238e+10  2.89e+03 2.56e+00  2.69e+06     0s
  10   3.78561238e+08 -3.15296435e+10  2.89e+03 3.06e+02  2.68e+06     0s
  11   3.78561238e+08 -3.15296435e+10  2.89e+03 3.06e+02  2.68e+06     0s
  12   1.78993548e+08 -3.33264161e+11  8.30e+06 1.28e+01  1.71e+09     0s
  13   7.61708350e+07 -2.08893812e+10  1.57e+05 5.94e+01  4.70e+07     0s
  14   3.75025711e+07 -6.98674848e+08  2.11e+03 2.00e+00  5.40e+05     0s
  15   9.68131362e+06 -5.44834199e+07  1.54e+01 2.90e-01  3.47e+04     0s
  16   9.68129393e+06 -5.44834583e+07  1.54e+01 3.71e+01  3.44e+04     0s
  17   9.68129393e+06 -5.44834583e+07  1.54e+01 3.71e+01  3.44e+04     0s
  18   9.68230540e+06 -5.44827257e+07  1.54e+01 2.80e+01  3.38e+04     0s
  19   9.66915819e+06 -5.43972216e+07  1.54e+01 5.86e+02  3.36e+04     0s
  20   9.66915819e+06 -5.43972216e+07  1.54e+01 5.86e+02  3.36e+04     0s
  21   9.66925137e+06 -5.43969965e+07  1.54e+01 5.50e+02  3.32e+04     0s
  22   9.66925137e+06 -5.43969965e+07  1.54e+01 5.50e+02  3.32e+04     0s
  23   9.66925137e+06 -5.43969965e+07  1.54e+01 5.50e+02  3.32e+04     0s
  24   9.66925137e+06 -5.43969965e+07  1.54e+01 5.50e+02  3.32e+04     1s
  25   9.66925137e+06 -5.43969965e+07  1.54e+01 5.50e+02  3.32e+04     1s

Barrier performed 25 iterations in 0.53 seconds (0.56 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   15016   -2.9081311e+07   0.000000e+00   0.000000e+00      1s

Solved in 15016 iterations and 1.06 seconds (2.71 work units)
Optimal objective -2.908131096e+07

(CVXPY) Apr 25 08:49:36 PM: Problem status: optimal
(CVXPY) Apr 25 08:49:36 PM: Optimal value: -2.908e+07
(CVXPY) Apr 25 08:49:36 PM: Compilation took 3.484e+01 seconds
(CVXPY) Apr 25 08:49:36 PM: Solver (including time spent in interface) took 1.189e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 5/10 (start=7877) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:49:40 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:49:41 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:49:41 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:49:41 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:49:41 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:49:42 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:49:42 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:49:42 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:49:42 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:49:44 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:49:56 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:49:56 PM: Finished problem compilation (took 1.514e+01 seconds).
(CVXPY) Apr 25 08:49:56 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0x9d678b39
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e-05, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 904 columns
Presolve time: 0.03s
Presolved: 11501 rows, 15607 columns, 41299 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.030e+04
 Factor NZ  : 1.119e+05 (roughly 12 MB of memory)
 Factor Ops : 1.705e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.22352194e+07 -2.93456587e+08  3.26e+05 1.15e+03  7.76e+05     0s
   1  -2.69250797e+07 -1.35376087e+08  3.73e+04 4.31e+01  5.48e+04     0s
   2  -1.83998430e+07 -4.56053589e+07  1.01e+03 7.23e-01  4.37e+03     0s
   3  -2.48863690e+07 -2.77170321e+07  6.61e+01 3.45e-01  3.84e+02     0s
   4  -2.59721915e+07 -2.71140934e+07  2.88e+01 1.43e+00  1.52e+02     0s
   5  -2.62699557e+07 -2.70259599e+07  1.94e+01 1.57e+00  1.00e+02     0s
   6  -2.64345876e+07 -2.69899204e+07  1.44e+01 1.61e-01  7.33e+01     0s
   7  -2.66352813e+07 -2.69720044e+07  8.24e+00 4.63e-01  4.44e+01     0s
   8  -2.67546383e+07 -2.69581784e+07  4.85e+00 2.57e-01  2.68e+01     0s
   9  -2.68132511e+07 -2.69536324e+07  3.26e+00 2.37e-01  1.84e+01     0s
  10  -2.68443459e+07 -2.69487210e+07  2.50e+00 4.60e-01  1.37e+01     0s
  11  -2.68980940e+07 -2.69480363e+07  1.13e+00 2.66e-01  6.55e+00     0s
  12  -2.69208787e+07 -2.69474130e+07  5.77e-01 5.37e-02  3.48e+00     0s
  13  -2.69451593e+07 -2.69472408e+07  1.47e-02 3.45e-02  2.69e-01     0s
  14  -2.69462251e+07 -2.69467382e+07  3.92e-03 3.08e-03  6.65e-02     0s
  15  -2.69464533e+07 -2.69466904e+07  1.78e-03 1.78e-03  3.07e-02     0s
  16  -2.69465287e+07 -2.69466719e+07  1.02e-03 1.07e-03  1.85e-02     0s
  17  -2.69465784e+07 -2.69466642e+07  5.37e-04 6.92e-04  1.11e-02     0s
  18  -2.69465975e+07 -2.69466571e+07  3.59e-04 4.96e-04  7.71e-03     0s
  19  -2.69466108e+07 -2.69466502e+07  2.34e-04 3.16e-04  5.10e-03     0s
  20  -2.69466188e+07 -2.69466464e+07  1.63e-04 2.34e-04  3.58e-03     0s
  21  -2.69466213e+07 -2.69466461e+07  1.41e-04 2.26e-04  3.20e-03     0s
  22  -2.69466253e+07 -2.69466443e+07  1.05e-04 1.76e-04  2.46e-03     0s
  23  -2.69466279e+07 -2.69466434e+07  8.11e-05 1.51e-04  2.00e-03     0s
  24  -2.69466308e+07 -2.69466427e+07  5.59e-05 1.31e-04  1.53e-03     0s
  25  -2.69466324e+07 -2.69466417e+07  4.28e-05 1.02e-04  1.21e-03     0s
  26  -2.69466332e+07 -2.69466411e+07  3.52e-05 8.48e-05  1.01e-03     0s
  27  -2.69466359e+07 -2.69466404e+07  1.35e-05 6.66e-05  5.81e-04     0s

Barrier performed 27 iterations in 0.23 seconds (0.21 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4129   -2.6946638e+07   0.000000e+00   0.000000e+00      0s

Solved in 4129 iterations and 0.24 seconds (0.47 work units)
Optimal objective -2.694663783e+07

(CVXPY) Apr 25 08:49:57 PM: Problem status: optimal
(CVXPY) Apr 25 08:49:57 PM: Optimal value: -2.695e+07
(CVXPY) Apr 25 08:49:57 PM: Compilation took 1.514e+01 seconds
(CVXPY) Apr 25 08:49:57 PM: Solver (including time spent in interface) took 3.120e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:50:00 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:50:02 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:50:02 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:50:02 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:50:02 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:50:03 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:50:03 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:50:03 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:50:05 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:50:10 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:50:35 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:50:35 PM: Finished problem compilation (took 3.356e+01 seconds).
(CVXPY) Apr 25 08:50:35 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0xf60ee0fc
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [5e-05, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 904 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27108 columns, 89087 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.466e+04
 Factor NZ  : 1.589e+05 (roughly 20 MB of memory)
 Factor Ops : 1.527e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.18464159e+08 -1.17032430e+09  1.02e+07 1.28e+01  9.78e+06     0s
   1   1.66381284e+08 -4.20736332e+08  1.06e+05 7.69e+00  6.25e+05     0s
   2   1.66388647e+08 -4.20737095e+08  1.06e+05 7.12e+01  6.23e+05     0s
   3   1.66381920e+08 -4.20766450e+08  1.06e+05 5.13e+02  6.14e+05     0s
   4   1.66329566e+08 -4.20776003e+08  1.06e+05 3.96e+02  6.05e+05     0s
   5   1.65890614e+08 -4.20776003e+08  1.06e+05 3.96e+02  6.02e+05     0s
   6   1.65892359e+08 -4.20778350e+08  1.06e+05 2.14e+02  6.02e+05     0s
   7   1.65892359e+08 -4.20778350e+08  1.06e+05 2.14e+02  6.02e+05     0s
   8   2.18464159e+08 -2.46792711e+11  1.02e+07 1.28e+01  2.12e+09     0s
   9   4.51675401e+08 -1.78515996e+11  1.05e+05 1.31e+01  8.16e+07     0s
  10   4.51676996e+08 -1.78516039e+11  1.05e+05 7.68e+02  8.12e+07     0s
  11   4.52058905e+08 -1.78516169e+11  1.05e+05 7.78e+02  8.09e+07     0s
  12   2.18464159e+08 -2.46792711e+11  1.02e+07 1.28e+01  2.12e+09     0s
  13   7.02690421e+07 -3.93645120e+09  7.72e+04 1.18e+01  1.80e+07     0s
  14   2.20058539e+07 -1.56369568e+08  1.48e+03 1.96e+00  2.84e+05     0s
  15  -1.24984245e+07 -3.42386166e+07  8.30e+01 1.70e+00  1.25e+04     0s
  16  -1.24999011e+07 -3.42389286e+07  8.30e+01 9.38e+00  1.23e+04     0s
  17  -1.25002277e+07 -3.42385980e+07  8.30e+01 3.54e+01  1.17e+04     0s
  18  -1.24992274e+07 -3.42395266e+07  8.30e+01 1.30e+02  1.12e+04     0s
  19  -1.25031961e+07 -3.42365781e+07  8.30e+01 2.52e+02  1.09e+04     0s
  20  -1.24757057e+07 -3.42619975e+07  8.31e+01 2.64e+02  1.05e+04     0s
  21  -1.24757146e+07 -3.42616963e+07  8.31e+01 1.78e+02  1.05e+04     0s
  22  -1.24757120e+07 -3.42619187e+07  8.31e+01 3.20e+02  1.05e+04     0s
  23  -1.24348937e+07 -3.42946784e+07  8.34e+01 3.24e+02  9.14e+03     0s
  24  -2.47819153e+07 -3.32034739e+07  1.33e+01 2.76e+02  3.33e+03     0s
  25  -2.58610646e+07 -3.13076331e+07  9.12e+00 1.71e+02  1.77e+03     1s
  26  -2.71249224e+07 -2.99533885e+07  5.00e+00 7.48e+01  6.24e+02     1s
  27  -2.89235832e+07 -2.95436117e+07  1.12e+00 2.22e+01  5.88e+01     1s
  28  -2.90228333e+07 -2.95706780e+07  9.93e-01 2.46e+05  4.46e+01     1s
  29  -2.90233523e+07 -2.95395462e+07  9.76e-01 2.31e+05  4.22e+01     1s
  30  -2.90100977e+07 -2.94994159e+07  9.60e-01 2.25e+05  4.25e+01     1s
  31  -2.90270450e+07 -2.95550881e+07  9.54e-01 2.19e+05  4.19e+01     1s
  32  -2.90567690e+07 -2.95832498e+07  9.15e-01 2.45e+05  4.66e+01     1s
  33  -2.90679698e+07 -2.95811823e+07  8.92e-01 2.40e+05  4.46e+01     1s
  34  -2.90921270e+07 -2.95715002e+07  8.46e-01 1.78e+05  3.07e+01     1s
  35  -2.90939262e+07 -2.95797060e+07  8.18e-01 1.71e+05  2.97e+01     1s
  36  -2.91328819e+07 -2.95819574e+07  7.54e-01 1.44e+05  2.37e+01     1s
  37  -2.91397057e+07 -2.95859046e+07  7.52e-01 1.44e+05  2.35e+01     1s
  38  -2.91789823e+07 -2.95841842e+07  6.71e-01 1.40e+05  2.11e+01     1s
  39  -2.91802559e+07 -2.95487408e+07  6.61e-01 1.24e+05  1.84e+01     1s
  40  -2.92181502e+07 -2.95339230e+07  5.47e-01 1.14e+05  1.58e+01     1s
  41  -2.92685587e+07 -2.94922602e+07  3.69e-01 7.84e+04  1.04e+01     1s
  42  -2.93170446e+07 -2.95000921e+07  3.15e-01 7.25e+04  8.15e+00     1s
  43  -2.93499205e+07 -2.94926676e+07  2.21e-01 6.52e+04  6.67e+00     1s
  44  -2.93278307e+07 -2.94728441e+07  2.25e-01 6.66e+04  7.48e+00     1s
  45  -2.93592816e+07 -2.94763519e+07  1.84e-01 5.72e+04  5.41e+00     1s
  46  -2.93593869e+07 -2.94764895e+07  1.81e-01 5.65e+04  5.39e+00     1s
  47  -2.93559447e+07 -2.94695621e+07  1.80e-01 5.43e+04  5.63e+00     1s
  48  -2.93534240e+07 -2.94681970e+07  1.82e-01 5.49e+04  5.75e+00     1s
  49  -2.93588072e+07 -2.94687332e+07  1.79e-01 5.51e+04  5.90e+00     1s

Barrier performed 49 iterations in 0.85 seconds (0.97 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   13679   -2.9531107e+07   0.000000e+00   0.000000e+00      1s

Solved in 13679 iterations and 0.86 seconds (1.95 work units)
Optimal objective -2.953110749e+07

(CVXPY) Apr 25 08:50:36 PM: Problem status: optimal
(CVXPY) Apr 25 08:50:36 PM: Optimal value: -2.953e+07
(CVXPY) Apr 25 08:50:36 PM: Compilation took 3.356e+01 seconds
(CVXPY) Apr 25 08:50:36 PM: Solver (including time spent in interface) took 9.900e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 6/10 (start=6833) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:50:41 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:50:42 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:50:42 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:50:42 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:50:42 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:50:42 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:50:42 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:50:42 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:50:42 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:50:45 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:50:58 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:50:58 PM: Finished problem compilation (took 1.643e+01 seconds).
(CVXPY) Apr 25 08:50:58 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0x2b31bf1f
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 683 columns
Presolve time: 0.03s
Presolved: 11501 rows, 15828 columns, 41962 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.096e+04
 Factor NZ  : 1.125e+05 (roughly 12 MB of memory)
 Factor Ops : 1.709e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -5.73629945e+07 -4.39573266e+08  4.50e+05 5.81e+02  6.52e+05     0s
   1  -3.27658666e+07 -1.88015654e+08  4.35e+04 2.82e+01  4.59e+04     0s
   2  -1.51254745e+07 -6.70519261e+07  1.79e+03 1.00e+00  4.67e+03     0s
   3  -2.35629938e+07 -2.80076534e+07  2.08e+01 1.18e+00  2.94e+02     0s
   4  -2.54226344e+07 -2.70518220e+07  8.17e+00 1.17e+00  1.05e+02     0s
   5  -2.54226344e+07 -2.70518220e+07  8.17e+00 1.17e+00  1.05e+02     0s
   6  -5.73926097e+07 -3.24657196e+10  4.50e+05 1.14e-13  5.16e+07     0s
   7  -1.36805027e+07 -2.78533652e+10  2.44e+04 4.67e+01  6.20e+06     0s
   8   2.21632588e+06 -3.42539042e+09  4.07e+02 1.41e+00  2.41e+05     0s
   9  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s
  10  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s
  11  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s
  12  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s
  13  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s
  14  -1.41083517e+07 -7.59254967e+07  3.16e+00 6.73e+00  3.97e+03     0s

Barrier performed 14 iterations in 0.15 seconds (0.15 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4143   -2.6804022e+07   0.000000e+00   0.000000e+00      0s

Solved in 4143 iterations and 0.24 seconds (0.53 work units)
Optimal objective -2.680402159e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:50:59 PM: Problem status: optimal
(CVXPY) Apr 25 08:50:59 PM: Optimal value: -2.680e+07
(CVXPY) Apr 25 08:50:59 PM: Compilation took 1.643e+01 seconds
(CVXPY) Apr 25 08:50:59 PM: Solver (including time spent in interface) took 3.145e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:51:01 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:51:03 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:51:03 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:51:03 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:51:03 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:51:04 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:51:04 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:51:04 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:51:06 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:51:11 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:51:38 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:51:38 PM: Finished problem compilation (took 3.461e+01 seconds).
(CVXPY) Apr 25 08:51:38 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0xdad6333f
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 683 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27329 columns, 90413 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.732e+04
 Factor NZ  : 1.582e+05 (roughly 20 MB of memory)
 Factor Ops : 1.481e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.64634872e+08 -1.16161288e+09  1.22e+07 6.40e+00  6.66e+06     0s
   1   2.64638595e+08 -1.16157278e+09  1.22e+07 7.55e+02  6.32e+06     0s
   2   2.64638595e+08 -1.16157278e+09  1.22e+07 7.55e+02  6.32e+06     0s
   3   2.64634872e+08 -4.20686353e+11  1.22e+07 6.40e+00  2.51e+09     0s
   4   5.89292914e+08 -3.72657001e+11  1.47e+05 6.60e+01  3.06e+08     0s
   5   6.20009596e+08 -4.20379103e+10  9.82e+03 3.89e+00  8.69e+06     0s
   6   6.20000461e+08 -4.20379153e+10  9.82e+03 1.48e+02  8.58e+06     0s
   7   6.19999167e+08 -4.20378995e+10  9.82e+03 3.18e+02  8.47e+06     0s
   8   6.19785396e+08 -4.20382622e+10  9.82e+03 6.33e+02  8.36e+06     0s
   9   6.19914980e+08 -4.20382794e+10  9.82e+03 1.09e+03  8.26e+06     0s
  10   6.19673030e+08 -4.20395975e+10  9.82e+03 1.59e+03  8.15e+06     0s
  11   2.64634872e+08 -4.20686353e+11  1.22e+07 6.40e+00  2.51e+09     0s
  12   1.00501195e+08 -2.94589984e+10  2.06e+05 6.37e+01  6.78e+07     0s
  13   9.78678368e+07 -4.94662589e+09  1.59e+04 1.06e+01  6.41e+06     0s
  14   6.17498963e+07 -1.50650651e+08  3.03e+02 4.46e-01  1.93e+05     0s
  15   6.17450928e+07 -1.50647125e+08  3.03e+02 3.36e+01  1.89e+05     0s
  16   6.17475586e+07 -1.50637245e+08  3.03e+02 9.29e+01  1.85e+05     0s
  17   6.17443183e+07 -1.50629948e+08  3.03e+02 7.21e+01  1.80e+05     0s
  18   6.17782841e+07 -1.50112500e+08  3.03e+02 3.48e+02  1.76e+05     0s
  19   6.17750082e+07 -1.50105735e+08  3.03e+02 3.47e+02  1.76e+05     0s
  20   6.17496323e+07 -1.50229145e+08  3.03e+02 1.93e+02  1.74e+05     0s
  21   6.17250885e+07 -1.50474273e+08  3.03e+02 2.33e+02  1.70e+05     0s
  22   6.17249397e+07 -1.50502400e+08  3.03e+02 3.08e+02  1.70e+05     0s
  23   4.64679104e+07 -1.33488419e+08  2.34e+02 1.78e+02  1.38e+05     0s
  24  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     0s
  25  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  26  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  27  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  28  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  29  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  30  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  31  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  32  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  33  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s
  34  -1.45989173e+06 -3.80272264e+07  4.06e+01 3.62e+01  1.91e+04     1s

Barrier performed 34 iterations in 0.68 seconds (0.73 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   12178   -2.9391016e+07   0.000000e+00   0.000000e+00      1s

Solved in 12178 iterations and 0.86 seconds (1.90 work units)
Optimal objective -2.939101582e+07

(CVXPY) Apr 25 08:51:39 PM: Problem status: optimal
(CVXPY) Apr 25 08:51:39 PM: Optimal value: -2.939e+07
(CVXPY) Apr 25 08:51:39 PM: Compilation took 3.461e+01 seconds
(CVXPY) Apr 25 08:51:39 PM: Solver (including time spent in interface) took 9.893e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 7/10 (start=5282) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:51:43 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:51:43 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:51:43 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:51:43 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:51:43 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:51:44 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:51:44 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:51:44 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:51:44 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:51:46 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:51:58 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:51:58 PM: Finished problem compilation (took 1.513e+01 seconds).
(CVXPY) Apr 25 08:51:58 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xfc204171
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 22000 rows and 899 columns
Presolve time: 0.03s
Presolved: 11501 rows, 15612 columns, 41314 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.031e+04
 Factor NZ  : 1.119e+05 (roughly 12 MB of memory)
 Factor Ops : 1.705e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.14236837e+07 -3.61187915e+08  3.24e+05 5.76e+02  4.86e+05     0s
   1  -2.45388989e+07 -1.65425779e+08  3.15e+04 3.05e+01  3.78e+04     0s
   2  -1.66596967e+07 -6.04616461e+07  7.28e+02 3.08e+00  4.31e+03     0s
   3  -2.37164444e+07 -2.76944475e+07  1.83e+01 1.11e+00  2.75e+02     0s
   4  -2.37164444e+07 -2.76944475e+07  1.83e+01 1.11e+00  2.75e+02     0s
   5  -4.14443236e+07 -2.60575983e+10  3.24e+05 1.14e-13  3.73e+07     0s
   6  -1.09095255e+07 -2.34938649e+10  1.35e+04 4.10e+01  4.21e+06     0s
   7  -3.26718612e+06 -2.08842020e+09  2.49e+02 1.47e+00  1.70e+05     0s
   8  -1.08350507e+07 -5.91862411e+07  5.01e-02 6.26e-01  3.35e+03     0s
   9  -1.08350507e+07 -5.91862411e+07  5.01e-02 6.26e-01  3.35e+03     0s
  10  -1.08350507e+07 -5.91862411e+07  5.01e-02 6.26e-01  3.35e+03     0s
  11  -1.08350507e+07 -5.91862411e+07  5.01e-02 6.26e-01  3.35e+03     0s
  12  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  13  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  14  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  15  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  16  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  17  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  18  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s
  19  -1.24988252e+07 -3.49457969e+07  1.09e-11 1.22e-01  1.44e+03     0s

Barrier performed 19 iterations in 0.23 seconds (0.23 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4173   -2.6831934e+07   0.000000e+00   0.000000e+00      0s

Solved in 4173 iterations and 0.24 seconds (0.50 work units)
Optimal objective -2.683193399e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:51:59 PM: Problem status: optimal
(CVXPY) Apr 25 08:51:59 PM: Optimal value: -2.683e+07
(CVXPY) Apr 25 08:51:59 PM: Compilation took 1.513e+01 seconds
(CVXPY) Apr 25 08:51:59 PM: Solver (including time spent in interface) took 3.110e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:52:02 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:52:04 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:52:04 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:52:04 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:52:04 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:52:05 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:52:05 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:52:05 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:52:07 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:52:12 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:52:38 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:52:38 PM: Finished problem compilation (took 3.409e+01 seconds).
(CVXPY) Apr 25 08:52:38 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0x026f4bd7
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 33000 rows and 899 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27113 columns, 89117 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.472e+04
 Factor NZ  : 1.589e+05 (roughly 20 MB of memory)
 Factor Ops : 1.526e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.86420693e+08 -9.01322001e+08  9.19e+06 1.28e+01  1.02e+07     0s
   1   1.48968151e+08 -4.10262785e+08  1.11e+05 5.62e+00  6.26e+05     0s
   2   1.48984050e+08 -4.10316396e+08  1.11e+05 2.14e+02  6.16e+05     0s
   3   1.48984050e+08 -4.10316396e+08  1.11e+05 2.14e+02  6.16e+05     0s
   4   1.86420693e+08 -1.60911981e+11  9.19e+06 1.28e+01  1.89e+09     0s
   5   3.58195056e+08 -1.43370240e+11  1.18e+05 1.34e+01  7.06e+07     0s
   6   3.62252550e+08 -1.48289773e+10  2.68e+03 2.94e+00  2.73e+06     0s
   7   3.62317174e+08 -1.48289831e+10  2.68e+03 2.93e+02  2.72e+06     0s
   8   3.61780646e+08 -1.48288541e+10  2.68e+03 2.43e+02  2.72e+06     0s
   9   3.61780646e+08 -1.48288541e+10  2.68e+03 2.43e+02  2.72e+06     0s
  10   3.61780646e+08 -1.48288541e+10  2.68e+03 2.43e+02  2.72e+06     0s
  11   1.86420693e+08 -1.60911981e+11  9.19e+06 1.28e+01  1.89e+09     0s
  12   6.26395555e+07 -3.49816057e+09  2.31e+05 9.70e+00  1.91e+07     0s
  13   7.59655475e+05 -3.60821613e+08  1.77e+03 1.49e+00  3.50e+05     0s
  14  -1.02645001e+07 -3.62720717e+07  8.30e+00 5.81e-01  2.01e+04     0s
  15  -2.65504237e+07 -2.98960039e+07  5.56e-01 1.91e+00  1.05e+03     0s
  16  -2.65503592e+07 -2.98959382e+07  5.56e-01 6.88e+00  1.03e+03     0s
  17  -2.65502801e+07 -2.98957443e+07  5.56e-01 3.77e+00  1.02e+03     0s
  18  -2.77217630e+07 -2.95582605e+07  3.20e-01 1.33e+01  4.24e+02     0s
  19  -2.77221112e+07 -2.95581972e+07  3.20e-01 6.56e+03  4.16e+02     0s
  20  -2.77264649e+07 -2.95564995e+07  3.19e-01 7.33e+03  4.06e+02     0s
  21  -2.89597225e+07 -2.94785997e+07  9.19e-02 2.35e+03  7.64e+01     1s
  22  -2.90936099e+07 -2.94821436e+07  6.93e-02 2.01e+03  5.87e+01     1s
  23  -2.91451327e+07 -2.94714523e+07  5.87e-02 1.55e+03  4.57e+01     1s
  24  -2.92877372e+07 -2.94638770e+07  3.24e-02 8.38e+02  2.97e+01     1s
  25  -2.93705457e+07 -2.94361872e+07  1.22e-02 2.48e+02  1.12e+01     1s
  26  -2.93887596e+07 -2.94240377e+07  6.68e-03 1.02e+02  5.84e+00     1s
  27  -2.94004895e+07 -2.94200305e+07  2.77e-03 6.75e+01  3.44e+00     1s
  28  -2.94050313e+07 -2.94180403e+07  1.66e-03 5.08e+01  2.33e+00     1s
  29  -2.94068406e+07 -2.94177885e+07  1.21e-03 4.87e+01  2.01e+00     1s
  30  -2.94084361e+07 -2.94168082e+07  7.50e-04 4.16e+01  1.58e+00     1s
  31  -2.94088149e+07 -2.94164174e+07  6.51e-04 3.86e+01  1.44e+00     1s
  32  -2.94089521e+07 -2.94162469e+07  6.13e-04 3.74e+01  1.38e+00     1s
  33  -2.94097334e+07 -2.94154206e+07  3.71e-04 3.11e+01  1.09e+00     1s
  34  -2.94104131e+07 -2.94144926e+07  2.00e-04 2.43e+01  8.06e-01     1s
  35  -2.94107458e+07 -2.94135091e+07  3.43e-04 1.69e+01  5.51e-01     1s
  36  -2.94109324e+07 -2.94131932e+07  8.91e-05 1.47e+01  4.57e-01     1s
  37  -2.94109970e+07 -2.94129370e+07  3.06e-04 1.28e+01  3.94e-01     1s
  38  -2.94110817e+07 -2.94127983e+07  2.45e-04 1.18e+01  3.52e-01     1s
  39  -2.94111057e+07 -2.94121080e+07  2.29e-04 6.70e+00  2.04e-01     1s
  40  -2.94111226e+07 -2.94117543e+07  2.29e-04 4.13e+00  1.28e-01     1s
  41  -2.94111383e+07 -2.94116075e+07  2.36e-04 3.07e+00  9.52e-02     1s
  42  -2.94111521e+07 -2.94115638e+07  1.34e-04 2.77e+00  8.48e-02     1s
  43  -2.94111622e+07 -2.94114290e+07  5.94e-05 1.79e+00  5.49e-02     1s
  44  -2.94111676e+07 -2.94113615e+07  3.06e-05 1.30e+00  4.00e-02     1s
  45  -2.94111721e+07 -2.94112961e+07  1.47e-05 8.27e-01  2.55e-02     1s
  46  -2.94111754e+07 -2.94112456e+07  1.53e-05 4.64e-01  1.45e-02     1s
  47  -2.94111771e+07 -2.94112366e+07  9.53e-06 3.99e-01  1.23e-02     1s
  48  -2.94111788e+07 -2.94112177e+07  1.63e-05 2.63e-01  7.91e-03     1s
  49  -2.94111796e+07 -2.94112021e+07  7.50e-06 1.52e-01  4.54e-03     1s
  50  -2.94111803e+07 -2.94111884e+07  1.12e-06 5.46e-02  1.95e-03     1s
  51  -2.94111808e+07 -2.94111820e+07  4.59e-07 5.92e-03  2.65e-04     1s
  52  -2.94111813e+07 -2.94111816e+07  1.05e-08 2.58e-03  8.80e-05     1s
  53  -2.94111813e+07 -2.94111813e+07  2.43e-09 9.82e-06  3.49e-06     1s
  54  -2.94111813e+07 -2.94111813e+07  1.56e-10 4.19e-08  4.52e-08     1s
  55  -2.94111813e+07 -2.94111813e+07  1.60e-10 5.89e-10  2.77e-10     1s

Barrier solved model in 55 iterations and 0.98 seconds (1.04 work units)
Optimal objective -2.94111813e+07

Crossover log...

    5971 DPushes remaining with DInf 0.0000000e+00                 1s

Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   12427   -2.9411181e+07   0.000000e+00   0.000000e+00      1s

Solved in 12427 iterations and 1.03 seconds (2.64 work units)
Optimal objective -2.941118128e+07

(CVXPY) Apr 25 08:52:39 PM: Problem status: optimal
(CVXPY) Apr 25 08:52:39 PM: Optimal value: -2.941e+07
(CVXPY) Apr 25 08:52:39 PM: Compilation took 3.409e+01 seconds
(CVXPY) Apr 25 08:52:39 PM: Solver (including time spent in interface) took 1.155e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 8/10 (start=6916) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:52:43 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:52:43 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:52:43 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:52:43 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:52:43 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:52:44 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:52:44 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:52:44 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:52:44 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:52:46 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:52:57 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:52:57 PM: Finished problem compilation (took 1.379e+01 seconds).
(CVXPY) Apr 25 08:52:57 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xfe13c99e
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 838 columns
Presolve time: 0.04s
Presolved: 11501 rows, 15673 columns, 41497 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.050e+04
 Factor NZ  : 1.121e+05 (roughly 12 MB of memory)
 Factor Ops : 1.706e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.59595623e+07 -3.48934626e+08  3.66e+05 5.77e+02  4.97e+05     0s
   1  -2.71854893e+07 -1.61574127e+08  3.54e+04 2.97e+01  3.85e+04     0s
   2  -1.63115135e+07 -5.22762048e+07  1.41e+03 9.28e-01  3.46e+03     0s
   3  -2.40826229e+07 -2.75031114e+07  1.58e+01 5.21e+00  2.35e+02     0s
   4  -2.40826229e+07 -2.75031114e+07  1.58e+01 5.21e+00  2.35e+02     0s
   5  -4.59845445e+07 -2.75845872e+10  3.67e+05 1.13e-13  4.21e+07     0s
   6  -1.13971195e+07 -2.48723039e+10  1.87e+04 4.82e+01  5.21e+06     0s
   7  -9.74296387e+05 -3.14485764e+09  3.63e+02 1.12e+00  2.89e+05     0s
   8  -5.85061290e+06 -6.70108391e+07  5.90e-08 9.18e-01  4.36e+03     0s
   9  -5.85061290e+06 -6.70108391e+07  5.90e-08 9.18e-01  4.36e+03     0s
  10  -5.85061290e+06 -6.70108391e+07  5.90e-08 9.18e-01  4.36e+03     0s
  11  -5.85061290e+06 -6.70108391e+07  5.90e-08 9.18e-01  4.36e+03     0s
  12  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  13  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  14  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  15  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  16  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  17  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s
  18  -1.02084221e+07 -4.49165535e+07  8.11e-09 1.67e-01  2.55e+03     0s

Barrier performed 18 iterations in 0.22 seconds (0.22 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4099   -2.6721114e+07   0.000000e+00   0.000000e+00      0s

Solved in 4099 iterations and 0.23 seconds (0.45 work units)
Optimal objective -2.672111393e+07

(CVXPY) Apr 25 08:52:58 PM: Problem status: optimal
(CVXPY) Apr 25 08:52:58 PM: Optimal value: -2.672e+07
(CVXPY) Apr 25 08:52:58 PM: Compilation took 1.379e+01 seconds
(CVXPY) Apr 25 08:52:58 PM: Solver (including time spent in interface) took 3.155e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:53:01 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:53:02 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:53:02 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:53:02 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:53:02 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:53:04 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:53:04 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:53:04 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:53:05 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:53:11 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:53:38 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:53:38 PM: Finished problem compilation (took 3.590e+01 seconds).
(CVXPY) Apr 25 08:53:38 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0x25503a0f
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 838 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27174 columns, 89483 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.546e+04
 Factor NZ  : 1.584e+05 (roughly 20 MB of memory)
 Factor Ops : 1.505e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.18420421e+08 -1.27779438e+09  9.75e+06 1.28e+01  7.26e+06     0s
   1   2.18403992e+08 -1.27781438e+09  9.75e+06 1.29e+03  6.85e+06     0s
   2   2.18403992e+08 -1.27781438e+09  9.75e+06 1.29e+03  6.85e+06     0s
   3   2.18420421e+08 -3.42752604e+11  9.75e+06 1.28e+01  2.01e+09     0s
   4   4.53960508e+08 -3.05082833e+11  9.03e+04 5.01e+00  4.49e+07     0s
   5   4.46302802e+08 -3.44546467e+10  3.08e+03 1.99e+00  2.93e+06     0s
   6   4.46240489e+08 -3.44546888e+10  3.08e+03 2.31e+02  2.92e+06     0s
   7   4.45570976e+08 -3.44547960e+10  3.08e+03 1.48e+01  2.92e+06     0s
   8   4.45570976e+08 -3.44547960e+10  3.08e+03 1.48e+01  2.92e+06     0s
   9   4.45570976e+08 -3.44547960e+10  3.08e+03 1.48e+01  2.92e+06     0s
  10   4.45570976e+08 -3.44547960e+10  3.08e+03 1.48e+01  2.92e+06     0s

Barrier performed 10 iterations in 0.28 seconds (0.25 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   14799   -2.9296581e+07   0.000000e+00   0.000000e+00      1s

Solved in 14799 iterations and 0.90 seconds (2.03 work units)
Optimal objective -2.929658123e+07

(CVXPY) Apr 25 08:53:40 PM: Problem status: optimal
(CVXPY) Apr 25 08:53:40 PM: Optimal value: -2.930e+07
(CVXPY) Apr 25 08:53:40 PM: Compilation took 3.590e+01 seconds
(CVXPY) Apr 25 08:53:40 PM: Solver (including time spent in interface) took 1.024e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 9/10 (start=6330) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (10,), (1,), (500, 10), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Apr 25 08:53:43 PM: Your problem has 5511 variables, 11501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:53:44 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:53:44 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:53:44 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:53:44 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:53:45 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:53:45 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:53:45 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 25 08:53:45 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:53:47 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:54:00 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:54:00 PM: Finished problem compilation (took 1.587e+01 seconds).
(CVXPY) Apr 25 08:54:00 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 33501 rows, 16511 columns and 66011 nonzeros
Model fingerprint: 0xd169ec3f
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 22000 rows and 924 columns
Presolve time: 0.06s
Presolved: 11501 rows, 15587 columns, 41239 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 11
 Free vars  : 11
 AA' NZ     : 3.024e+04
 Factor NZ  : 1.118e+05 (roughly 12 MB of memory)
 Factor Ops : 1.704e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.25375675e+07 -3.75466736e+08  3.03e+05 5.75e+02  4.53e+05     0s
   1  -2.64094597e+07 -1.59395710e+08  3.43e+04 3.24e+01  3.82e+04     0s
   2  -1.70459637e+07 -6.08534240e+07  8.50e+02 2.88e+00  4.48e+03     0s
   3  -2.36988207e+07 -2.76989315e+07  1.15e+01 1.75e+00  2.84e+02     0s
   4  -2.36988207e+07 -2.76989315e+07  1.15e+01 1.75e+00  2.84e+02     0s
   5  -4.25606662e+07 -2.72918227e+10  3.04e+05 1.14e-13  3.51e+07     0s
   6  -1.23300238e+07 -2.28353624e+10  1.23e+04 3.70e+01  3.80e+06     0s
   7  -4.89298936e+06 -1.70638623e+09  2.28e+02 8.71e-01  1.29e+05     0s
   8  -1.40224357e+07 -5.14328149e+07  1.19e+01 2.70e+00  2.57e+03     0s
   9  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  10  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  11  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  12  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  13  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  14  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  15  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  16  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  17  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  18  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s
  19  -2.46574774e+07 -2.83943329e+07  9.37e-01 2.13e+00  2.45e+02     0s

Barrier performed 19 iterations in 0.23 seconds (0.20 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4295   -2.6709503e+07   0.000000e+00   0.000000e+00      0s

Solved in 4295 iterations and 0.27 seconds (0.55 work units)
Optimal objective -2.670950253e+07
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:54:00 PM: Problem status: optimal
(CVXPY) Apr 25 08:54:00 PM: Optimal value: -2.671e+07
(CVXPY) Apr 25 08:54:00 PM: Compilation took 1.587e+01 seconds
(CVXPY) Apr 25 08:54:00 PM: Solver (including time spent in interface) took 3.476e-01 seconds

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Apr 25 08:54:03 PM: Your problem has 6012 variables, 12001 constraints, and 0 parameters.
(CVXPY) Apr 25 08:54:04 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 25 08:54:04 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 25 08:54:04 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Apr 25 08:54:04 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Apr 25 08:54:06 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Apr 25 08:54:06 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Apr 25 08:54:06 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Apr 25 08:54:08 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Apr 25 08:54:12 PM: Applying reduction QpMatrixStuffing
(CVXPY) Apr 25 08:54:40 PM: Applying reduction GUROBI
(CVXPY) Apr 25 08:54:40 PM: Finished problem compilation (took 3.532e+01 seconds).
(CVXPY) Apr 25 08:54:40 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 56001 rows, 28012 columns and 127511 nonzeros
Model fingerprint: 0x2b992f27
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 33000 rows and 924 columns
Presolve time: 0.04s
Presolved: 23001 rows, 27088 columns, 88967 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 12
 Free vars  : 12
 AA' NZ     : 9.442e+04
 Factor NZ  : 1.593e+05 (roughly 20 MB of memory)
 Factor Ops : 1.542e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.04018172e+08 -1.40288727e+09  1.01e+07 1.28e+01  1.09e+07     0s
   1   1.75016491e+08 -1.01261327e+09  4.76e+06 6.18e+02  5.17e+06     0s
   2   1.75016491e+08 -1.01261327e+09  4.76e+06 6.18e+02  5.17e+06     0s
   3   2.04018172e+08 -2.62285173e+11  1.01e+07 1.28e+01  2.09e+09     0s
   4   3.73032380e+08 -1.87232830e+11  2.39e+05 1.11e+02  3.84e+08     0s
   5   3.78891691e+08 -2.11319235e+10  3.92e+04 8.04e+00  3.02e+07     0s
   6   3.69374329e+08 -2.53428646e+09  1.94e+03 5.08e-01  7.85e+05     0s
   7   3.69449121e+08 -2.53424806e+09  1.94e+03 1.50e+02  7.81e+05     0s
   8   3.69557951e+08 -2.53424827e+09  1.94e+03 4.85e+02  7.78e+05     0s
   9   3.68866152e+08 -2.53427760e+09  1.94e+03 5.72e+02  7.69e+05     0s
  10   3.68866152e+08 -2.53427760e+09  1.94e+03 5.72e+02  7.69e+05     0s
  11   2.04018172e+08 -2.62285173e+11  1.01e+07 1.28e+01  2.09e+09     0s
  12   1.10431687e+08 -2.79489534e+10  3.58e+05 9.73e+01  1.24e+08     0s
  13   9.11701289e+07 -2.86132696e+09  2.05e+04 1.01e+01  6.85e+06     0s
  14   4.11176021e+07 -9.02589540e+07  2.41e+02 1.59e+00  1.86e+05     0s
  15   4.11169740e+07 -9.02602699e+07  2.41e+02 8.69e+01  1.82e+05     0s
  16   4.11220373e+07 -9.02366341e+07  2.41e+02 1.10e+02  1.73e+05     0s
  17   3.12952444e+07 -7.90865484e+07  2.02e+02 8.36e+01  1.34e+05     0s
  18   3.13082059e+07 -7.92965146e+07  2.02e+02 1.07e+02  1.32e+05     0s
  19   3.10801313e+07 -7.90303539e+07  2.01e+02 1.26e+02  1.30e+05     0s
  20   2.88279554e+07 -7.63795096e+07  1.92e+02 5.77e+01  1.20e+05     0s
  21   9.60725487e+06 -4.66448643e+07  1.12e+02 1.01e+02  5.00e+04     0s
  22   9.55979490e+06 -4.63885545e+07  1.12e+02 1.46e+03  4.89e+04     0s
  23   9.55899606e+06 -4.63887183e+07  1.12e+02 1.47e+03  4.89e+04     1s
  24   9.55873963e+06 -4.63891194e+07  1.12e+02 1.51e+03  4.88e+04     1s
  25   9.52141723e+06 -4.63289466e+07  1.11e+02 8.12e+02  4.79e+04     1s
  26   9.52162466e+06 -4.63285299e+07  1.11e+02 7.70e+02  4.79e+04     1s
  27   9.52162466e+06 -4.63285299e+07  1.11e+02 7.70e+02  4.79e+04     1s
  28   9.52096162e+06 -4.63281291e+07  1.11e+02 8.18e+02  4.79e+04     1s
  29   9.51151999e+06 -4.63199420e+07  1.11e+02 7.72e+02  4.78e+04     1s
  30   9.51089659e+06 -4.63193456e+07  1.11e+02 7.11e+02  4.76e+04     1s
  31   9.49488974e+06 -4.62389478e+07  1.11e+02 9.62e+03  4.72e+04     1s
  32   9.41990264e+06 -4.61143594e+07  1.11e+02 9.44e+03  4.52e+04     1s

Barrier performed 32 iterations in 0.70 seconds (0.64 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   18028   -2.9297998e+07   0.000000e+00   0.000000e+00      1s

Solved in 18028 iterations and 1.41 seconds (2.64 work units)
Optimal objective -2.929799811e+07

(CVXPY) Apr 25 08:54:42 PM: Problem status: optimal
(CVXPY) Apr 25 08:54:42 PM: Optimal value: -2.930e+07
(CVXPY) Apr 25 08:54:42 PM: Compilation took 3.532e+01 seconds
(CVXPY) Apr 25 08:54:42 PM: Solver (including time spent in interface) took 1.545e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 10/10 (start=8061) done.

In [13]:
# Aggregate and average
keys = list(results_list[0].keys())
means = {k: np.mean([r[k] for r in results_list]) for k in keys}
stds = {k: np.std([r[k] for r in results_list]) for k in keys}

print("============== Real-data results (averaged over {} instances) ================".format(NUM_INSTANCES))
print("Distortion (DA vs E[RT price]):")
print("  Stochastic:", means["stoch_distortion"], "±", stds["stoch_distortion"])
print("  CVaR:", means["cvar_distortion"], "±", stds["cvar_distortion"])
print("  Deterministic:", means["det_distortion"], "±", stds["det_distortion"])
print("E[Social Surplus]:")
print("  Stochastic:", means["stoch_ss"], "±", stds["stoch_ss"])
print("  CVaR:", means["cvar_ss"], "±", stds["cvar_ss"])
print("  Deterministic:", means["det_ss"], "±", stds["det_ss"])
print("Tail (5%) welfare (mean positive SS in worst tail):")
print("  Stochastic:", means["stoch_tail_welfare"], "±", stds["stoch_tail_welfare"])
print("  CVaR:", means["cvar_tail_welfare"], "±", stds["cvar_tail_welfare"])
print("  Deterministic:", means["det_tail_welfare"], "±", stds["det_tail_welfare"])
print("Tail (5%) price distortion:")
print("  Stochastic:", means["stoch_tail_distortion"], "±", stds["stoch_tail_distortion"])
print("  CVaR:", means["cvar_tail_distortion"], "±", stds["cvar_tail_distortion"])
print("  Deterministic:", means["det_tail_distortion"], "±", stds["det_tail_distortion"])
print("Probability feasible:", means["prob_feasible"], "±", stds["prob_feasible"])

============== Real-data results (averaged over 10 instances) ================
Distortion (DA vs E[RT price]):
  Stochastic: 0.16819282522926643 ± 0.07806781490385745
  CVaR: 110.22211520562048 ± 0.08311298545890572
  Deterministic: 327.159378727471 ± 57.63444246622435
E[Social Surplus]:
  Stochastic: 26757738.536068495 ± 132777.23886825083
  CVaR: 26757216.579716254 ± 132566.21914937
  Deterministic: 26451556.706609238 ± 135091.76268224782
Tail (5%) welfare (mean positive SS in worst tail):
  Stochastic: 25806372.615412332 ± 44420.63408768873
  CVaR: 25816493.03541882 ± 43870.25614436774
  Deterministic: 25781098.420765825 ± 42949.94296159389
Tail (5%) price distortion:
  Stochastic: 100.00000000000054 ± 1.038627808283258e-12
  CVaR: 6.109585552904134e-13 ± 2.474392568442086e-13
  Deterministic: 100.0 ± 0.0
Probability feasible: 0.191265120431626 ± 0.11050471512986863

In [14]:
summary = pd.DataFrame({
    "Method": ["Stochastic", "CVaR", "Deterministic"] * 3,
    "Metric": ["Distortion", "Distortion", "Distortion", "E[SS]", "E[SS]", "E[SS]", "Tail welfare", "Tail welfare", "Tail welfare"],
    "Mean": [
        means["stoch_distortion"], means["cvar_distortion"], means["det_distortion"],
        means["stoch_ss"], means["cvar_ss"], means["det_ss"],
        means["stoch_tail_welfare"], means["cvar_tail_welfare"], means["det_tail_welfare"],
    ],
    "Std": [
        stds["stoch_distortion"], stds["cvar_distortion"], stds["det_distortion"],
        stds["stoch_ss"], stds["cvar_ss"], stds["det_ss"],
        stds["stoch_tail_welfare"], stds["cvar_tail_welfare"], stds["det_tail_welfare"],
    ],
})
summary["Std/Mean"] = summary["Std"] / summary["Mean"]
display(summary)

          Method        Metric          Mean            Std  Std/Mean
0     Stochastic    Distortion  1.681928e-01       0.078068  0.464157
1           CVaR    Distortion  1.102221e+02       0.083113  0.000754
2  Deterministic    Distortion  3.271594e+02      57.634442  0.176166
3     Stochastic         E[SS]  2.675774e+07  132777.238868  0.004962
4           CVaR         E[SS]  2.675722e+07  132566.219149  0.004954
5  Deterministic         E[SS]  2.645156e+07  135091.762682  0.005107
6     Stochastic  Tail welfare  2.580637e+07   44420.634088  0.001721
7           CVaR  Tail welfare  2.581649e+07   43870.256144  0.001699
8  Deterministic  Tail welfare  2.578110e+07   42949.942962  0.001666