In [43]:
import os
import numpy as np
import pandas as pd

# Paths: notebook is in zavala_electricity_market, data in dataset/IM-3-GO-WEST
# Run from project root (prj_market) or from zavala_electricity_market
_cwd = os.getcwd()
if os.path.basename(_cwd) == "zavala_electricity_market":
    BASE_DIR = os.path.dirname(_cwd)
else:
    BASE_DIR = _cwd
DATA_DIR = os.path.join(BASE_DIR, "dataset", "IM-3-GO-WEST")
if not os.path.isdir(DATA_DIR):
    DATA_DIR = os.path.join(_cwd, "dataset", "IM-3-GO-WEST")

# Ensure zavala_electricity_market is on path (when running from project root)
import sys
ZAVALA_DIR = os.path.join(BASE_DIR, "zavala_electricity_market")
if os.path.isdir(ZAVALA_DIR) and ZAVALA_DIR not in sys.path:
    sys.path.insert(0, ZAVALA_DIR)

# --- Minimal customization for current repo layout ---

# 1) If the original DATA_DIR doesn't exist, try archive/dataset/IM-3-GO-WEST
if not os.path.isdir(DATA_DIR):
    alt_data_dir = os.path.join(BASE_DIR, "archive", "dataset", "IM-3-GO-WEST")
    if os.path.isdir(alt_data_dir):
        DATA_DIR = alt_data_dir

# 2) If ZAVALA_DIR isn't a valid dir (e.g. code is at repo root),
#    fall back to BASE_DIR itself when it has zavala_funcs.py
if not os.path.isdir(ZAVALA_DIR):
    repo_root_candidate = BASE_DIR
    if os.path.isfile(os.path.join(repo_root_candidate, "zavala_funcs.py")):
        if repo_root_candidate not in sys.path:
            sys.path.insert(0, repo_root_candidate)
        ZAVALA_DIR = repo_root_candidate

print("Using DATA_DIR:", DATA_DIR)
print("Using ZAVALA_DIR:", ZAVALA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

from zavala_funcs import (
    zavala,
    zavala_cvar,
    zavala_deterministic_da,
    zavala_rt_energy_only,
    expected_caps_from_scenarios,
    price_distortion,
    probability_feasible,
    expected_cumulative_regret,
    compute_social_surplus,
    tail_worst_indices_by_value,
    _stack_rt,
)

print("Data dir:", DATA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

Using DATA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Using ZAVALA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']
Data dir: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']

In [44]:
# Load nodal time series (rows = time, columns = bus_XXXXX)
solar = pd.read_csv(os.path.join(DATA_DIR, "nodal_solar.csv"))
wind = pd.read_csv(os.path.join(DATA_DIR, "nodal_wind.csv"))
load_df = pd.read_csv(os.path.join(DATA_DIR, "nodal_load.csv"))
thermal_df = pd.read_csv(os.path.join(DATA_DIR, "thermal_gens.csv"))

T = len(solar)
assert len(wind) == T and len(load_df) == T, "Solar, wind, load must have same length"
print(f"Time steps: {T}")
print(f"Solar columns: {solar.shape[1]}, Wind: {wind.shape[1]}, Load: {load_df.shape[1]}")
print(f"Thermal generators: {len(thermal_df)}")

Time steps: 8760
Solar columns: 125, Wind: 125, Load: 125
Thermal generators: 280

In [45]:
# Choose buses with non-trivial solar: columns with max > threshold
solar_cols = [c for c in solar.columns if solar[c].max() > 50]
wind_cols = [c for c in wind.columns if wind[c].max() > 50]
# Pick x solar and y wind (unreliable)
num_solar, num_wind = 1, 4
num_thermal = 1
solar_buses = solar_cols[:num_solar] if len(solar_cols) >= num_solar else list(solar.columns[:num_solar])
wind_buses = wind_cols[:num_wind] if len(wind_cols) >= num_wind else list(wind.columns[:num_wind])

# Reliable: aggregate thermal by bus, pick 4 buses with largest capacity
thermal_by_bus = thermal_df.groupby("Bus")["Max_Cap"].sum().sort_values(ascending=False)
thermal_buses_numeric = list(thermal_by_bus.head(num_thermal).index)  # e.g. [408441, 135041, ...]
thermal_bus_cols = [f"bus_{b}" for b in thermal_buses_numeric]  # for load alignment if needed

# Load: use total system load (sum over all buses)
load_total = load_df.sum(axis=1).values  # (T,)

print("Solar buses (unreliable):", solar_buses)
print("Wind buses (unreliable):", wind_buses)
print("Thermal buses (reliable):", thermal_buses_numeric)
print("Load: system total (sum over all buses)")

Solar buses (unreliable): ['bus_100931']
Wind buses (unreliable): ['bus_100931', 'bus_102281', 'bus_105701', 'bus_106771']
Thermal buses (reliable): [500991]
Load: system total (sum over all buses)

In [46]:
len(wind_cols)

30

In [47]:
# Filter thermal_df for the selected buses
selected_buses = [500991, 605141, 408441, 261001]
thermal_selected = thermal_df[thermal_df['Bus'].isin(selected_buses)]
display(thermal_selected)

,Name,Bus,Fuel,Max_Cap,Min_Cap,Heat_Rate
0,PHOENIX_Nuc,408441,NUC (Nuclear),4209.60,1046.90,8.530000
1,TONOPAH_NG,408441,NG (Natural Gas),1325.10,393.07,4.177264
2,PHOENIX_NG,408441,NG (Natural Gas),1207.38,449.72,3.622784
28,BRUSH_C,605141,BIT (Bituminous Coal),552.30,78.79,8.941106
29,WELLINGTON_C,605141,BIT (Bituminous Coal),800.40,247.36,8.242654
30,DENVER_C,605141,BIT (Bituminous Coal),586.31,164.07,7.933221
31,KEENESBURG_NG,605141,NG (Natural Gas),685.11,246.77,5.015047
32,BOULDER_C,605141,BIT (Bituminous Coal),251.00,55.58,8.227582
33,PLATTEVILLE_NG,605141,NG (Natural Gas),1185.48,481.17,2.758167
34,AURORA_NG,605141,NG (Natural Gas),397.80,147.60,4.898308
35,COMMERCECITY_NG,605141,NG (Natural Gas),154.20,29.25,4.799750
36,DENVER_NG,605141,NG (Natural Gas),269.01,54.48,3.526185
37,FORTLUPTON_NG,605141,NG (Natural Gas),497.70,120.82,4.718237
38,BURLINGTON_C,605141,BIT (Bituminous Coal),129.40,47.19,7.651625
39,FREDERICK_NG,605141,NG (Natural Gas),394.00,136.49,2.436760
40,BRUSH_NG,605141,NG (Natural Gas),597.22,156.56,3.038616
41,LIMON_NG,605141,NG (Natural Gas),154.20,37.06,4.622871
42,LAMAR_C,605141,BIT (Bituminous Coal),43.50,17.89,7.974531
43,CHEYENNE_NG,605141,NG (Natural Gas),139.99,33.48,4.731375
55,CASTLEDALE_C,500991,BIT (Bituminous Coal),1577.19,296.35,8.900558
56,HUNTINGTON_C,500991,BIT (Bituminous Coal),1037.30,382.51,8.612997
57,OREM_NG,500991,NG (Natural Gas),1392.48,370.22,3.543914
58,MONA_NG,500991,NG (Natural Gas),648.99,208.10,5.030309
59,KEMMERER_C,500991,BIT (Bituminous Coal),831.99,304.11,8.195294
60,HELPER_C,500991,BIT (Bituminous Coal),208.60,49.90,8.192120
61,SALTLAKECITY_NG,500991,NG (Natural Gas),783.49,218.84,3.554682
62,PAYSON_NG,500991,NG (Natural Gas),140.00,43.07,3.959980
63,SUNNYSIDE_C,500991,BIT (Bituminous Coal),58.10,6.34,8.114105
64,MAGNA_C,500991,BIT (Bituminous Coal),213.80,41.00,7.651219
65,BOUNTIFUL_NG,500991,NG (Natural Gas),30.39,8.90,2.977745
77,SUNCITY_NG,261001,NG (Natural Gas),819.00,228.42,2.720162
78,REDONDOBEACH_NG,261001,NG (Natural Gas),1316.40,454.78,5.271419
79,LONGBEACH_NG,261001,NG (Natural Gas),2173.98,657.33,4.487376
80,PLAYADELREY_NG,261001,NG (Natural Gas),823.20,271.80,5.154075
81,HUNTINGTONBEACH_NG,261001,NG (Natural Gas),436.00,100.93,2.516905
82,WILMINGTON_NG,261001,NG (Natural Gas),548.11,163.17,5.168842
83,CARSON_NG,261001,NG (Natural Gas),405.00,135.72,3.373920

Debug Logs

In [48]:
# For diagnostics: breakdown of DA and RT allocations
def _log(msg, logfile=None):
    if logfile is None:
        print(msg)
    else:
        with open(logfile, "a", encoding="utf-8") as f:
            f.write(str(msg) + "\n")

def _tech_breakdown_da(g_da):
    g_da = np.asarray(g_da, dtype=float)
    return {
        "solar": g_da[:3].sum(),
        "wind": g_da[3:6].sum(),
        "thermal": g_da[6:10].sum(),
        "total": g_da.sum(),
    }

def _tech_breakdown_rt(G_rt, probs=None):
    G_rt = np.asarray(G_rt, dtype=float)  # shape (S, 10)
    solar = G_rt[:, :3].sum(axis=1)
    wind = G_rt[:, 3:6].sum(axis=1)
    thermal = G_rt[:, 6:10].sum(axis=1)
    total = G_rt.sum(axis=1)

    if probs is None:
        return {
            "solar": solar.mean(),
            "wind": wind.mean(),
            "thermal": thermal.mean(),
            "total": total.mean(),
        }

    probs = np.asarray(probs, dtype=float)
    return {
        "solar": np.dot(probs, solar),
        "wind": np.dot(probs, wind),
        "thermal": np.dot(probs, thermal),
        "total": np.dot(probs, total),
    }

def _print_case_diag(name, probs, g_da, d_da, G_rt, D_rt, pi, Pi,
                     n_solar, n_wind, n_thermal, logfile=None):
    g_da = np.asarray(g_da, dtype=float)
    d_da = np.asarray(d_da, dtype=float)
    G_rt = np.asarray(G_rt, dtype=float)
    D_rt = np.asarray(D_rt, dtype=float)
    probs = np.asarray(probs, dtype=float)
    Pi = np.asarray(Pi, dtype=float)

    exp_rt = np.dot(probs, G_rt)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    da_alloc = {
        "solar": g_da[solar_slice].sum(),
        "wind": g_da[wind_slice].sum(),
        "thermal": g_da[thermal_slice].sum(),
        "total": g_da.sum(),
    }
    rt_alloc = {
        "solar": exp_rt[solar_slice].sum(),
        "wind": exp_rt[wind_slice].sum(),
        "thermal": exp_rt[thermal_slice].sum(),
        "total": exp_rt.sum(),
    }

    da_load = float(d_da.sum())
    exp_rt_load = float(np.dot(probs, D_rt.sum(axis=1)))

    _log(f"\n===== {name} =====", logfile)
    _log(f"DA price pi: {float(pi):.6f}", logfile)
    _log(f"E[RT price]: {float(np.dot(probs, Pi)):.6f}", logfile)
    _log(f"DA load: {da_load:.6f}", logfile)
    _log(f"E[RT load]: {exp_rt_load:.6f}", logfile)
    _log("DA allocation by tech: " + str({k: round(v, 4) for k, v in da_alloc.items()}), logfile)
    _log("Expected RT allocation by tech: " + str({k: round(v, 4) for k, v in rt_alloc.items()}), logfile)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "DA": g_da,
        "E_RT": exp_rt,
        "RT_minus_DA": exp_rt - g_da,
    })
    _log(df.to_string(index=False), logfile)
    
def _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i, n_solar, n_wind, n_thermal, logfile=None):
    z = np.asarray(z_g_i, dtype=float)
    c = np.asarray(cvar_g_i, dtype=float)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "stoch_DA": z,
        "cvar_DA": c,
        "cvar_minus_stoch": c - z,
    })

    _log("\n===== CVaR - Stochastic DA difference =====", logfile)
    _log(df.to_string(index=False), logfile)
    _log("Tech-level difference: " + str({
        "solar": round((c[solar_slice] - z[solar_slice]).sum(), 4),
        "wind": round((c[wind_slice] - z[wind_slice]).sum(), 4),
        "thermal": round((c[thermal_slice] - z[thermal_slice]).sum(), 4),
        "total": round((c - z).sum(), 4),
    }), logfile)

In [49]:
# Initialize log files
log_dir = "logs"
os.makedirs(log_dir, exist_ok=True)

debug_log = os.path.join(log_dir, "zavala_debug_log.txt")
with open(debug_log, "w", encoding="utf-8") as f:
    f.write("Zavala diagnostics log\n")

Build Real Data

In [50]:
def build_real_data_instance(solar_df, wind_df, load_total_vec, thermal_by_bus, thermal_buses_numeric,
                              solar_buses, wind_buses, start_idx, num_scenarios, rng=None):
    """
    Build (probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar) from real data for one time window.
    - start_idx: first time index
    - num_scenarios: number of consecutive time steps (scenarios)
    """
    if rng is None:
        rng = np.random.default_rng()
    end_idx = start_idx + num_scenarios
    S = num_scenarios

    # Scenario probabilities: near-uniform (same idea as s_real10_mix)
    kappa = 1500.0
    alpha = np.full(S, kappa / S)
    probs = rng.dirichlet(alpha)
    probs = probs / probs.sum()

    # Marginal costs: cheap for unreliable (solar/wind), higher for reliable (thermal)
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_unrel = n_solar + n_wind
    n_rel = len(thermal_buses_numeric)

    mc_unrel = rng.uniform(8.0, 14.0, size=n_unrel)
    mc_rel = rng.uniform(35.0, 55.0, size=n_rel)
    mc_g_i = np.concatenate([mc_unrel, mc_rel]).astype(float)

    # Single inelastic load (VOLL)
    mv_d_j = np.array([1000.0], dtype=float)

    # Generator capacities per scenario (S x 10)
    # Columns 0..2: solar, 3..5: wind, 6..9: thermal (constant)
    solar_vals = solar_df.loc[start_idx:end_idx - 1, solar_buses].values  # (S, 3)
    wind_vals = wind_df.loc[start_idx:end_idx - 1, wind_buses].values    # (S, 3)
    unrel_caps = np.clip(np.hstack([solar_vals, wind_vals]), 0.0, None)  # (S, 6)

    rel_caps = np.array([thermal_by_bus[b] for b in thermal_buses_numeric], dtype=float)
    rel_caps = np.broadcast_to(rel_caps, (S, len(thermal_buses_numeric)))  # (S, 4) constant across scenarios

    g_i_bar = np.hstack([unrel_caps, rel_caps])  # (S, 10)

    # Demand: system total load for each scenario (S x 1)
    d_j_bar = load_total_vec[start_idx:end_idx].reshape(-1, 1).astype(float)
    d_j_bar = np.clip(d_j_bar, 1e-6, None)  # avoid zeros

    return probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar

In [51]:
# Quick sanity check: one small window
NUM_SCENARIOS = 500
rng = np.random.default_rng(42)
probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
    solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
    solar_buses, wind_buses, start_idx=0, num_scenarios=min(NUM_SCENARIOS, T), rng=rng
)
print("probs.shape:", probs.shape, "sum:", probs.sum())
print("g_i_bar.shape:", g_i_bar.shape)
print("d_j_bar.shape:", d_j_bar.shape)
print("Unreliable (solar+wind) sample mean:", g_i_bar[:, :6].mean(axis=0))
print("Reliable (thermal) constant:", g_i_bar[0, 6:])
print("Load sample:", d_j_bar[:5].ravel())

probs.shape: (500,) sum: 1.0
g_i_bar.shape: (500, 6)
d_j_bar.shape: (500, 1)
Unreliable (solar+wind) sample mean: [  67.33335058  660.0882676   133.714       215.59573142   17.68757946
 6922.33      ]
Reliable (thermal) constant: []
Load sample: [75073. 72985. 71226. 70105. 69772.]

In [52]:
def run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=None):
    """Run stochastic, CVaR, and deterministic Zavala for one instance. Returns dict of metrics.
    Same logic as run_zavala.py, no changes to external files.
    """
    # ----- Stochastic Zavala -----
    z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi = zavala(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    prob_f = probability_feasible(probs, z_g_i, z_d_j, g_i_bar, d_j_bar)
    z_dist = price_distortion(probs, z_pi, z_Pi)
    z_reg = expected_cumulative_regret(probs, z_g_i, z_d_j, z_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_stoch = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=z_g_i, d_da=z_d_j, G_rt=Z_G, D_rt=Z_D)

    # # ----- CVaR Zavala -----
    cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi, _ = zavala_cvar(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    cvar_dist = price_distortion(probs, cvar_pi, cvar_Pi)
    cvar_reg = expected_cumulative_regret(probs, cvar_g_i, cvar_d_j, cvar_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_cvar = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=cvar_g_i, d_da=cvar_d_j, G_rt=C_G, D_rt=C_D)

    # ----- Deterministic (expected capacities) -----
    gbar_det, dbar_det = expected_caps_from_scenarios(probs, g_i_bar, d_j_bar)
    g_det, d_det, pi_det = zavala_deterministic_da(mc_g_i, mv_d_j, gbar_det, dbar_det)
    G_det_list, D_det_list, Pi_det_list = [], [], []
    for p in range(len(probs)):
        Gp, Dp, Pi_p = zavala_rt_energy_only(mc_g_i, mv_d_j, g_det, d_det, g_i_bar[p], d_j_bar[p])
        G_det_list.append(Gp)
        D_det_list.append(Dp)
        Pi_det_list.append(Pi_p)
    G_det_rt, D_det_rt = _stack_rt(G_det_list, D_det_list)
    Pi_det = np.array(Pi_det_list)
    det_dist = price_distortion(probs, pi_det, Pi_det)
    det_reg = expected_cumulative_regret(probs, g_det, d_det, pi_det, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_det = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=g_det, d_da=d_det, G_rt=G_det_rt, D_rt=D_det_rt)

    # ----- Tail metrics (5% worst by high neg-surplus) -----
    tail = 0.05
    stoch_tail_idx = tail_worst_indices_by_value(ss_stoch["ss_per_scenario"], probs, tail=tail, worst="high")
    cvar_tail_idx = tail_worst_indices_by_value(ss_cvar["ss_per_scenario"], probs, tail=tail, worst="high")
    det_tail_idx = tail_worst_indices_by_value(ss_det["ss_per_scenario"], probs, tail=tail, worst="high")

    stoch_tail_welfare = -np.mean(ss_stoch["ss_per_scenario"][stoch_tail_idx])
    cvar_tail_welfare = -np.mean(ss_cvar["ss_per_scenario"][cvar_tail_idx])
    det_tail_welfare = -np.mean(ss_det["ss_per_scenario"][det_tail_idx])

    stoch_tail_dist = np.mean(np.abs(z_pi - np.array(z_Pi)[stoch_tail_idx]))
    cvar_tail_dist = np.mean(np.abs(cvar_pi - np.array(cvar_Pi)[cvar_tail_idx]))
    det_tail_dist = np.mean(np.abs(pi_det - Pi_det[det_tail_idx]))

    # Log diagnostics/output results analysis
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_thermal = len(thermal_buses_numeric)

    _print_case_diag("Stochastic", probs, z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("CVaR", probs, cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("Deterministic", probs, g_det, d_det, G_det_rt, D_det_rt, pi_det, Pi_det,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i,
                            n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)

    return {
        "prob_feasible": prob_f,
        "stoch_distortion": z_dist, "stoch_regret": z_reg, "stoch_ss": ss_stoch["E_social_surplus"],
        "stoch_tail_welfare": stoch_tail_welfare, "stoch_tail_distortion": stoch_tail_dist,
        "cvar_distortion": cvar_dist, "cvar_regret": cvar_reg, "cvar_ss": ss_cvar["E_social_surplus"],
        "cvar_tail_welfare": cvar_tail_welfare, "cvar_tail_distortion": cvar_tail_dist,
        "det_distortion": det_dist, "det_regret": det_reg, "det_ss": ss_det["E_social_surplus"],
        "det_tail_welfare": det_tail_welfare, "det_tail_distortion": det_tail_dist,
    }

In [53]:
NUM_INSTANCES = 10
NUM_SCENARIOS = 500
rng = np.random.default_rng(2025)

max_start = T - NUM_SCENARIOS
if max_start <= 0:
    raise ValueError(f"Need at least {NUM_SCENARIOS} time steps; have {T}")

# Random start indices for each instance (non-overlapping or random)
start_indices = rng.integers(0, max_start + 1, size=NUM_INSTANCES)

results_list = []
for i in range(NUM_INSTANCES):
    start = int(start_indices[i])
    probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
        solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
        solar_buses, wind_buses, start_idx=start, num_scenarios=NUM_SCENARIOS, rng=rng
    )
    print(f"the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are {probs.shape}, {mc_g_i.shape}, {mv_d_j.shape}, {g_i_bar.shape}, {d_j_bar.shape}")
    res = run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=debug_log)
    results_list.append(res)
    print(f"Instance {i+1}/{NUM_INSTANCES} (start={start}) done.")

the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:21:45 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:21:46 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:21:46 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:21:46 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:21:46 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:21:46 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:21:46 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:21:46 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:21:46 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:21:47 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:21:51 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:21:51 PM: Finished problem compilation (took 5.084e+00 seconds).
(CVXPY) Jun 08 10:21:51 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x9f9e9410
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 317 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10190 columns, 27056 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 2.006e+04
 Factor NZ  : 1.003e+05 (roughly 8 MB of memory)
 Factor Ops : 1.542e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -5.11912153e+07 -3.17659774e+08  2.00e+05 5.51e+02  5.35e+05     0s
   1  -2.32207959e+07 -8.62586196e+07  3.56e+04 2.52e+01  4.75e+04     0s
   2  -2.04225204e+06 -2.32120025e+07  5.72e+02 1.07e+00  2.94e+03     0s
   3  -6.56064084e+06 -8.06803905e+06  1.60e+01 2.13e+00  1.55e+02     0s
   4  -6.56064084e+06 -8.06803905e+06  1.60e+01 2.13e+00  1.55e+02     0s
   5  -5.12431710e+07 -2.30186565e+10  2.00e+05 1.14e-13  4.17e+07     0s
   6  -7.55488829e+06 -1.45700637e+10  2.01e+04 7.28e+01  7.10e+06     0s
   7   1.01060969e+07 -2.41538545e+09  1.87e+02 2.59e+00  4.04e+05     0s
   8   7.62061557e+06 -3.29879714e+07  1.08e+00 4.78e-01  4.35e+03     0s
   9  -6.42359004e+06 -8.99256643e+06  1.85e-02 1.18e+00  2.63e+02     0s
  10  -7.40195523e+06 -7.79955131e+06  2.32e-03 1.24e-01  3.94e+01     0s
  11  -7.59611097e+06 -7.66308403e+06  1.97e-04 1.39e-02  6.59e+00     0s
  12  -7.62309689e+06 -7.64254316e+06  4.22e-05 4.81e-03  1.91e+00     0s
  13  -7.62794544e+06 -7.63724801e+06  2.09e-05 2.16e-03  9.15e-01     0s
  14  -7.63041297e+06 -7.63608594e+06  1.01e-05 1.59e-03  5.58e-01     0s
  15  -7.63197678e+06 -7.63516943e+06  1.93e-06 1.16e-03  3.14e-01     0s
  16  -7.63241021e+06 -7.63328205e+06  4.91e-07 2.93e-04  8.58e-02     0s
  17  -7.63249558e+06 -7.63286171e+06  1.67e-07 1.29e-04  3.60e-02     0s
  18  -7.63252698e+06 -7.63261227e+06  8.84e-08 1.68e-05  8.39e-03     0s
  19  -7.63254067e+06 -7.63260083e+06  6.00e-08 1.22e-05  5.92e-03     0s
  20  -7.63255459e+06 -7.63258590e+06  3.08e-08 6.36e-06  3.08e-03     0s
  21  -7.63256669e+06 -7.63257848e+06  3.62e-09 3.53e-06  1.16e-03     0s
  22  -7.63256841e+06 -7.63257333e+06  6.58e-10 1.64e-06  4.84e-04     0s
  23  -7.63256874e+06 -7.63257013e+06  2.29e-10 3.80e-07  1.37e-04     0s
  24  -7.63256897e+06 -7.63256905e+06  2.27e-11 4.60e-08  7.45e-06     0s
  25  -7.63256899e+06 -7.63256899e+06  5.58e-10 8.48e-11  2.02e-08     0s
  26  -7.63256899e+06 -7.63256899e+06  2.87e-09 6.46e-11  2.02e-11     0s

Barrier solved model in 26 iterations and 0.11 seconds (0.15 work units)
Optimal objective -7.63256899e+06

Crossover log...

    1027 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 0s

       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 2.9218644e-11      0s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
     836   -7.6325690e+06   0.000000e+00   0.000000e+00      0s

Solved in 836 iterations and 0.14 seconds (0.18 work units)
Optimal objective -7.632568994e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:21:51 PM: Problem status: optimal
(CVXPY) Jun 08 10:21:51 PM: Optimal value: -7.633e+06
(CVXPY) Jun 08 10:21:51 PM: Compilation took 5.084e+00 seconds
(CVXPY) Jun 08 10:21:51 PM: Solver (including time spent in interface) took 1.712e-01 seconds
(CVXPY) Jun 08 10:21:52 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:21:53 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:21:53 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:21:53 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:21:53 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:21:54 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:21:54 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:21:54 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:21:54 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:21:56 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:04 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:04 PM: Finished problem compilation (took 1.093e+01 seconds).
(CVXPY) Jun 08 10:22:04 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0xa0be5f92
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 317 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17691 columns, 58605 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.370e+04
 Factor NZ  : 1.143e+05 (roughly 14 MB of memory)
 Factor Ops : 1.112e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.42141293e+08 -1.34614863e+09  6.70e+06 1.28e+01  8.94e+06     0s
   1   1.61009206e+08 -6.10812083e+08  1.60e+05 1.71e+00  5.36e+05     0s
   2   1.61092184e+08 -6.11041456e+08  1.60e+05 6.25e+01  5.32e+05     0s
   3   1.61149529e+08 -6.11058061e+08  1.60e+05 2.87e+02  5.23e+05     0s
   4   1.61149529e+08 -6.11084125e+08  1.60e+05 3.07e+02  5.23e+05     0s
   5   1.61255340e+08 -6.11186783e+08  1.60e+05 2.67e+02  5.22e+05     0s
   6   1.61255340e+08 -6.11186783e+08  1.60e+05 2.67e+02  5.22e+05     0s
   7   1.42140977e+08 -3.39658334e+11  6.70e+06 1.28e+01  2.32e+09     0s
   8   4.17056750e+08 -3.07667939e+11  1.41e+05 4.99e+00  7.17e+07     0s
   9   4.54461726e+08 -4.15953084e+10  5.20e+03 4.09e+00  6.32e+06     0s
  10   4.54040108e+08 -4.15955333e+10  5.20e+03 3.76e+02  6.30e+06     0s
  11   4.54223465e+08 -4.15955274e+10  5.20e+03 1.20e+03  6.27e+06     0s
  12   1.42141293e+08 -3.39658334e+11  6.70e+06 1.28e+01  2.32e+09     0s
  13   8.13762710e+07 -1.82634429e+10  1.22e+05 3.27e+01  5.43e+07     0s
  14   1.28024664e+08 -2.60656912e+09  6.72e+03 6.16e+00  7.16e+06     0s
  15   6.58227293e+07 -9.03364519e+07  3.29e+02 4.36e-01  2.48e+05     0s
  16   8.32575540e+06 -1.35122963e+07  2.71e+01 8.64e-01  1.41e+04     0s
  17   8.33050051e+06 -1.35123931e+07  2.71e+01 3.88e+01  1.27e+04     0s
  18   8.38445995e+06 -1.33272686e+07  2.69e+01 1.70e+05  1.19e+04     0s
  19   8.36501867e+06 -1.33095127e+07  2.68e+01 1.71e+05  1.09e+04     0s
  20   8.32985723e+06 -1.32923468e+07  2.68e+01 1.70e+05  1.06e+04     0s
  21   7.87359888e+06 -1.30938751e+07  2.57e+01 1.67e+05  9.37e+03     0s
  22   7.93681563e+06 -1.31501387e+07  2.58e+01 1.68e+05  9.01e+03     0s
  23  -6.27607947e+06 -8.58016804e+06  2.09e+00 1.62e+04  2.58e+02     0s
  24  -6.32023746e+06 -8.65196276e+06  2.10e+00 1.63e+04  2.44e+02     0s
  25  -6.36569937e+06 -8.64197728e+06  2.04e+00 1.51e+04  2.33e+02     0s
  26  -6.38102418e+06 -8.72445162e+06  2.05e+00 1.53e+04  2.39e+02     0s
  27  -6.40079517e+06 -8.72196516e+06  2.02e+00 1.46e+04  2.36e+02     0s
  28  -7.36022316e+06 -8.51898841e+06  1.04e+00 6.47e+03  5.63e+01     0s
  29  -7.63863454e+06 -8.41112511e+06  7.16e-01 3.89e+03  2.62e+01     0s
  30  -7.82996285e+06 -8.40554384e+06  5.27e-01 2.96e+03  1.84e+01     0s
  31  -7.91635162e+06 -8.39470584e+06  4.22e-01 2.70e+03  1.49e+01     0s
  32  -7.97838232e+06 -8.39458701e+06  3.67e-01 2.23e+03  1.15e+01     0s
  33  -7.96129297e+06 -8.40267141e+06  3.89e-01 2.40e+03  1.37e+01     0s
  34  -7.96006475e+06 -8.40498754e+06  3.90e-01 2.46e+03  1.41e+01     0s
  35  -7.96452641e+06 -8.40119661e+06  3.85e-01 2.38e+03  1.30e+01     0s
  36  -7.96548443e+06 -8.39881599e+06  3.84e-01 2.35e+03  1.27e+01     0s
  37  -7.96319333e+06 -8.39874297e+06  3.85e-01 2.35e+03  1.28e+01     0s
  38  -8.04985961e+06 -8.39572350e+06  2.85e-01 2.28e+03  9.90e+00     0s
  39  -8.05672756e+06 -8.39017352e+06  2.77e-01 2.17e+03  9.14e+00     0s
  40  -8.05632488e+06 -8.39017680e+06  2.77e-01 2.17e+03  9.15e+00     0s
  41  -8.05141022e+06 -8.39282104e+06  2.90e-01 2.20e+03  9.81e+00     0s
  42  -8.06716961e+06 -8.39208249e+06  2.75e-01 2.12e+03  9.32e+00     0s

Barrier performed 42 iterations in 0.41 seconds (0.66 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with primal simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   15471   -8.2951956e+06   0.000000e+00   0.000000e+00      0s

Solved in 15471 iterations and 0.42 seconds (1.31 work units)
Optimal objective -8.295195634e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:06 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:06 PM: Optimal value: -8.295e+06
(CVXPY) Jun 08 10:22:06 PM: Compilation took 1.093e+01 seconds
(CVXPY) Jun 08 10:22:06 PM: Solver (including time spent in interface) took 1.299e+00 seconds

Instance 1/10 (start=3696) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:22:08 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:22:08 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:22:08 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:22:08 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:22:08 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:22:08 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:22:08 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:22:08 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:22:08 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:09 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:13 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:13 PM: Finished problem compilation (took 4.898e+00 seconds).
(CVXPY) Jun 08 10:22:13 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0xf530777d
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [9e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 14000 rows and 388 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10119 columns, 26843 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.984e+04
 Factor NZ  : 9.770e+04 (roughly 8 MB of memory)
 Factor Ops : 1.484e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.38998403e+07 -2.93966160e+08  1.58e+05 5.48e+02  4.08e+05     0s
   1  -2.07252973e+07 -7.87809094e+07  2.70e+04 2.64e+01  3.71e+04     0s
   2  -2.86056953e+06 -2.34577674e+07  5.63e+02 2.61e+00  3.24e+03     0s
   3  -6.28561684e+06 -7.79493404e+06  2.64e+01 1.78e+00  1.62e+02     0s
   4  -7.00356820e+06 -7.53935938e+06  7.67e+00 6.52e-01  5.56e+01     0s
   5  -7.16798941e+06 -7.41695823e+06  4.04e+00 1.14e-01  2.54e+01     0s
   6  -7.24439766e+06 -7.39304417e+06  2.46e+00 5.09e-02  1.51e+01     0s
   7  -7.31463889e+06 -7.38137736e+06  1.06e+00 5.47e-02  6.75e+00     0s
   8  -7.35331992e+06 -7.37596014e+06  3.28e-01 2.77e-02  2.28e+00     0s
   9  -7.36662450e+06 -7.37496467e+06  1.05e-01 1.48e-02  8.38e-01     0s
  10  -7.37121648e+06 -7.37418045e+06  3.65e-02 3.28e-03  2.97e-01     0s
  11  -7.37284209e+06 -7.37401896e+06  1.32e-02 4.39e-03  1.18e-01     0s
  12  -7.37371965e+06 -7.37388885e+06  1.48e-03 2.02e-03  1.69e-02     0s
  13  -7.37380794e+06 -7.37385860e+06  3.86e-04 1.88e-03  5.05e-03     0s
  14  -7.37383317e+06 -7.37385061e+06  1.11e-04 8.96e-04  1.74e-03     0s
  15  -7.37383837e+06 -7.37384721e+06  5.43e-05 4.30e-04  8.80e-04     0s
  16  -7.37384236e+06 -7.37384664e+06  1.22e-05 3.59e-04  4.24e-04     0s
  17  -7.37384273e+06 -7.37384558e+06  8.90e-06 2.20e-04  2.82e-04     0s
  18  -7.37384298e+06 -7.37384494e+06  6.92e-06 1.35e-04  1.94e-04     0s
  19  -7.37384332e+06 -7.37384470e+06  4.18e-06 1.04e-04  1.37e-04     0s
  20  -7.37384338e+06 -7.37384459e+06  3.75e-06 9.12e-05  1.20e-04     0s
  21  -7.37384360e+06 -7.37384444e+06  1.74e-06 7.32e-05  8.39e-05     0s
  22  -7.37384372e+06 -7.37384429e+06  7.40e-07 5.38e-05  5.65e-05     0s
  23  -7.37384376e+06 -7.37384420e+06  5.42e-07 4.10e-05  4.38e-05     0s
  24  -7.37384379e+06 -7.37384417e+06  3.93e-07 3.80e-05  3.77e-05     0s
  25  -7.37384381e+06 -7.37384410e+06  2.73e-07 2.83e-05  2.79e-05     0s
  26  -7.37384387e+06 -7.37384388e+06  1.03e-09 2.84e-07  1.40e-06     0s
  27  -7.37384387e+06 -7.37384388e+06  4.55e-07 2.94e-07  5.88e-07     0s
  28  -7.37384388e+06 -7.37384388e+06  2.32e-08 8.85e-10  2.89e-08     0s
  29  -7.37384388e+06 -7.37384388e+06  4.68e-08 2.32e-08  1.19e-08     0s
  30  -7.37384388e+06 -7.37384388e+06  7.00e-11 5.83e-09  7.28e-12     0s

Barrier solved model in 30 iterations and 0.13 seconds (0.15 work units)
Optimal objective -7.37384388e+06

Crossover log...

    1091 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 0s

       4 PPushes remaining with PInf 0.0000000e+00                 0s
       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 8.2382885e-13      0s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
     878   -7.3738439e+06   0.000000e+00   0.000000e+00      0s

Solved in 878 iterations and 0.15 seconds (0.18 work units)
Optimal objective -7.373843876e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:13 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:13 PM: Optimal value: -7.374e+06
(CVXPY) Jun 08 10:22:13 PM: Compilation took 4.898e+00 seconds
(CVXPY) Jun 08 10:22:13 PM: Solver (including time spent in interface) took 1.861e-01 seconds
(CVXPY) Jun 08 10:22:14 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:22:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:22:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:22:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:22:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:22:16 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:22:16 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:22:16 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:16 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:22:18 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:27 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:27 PM: Finished problem compilation (took 1.180e+01 seconds).
(CVXPY) Jun 08 10:22:27 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0xc8740a13
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [9e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 21000 rows and 388 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17620 columns, 58179 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.285e+04
 Factor NZ  : 1.128e+05 (roughly 14 MB of memory)
 Factor Ops : 1.085e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.09608821e+08 -1.26377016e+09  5.29e+06 1.28e+01  6.88e+06     0s
   1   1.18478917e+08 -5.09121917e+08  2.00e+05 4.22e+00  4.31e+05     0s
   2   1.18481393e+08 -5.09323520e+08  2.00e+05 1.83e+02  4.28e+05     0s
   3   1.18481393e+08 -5.09323520e+08  2.00e+05 1.83e+02  4.28e+05     0s
   4   1.09608821e+08 -3.28375309e+11  5.29e+06 1.28e+01  1.84e+09     0s
   5   3.19079449e+08 -2.67706796e+11  2.06e+05 8.25e+00  6.77e+07     0s
   6   3.66378307e+08 -2.72369477e+10  5.67e+03 1.90e+00  4.69e+06     0s
   7   3.66297015e+08 -2.72367850e+10  5.67e+03 1.60e+02  4.63e+06     0s
   8   3.65611816e+08 -2.72370687e+10  5.67e+03 1.48e+02  4.60e+06     0s
   9   3.65233655e+08 -2.72370699e+10  5.67e+03 9.82e+02  4.57e+06     0s
  10   3.65233655e+08 -2.72370699e+10  5.67e+03 9.82e+02  4.57e+06     0s
  11   1.09608821e+08 -3.28375309e+11  5.29e+06 1.28e+01  1.84e+09     0s
  12   8.61098512e+07 -3.96404194e+09  1.44e+05 9.10e+00  1.58e+07     0s
  13   2.02504429e+07 -2.87489544e+08  1.72e+03 1.62e+00  2.28e+05     0s
  14   4.69808576e+06 -1.48530149e+07  1.12e+02 7.13e-01  9.41e+03     0s
  15   4.69668998e+06 -1.48576435e+07  1.12e+02 3.55e+01  8.69e+03     0s
  16   4.60090990e+06 -1.46185043e+07  1.11e+02 1.44e+02  7.85e+03     0s
  17  -5.61721006e+06 -8.56392866e+06  1.35e+01 4.51e+01  5.59e+02     0s
  18  -5.84071185e+06 -8.46356409e+06  1.21e+01 4.11e+01  4.64e+02     0s
  19  -6.62445815e+06 -8.29632089e+06  7.51e+00 3.04e+01  2.52e+02     0s
  20  -7.65242784e+06 -8.06536765e+06  1.93e+00 7.49e+00  2.88e+01     0s
  21  -7.75308472e+06 -8.04480229e+06  1.31e+00 5.75e+00  1.54e+01     0s
  22  -7.86359853e+06 -8.02722499e+06  6.90e-01 3.95e+00  7.98e+00     0s
  23  -7.87394435e+06 -8.02353241e+06  6.36e-01 3.38e+00  7.01e+00     0s
  24  -7.86361856e+06 -8.02181813e+06  6.14e-01 2.85e+01  6.70e+00     0s
  25  -7.88736085e+06 -8.02201865e+06  5.46e-01 2.69e+01  6.26e+00     0s
  26  -7.90482262e+06 -8.02905375e+06  5.52e-01 2.76e+01  6.19e+00     0s
  27  -7.90643282e+06 -8.02671565e+06  5.41e-01 2.61e+01  5.87e+00     0s
  28  -7.91655087e+06 -8.02213305e+06  4.83e-01 2.59e+01  4.67e+00     0s
  29  -7.92374857e+06 -8.02802773e+06  4.62e-01 2.36e+01  4.36e+00     0s
  30  -7.95053190e+06 -8.02697647e+06  3.19e-01 2.20e+01  3.22e+00     0s
  31  -7.95301163e+06 -8.02437971e+06  3.03e-01 1.95e+01  2.90e+00     0s
  32  -7.96400443e+06 -8.02909775e+06  2.67e-01 1.38e+01  3.39e+00     0s
  33  -7.98324842e+06 -8.03299127e+06  2.20e-01 1.29e+01  3.80e+00     0s
  34  -7.97876906e+06 -8.02384365e+06  1.98e-01 1.18e+01  3.37e+00     0s
  35  -7.97406075e+06 -8.02084937e+06  2.12e-01 1.32e+01  4.22e+00     0s
  36  -7.98290886e+06 -8.02144187e+06  1.87e-01 1.29e+01  3.61e+00     0s
  37  -7.98332327e+06 -8.02082090e+06  1.83e-01 1.25e+01  3.39e+00     0s
  38  -7.98424655e+06 -8.02193498e+06  1.92e-01 1.26e+01  3.96e+00     0s

Barrier performed 38 iterations in 0.46 seconds (0.62 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10504   -8.0303481e+06   0.000000e+00   0.000000e+00      0s

Solved in 10504 iterations and 0.47 seconds (1.18 work units)
Optimal objective -8.030348123e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:28 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:28 PM: Optimal value: -8.030e+06
(CVXPY) Jun 08 10:22:28 PM: Compilation took 1.180e+01 seconds
(CVXPY) Jun 08 10:22:28 PM: Solver (including time spent in interface) took 5.304e-01 seconds

Instance 2/10 (start=8215) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:22:30 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:22:30 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:22:30 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:22:30 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:22:30 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:22:31 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:22:31 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:22:31 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:22:31 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:32 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:35 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:35 PM: Finished problem compilation (took 5.162e+00 seconds).
(CVXPY) Jun 08 10:22:35 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x8b74f2e3
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [9e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 378 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10129 columns, 26873 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.987e+04
 Factor NZ  : 9.806e+04 (roughly 8 MB of memory)
 Factor Ops : 1.492e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.44855103e+07 -3.52611416e+08  1.58e+05 5.49e+02  4.97e+05     0s
   1  -1.98630691e+07 -1.05035531e+08  2.68e+04 2.45e+01  4.51e+04     0s
   2  -2.77624145e+06 -2.66837730e+07  4.45e+02 2.57e+00  3.56e+03     0s
   3  -6.32307005e+06 -8.05073754e+06  1.91e+01 2.71e+00  1.88e+02     0s
   4  -6.56417950e+06 -7.51297277e+06  1.50e+01 1.88e-01  9.73e+01     0s
   5  -6.56417950e+06 -7.51297277e+06  1.50e+01 1.88e-01  9.73e+01     0s
   6  -4.45290415e+07 -2.22273002e+10  1.58e+05 1.14e-13  3.34e+07     0s
   7  -6.47984995e+06 -1.20225813e+10  1.45e+04 6.48e+01  5.17e+06     0s
   8   6.65250461e+06 -1.48025635e+09  3.33e+02 1.58e+00  1.77e+05     0s
   9  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s
  10  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s
  11  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s
  12  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s
  13  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s
  14  -3.44738256e+06 -4.61147199e+07  1.87e+00 6.59e+00  4.31e+03     0s

Barrier performed 14 iterations in 0.09 seconds (0.10 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3769   -7.4490995e+06   0.000000e+00   0.000000e+00      0s

Solved in 3769 iterations and 0.15 seconds (0.42 work units)
Optimal objective -7.449099465e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:36 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:36 PM: Optimal value: -7.449e+06
(CVXPY) Jun 08 10:22:36 PM: Compilation took 5.162e+00 seconds
(CVXPY) Jun 08 10:22:36 PM: Solver (including time spent in interface) took 1.799e-01 seconds
(CVXPY) Jun 08 10:22:37 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:22:37 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:22:37 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:22:37 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:22:37 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:22:38 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:22:38 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:22:38 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:39 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:22:41 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:50 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:50 PM: Finished problem compilation (took 1.220e+01 seconds).
(CVXPY) Jun 08 10:22:50 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x778d4031
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [9e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 378 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17630 columns, 58239 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.297e+04
 Factor NZ  : 1.128e+05 (roughly 14 MB of memory)
 Factor Ops : 1.085e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.00757804e+08 -1.39609619e+09  5.42e+06 1.28e+01  7.82e+06     0s
   1   1.18053252e+08 -5.67896981e+08  1.99e+05 7.33e-01  4.79e+05     0s
   2   1.18052778e+08 -5.67887758e+08  1.99e+05 4.06e+01  4.76e+05     0s
   3   1.18159680e+08 -5.67944425e+08  1.99e+05 2.88e+01  4.75e+05     0s
   4   1.18135691e+08 -5.67960254e+08  1.99e+05 3.13e+01  4.75e+05     0s
   5   1.18135691e+08 -5.67960254e+08  1.99e+05 3.13e+01  4.75e+05     0s
   6   1.00757804e+08 -3.27667915e+11  5.42e+06 1.28e+01  1.89e+09     0s
   7   3.15215051e+08 -2.71163475e+11  2.06e+05 7.30e+00  6.90e+07     0s
   8   3.62559350e+08 -2.60462940e+10  5.84e+03 4.39e+00  4.52e+06     0s
   9   3.60097476e+08 -2.60464749e+10  5.84e+03 1.45e+02  4.50e+06     0s
  10   3.59297493e+08 -2.60465037e+10  5.84e+03 9.85e+02  4.47e+06     0s
  11   1.00757804e+08 -3.27667915e+11  5.42e+06 1.28e+01  1.89e+09     0s
  12   7.29399857e+07 -1.29127488e+10  1.71e+05 3.46e+01  4.09e+07     0s
  13   1.08498844e+08 -2.16565473e+09  8.45e+03 5.94e+00  4.67e+06     0s
  14   6.50612315e+07 -7.68438940e+07  3.26e+02 4.90e-01  1.86e+05     0s
  15   6.50575472e+07 -7.68468434e+07  3.26e+02 1.48e+02  1.81e+05     0s
  16   6.50553544e+07 -7.68172768e+07  3.26e+02 1.65e+02  1.76e+05     0s
  17   6.50500992e+07 -7.67823261e+07  3.26e+02 6.42e+01  1.72e+05     0s
  18   6.50582870e+07 -7.65675343e+07  3.26e+02 1.17e+02  1.71e+05     0s
  19   6.51102067e+07 -7.67144285e+07  3.27e+02 9.75e+01  1.68e+05     0s
  20   6.51019861e+07 -7.64827965e+07  3.26e+02 5.93e+03  1.63e+05     0s
  21   1.71951814e+07 -2.13402105e+07  9.12e+01 1.68e+03  2.85e+04     0s
  22   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  23   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  24   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  25   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  26   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  27   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  28   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  29   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  30   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s
  31   1.72000864e+07 -2.13253677e+07  9.12e+01 1.50e+03  2.85e+04     0s

Barrier performed 31 iterations in 0.33 seconds (0.45 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    8479   -8.1119112e+06   0.000000e+00   0.000000e+00      0s

Solved in 8479 iterations and 0.42 seconds (1.13 work units)
Optimal objective -8.111911212e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:50 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:50 PM: Optimal value: -8.112e+06
(CVXPY) Jun 08 10:22:50 PM: Compilation took 1.220e+01 seconds
(CVXPY) Jun 08 10:22:50 PM: Solver (including time spent in interface) took 4.757e-01 seconds

Instance 3/10 (start=8199) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:22:52 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:22:53 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:22:53 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:22:53 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:22:53 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:22:53 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:22:53 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:22:53 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:22:53 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:54 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:22:58 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:22:58 PM: Finished problem compilation (took 4.964e+00 seconds).
(CVXPY) Jun 08 10:22:58 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x2ecfbd01
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 349 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10158 columns, 26960 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.996e+04
 Factor NZ  : 9.908e+04 (roughly 8 MB of memory)
 Factor Ops : 1.514e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.62646596e+07 -2.78205202e+08  1.82e+05 5.49e+02  4.62e+05     0s
   1  -2.06768206e+07 -9.78983714e+07  2.87e+04 2.69e+01  4.28e+04     0s
   2  -2.02994878e+06 -2.12830151e+07  3.89e+02 1.39e+00  2.55e+03     0s
   3  -6.56578275e+06 -7.76639641e+06  1.14e+01 2.29e+00  1.24e+02     0s
   4  -6.56578275e+06 -7.76639641e+06  1.14e+01 2.29e+00  1.24e+02     0s
   5  -4.63149720e+07 -2.12968557e+10  1.83e+05 1.14e-13  3.81e+07     0s
   6  -6.75899435e+06 -1.35880688e+10  1.84e+04 7.62e+01  6.66e+06     0s
   7   8.96549566e+06 -2.20180318e+09  2.10e+02 2.61e+00  3.73e+05     0s
   8   6.75275721e+06 -3.49531480e+07  8.96e-01 6.35e-01  4.48e+03     0s
   9  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s
  10  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s
  11  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s
  12  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s
  13  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s
  14  -6.40893741e+06 -8.85468887e+06  8.77e-03 1.20e-01  2.52e+02     0s

Barrier performed 14 iterations in 0.07 seconds (0.10 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3598   -7.4596744e+06   0.000000e+00   0.000000e+00      0s

Solved in 3598 iterations and 0.13 seconds (0.40 work units)
Optimal objective -7.459674410e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:22:58 PM: Problem status: optimal
(CVXPY) Jun 08 10:22:58 PM: Optimal value: -7.460e+06
(CVXPY) Jun 08 10:22:58 PM: Compilation took 4.964e+00 seconds
(CVXPY) Jun 08 10:22:58 PM: Solver (including time spent in interface) took 1.655e-01 seconds
(CVXPY) Jun 08 10:22:59 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:00 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:00 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:00 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:00 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:00 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:00 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:00 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:01 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:23:03 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:23:12 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:23:12 PM: Finished problem compilation (took 1.228e+01 seconds).
(CVXPY) Jun 08 10:23:12 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x0ee2b36a
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 349 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17659 columns, 58413 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.332e+04
 Factor NZ  : 1.136e+05 (roughly 14 MB of memory)
 Factor Ops : 1.100e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.39414245e+08 -1.19626895e+09  6.14e+06 1.28e+01  7.91e+06     0s
   1   1.39410470e+08 -1.19638497e+09  6.14e+06 8.94e+02  7.23e+06     0s
   2   3.10070815e+08 -1.03640483e+09  3.29e+05 1.77e+02  1.76e+06     0s
   3   2.15264280e+08 -1.25538728e+08  8.55e+04 1.66e+01  1.98e+05     0s
   4   2.15182852e+08 -1.25600465e+08  8.55e+04 2.11e+02  1.96e+05     0s
   5   2.14255458e+08 -1.25550164e+08  8.55e+04 6.42e+02  1.91e+05     0s
   6   2.14255458e+08 -1.25550164e+08  8.55e+04 6.42e+02  1.91e+05     0s
   7   1.39414245e+08 -3.12541998e+11  6.14e+06 1.28e+01  2.13e+09     0s
   8   3.89088690e+08 -2.83211190e+11  1.32e+05 7.50e+00  6.44e+07     0s
   9   4.23272050e+08 -4.02577727e+10  5.08e+03 3.01e+00  6.20e+06     0s
  10   4.22592254e+08 -4.02578677e+10  5.08e+03 1.02e+03  6.17e+06     0s
  11   4.22599636e+08 -4.02578654e+10  5.08e+03 2.96e+03  6.12e+06     0s
  12   1.39414245e+08 -3.12541998e+11  6.14e+06 1.28e+01  2.13e+09     0s
  13   8.14711159e+07 -1.15496425e+10  9.87e+04 2.66e+01  3.65e+07     0s
  14   1.19301572e+08 -2.07379122e+09  5.30e+03 5.09e+00  5.07e+06     0s
  15   7.36362465e+07 -8.25720180e+07  2.32e+02 3.68e-01  2.49e+05     0s
  16   7.36323448e+07 -8.25731760e+07  2.32e+02 1.72e+02  2.46e+05     0s
  17   7.36336455e+07 -8.25852467e+07  2.32e+02 2.32e+02  2.41e+05     0s
  18  -3.03593434e+06 -9.35601052e+06  7.82e+00 8.56e+00  2.07e+03     0s
  19  -3.04245751e+06 -9.36289670e+06  7.82e+00 8.47e+01  2.03e+03     0s
  20  -3.04250658e+06 -9.36292711e+06  7.82e+00 6.76e+01  2.00e+03     0s
  21  -2.98947205e+06 -9.37259110e+06  7.90e+00 4.36e+03  2.03e+03     0s
  22  -2.99867487e+06 -9.38054038e+06  7.90e+00 4.58e+03  2.03e+03     0s
  23  -2.99867487e+06 -9.38054038e+06  7.90e+00 4.58e+03  1.92e+03     0s
  24  -2.99825433e+06 -9.37989911e+06  7.90e+00 4.59e+03  1.88e+03     0s
  25  -2.99825433e+06 -9.37989911e+06  7.90e+00 4.59e+03  1.88e+03     0s
  26  -2.99825433e+06 -9.37989911e+06  7.90e+00 4.59e+03  1.88e+03     0s
  27  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  28  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  29  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  30  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  31  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  32  -2.99920135e+06 -9.38019341e+06  7.89e+00 4.57e+03  1.79e+03     0s
  33  -2.99929646e+06 -9.37990604e+06  7.89e+00 4.50e+03  1.78e+03     0s

Barrier performed 33 iterations in 0.33 seconds (0.49 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    9180   -8.1115142e+06   0.000000e+00   0.000000e+00      0s

Solved in 9180 iterations and 0.40 seconds (1.05 work units)
Optimal objective -8.111514205e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:13 PM: Problem status: optimal
(CVXPY) Jun 08 10:23:13 PM: Optimal value: -8.112e+06
(CVXPY) Jun 08 10:23:13 PM: Compilation took 1.228e+01 seconds
(CVXPY) Jun 08 10:23:13 PM: Solver (including time spent in interface) took 4.485e-01 seconds

Instance 4/10 (start=3155) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:23:15 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:15 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:15 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:23:15 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:16 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:23:20 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:23:20 PM: Finished problem compilation (took 5.109e+00 seconds).
(CVXPY) Jun 08 10:23:20 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x28093392
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 418 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10089 columns, 26753 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.975e+04
 Factor NZ  : 9.663e+04 (roughly 8 MB of memory)
 Factor Ops : 1.460e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.41756346e+07 -2.57336771e+08  1.58e+05 5.48e+02  3.60e+05     0s
   1  -2.14621232e+07 -8.37525002e+07  2.84e+04 3.01e+01  3.61e+04     0s
   2  -2.98663557e+06 -2.09074062e+07  5.53e+02 2.91e+00  2.92e+03     0s
   3  -6.32292135e+06 -7.57235739e+06  1.81e+01 4.77e-01  1.32e+02     0s
   4  -6.32292135e+06 -7.57235739e+06  1.81e+01 4.77e-01  1.32e+02     0s
   5  -4.42355630e+07 -2.18946247e+10  1.58e+05 1.14e-13  3.33e+07     0s
   6  -6.00387097e+06 -1.19240982e+10  1.36e+04 7.34e+01  5.43e+06     0s
   7   6.72928861e+06 -1.47197551e+09  5.11e+02 2.07e+00  2.14e+05     0s
   8   9.54340724e+05 -7.86266288e+07  4.91e+00 9.26e-01  8.66e+03     0s
   9  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s
  10  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s
  11  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s
  12  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s
  13  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s
  14  -5.88077937e+06 -9.68976735e+06  1.49e-01 2.37e+00  3.94e+02     0s

Barrier performed 14 iterations in 0.07 seconds (0.10 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3738   -7.2437217e+06   0.000000e+00   0.000000e+00      0s

Solved in 3738 iterations and 0.14 seconds (0.42 work units)
Optimal objective -7.243721660e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:20 PM: Problem status: optimal
(CVXPY) Jun 08 10:23:20 PM: Optimal value: -7.244e+06
(CVXPY) Jun 08 10:23:20 PM: Compilation took 5.109e+00 seconds
(CVXPY) Jun 08 10:23:20 PM: Solver (including time spent in interface) took 1.714e-01 seconds
(CVXPY) Jun 08 10:23:22 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:22 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:22 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:22 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:22 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:23 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:23 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:23 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:24 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:23:25 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:23:33 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:23:33 PM: Finished problem compilation (took 1.105e+01 seconds).
(CVXPY) Jun 08 10:23:33 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x813dc6bf
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 418 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17590 columns, 57999 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.249e+04
 Factor NZ  : 1.122e+05 (roughly 14 MB of memory)
 Factor Ops : 1.074e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   9.92250564e+07 -8.44348497e+08  5.38e+06 6.40e+00  4.68e+06     0s
   1   1.06657619e+08 -3.58897004e+08  2.28e+05 2.32e+00  3.12e+05     0s
   2   1.07016818e+08 -3.58694778e+08  2.28e+05 1.49e+02  3.08e+05     0s
   3   1.06875630e+08 -3.58843458e+08  2.28e+05 3.67e+02  3.03e+05     0s
   4   1.06875630e+08 -3.58843458e+08  2.28e+05 3.67e+02  3.03e+05     0s
   5   9.92250564e+07 -3.23186925e+11  5.38e+06 6.40e+00  1.87e+09     0s
   6   3.37383555e+08 -2.69482765e+11  2.61e+05 7.25e+01  2.82e+08     0s
   7   3.88599989e+08 -2.30257059e+10  1.74e+04 6.21e+00  9.92e+06     0s
   8   3.88548849e+08 -2.30257374e+10  1.74e+04 8.14e+02  9.63e+06     0s
   9   3.88535764e+08 -2.30257342e+10  1.74e+04 1.92e+03  9.21e+06     0s
  10   3.89268360e+08 -2.30221156e+10  1.74e+04 1.41e+03  9.00e+06     0s
  11   9.92250564e+07 -3.23186925e+11  5.38e+06 6.40e+00  1.87e+09     0s
  12   3.68228005e+07 -2.72500199e+09  2.03e+05 1.46e+01  2.05e+07     0s
  13   1.55242430e+07 -3.38528863e+08  1.28e+03 1.09e+00  3.11e+05     0s
  14   5.26044376e+06 -1.47665446e+07  5.21e+01 2.51e-01  1.26e+04     0s
  15   5.25933035e+06 -1.47662524e+07  5.21e+01 4.33e+01  1.18e+04     0s
  16  -5.67445842e+06 -8.49213496e+06  6.14e+00 6.01e+00  8.34e+02     0s
  17  -5.67451300e+06 -8.49231678e+06  6.14e+00 8.35e+01  7.85e+02     0s
  18  -5.71383521e+06 -8.46565854e+06  6.00e+00 9.30e+02  7.22e+02     0s
  19  -5.71676733e+06 -8.47941323e+06  6.00e+00 1.56e+03  7.17e+02     0s
  20  -5.72252718e+06 -8.49252973e+06  6.01e+00 2.00e+05  7.15e+02     0s
  21  -5.72413933e+06 -8.49687557e+06  6.01e+00 2.04e+05  6.17e+02     0s
  22  -5.72426111e+06 -8.49703600e+06  6.01e+00 2.04e+05  5.81e+02     0s
  23  -5.72418821e+06 -8.49597951e+06  6.01e+00 2.04e+05  5.80e+02     0s
  24  -5.82420328e+06 -8.49238762e+06  5.72e+00 2.04e+05  5.58e+02     0s
  25  -5.82347193e+06 -8.49349255e+06  5.72e+00 2.04e+05  5.35e+02     0s
  26  -7.01475414e+06 -8.10528099e+06  2.41e+00 1.01e+05  1.53e+02     0s
  27  -7.01565442e+06 -8.10540618e+06  2.41e+00 1.01e+05  1.53e+02     0s
  28  -7.01554930e+06 -8.10321744e+06  2.41e+00 1.01e+05  1.53e+02     0s
  29  -7.01579576e+06 -8.10315689e+06  2.41e+00 1.01e+05  1.45e+02     0s
  30  -7.01921928e+06 -8.10268056e+06  2.40e+00 1.01e+05  1.42e+02     0s
  31  -7.54401035e+06 -7.94872896e+06  9.40e-01 2.95e+04  2.22e+01     0s
  32  -7.66342888e+06 -7.92327032e+06  6.09e-01 1.66e+04  9.73e+00     0s
  33  -7.75451266e+06 -7.91660679e+06  3.59e-01 1.34e+04  5.98e+00     0s
  34  -7.83528358e+06 -7.92856370e+06  2.24e-01 1.03e+04  3.53e+00     0s
  35  -7.83071325e+06 -7.92920891e+06  2.37e-01 1.10e+04  4.12e+00     0s
  36  -7.82731751e+06 -7.92939330e+06  2.48e-01 1.11e+04  4.58e+00     0s
  37  -7.83288916e+06 -7.92937775e+06  2.32e-01 1.11e+04  4.46e+00     0s
  38  -7.83665585e+06 -7.92950134e+06  2.24e-01 1.07e+04  4.14e+00     0s
  39  -7.84144209e+06 -7.92919718e+06  2.09e-01 1.04e+04  4.02e+00     0s
  40  -7.84053168e+06 -7.92932911e+06  2.14e-01 1.05e+04  4.35e+00     0s
  41  -7.84478873e+06 -7.92761616e+06  1.80e-01 9.92e+03  4.06e+00     0s
  42  -7.84089638e+06 -7.92831427e+06  1.89e-01 1.08e+04  5.30e+00     0s
  43  -7.83843894e+06 -7.92740880e+06  1.94e-01 1.18e+04  6.06e+00     0s
  44  -7.84176063e+06 -7.92762982e+06  1.87e-01 1.11e+04  5.71e+00     0s

Barrier performed 44 iterations in 0.43 seconds (0.64 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10611   -7.9055487e+06   0.000000e+00   0.000000e+00      0s

Solved in 10611 iterations and 0.44 seconds (1.23 work units)
Optimal objective -7.905548680e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:34 PM: Problem status: optimal
(CVXPY) Jun 08 10:23:34 PM: Optimal value: -7.906e+06
(CVXPY) Jun 08 10:23:34 PM: Compilation took 1.105e+01 seconds
(CVXPY) Jun 08 10:23:34 PM: Solver (including time spent in interface) took 4.937e-01 seconds

Instance 5/10 (start=7877) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:23:36 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:36 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:36 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:36 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:36 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:36 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:36 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:36 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:23:36 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:37 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:23:41 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:23:41 PM: Finished problem compilation (took 4.833e+00 seconds).
(CVXPY) Jun 08 10:23:41 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x2794cc95
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-05, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 357 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10150 columns, 26936 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.994e+04
 Factor NZ  : 9.877e+04 (roughly 8 MB of memory)
 Factor Ops : 1.507e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.46626875e+07 -2.57800713e+08  1.70e+05 1.10e+03  7.95e+05     0s
   1  -2.14531278e+07 -6.80555822e+07  2.95e+04 4.45e+01  6.74e+04     0s
   2  -3.33725951e+06 -2.01857792e+07  5.48e+02 2.67e+00  4.86e+03     0s
   3  -6.69983037e+06 -8.04879146e+06  3.15e+01 1.32e+00  2.89e+02     0s
   4  -6.69983037e+06 -8.04879146e+06  3.15e+01 1.32e+00  2.89e+02     0s
   5  -4.47166502e+07 -1.06373789e+10  1.70e+05 1.14e-13  3.56e+07     0s
   6  -6.64883916e+06 -6.48001348e+09  1.55e+04 5.98e+01  5.39e+06     0s
   7   7.51520457e+06 -9.58203816e+08  2.01e+02 1.38e+00  2.56e+05     0s
   8   6.14760127e+05 -2.54954424e+07  1.03e+00 8.47e-01  5.56e+03     0s
   9  -6.49341430e+06 -8.85616944e+06  7.90e-02 3.84e-01  4.80e+02     0s
  10  -7.38475292e+06 -7.89875989e+06  1.64e-02 1.33e-01  1.02e+02     0s
  11  -7.63779476e+06 -7.71091386e+06  9.18e-04 1.57e-02  1.44e+01     0s
  12  -7.67036355e+06 -7.68441271e+06  6.82e-05 3.71e-03  2.77e+00     0s
  13  -7.67237549e+06 -7.68059082e+06  3.37e-05 2.20e-03  1.62e+00     0s
  14  -7.67384067e+06 -7.67731337e+06  1.19e-05 9.44e-04  6.85e-01     0s
  15  -7.67446143e+06 -7.67608553e+06  2.84e-06 4.84e-04  3.20e-01     0s
  16  -7.67461213e+06 -7.67499511e+06  1.13e-06 8.04e-05  7.55e-02     0s
  17  -7.67466126e+06 -7.67489107e+06  6.22e-07 4.59e-05  4.53e-02     0s
  18  -7.67469657e+06 -7.67476986e+06  2.84e-07 1.31e-05  1.45e-02     0s
  19  -7.67472338e+06 -7.67473678e+06  5.47e-08 1.87e-06  2.64e-03     0s
  20  -7.67472772e+06 -7.67473489e+06  2.64e-08 1.02e-06  1.41e-03     0s
  21  -7.67472921e+06 -7.67473464e+06  1.82e-08 9.18e-07  1.07e-03     0s
  22  -7.67473112e+06 -7.67473332e+06  7.65e-09 3.06e-07  4.35e-04     0s
  23  -7.67473180e+06 -7.67473284e+06  4.01e-09 8.95e-08  2.04e-04     0s
  24  -7.67473260e+06 -7.67473262e+06  1.82e-12 3.95e-09  5.02e-06     0s
  25  -7.67473260e+06 -7.67473260e+06  9.73e-11 2.42e-09  4.78e-08     0s
  26  -7.67473260e+06 -7.67473260e+06  8.84e-10 1.09e-10  4.78e-11     0s

Barrier solved model in 26 iterations and 0.11 seconds (0.15 work units)
Optimal objective -7.67473260e+06

Crossover log...

    1615 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 0s

       1 PPushes remaining with PInf 0.0000000e+00                 0s
       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 2.7177037e-12      0s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    1444   -7.6747326e+06   0.000000e+00   0.000000e+00      0s

Solved in 1444 iterations and 0.13 seconds (0.19 work units)
Optimal objective -7.674732604e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:41 PM: Problem status: optimal
(CVXPY) Jun 08 10:23:41 PM: Optimal value: -7.675e+06
(CVXPY) Jun 08 10:23:41 PM: Compilation took 4.833e+00 seconds
(CVXPY) Jun 08 10:23:41 PM: Solver (including time spent in interface) took 1.677e-01 seconds
(CVXPY) Jun 08 10:23:43 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:43 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:43 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:43 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:43 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:44 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:44 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:44 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:44 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:23:46 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:23:54 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:23:54 PM: Finished problem compilation (took 1.084e+01 seconds).
(CVXPY) Jun 08 10:23:54 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x1d0da8de
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [6e-05, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 357 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17651 columns, 58365 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.322e+04
 Factor NZ  : 1.127e+05 (roughly 14 MB of memory)
 Factor Ops : 1.079e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.18736690e+08 -1.15320227e+09  5.57e+06 1.28e+01  6.96e+06     0s
   1   1.29670029e+08 -4.99177857e+08  1.26e+05 1.38e+00  4.27e+05     0s
   2   1.29782499e+08 -4.98922857e+08  1.26e+05 1.33e+01  4.23e+05     0s
   3   1.29709921e+08 -4.98924184e+08  1.26e+05 7.64e+01  4.19e+05     0s
   4   1.29709921e+08 -4.98924184e+08  1.26e+05 7.64e+01  4.19e+05     0s
   5   1.18736690e+08 -3.10943226e+11  5.57e+06 1.28e+01  1.93e+09     0s
   6   3.46353031e+08 -2.69598966e+11  1.31e+05 4.76e+00  6.18e+07     0s
   7   3.79642732e+08 -3.04330884e+10  5.01e+03 1.24e+01  4.87e+06     0s
   8   3.79130572e+08 -3.04330464e+10  5.01e+03 9.59e+02  4.85e+06     0s
   9   3.79130572e+08 -3.04330464e+10  5.01e+03 9.59e+02  4.85e+06     0s
  10   3.79130572e+08 -3.04330464e+10  5.01e+03 9.59e+02  4.85e+06     0s
  11   1.18736690e+08 -3.10943226e+11  5.57e+06 1.28e+01  1.93e+09     0s
  12   7.62654848e+07 -1.29069436e+10  1.09e+05 2.72e+01  3.97e+07     0s
  13   1.11776662e+08 -1.81265658e+09  4.98e+03 4.23e+00  4.31e+06     0s
  14   7.17377195e+07 -7.05774082e+07  2.10e+02 3.46e-01  2.23e+05     0s
  15   7.17266795e+07 -7.05744082e+07  2.10e+02 8.38e+01  2.18e+05     0s
  16   7.17353121e+07 -7.06125282e+07  2.10e+02 1.12e+02  2.13e+05     0s
  17   7.17353121e+07 -7.06125282e+07  2.10e+02 1.12e+02  2.13e+05     0s
  18   7.17353121e+07 -7.06125282e+07  2.10e+02 1.12e+02  2.13e+05     0s

Barrier performed 18 iterations in 0.21 seconds (0.28 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    8657   -8.3329061e+06   0.000000e+00   0.000000e+00      0s

Solved in 8657 iterations and 0.36 seconds (1.08 work units)
Optimal objective -8.332906080e+06

(CVXPY) Jun 08 10:23:55 PM: Problem status: optimal
(CVXPY) Jun 08 10:23:55 PM: Optimal value: -8.333e+06
(CVXPY) Jun 08 10:23:55 PM: Compilation took 1.084e+01 seconds
(CVXPY) Jun 08 10:23:55 PM: Solver (including time spent in interface) took 4.181e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 6/10 (start=6833) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:23:57 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:23:57 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:23:57 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:23:57 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:23:57 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:23:58 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:23:58 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:23:58 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:23:58 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:23:58 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:24:02 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:24:02 PM: Finished problem compilation (took 4.949e+00 seconds).
(CVXPY) Jun 08 10:24:02 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0xd46ab48e
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 336 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10171 columns, 26999 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 2.000e+04
 Factor NZ  : 9.967e+04 (roughly 8 MB of memory)
 Factor Ops : 1.529e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -5.94867893e+07 -3.50718565e+08  2.35e+05 5.48e+02  5.81e+05     0s
   1  -2.66843032e+07 -1.08029333e+08  3.95e+04 1.99e+01  4.89e+04     0s
   2  -1.47118530e+06 -2.36869785e+07  1.37e+03 4.62e-01  3.49e+03     0s
   3  -6.05315459e+06 -8.17556392e+06  2.93e+01 6.74e-01  2.27e+02     0s
   4  -6.78325600e+06 -7.72174037e+06  1.07e+01 4.95e-01  9.71e+01     0s
   5  -7.04204296e+06 -7.45007246e+06  5.24e+00 1.17e-01  4.16e+01     0s
   6  -7.18793947e+06 -7.37511222e+06  2.48e+00 1.01e-01  1.89e+01     0s
   7  -7.27690916e+06 -7.35289080e+06  9.27e-01 2.14e-02  7.63e+00     0s
   8  -7.30733570e+06 -7.33972868e+06  4.48e-01 1.58e-02  3.24e+00     0s
   9  -7.33029750e+06 -7.33903339e+06  1.04e-01 4.92e-03  8.71e-01     0s
  10  -7.33564666e+06 -7.33841950e+06  3.10e-02 4.61e-03  2.76e-01     0s
  11  -7.33740840e+06 -7.33819613e+06  6.98e-03 3.06e-03  7.81e-02     0s
  12  -7.33779123e+06 -7.33804302e+06  2.44e-03 3.00e-03  2.51e-02     0s
  13  -7.33793316e+06 -7.33801220e+06  7.85e-04 2.98e-03  7.86e-03     0s
  14  -7.33799073e+06 -7.33800602e+06  1.30e-04 9.08e-04  1.53e-03     0s
  15  -7.33800043e+06 -7.33800409e+06  3.31e-05 1.14e-04  3.66e-04     0s
  16  -7.33800302e+06 -7.33800390e+06  7.75e-06 4.96e-05  8.76e-05     0s
  17  -7.33800371e+06 -7.33800386e+06  1.26e-06 5.84e-06  1.47e-05     0s
  18  -7.33800384e+06 -7.33800384e+06  2.36e-11 4.08e-08  1.96e-08     0s
  19  -7.33800384e+06 -7.33800384e+06  2.73e-12 2.71e-11  3.28e-14     0s

Barrier solved model in 19 iterations and 0.09 seconds (0.10 work units)
Optimal objective -7.33800384e+06

Crossover log...

    1025 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 0s

       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 5.6337747e-13      0s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
     847   -7.3380038e+06   0.000000e+00   0.000000e+00      0s

Solved in 847 iterations and 0.11 seconds (0.13 work units)
Optimal objective -7.338003845e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:02 PM: Problem status: optimal
(CVXPY) Jun 08 10:24:02 PM: Optimal value: -7.338e+06
(CVXPY) Jun 08 10:24:02 PM: Compilation took 4.949e+00 seconds
(CVXPY) Jun 08 10:24:02 PM: Solver (including time spent in interface) took 1.446e-01 seconds
(CVXPY) Jun 08 10:24:04 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:24:04 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:24:04 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:24:04 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:24:04 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:24:05 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:24:05 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:24:05 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:06 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:24:08 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:24:16 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:24:16 PM: Finished problem compilation (took 1.162e+01 seconds).
(CVXPY) Jun 08 10:24:16 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0xa1603c88
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 336 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17672 columns, 58491 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.348e+04
 Factor NZ  : 1.150e+05 (roughly 14 MB of memory)
 Factor Ops : 1.130e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.80431469e+08 -1.58161314e+09  7.66e+06 6.40e+00  4.97e+06     0s
   1   1.80453173e+08 -1.58217738e+09  7.66e+06 2.64e+02  4.70e+06     0s
   2   1.80453173e+08 -1.58217738e+09  7.66e+06 2.64e+02  4.70e+06     0s
   3   1.80431469e+08 -8.21118803e+11  7.66e+06 6.40e+00  2.66e+09     0s
   4   4.96693468e+08 -7.18589644e+11  1.56e+05 9.85e+00  8.08e+07     0s
   5   5.75336893e+08 -1.05763870e+11  6.37e+03 6.52e+00  7.69e+06     0s
   6   5.74575083e+08 -1.05763665e+11  6.37e+03 1.30e+03  7.66e+06     0s
   7   5.73389281e+08 -1.05763925e+11  6.37e+03 5.53e+02  7.62e+06     0s
   8   5.73389281e+08 -1.05763925e+11  6.37e+03 5.53e+02  7.62e+06     0s
   9   5.73389281e+08 -1.05763925e+11  6.37e+03 5.53e+02  7.62e+06     0s
  10   5.73389281e+08 -1.05763925e+11  6.37e+03 5.53e+02  7.62e+06     0s

Barrier performed 10 iterations in 0.11 seconds (0.17 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10299   -7.9911148e+06   0.000000e+00   0.000000e+00      0s

Solved in 10299 iterations and 0.40 seconds (1.20 work units)
Optimal objective -7.991114814e+06

(CVXPY) Jun 08 10:24:17 PM: Problem status: optimal
(CVXPY) Jun 08 10:24:17 PM: Optimal value: -7.991e+06
(CVXPY) Jun 08 10:24:17 PM: Compilation took 1.162e+01 seconds
(CVXPY) Jun 08 10:24:17 PM: Solver (including time spent in interface) took 4.600e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 7/10 (start=5282) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:24:19 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:24:19 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:24:19 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:24:19 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:24:19 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:24:20 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:24:20 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:24:20 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:24:20 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:21 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:24:25 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:24:25 PM: Finished problem compilation (took 5.211e+00 seconds).
(CVXPY) Jun 08 10:24:25 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x8bde181a
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 14000 rows and 365 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10142 columns, 26912 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.991e+04
 Factor NZ  : 9.850e+04 (roughly 8 MB of memory)
 Factor Ops : 1.501e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.43816506e+07 -2.80874540e+08  1.69e+05 5.49e+02  4.39e+05     0s
   1  -1.99521334e+07 -8.09772566e+07  2.57e+04 1.66e+01  3.33e+04     0s
   2  -3.48960926e+06 -2.03523244e+07  4.81e+02 1.22e+00  2.22e+03     0s
   3  -6.73908466e+06 -7.97823758e+06  2.57e+01 1.06e+00  1.32e+02     0s
   4  -6.73908466e+06 -7.97823758e+06  2.57e+01 1.06e+00  1.32e+02     0s
   5  -4.44301319e+07 -2.10172712e+10  1.69e+05 1.14e-13  3.54e+07     0s
   6  -6.30884108e+06 -1.26861699e+10  1.48e+04 5.19e+01  4.93e+06     0s
   7   7.53028268e+06 -1.81709685e+09  1.87e+02 1.47e+00  2.32e+05     0s
   8   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.90e+03     0s
   9   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.90e+03     0s
  10   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.90e+03     0s
  11   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.90e+03     0s
  12   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.88e+03     0s
  13   2.17932925e+06 -3.54616823e+07  4.42e-01 1.08e+00  3.88e+03     0s

Barrier performed 13 iterations in 0.07 seconds (0.09 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3720   -7.5778975e+06   0.000000e+00   0.000000e+00      0s

Solved in 3720 iterations and 0.13 seconds (0.39 work units)
Optimal objective -7.577897453e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:25 PM: Problem status: optimal
(CVXPY) Jun 08 10:24:25 PM: Optimal value: -7.578e+06
(CVXPY) Jun 08 10:24:25 PM: Compilation took 5.211e+00 seconds
(CVXPY) Jun 08 10:24:25 PM: Solver (including time spent in interface) took 1.643e-01 seconds
(CVXPY) Jun 08 10:24:26 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:24:27 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:24:27 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:24:27 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:24:27 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:24:27 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:24:27 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:24:27 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:28 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:24:30 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:24:38 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:24:38 PM: Finished problem compilation (took 1.179e+01 seconds).
(CVXPY) Jun 08 10:24:38 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0xf95e4000
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-01, 1e+05]
Presolve removed 21000 rows and 365 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17643 columns, 58317 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.313e+04
 Factor NZ  : 1.126e+05 (roughly 14 MB of memory)
 Factor Ops : 1.079e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.16034201e+08 -1.20013243e+09  5.57e+06 1.28e+01  7.33e+06     0s
   1   1.29556167e+08 -5.21111129e+08  1.48e+05 1.28e+01  4.48e+05     0s
   2   1.29587548e+08 -5.21140851e+08  1.48e+05 2.75e+02  4.44e+05     0s
   3   1.29587548e+08 -5.21140851e+08  1.48e+05 2.75e+02  4.44e+05     0s
   4   1.16034201e+08 -3.07735245e+11  5.57e+06 1.28e+01  1.94e+09     0s
   5   3.42231308e+08 -2.68262896e+11  1.47e+05 4.69e+00  6.32e+07     0s
   6   3.78085853e+08 -3.05519181e+10  4.99e+03 4.92e+00  4.98e+06     0s
   7   3.78017521e+08 -3.05516423e+10  4.99e+03 2.20e+02  4.96e+06     0s
   8   3.76825705e+08 -3.05516048e+10  4.99e+03 6.17e+02  4.92e+06     0s
   9   3.74598313e+08 -3.05515716e+10  4.99e+03 8.04e+02  4.92e+06     0s
  10   3.74598313e+08 -3.05515730e+10  4.99e+03 8.12e+02  4.92e+06     0s
  11   1.16034201e+08 -3.07735245e+11  5.57e+06 1.28e+01  1.94e+09     0s
  12   7.24410174e+07 -3.15181451e+09  1.08e+05 8.26e+00  1.14e+07     0s
  13   1.86582285e+07 -1.45866788e+08  9.56e+02 5.84e-01  1.10e+05     0s
  14   8.11096002e+05 -1.14339134e+07  6.11e+01 2.61e-01  4.91e+03     0s
  15   8.11476327e+05 -1.14335983e+07  6.11e+01 4.41e+00  4.77e+03     0s
  16   8.11804263e+05 -1.14332485e+07  6.11e+01 1.10e+01  4.61e+03     0s
  17   6.99864937e+05 -1.13921794e+07  6.02e+01 3.74e+01  4.64e+03     0s
  18   6.99803562e+05 -1.13921827e+07  6.02e+01 3.64e+01  4.64e+03     0s
  19   6.94814920e+05 -1.13921827e+07  6.02e+01 3.64e+01  4.19e+03     0s
  20   6.96900182e+05 -1.13894221e+07  6.02e+01 4.15e+01  3.99e+03     0s
  21   6.98997767e+05 -1.13875137e+07  6.02e+01 2.97e+02  4.00e+03     0s
  22   6.98997767e+05 -1.13875137e+07  6.02e+01 2.97e+02  4.00e+03     0s
  23   6.99026869e+05 -1.14028708e+07  6.02e+01 3.03e+02  3.99e+03     0s
  24   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.83e+03     0s
  25   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s
  26   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s
  27   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s
  28   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s
  29   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s
  30   7.32004645e+05 -1.14414646e+07  6.06e+01 3.30e+02  3.81e+03     0s

Barrier performed 30 iterations in 0.36 seconds (0.45 work units)
Numerical trouble encountered


Solved with primal simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   15316   -8.2391165e+06   0.000000e+00   0.000000e+00      0s

Solved in 15316 iterations and 0.48 seconds (1.26 work units)
Optimal objective -8.239116461e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:39 PM: Problem status: optimal
(CVXPY) Jun 08 10:24:39 PM: Optimal value: -8.239e+06
(CVXPY) Jun 08 10:24:39 PM: Compilation took 1.179e+01 seconds
(CVXPY) Jun 08 10:24:39 PM: Solver (including time spent in interface) took 5.412e-01 seconds

Instance 8/10 (start=6916) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:24:42 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:24:42 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:24:42 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:24:42 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:24:42 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:24:42 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:24:42 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:24:42 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:24:42 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:43 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:24:48 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:24:48 PM: Finished problem compilation (took 5.738e+00 seconds).
(CVXPY) Jun 08 10:24:48 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0x87a05214
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 404 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10103 columns, 26795 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.980e+04
 Factor NZ  : 9.712e+04 (roughly 8 MB of memory)
 Factor Ops : 1.471e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.89958563e+07 -2.80666040e+08  1.86e+05 5.48e+02  4.48e+05     0s
   1  -2.24179229e+07 -9.58784859e+07  3.11e+04 2.68e+01  4.14e+04     0s
   2  -2.49434116e+06 -2.12874616e+07  5.18e+02 1.02e+00  2.61e+03     0s
   3  -6.53618271e+06 -7.79580103e+06  2.29e+01 3.92e+00  1.35e+02     0s
   4  -6.53618271e+06 -7.79580103e+06  2.29e+01 3.92e+00  1.35e+02     0s
   5  -4.90542660e+07 -2.25407506e+10  1.86e+05 1.14e-13  3.90e+07     0s
   6  -7.36100106e+06 -1.35592100e+10  1.95e+04 7.50e+01  6.74e+06     0s
   7   8.85664022e+06 -2.14065583e+09  4.74e+02 2.51e+00  3.81e+05     0s
   8   6.55574358e+06 -6.04357964e+07  3.26e+00 6.16e-01  7.02e+03     0s
   9  -6.44568125e+06 -9.70592171e+06  3.25e-02 6.35e-01  3.29e+02     0s
  10  -6.44568125e+06 -9.70592171e+06  3.25e-02 6.35e-01  3.29e+02     0s
  11  -6.44568125e+06 -9.70592171e+06  3.25e-02 6.35e-01  3.29e+02     0s
  12  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  13  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  14  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  15  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  16  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  17  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  18  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  19  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  20  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  21  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s
  22  -5.59254797e+06 -7.64140080e+06  1.18e-11 1.76e-02  2.03e+02     0s

Barrier performed 22 iterations in 0.11 seconds (0.15 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3677   -7.4655142e+06   0.000000e+00   0.000000e+00      0s

Solved in 3677 iterations and 0.15 seconds (0.37 work units)
Optimal objective -7.465514211e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:48 PM: Problem status: optimal
(CVXPY) Jun 08 10:24:48 PM: Optimal value: -7.466e+06
(CVXPY) Jun 08 10:24:48 PM: Compilation took 5.738e+00 seconds
(CVXPY) Jun 08 10:24:48 PM: Solver (including time spent in interface) took 1.848e-01 seconds
(CVXPY) Jun 08 10:24:49 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:24:50 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:24:50 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:24:50 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:24:50 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:24:50 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:24:50 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:24:50 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:24:51 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:24:53 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:25:03 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:25:03 PM: Finished problem compilation (took 1.288e+01 seconds).
(CVXPY) Jun 08 10:25:03 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x2391071c
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 404 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17604 columns, 58083 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.266e+04
 Factor NZ  : 1.130e+05 (roughly 14 MB of memory)
 Factor Ops : 1.092e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.30645925e+08 -1.24941648e+09  6.43e+06 1.28e+01  8.12e+06     0s
   1   1.49334980e+08 -5.61789848e+08  2.28e+05 7.29e+00  5.16e+05     0s
   2   1.49328755e+08 -5.61796122e+08  2.28e+05 1.96e+02  5.11e+05     0s
   3   1.49316327e+08 -5.61808472e+08  2.28e+05 4.45e+02  5.06e+05     0s
   4   1.49026462e+08 -5.61771713e+08  2.28e+05 2.18e+02  5.01e+05     0s
   5   1.49026462e+08 -5.61771713e+08  2.28e+05 2.18e+02  5.01e+05     0s
   6   1.30645925e+08 -3.32664255e+11  6.43e+06 1.28e+01  2.23e+09     0s
   7   3.89017982e+08 -2.96735643e+11  2.22e+05 5.28e+00  7.71e+07     0s
   8   3.89034084e+08 -2.96735689e+11  2.22e+05 1.29e+03  7.57e+07     0s
   9   3.89042569e+08 -2.96735229e+11  2.22e+05 2.52e+03  7.39e+07     0s
  10   8.06754617e+08 -8.50103750e+10  4.54e+04 1.85e+03  2.69e+07     0s
  11   8.06695165e+08 -8.50058905e+10  4.54e+04 3.62e+03  2.56e+07     0s
  12   8.08389450e+08 -8.50058657e+10  4.54e+04 2.95e+03  2.53e+07     0s
  13   1.30645925e+08 -3.32664255e+11  6.43e+06 1.28e+01  2.23e+09     0s
  14   4.29240156e+07 -2.62294710e+09  1.86e+05 1.10e+01  2.28e+07     0s
  15   3.99293658e+07 -7.28007486e+08  4.82e+04 3.23e+00  3.93e+06     0s
  16   1.01664440e+07 -5.92828027e+07  7.59e+02 4.63e-01  1.17e+05     0s
  17  -2.88784512e+06 -9.41258818e+06  4.81e+01 3.39e-01  4.22e+03     0s
  18  -7.17753683e+06 -8.25793377e+06  4.18e+00 2.97e-01  2.53e+02     0s
  19  -7.17753683e+06 -8.25793377e+06  4.18e+00 2.97e-01  2.53e+02     0s
  20  -7.17753683e+06 -8.25793377e+06  4.18e+00 2.97e-01  2.53e+02     0s
  21  -7.17753683e+06 -8.25793377e+06  4.18e+00 2.97e-01  2.26e+02     0s
  22  -8.02803402e+06 -8.16838823e+06  5.24e-01 2.63e-01  1.82e+01     0s
  23  -8.11271820e+06 -8.13451919e+06  8.61e-02 2.14e-02  2.68e+00     0s
  24  -8.12192926e+06 -8.12992083e+06  3.44e-02 4.31e-03  9.62e-01     0s
  25  -8.12538844e+06 -8.12875238e+06  1.22e-02 2.24e-03  4.09e-01     0s
  26  -8.12647369e+06 -8.12830858e+06  4.61e-03 1.61e-03  2.26e-01     0s
  27  -8.12678008e+06 -8.12806299e+06  2.35e-03 1.25e-03  1.59e-01     0s
  28  -8.12695088e+06 -8.12772015e+06  1.16e-03 7.62e-04  9.60e-02     0s
  29  -8.12705950e+06 -8.12760802e+06  4.47e-04 6.13e-04  6.91e-02     0s
  30  -8.12708376e+06 -8.12746172e+06  2.99e-04 4.23e-04  4.77e-02     0s
  31  -8.12710845e+06 -8.12738492e+06  1.67e-04 3.21e-04  3.50e-02     0s
  32  -8.12711769e+06 -8.12729397e+06  1.11e-04 2.01e-04  2.23e-02     0s
  33  -8.12712500e+06 -8.12724741e+06  7.39e-05 1.40e-04  1.55e-02     0s
  34  -8.12712860e+06 -8.12721722e+06  5.46e-05 1.01e-04  1.12e-02     0s
  35  -8.12713408e+06 -8.12719645e+06  2.52e-05 7.34e-05  7.91e-03     0s
  36  -8.12713615e+06 -8.12718127e+06  1.54e-05 5.35e-05  5.73e-03     0s
  37  -8.12713719e+06 -8.12717647e+06  1.12e-05 4.72e-05  4.99e-03     0s
  38  -8.12713788e+06 -8.12716685e+06  8.06e-06 3.51e-05  3.69e-03     0s
  39  -8.12713895e+06 -8.12715997e+06  3.73e-06 2.61e-05  2.68e-03     0s
  40  -8.12714020e+06 -8.12714720e+06  9.97e-08 9.14e-06  8.97e-04     0s
  41  -8.12714033e+06 -8.12714483e+06  4.92e-08 5.93e-06  5.78e-04     0s
  42  -8.12714040e+06 -8.12714095e+06  6.31e-09 1.15e-06  7.19e-05     0s

Barrier performed 42 iterations in 0.46 seconds (0.64 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    9024   -8.1271405e+06   0.000000e+00   0.000000e+00      0s

Solved in 9024 iterations and 0.47 seconds (0.99 work units)
Optimal objective -8.127140467e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:25:04 PM: Problem status: optimal
(CVXPY) Jun 08 10:25:04 PM: Optimal value: -8.127e+06
(CVXPY) Jun 08 10:25:04 PM: Compilation took 1.288e+01 seconds
(CVXPY) Jun 08 10:25:04 PM: Solver (including time spent in interface) took 5.252e-01 seconds

Instance 9/10 (start=6330) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (6,), (1,), (500, 6), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
(CVXPY) Jun 08 10:25:06 PM: Your problem has 3507 variables, 7501 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:25:06 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:25:06 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:25:06 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:25:06 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:25:06 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:25:06 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:25:06 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 08 10:25:06 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:25:07 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:25:11 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:25:11 PM: Finished problem compilation (took 5.309e+00 seconds).
(CVXPY) Jun 08 10:25:11 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 21501 rows, 10507 columns and 42007 nonzeros
Model fingerprint: 0xce3390a0
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 14000 rows and 414 columns
Presolve time: 0.02s
Presolved: 7501 rows, 10093 columns, 26765 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 7
 Free vars  : 7
 AA' NZ     : 1.976e+04
 Factor NZ  : 9.679e+04 (roughly 8 MB of memory)
 Factor Ops : 1.464e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.48608889e+07 -3.03506335e+08  1.58e+05 5.48e+02  4.23e+05     0s
   1  -2.13052610e+07 -9.57842145e+07  3.01e+04 2.85e+01  4.31e+04     0s
   2  -2.99964146e+06 -2.45820406e+07  6.99e+02 2.23e+00  3.49e+03     0s
   3  -6.38405760e+06 -7.91955978e+06  2.50e+01 1.75e+00  1.64e+02     0s
   4  -6.38405760e+06 -7.91955978e+06  2.50e+01 1.75e+00  1.64e+02     0s
   5  -4.49133960e+07 -2.22555425e+10  1.58e+05 1.14e-13  3.34e+07     0s
   6  -6.27064793e+06 -1.20384239e+10  1.35e+04 7.31e+01  5.42e+06     0s
   7   6.30234073e+06 -1.50694345e+09  5.20e+02 1.76e+00  2.13e+05     0s
   8  -2.35966016e+04 -9.07344358e+07  5.91e+00 1.58e+00  9.86e+03     0s
   9  -6.07493791e+06 -9.49761383e+06  1.83e-01 1.94e+00  3.54e+02     0s
  10  -7.10756088e+06 -7.95417494e+06  3.45e-02 3.19e-01  8.52e+01     0s
  11  -7.32953466e+06 -7.52282683e+06  7.80e-03 9.32e-02  1.93e+01     0s
  12  -7.40952257e+06 -7.46344935e+06  1.36e-03 2.88e-02  5.36e+00     0s
  13  -7.42468586e+06 -7.44427169e+06  4.65e-04 9.24e-03  1.95e+00     0s
  14  -7.43029681e+06 -7.43894205e+06  1.91e-04 4.06e-03  8.59e-01     0s
  15  -7.43336893e+06 -7.43619207e+06  4.35e-05 1.51e-03  2.80e-01     0s
  16  -7.43433986e+06 -7.43460436e+06  3.09e-06 8.96e-05  2.63e-02     0s
  17  -7.43441109e+06 -7.43449198e+06  8.57e-07 2.32e-05  8.03e-03     0s
  18  -7.43442782e+06 -7.43447046e+06  3.89e-07 1.24e-05  4.23e-03     0s
  19  -7.43443548e+06 -7.43446217e+06  2.03e-07 7.98e-06  2.65e-03     0s
  20  -7.43443690e+06 -7.43446032e+06  1.72e-07 7.11e-06  2.32e-03     0s
  21  -7.43444077e+06 -7.43445660e+06  8.21e-08 5.30e-06  1.57e-03     0s
  22  -7.43444273e+06 -7.43445438e+06  3.64e-08 4.25e-06  1.16e-03     0s
  23  -7.43444338e+06 -7.43445057e+06  2.50e-08 2.46e-06  7.14e-04     0s
  24  -7.43444350e+06 -7.43445024e+06  2.31e-08 2.32e-06  6.69e-04     0s
  25  -7.43444386e+06 -7.43444961e+06  1.68e-08 2.05e-06  5.71e-04     0s
  26  -7.43444420e+06 -7.43444758e+06  1.17e-08 1.11e-06  3.36e-04     0s
  27  -7.43444440e+06 -7.43444662e+06  8.33e-09 6.93e-07  2.21e-04     0s
  28  -7.43444458e+06 -7.43444560e+06  5.41e-09 2.70e-07  1.01e-04     0s
  29  -7.43444469e+06 -7.43444546e+06  3.80e-09 2.05e-07  7.68e-05     0s
  30  -7.43444470e+06 -7.43444545e+06  3.57e-09 2.00e-07  7.40e-05     0s
  31  -7.43444479e+06 -7.43444542e+06  2.54e-09 1.89e-07  6.32e-05     0s

Barrier performed 31 iterations in 0.13 seconds (0.17 work units)
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3804   -7.4344450e+06   0.000000e+00   0.000000e+00      0s

Solved in 3804 iterations and 0.15 seconds (0.40 work units)
Optimal objective -7.434444980e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:25:12 PM: Problem status: optimal
(CVXPY) Jun 08 10:25:12 PM: Optimal value: -7.434e+06
(CVXPY) Jun 08 10:25:12 PM: Compilation took 5.309e+00 seconds
(CVXPY) Jun 08 10:25:12 PM: Solver (including time spent in interface) took 1.807e-01 seconds
(CVXPY) Jun 08 10:25:13 PM: Your problem has 4008 variables, 8001 constraints, and 0 parameters.

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) Jun 08 10:25:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 08 10:25:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 08 10:25:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 08 10:25:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 08 10:25:14 PM: Compiling problem (target solver=GUROBI).
(CVXPY) Jun 08 10:25:14 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) Jun 08 10:25:14 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:25:15 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Jun 08 10:25:17 PM: Applying reduction QpMatrixStuffing
(CVXPY) Jun 08 10:25:26 PM: Applying reduction GUROBI
(CVXPY) Jun 08 10:25:26 PM: Finished problem compilation (took 1.252e+01 seconds).
(CVXPY) Jun 08 10:25:26 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 36001 rows, 18008 columns and 81507 nonzeros
Model fingerprint: 0x897b4e09
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+05]
Presolve removed 21000 rows and 414 columns
Presolve time: 0.02s
Presolved: 15001 rows, 17594 columns, 58023 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 8
 Free vars  : 8
 AA' NZ     : 6.254e+04
 Factor NZ  : 1.124e+05 (roughly 14 MB of memory)
 Factor Ops : 1.078e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   7.53799512e+07 -9.25779995e+08  5.21e+06 6.40e+00  4.92e+06     0s
   1   9.02561909e+07 -3.82463441e+08  2.12e+05 7.34e+00  3.47e+05     0s
   2   9.04033799e+07 -3.82173254e+08  2.12e+05 1.04e+02  3.43e+05     0s
   3   9.04093768e+07 -3.82193508e+08  2.12e+05 3.31e+02  3.34e+05     0s
   4   9.02499944e+07 -3.82203952e+08  2.12e+05 4.52e+02  3.30e+05     0s
   5   9.02499944e+07 -3.82203952e+08  2.12e+05 4.52e+02  3.30e+05     0s
   6   7.53799512e+07 -3.28240688e+11  5.21e+06 6.40e+00  1.82e+09     0s
   7   2.58240729e+08 -2.63141914e+11  2.32e+05 1.43e+01  9.95e+07     0s
   8   3.12709982e+08 -2.33868084e+10  8.30e+03 2.60e+00  5.30e+06     0s
   9   3.12708664e+08 -2.33867891e+10  8.30e+03 2.84e+02  5.28e+06     0s
  10   3.12546158e+08 -2.33865194e+10  8.30e+03 1.31e+02  5.27e+06     0s
  11   7.53799512e+07 -3.28240688e+11  5.21e+06 6.40e+00  1.82e+09     0s
  12   5.34143389e+07 -1.15193773e+10  1.87e+05 3.37e+01  3.60e+07     0s
  13   8.35478672e+07 -1.75888442e+09  8.64e+03 5.07e+00  3.45e+06     0s
  14   4.95425282e+07 -7.07996494e+07  3.21e+02 4.32e-01  1.46e+05     0s
  15   4.95405950e+07 -7.07986033e+07  3.21e+02 4.78e+01  1.45e+05     0s
  16   4.95407412e+07 -7.07986903e+07  3.21e+02 5.72e+01  1.44e+05     0s
  17   4.95380112e+07 -7.08013961e+07  3.21e+02 1.60e+02  1.40e+05     0s
  18   4.95185379e+07 -7.08316164e+07  3.21e+02 1.19e+02  1.39e+05     0s
  19   4.95233976e+07 -7.08264407e+07  3.21e+02 4.26e+01  1.38e+05     0s
  20   4.95236862e+07 -7.08262231e+07  3.21e+02 4.91e+01  1.38e+05     0s
  21   4.95118936e+07 -7.08366963e+07  3.21e+02 3.93e+01  1.37e+05     0s
  22   4.94120770e+07 -7.06482368e+07  3.20e+02 6.72e+04  1.36e+05     0s
  23   1.92120383e+07 -3.71927915e+07  1.22e+02 3.56e+04  4.99e+04     0s
  24   1.92142172e+07 -3.71905976e+07  1.22e+02 3.53e+04  4.88e+04     0s
  25   1.92138308e+07 -3.75166799e+07  1.23e+02 3.54e+04  4.83e+04     0s
  26   1.92204343e+07 -3.73014135e+07  1.20e+02 3.53e+04  4.63e+04     0s
  27  -4.40092121e+06 -8.77278515e+06  8.84e+00 2.10e+03  1.08e+03     0s
  28  -4.40058435e+06 -8.77235829e+06  8.84e+00 2.12e+03  1.04e+03     0s
  29  -4.39980460e+06 -8.76588953e+06  8.84e+00 2.13e+03  1.04e+03     0s
  30  -4.39070736e+06 -8.75979146e+06  8.84e+00 2.47e+03  1.04e+03     0s
  31  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  32  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  33  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  34  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  35  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  36  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s
  37  -4.38780358e+06 -8.75817340e+06  8.84e+00 2.68e+03  1.02e+03     0s

Barrier performed 37 iterations in 0.41 seconds (0.55 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11189   -8.1014498e+06   0.000000e+00   0.000000e+00      0s

Solved in 11189 iterations and 0.46 seconds (1.07 work units)
Optimal objective -8.101449821e+06
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------

(CVXPY) Jun 08 10:25:27 PM: Problem status: optimal
(CVXPY) Jun 08 10:25:27 PM: Optimal value: -8.101e+06
(CVXPY) Jun 08 10:25:27 PM: Compilation took 1.252e+01 seconds
(CVXPY) Jun 08 10:25:27 PM: Solver (including time spent in interface) took 5.184e-01 seconds

Instance 10/10 (start=8061) done.

In [54]:
# Aggregate and average
keys = list(results_list[0].keys())
means = {k: np.mean([r[k] for r in results_list]) for k in keys}
stds = {k: np.std([r[k] for r in results_list]) for k in keys}

print("============== Real-data results (averaged over {} instances) ================".format(NUM_INSTANCES))
print("Distortion (DA vs E[RT price]):")
print("  Stochastic:", means["stoch_distortion"], "±", stds["stoch_distortion"])
print("  CVaR:", means["cvar_distortion"], "±", stds["cvar_distortion"])
print("  Deterministic:", means["det_distortion"], "±", stds["det_distortion"])
print("E[Social Surplus]:")
print("  Stochastic:", means["stoch_ss"], "±", stds["stoch_ss"])
print("  CVaR:", means["cvar_ss"], "±", stds["cvar_ss"])
print("  Deterministic:", means["det_ss"], "±", stds["det_ss"])
print("Tail (5%) welfare (mean positive SS in worst tail):")
print("  Stochastic:", means["stoch_tail_welfare"], "±", stds["stoch_tail_welfare"])
print("  CVaR:", means["cvar_tail_welfare"], "±", stds["cvar_tail_welfare"])
print("  Deterministic:", means["det_tail_welfare"], "±", stds["det_tail_welfare"])
print("Tail (5%) price distortion:")
print("  Stochastic:", means["stoch_tail_distortion"], "±", stds["stoch_tail_distortion"])
print("  CVaR:", means["cvar_tail_distortion"], "±", stds["cvar_tail_distortion"])
print("  Deterministic:", means["det_tail_distortion"], "±", stds["det_tail_distortion"])
print("Probability feasible:", means["prob_feasible"], "±", stds["prob_feasible"])

============== Real-data results (averaged over 10 instances) ================
Distortion (DA vs E[RT price]):
  Stochastic: 0.10322271705047115 ± 0.03424412492273862
  CVaR: 110.13745034862677 ± 0.0542569754085183
  Deterministic: 319.9997050722226 ± 63.2732247277555
E[Social Surplus]:
  Stochastic: 7464950.149920413 ± 126265.42365608271
  CVaR: 7464403.498541241 ± 125901.87218025303
  Deterministic: 7157107.150425534 ± 108607.39368294517
Tail (5%) welfare (mean positive SS in worst tail):
  Stochastic: 6591193.203497878 ± 44278.587082714905
  CVaR: 6602446.4061759785 ± 44533.45618233329
  Deterministic: 6563198.315027048 ± 42004.89984181003
Tail (5%) price distortion:
  Stochastic: 99.99999999999967 ± 4.895221768568046e-13
  CVaR: 4.591506925615025e-13 ± 2.2381399408218101e-13
  Deterministic: 100.0 ± 0.0
Probability feasible: 0.21528565591701193 ± 0.10190894473253172

In [55]:
summary = pd.DataFrame({
    "Method": ["Stochastic", "CVaR", "Deterministic"] * 3,
    "Metric": ["Distortion", "Distortion", "Distortion", "E[SS]", "E[SS]", "E[SS]", "Tail welfare", "Tail welfare", "Tail welfare"],
    "Mean": [
        means["stoch_distortion"], means["cvar_distortion"], means["det_distortion"],
        means["stoch_ss"], means["cvar_ss"], means["det_ss"],
        means["stoch_tail_welfare"], means["cvar_tail_welfare"], means["det_tail_welfare"],
    ],
    "Std": [
        stds["stoch_distortion"], stds["cvar_distortion"], stds["det_distortion"],
        stds["stoch_ss"], stds["cvar_ss"], stds["det_ss"],
        stds["stoch_tail_welfare"], stds["cvar_tail_welfare"], stds["det_tail_welfare"],
    ],
})
summary["Std/Mean"] = summary["Std"] / summary["Mean"]
display(summary)

          Method        Metric          Mean            Std  Std/Mean
0     Stochastic    Distortion  1.032227e-01       0.034244  0.331750
1           CVaR    Distortion  1.101375e+02       0.054257  0.000493
2  Deterministic    Distortion  3.199997e+02      63.273225  0.197729
3     Stochastic         E[SS]  7.464950e+06  126265.423656  0.016914
4           CVaR         E[SS]  7.464403e+06  125901.872180  0.016867
5  Deterministic         E[SS]  7.157107e+06  108607.393683  0.015175
6     Stochastic  Tail welfare  6.591193e+06   44278.587083  0.006718
7           CVaR  Tail welfare  6.602446e+06   44533.456182  0.006745
8  Deterministic  Tail welfare  6.563198e+06   42004.899842  0.006400

In [56]:
from pathlib import Path

LOG_DIR = Path("outputs/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

print("\n=== Summary dataframe ===")
print(summary.to_string(index=False))

with open(LOG_DIR / "summary_dataframe.log", "w") as f:
    f.write(summary.to_string(index=False))
    f.write("\n")

=== Summary dataframe ===
       Method       Metric         Mean           Std  Std/Mean
   Stochastic   Distortion 1.032227e-01      0.034244  0.331750
         CVaR   Distortion 1.101375e+02      0.054257  0.000493
Deterministic   Distortion 3.199997e+02     63.273225  0.197729
   Stochastic        E[SS] 7.464950e+06 126265.423656  0.016914
         CVaR        E[SS] 7.464403e+06 125901.872180  0.016867
Deterministic        E[SS] 7.157107e+06 108607.393683  0.015175
   Stochastic Tail welfare 6.591193e+06  44278.587083  0.006718
         CVaR Tail welfare 6.602446e+06  44533.456182  0.006745
Deterministic Tail welfare 6.563198e+06  42004.899842  0.006400