In [1]:
import os
import numpy as np
import pandas as pd

# Paths: notebook is in zavala_electricity_market, data in dataset/IM-3-GO-WEST
# Run from project root (prj_market) or from zavala_electricity_market
_cwd = os.getcwd()
if os.path.basename(_cwd) == "zavala_electricity_market":
    BASE_DIR = os.path.dirname(_cwd)
else:
    BASE_DIR = _cwd
DATA_DIR = os.path.join(BASE_DIR, "dataset", "IM-3-GO-WEST")
if not os.path.isdir(DATA_DIR):
    DATA_DIR = os.path.join(_cwd, "dataset", "IM-3-GO-WEST")

# Ensure zavala_electricity_market is on path (when running from project root)
import sys
ZAVALA_DIR = os.path.join(BASE_DIR, "zavala_electricity_market")
if os.path.isdir(ZAVALA_DIR) and ZAVALA_DIR not in sys.path:
    sys.path.insert(0, ZAVALA_DIR)

# --- Minimal customization for current repo layout ---

# 1) If the original DATA_DIR doesn't exist, try archive/dataset/IM-3-GO-WEST
if not os.path.isdir(DATA_DIR):
    alt_data_dir = os.path.join(BASE_DIR, "archive", "dataset", "IM-3-GO-WEST")
    if os.path.isdir(alt_data_dir):
        DATA_DIR = alt_data_dir

# 2) If ZAVALA_DIR isn't a valid dir (e.g. code is at repo root),
#    fall back to BASE_DIR itself when it has zavala_funcs.py
if not os.path.isdir(ZAVALA_DIR):
    repo_root_candidate = BASE_DIR
    if os.path.isfile(os.path.join(repo_root_candidate, "zavala_funcs.py")):
        if repo_root_candidate not in sys.path:
            sys.path.insert(0, repo_root_candidate)
        ZAVALA_DIR = repo_root_candidate

print("Using DATA_DIR:", DATA_DIR)
print("Using ZAVALA_DIR:", ZAVALA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

from zavala_funcs import (
    zavala,
    zavala_cvar,
    zavala_deterministic_da,
    zavala_rt_energy_only,
    expected_caps_from_scenarios,
    price_distortion,
    probability_feasible,
    expected_cumulative_regret,
    compute_social_surplus,
    tail_worst_indices_by_value,
    _stack_rt,
)

print("Data dir:", DATA_DIR)
print("Files:", os.listdir(DATA_DIR) if os.path.isdir(DATA_DIR) else "not found")

Using DATA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Using ZAVALA_DIR: /Users/maxwirattawut/Developer/zavala_electricity_market
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']
Data dir: /Users/maxwirattawut/Developer/zavala_electricity_market/dataset/IM-3-GO-WEST
Files: ['nodal_load.csv', 'nodal_wind.csv', 'thermal_gens.csv', 'egrid2023_data_rev2.xlsx', 'nodal_solar.csv']

In [2]:
# Load nodal time series (rows = time, columns = bus_XXXXX)
solar = pd.read_csv(os.path.join(DATA_DIR, "nodal_solar.csv"))
wind = pd.read_csv(os.path.join(DATA_DIR, "nodal_wind.csv"))
load_df = pd.read_csv(os.path.join(DATA_DIR, "nodal_load.csv"))
thermal_df = pd.read_csv(os.path.join(DATA_DIR, "thermal_gens.csv"))

T = len(solar)
assert len(wind) == T and len(load_df) == T, "Solar, wind, load must have same length"
print(f"Time steps: {T}")
print(f"Solar columns: {solar.shape[1]}, Wind: {wind.shape[1]}, Load: {load_df.shape[1]}")
print(f"Thermal generators: {len(thermal_df)}")

Time steps: 8760
Solar columns: 125, Wind: 125, Load: 125
Thermal generators: 280

In [3]:
# Choose buses with non-trivial solar: columns with max > threshold
solar_cols = [c for c in solar.columns if solar[c].max() > 50]
wind_cols = [c for c in wind.columns if wind[c].max() > 50]
# Pick x solar and y wind (unreliable)
num_solar, num_wind = 9, 9
solar_buses = solar_cols[:num_solar] if len(solar_cols) >= num_solar else list(solar.columns[:num_solar])
wind_buses = wind_cols[:num_wind] if len(wind_cols) >= num_wind else list(wind.columns[:num_wind])

# Reliable: aggregate thermal by bus, pick 4 buses with largest capacity
thermal_by_bus = thermal_df.groupby("Bus")["Max_Cap"].sum().sort_values(ascending=False)
thermal_buses_numeric = list(thermal_by_bus.head(4).index)  # e.g. [408441, 135041, ...]
thermal_bus_cols = [f"bus_{b}" for b in thermal_buses_numeric]  # for load alignment if needed

# Load: use total system load (sum over all buses)
load_total = load_df.sum(axis=1).values  # (T,)

print("Solar buses (unreliable):", solar_buses)
print("Wind buses (unreliable):", wind_buses)
print("Thermal buses (reliable):", thermal_buses_numeric)
print("Load: system total (sum over all buses)")

Solar buses (unreliable): ['bus_100931', 'bus_200261', 'bus_201361', 'bus_204901', 'bus_211211', 'bus_230601', 'bus_232301', 'bus_232631', 'bus_251601']
Wind buses (unreliable): ['bus_100931', 'bus_102281', 'bus_105701', 'bus_106771', 'bus_134461', 'bus_135041', 'bus_211211', 'bus_211651', 'bus_251601']
Thermal buses (reliable): [500991, 605141, 408441, 261001]
Load: system total (sum over all buses)

In [4]:
# Filter thermal_df for the selected buses
selected_buses = [500991, 605141, 408441, 261001]
thermal_selected = thermal_df[thermal_df['Bus'].isin(selected_buses)]
display(thermal_selected)

,Name,Bus,Fuel,Max_Cap,Min_Cap,Heat_Rate
0,PHOENIX_Nuc,408441,NUC (Nuclear),4209.60,1046.90,8.530000
1,TONOPAH_NG,408441,NG (Natural Gas),1325.10,393.07,4.177264
2,PHOENIX_NG,408441,NG (Natural Gas),1207.38,449.72,3.622784
28,BRUSH_C,605141,BIT (Bituminous Coal),552.30,78.79,8.941106
29,WELLINGTON_C,605141,BIT (Bituminous Coal),800.40,247.36,8.242654
30,DENVER_C,605141,BIT (Bituminous Coal),586.31,164.07,7.933221
31,KEENESBURG_NG,605141,NG (Natural Gas),685.11,246.77,5.015047
32,BOULDER_C,605141,BIT (Bituminous Coal),251.00,55.58,8.227582
33,PLATTEVILLE_NG,605141,NG (Natural Gas),1185.48,481.17,2.758167
34,AURORA_NG,605141,NG (Natural Gas),397.80,147.60,4.898308
35,COMMERCECITY_NG,605141,NG (Natural Gas),154.20,29.25,4.799750
36,DENVER_NG,605141,NG (Natural Gas),269.01,54.48,3.526185
37,FORTLUPTON_NG,605141,NG (Natural Gas),497.70,120.82,4.718237
38,BURLINGTON_C,605141,BIT (Bituminous Coal),129.40,47.19,7.651625
39,FREDERICK_NG,605141,NG (Natural Gas),394.00,136.49,2.436760
40,BRUSH_NG,605141,NG (Natural Gas),597.22,156.56,3.038616
41,LIMON_NG,605141,NG (Natural Gas),154.20,37.06,4.622871
42,LAMAR_C,605141,BIT (Bituminous Coal),43.50,17.89,7.974531
43,CHEYENNE_NG,605141,NG (Natural Gas),139.99,33.48,4.731375
55,CASTLEDALE_C,500991,BIT (Bituminous Coal),1577.19,296.35,8.900558
56,HUNTINGTON_C,500991,BIT (Bituminous Coal),1037.30,382.51,8.612997
57,OREM_NG,500991,NG (Natural Gas),1392.48,370.22,3.543914
58,MONA_NG,500991,NG (Natural Gas),648.99,208.10,5.030309
59,KEMMERER_C,500991,BIT (Bituminous Coal),831.99,304.11,8.195294
60,HELPER_C,500991,BIT (Bituminous Coal),208.60,49.90,8.192120
61,SALTLAKECITY_NG,500991,NG (Natural Gas),783.49,218.84,3.554682
62,PAYSON_NG,500991,NG (Natural Gas),140.00,43.07,3.959980
63,SUNNYSIDE_C,500991,BIT (Bituminous Coal),58.10,6.34,8.114105
64,MAGNA_C,500991,BIT (Bituminous Coal),213.80,41.00,7.651219
65,BOUNTIFUL_NG,500991,NG (Natural Gas),30.39,8.90,2.977745
77,SUNCITY_NG,261001,NG (Natural Gas),819.00,228.42,2.720162
78,REDONDOBEACH_NG,261001,NG (Natural Gas),1316.40,454.78,5.271419
79,LONGBEACH_NG,261001,NG (Natural Gas),2173.98,657.33,4.487376
80,PLAYADELREY_NG,261001,NG (Natural Gas),823.20,271.80,5.154075
81,HUNTINGTONBEACH_NG,261001,NG (Natural Gas),436.00,100.93,2.516905
82,WILMINGTON_NG,261001,NG (Natural Gas),548.11,163.17,5.168842
83,CARSON_NG,261001,NG (Natural Gas),405.00,135.72,3.373920

Debug Logs

In [5]:
# For diagnostics: breakdown of DA and RT allocations
def _log(msg, logfile=None):
    if logfile is None:
        print(msg)
    else:
        with open(logfile, "a", encoding="utf-8") as f:
            f.write(str(msg) + "\n")

def _tech_breakdown_da(g_da):
    g_da = np.asarray(g_da, dtype=float)
    return {
        "solar": g_da[:3].sum(),
        "wind": g_da[3:6].sum(),
        "thermal": g_da[6:10].sum(),
        "total": g_da.sum(),
    }

def _tech_breakdown_rt(G_rt, probs=None):
    G_rt = np.asarray(G_rt, dtype=float)  # shape (S, 10)
    solar = G_rt[:, :3].sum(axis=1)
    wind = G_rt[:, 3:6].sum(axis=1)
    thermal = G_rt[:, 6:10].sum(axis=1)
    total = G_rt.sum(axis=1)

    if probs is None:
        return {
            "solar": solar.mean(),
            "wind": wind.mean(),
            "thermal": thermal.mean(),
            "total": total.mean(),
        }

    probs = np.asarray(probs, dtype=float)
    return {
        "solar": np.dot(probs, solar),
        "wind": np.dot(probs, wind),
        "thermal": np.dot(probs, thermal),
        "total": np.dot(probs, total),
    }

def _print_case_diag(name, probs, g_da, d_da, G_rt, D_rt, pi, Pi,
                     n_solar, n_wind, n_thermal, logfile=None):
    g_da = np.asarray(g_da, dtype=float)
    d_da = np.asarray(d_da, dtype=float)
    G_rt = np.asarray(G_rt, dtype=float)
    D_rt = np.asarray(D_rt, dtype=float)
    probs = np.asarray(probs, dtype=float)
    Pi = np.asarray(Pi, dtype=float)

    exp_rt = np.dot(probs, G_rt)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    da_alloc = {
        "solar": g_da[solar_slice].sum(),
        "wind": g_da[wind_slice].sum(),
        "thermal": g_da[thermal_slice].sum(),
        "total": g_da.sum(),
    }
    rt_alloc = {
        "solar": exp_rt[solar_slice].sum(),
        "wind": exp_rt[wind_slice].sum(),
        "thermal": exp_rt[thermal_slice].sum(),
        "total": exp_rt.sum(),
    }

    da_load = float(d_da.sum())
    exp_rt_load = float(np.dot(probs, D_rt.sum(axis=1)))

    _log(f"\n===== {name} =====", logfile)
    _log(f"DA price pi: {float(pi):.6f}", logfile)
    _log(f"E[RT price]: {float(np.dot(probs, Pi)):.6f}", logfile)
    _log(f"DA load: {da_load:.6f}", logfile)
    _log(f"E[RT load]: {exp_rt_load:.6f}", logfile)
    _log("DA allocation by tech: " + str({k: round(v, 4) for k, v in da_alloc.items()}), logfile)
    _log("Expected RT allocation by tech: " + str({k: round(v, 4) for k, v in rt_alloc.items()}), logfile)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "DA": g_da,
        "E_RT": exp_rt,
        "RT_minus_DA": exp_rt - g_da,
    })
    _log(df.to_string(index=False), logfile)
    
def _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i, n_solar, n_wind, n_thermal, logfile=None):
    z = np.asarray(z_g_i, dtype=float)
    c = np.asarray(cvar_g_i, dtype=float)

    solar_slice = slice(0, n_solar)
    wind_slice = slice(n_solar, n_solar + n_wind)
    thermal_slice = slice(n_solar + n_wind, n_solar + n_wind + n_thermal)

    gen_names = (
        [f"solar_{i+1}" for i in range(n_solar)] +
        [f"wind_{i+1}" for i in range(n_wind)] +
        [f"thermal_{i+1}" for i in range(n_thermal)]
    )

    df = pd.DataFrame({
        "gen": gen_names,
        "stoch_DA": z,
        "cvar_DA": c,
        "cvar_minus_stoch": c - z,
    })

    _log("\n===== CVaR - Stochastic DA difference =====", logfile)
    _log(df.to_string(index=False), logfile)
    _log("Tech-level difference: " + str({
        "solar": round((c[solar_slice] - z[solar_slice]).sum(), 4),
        "wind": round((c[wind_slice] - z[wind_slice]).sum(), 4),
        "thermal": round((c[thermal_slice] - z[thermal_slice]).sum(), 4),
        "total": round((c - z).sum(), 4),
    }), logfile)

In [6]:
# Initialize log files
log_dir = "logs"
os.makedirs(log_dir, exist_ok=True)

debug_log = os.path.join(log_dir, "zavala_debug_log.txt")
with open(debug_log, "w", encoding="utf-8") as f:
    f.write("Zavala diagnostics log\n")

Build Real Data

In [7]:
def build_real_data_instance(solar_df, wind_df, load_total_vec, thermal_by_bus, thermal_buses_numeric,
                              solar_buses, wind_buses, start_idx, num_scenarios, rng=None):
    """
    Build (probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar) from real data for one time window.
    - start_idx: first time index
    - num_scenarios: number of consecutive time steps (scenarios)
    """
    if rng is None:
        rng = np.random.default_rng()
    end_idx = start_idx + num_scenarios
    S = num_scenarios

    # Scenario probabilities: near-uniform (same idea as s_real10_mix)
    kappa = 1500.0
    alpha = np.full(S, kappa / S)
    probs = rng.dirichlet(alpha)
    probs = probs / probs.sum()

    # Marginal costs: cheap for unreliable (solar/wind), higher for reliable (thermal)
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_unrel = n_solar + n_wind
    n_rel = len(thermal_buses_numeric)

    mc_unrel = rng.uniform(8.0, 14.0, size=n_unrel)
    mc_rel = rng.uniform(35.0, 55.0, size=n_rel)
    mc_g_i = np.concatenate([mc_unrel, mc_rel]).astype(float)

    # Single inelastic load (VOLL)
    mv_d_j = np.array([1000.0], dtype=float)

    # Generator capacities per scenario (S x 10)
    # Columns 0..2: solar, 3..5: wind, 6..9: thermal (constant)
    solar_vals = solar_df.loc[start_idx:end_idx - 1, solar_buses].values  # (S, 3)
    wind_vals = wind_df.loc[start_idx:end_idx - 1, wind_buses].values    # (S, 3)
    unrel_caps = np.clip(np.hstack([solar_vals, wind_vals]), 0.0, None)  # (S, 6)

    rel_caps = np.array([thermal_by_bus[b] for b in thermal_buses_numeric], dtype=float)
    rel_caps = np.broadcast_to(rel_caps, (S, len(thermal_buses_numeric)))  # (S, 4) constant across scenarios

    g_i_bar = np.hstack([unrel_caps, rel_caps])  # (S, 10)

    # Demand: system total load for each scenario (S x 1)
    d_j_bar = load_total_vec[start_idx:end_idx].reshape(-1, 1).astype(float)
    d_j_bar = np.clip(d_j_bar, 1e-6, None)  # avoid zeros

    return probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar

In [8]:
# Quick sanity check: one small window
NUM_SCENARIOS = 500
rng = np.random.default_rng(42)
probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
    solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
    solar_buses, wind_buses, start_idx=0, num_scenarios=min(NUM_SCENARIOS, T), rng=rng
)
print("probs.shape:", probs.shape, "sum:", probs.sum())
print("g_i_bar.shape:", g_i_bar.shape)
print("d_j_bar.shape:", d_j_bar.shape)
print("Unreliable (solar+wind) sample mean:", g_i_bar[:, :6].mean(axis=0))
print("Reliable (thermal) constant:", g_i_bar[0, 6:])
print("Load sample:", d_j_bar[:5].ravel())

probs.shape: (500,) sum: 1.0
g_i_bar.shape: (500, 22)
d_j_bar.shape: (500, 1)
Unreliable (solar+wind) sample mean: [ 67.33335058  17.28        28.36311076 390.34965713 131.82143061
  24.22398934]
Reliable (thermal) constant: [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.26796677e+03
 2.58000000e+02 4.17920476e+02 2.42095982e+01 2.93740174e+02
 4.60995965e+02 6.63495200e+01 1.68442245e+01 6.00000000e-01
 6.92233000e+03 6.83762000e+03 6.74208000e+03 6.52169000e+03]
Load sample: [75073. 72985. 71226. 70105. 69772.]

In [9]:
def run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=None):
    """Run stochastic, CVaR, and deterministic Zavala for one instance. Returns dict of metrics.
    Same logic as run_zavala.py, no changes to external files.
    """
    # ----- Stochastic Zavala -----
    z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi = zavala(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    prob_f = probability_feasible(probs, z_g_i, z_d_j, g_i_bar, d_j_bar)
    z_dist = price_distortion(probs, z_pi, z_Pi)
    z_reg = expected_cumulative_regret(probs, z_g_i, z_d_j, z_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_stoch = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=z_g_i, d_da=z_d_j, G_rt=Z_G, D_rt=Z_D)

    # # ----- CVaR Zavala -----
    cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi, _ = zavala_cvar(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    cvar_dist = price_distortion(probs, cvar_pi, cvar_Pi)
    cvar_reg = expected_cumulative_regret(probs, cvar_g_i, cvar_d_j, cvar_pi, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_cvar = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=cvar_g_i, d_da=cvar_d_j, G_rt=C_G, D_rt=C_D)

    # ----- Deterministic (expected capacities) -----
    gbar_det, dbar_det = expected_caps_from_scenarios(probs, g_i_bar, d_j_bar)
    g_det, d_det, pi_det = zavala_deterministic_da(mc_g_i, mv_d_j, gbar_det, dbar_det)
    G_det_list, D_det_list, Pi_det_list = [], [], []
    for p in range(len(probs)):
        Gp, Dp, Pi_p = zavala_rt_energy_only(mc_g_i, mv_d_j, g_det, d_det, g_i_bar[p], d_j_bar[p])
        G_det_list.append(Gp)
        D_det_list.append(Dp)
        Pi_det_list.append(Pi_p)
    G_det_rt, D_det_rt = _stack_rt(G_det_list, D_det_list)
    Pi_det = np.array(Pi_det_list)
    det_dist = price_distortion(probs, pi_det, Pi_det)
    det_reg = expected_cumulative_regret(probs, g_det, d_det, pi_det, mc_g_i, mv_d_j, g_i_bar, d_j_bar)
    ss_det = compute_social_surplus(probs, mc_g_i, mv_d_j, g_da=g_det, d_da=d_det, G_rt=G_det_rt, D_rt=D_det_rt)

    # ----- Tail metrics (5% worst by high neg-surplus) -----
    tail = 0.05
    stoch_tail_idx = tail_worst_indices_by_value(ss_stoch["ss_per_scenario"], probs, tail=tail, worst="high")
    cvar_tail_idx = tail_worst_indices_by_value(ss_cvar["ss_per_scenario"], probs, tail=tail, worst="high")
    det_tail_idx = tail_worst_indices_by_value(ss_det["ss_per_scenario"], probs, tail=tail, worst="high")

    stoch_tail_welfare = -np.mean(ss_stoch["ss_per_scenario"][stoch_tail_idx])
    cvar_tail_welfare = -np.mean(ss_cvar["ss_per_scenario"][cvar_tail_idx])
    det_tail_welfare = -np.mean(ss_det["ss_per_scenario"][det_tail_idx])

    stoch_tail_dist = np.mean(np.abs(z_pi - np.array(z_Pi)[stoch_tail_idx]))
    cvar_tail_dist = np.mean(np.abs(cvar_pi - np.array(cvar_Pi)[cvar_tail_idx]))
    det_tail_dist = np.mean(np.abs(pi_det - Pi_det[det_tail_idx]))

    # Log diagnostics/output results analysis
    n_solar = len(solar_buses)
    n_wind = len(wind_buses)
    n_thermal = len(thermal_buses_numeric)

    _print_case_diag("Stochastic", probs, z_g_i, z_d_j, Z_G, Z_D, z_pi, z_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("CVaR", probs, cvar_g_i, cvar_d_j, C_G, C_D, cvar_pi, cvar_Pi,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_case_diag("Deterministic", probs, g_det, d_det, G_det_rt, D_det_rt, pi_det, Pi_det,
                    n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)
    _print_stoch_vs_cvar_diff(z_g_i, cvar_g_i,
                            n_solar=n_solar, n_wind=n_wind, n_thermal=n_thermal, logfile=logfile)

    return {
        "prob_feasible": prob_f,
        "stoch_distortion": z_dist, "stoch_regret": z_reg, "stoch_ss": ss_stoch["E_social_surplus"],
        "stoch_tail_welfare": stoch_tail_welfare, "stoch_tail_distortion": stoch_tail_dist,
        "cvar_distortion": cvar_dist, "cvar_regret": cvar_reg, "cvar_ss": ss_cvar["E_social_surplus"],
        "cvar_tail_welfare": cvar_tail_welfare, "cvar_tail_distortion": cvar_tail_dist,
        "det_distortion": det_dist, "det_regret": det_reg, "det_ss": ss_det["E_social_surplus"],
        "det_tail_welfare": det_tail_welfare, "det_tail_distortion": det_tail_dist,
    }

In [10]:
NUM_INSTANCES = 10
NUM_SCENARIOS = 500
rng = np.random.default_rng(2025)

max_start = T - NUM_SCENARIOS
if max_start <= 0:
    raise ValueError(f"Need at least {NUM_SCENARIOS} time steps; have {T}")

# Random start indices for each instance (non-overlapping or random)
start_indices = rng.integers(0, max_start + 1, size=NUM_INSTANCES)

results_list = []
for i in range(NUM_INSTANCES):
    start = int(start_indices[i])
    probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar = build_real_data_instance(
        solar, wind, load_total, thermal_by_bus, thermal_buses_numeric,
        solar_buses, wind_buses, start_idx=start, num_scenarios=NUM_SCENARIOS, rng=rng
    )
    print(f"the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are {probs.shape}, {mc_g_i.shape}, {mv_d_j.shape}, {g_i_bar.shape}, {d_j_bar.shape}")
    res = run_zavala_one_instance(probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar, logfile=debug_log)
    results_list.append(res)
    print(f"Instance {i+1}/{NUM_INSTANCES} (start={start}) done.")

the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:52:53 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 08:52:55 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:52:55 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:52:55 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:52:55 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:52:56 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:52:56 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:52:56 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 08:52:56 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:53:01 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 08:53:34 PM: Applying reduction GUROBI
(CVXPY) May 02 08:53:34 PM: Finished problem compilation (took 3.887e+01 seconds).
(CVXPY) May 02 08:53:34 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter Username
Set parameter LicenseID to value 2797952
Academic license - for non-commercial use only - expires 2027-03-25
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x6782229e
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2142 columns
Presolve time: 0.07s
Presolved: 23501 rows, 32381 columns, 85597 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.260e+04
 Factor NZ  : 8.637e+04 (roughly 23 MB of memory)
 Factor Ops : 5.440e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.37477532e+07 -4.13479447e+08  9.20e+05 6.16e+02  6.00e+05     0s
   1  -2.94550867e+07 -2.03279536e+08  7.41e+04 2.26e+01  3.55e+04     0s
   2  -1.69458598e+07 -7.99586391e+07  5.00e+03 3.43e+00  5.01e+03     0s
   3  -2.28877949e+07 -3.35485529e+07  7.02e+02 3.68e+00  4.57e+02     0s
   4  -2.43521333e+07 -3.02621621e+07  5.38e+02 8.69e-01  2.20e+02     0s
   5  -2.75518775e+07 -2.97534312e+07  1.91e+02 2.04e+00  7.77e+01     0s
   6  -2.85609439e+07 -2.96261116e+07  8.51e+01 1.61e+00  3.66e+01     0s
   7  -2.89634211e+07 -2.95475183e+07  4.73e+01 2.45e-01  1.97e+01     0s
   8  -2.92555621e+07 -2.95233022e+07  2.03e+01 3.57e-01  8.91e+00     0s
   9  -2.93862704e+07 -2.95089635e+07  8.96e+00 5.52e-02  4.05e+00     0s
  10  -2.94742895e+07 -2.95068169e+07  2.10e+00 4.64e-02  1.06e+00     0s
  11  -2.94977606e+07 -2.95055084e+07  4.07e-01 1.09e-02  2.50e-01     0s
  12  -2.95021347e+07 -2.95046727e+07  1.34e-01 2.31e-02  8.19e-02     0s
  13  -2.95034135e+07 -2.95045032e+07  5.08e-02 1.94e-02  3.50e-02     0s
  14  -2.95038074e+07 -2.95043622e+07  2.39e-02 9.84e-03  1.78e-02     0s
  15  -2.95040495e+07 -2.95042744e+07  7.89e-03 3.14e-03  7.16e-03     0s
  16  -2.95041024e+07 -2.95042143e+07  4.75e-03 1.05e-03  3.59e-03     0s
  17  -2.95041662e+07 -2.95041895e+07  1.06e-03 1.96e-03  7.70e-04     0s
  18  -2.95041794e+07 -2.95041863e+07  3.04e-04 5.07e-04  2.28e-04     0s
  19  -2.95041839e+07 -2.95041856e+07  5.15e-05 2.27e-04  5.77e-05     0s
  20  -2.95041846e+07 -2.95041852e+07  1.30e-05 1.15e-04  2.01e-05     0s
  21  -2.95041849e+07 -2.95041851e+07  1.19e-06 3.85e-05  5.09e-06     0s
  22  -2.95041849e+07 -2.95041850e+07  1.14e-07 6.53e-06  3.84e-07     0s
  23  -2.95041850e+07 -2.95041850e+07  3.71e-10 4.07e-08  9.82e-10     0s

Barrier solved model in 23 iterations and 0.35 seconds (0.34 work units)
Optimal objective -2.95041850e+07

Crossover log...

    4030 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 0s

     441 PPushes remaining with PInf 0.0000000e+00                 0s
       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 3.2604622e-12      0s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3532   -2.9504185e+07   0.000000e+00   0.000000e+00      0s

Solved in 3532 iterations and 0.47 seconds (0.50 work units)
Optimal objective -2.950418495e+07

(CVXPY) May 02 08:53:35 PM: Problem status: optimal
(CVXPY) May 02 08:53:35 PM: Optimal value: -2.950e+07
(CVXPY) May 02 08:53:35 PM: Compilation took 3.887e+01 seconds
(CVXPY) May 02 08:53:35 PM: Solver (including time spent in interface) took 6.212e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:53:43 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 08:53:45 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:53:45 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:53:45 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:53:45 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:53:47 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:53:47 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:53:47 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:53:53 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 08:54:04 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 08:55:28 PM: Applying reduction GUROBI
(CVXPY) May 02 08:55:28 PM: Finished problem compilation (took 1.037e+02 seconds).
(CVXPY) May 02 08:55:28 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x1f456ffc
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2142 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55882 columns, 183671 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.938e+05
 Factor NZ  : 2.858e+05 (roughly 40 MB of memory)
 Factor Ops : 2.935e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.98328351e+08 -9.93881775e+08  2.13e+07 6.40e+00  5.36e+06     0s
   1   2.39230374e+08 -4.41048179e+08  1.35e+05 8.46e+00  3.04e+05     0s
   2   2.39230042e+08 -4.41053599e+08  1.35e+05 7.16e+00  3.04e+05     0s
   3   2.39230042e+08 -4.41053599e+08  1.35e+05 7.16e+00  3.04e+05     0s
   4   2.98328351e+08 -3.51163212e+11  2.13e+07 6.40e+00  1.97e+09     0s
   5   6.34214974e+08 -3.08876676e+11  1.60e+05 1.26e+01  5.95e+07     0s
   6   6.44613996e+08 -5.59568488e+10  1.32e+04 1.05e+02  1.01e+07     0s
   7   6.44623214e+08 -5.59567969e+10  1.32e+04 1.74e+03  1.01e+07     0s
   8   1.60338245e+09 -2.28370139e+10  1.30e+03 4.04e+02  4.76e+06     0s
   9   1.29663563e+09 -2.89627694e+08  1.32e+01 1.08e+01  5.72e+04     0s
  10   1.29663563e+09 -2.89627694e+08  1.32e+01 1.08e+01  5.72e+04     0s
  11   1.29663563e+09 -2.89627694e+08  1.32e+01 1.08e+01  5.72e+04     0s
  12   2.98328351e+08 -3.51163212e+11  2.13e+07 6.40e+00  1.97e+09     1s
  13   1.08389548e+08 -3.03225364e+10  2.08e+05 6.34e+01  6.55e+07     1s
  14   1.02200816e+08 -3.70367804e+09  1.20e+04 7.84e+00  4.67e+06     1s
  15   6.79899002e+07 -1.76280511e+08  3.53e+02 1.99e+00  2.16e+05     1s
  16   6.79914486e+07 -1.76282907e+08  3.53e+02 2.27e+02  2.13e+05     1s
  17   6.79908850e+07 -1.76282799e+08  3.53e+02 1.44e+02  2.11e+05     1s
  18   6.79881802e+07 -1.76293562e+08  3.53e+02 9.81e+02  2.06e+05     1s
  19   6.79966376e+07 -1.76281286e+08  3.53e+02 8.97e+02  2.02e+05     1s
  20   6.79972079e+07 -1.76271726e+08  3.53e+02 4.79e+02  1.98e+05     1s
  21   6.80227988e+07 -1.76066281e+08  3.53e+02 3.34e+02  1.95e+05     1s
  22   6.80853397e+07 -1.75671622e+08  3.52e+02 3.95e+02  1.88e+05     1s
  23   2.61652823e+07 -1.13679118e+08  1.57e+02 4.33e+02  8.03e+04     1s
  24   2.61615086e+07 -1.13679840e+08  1.57e+02 4.51e+02  7.85e+04     1s
  25   2.61413086e+07 -1.13700399e+08  1.57e+02 7.59e+02  7.67e+04     1s
  26   2.61446255e+07 -1.13697035e+08  1.57e+02 5.69e+02  7.48e+04     1s
  27   2.61389668e+07 -1.13700786e+08  1.57e+02 5.10e+02  7.45e+04     1s
  28   2.61379532e+07 -1.13704893e+08  1.57e+02 3.04e+02  7.41e+04     1s
  29   2.61376983e+07 -1.13698396e+08  1.57e+02 6.43e+02  7.22e+04     1s
  30  -1.33805566e+07 -3.75218758e+07  2.34e+01 1.08e+02  5.33e+03     1s
  31  -1.33821219e+07 -3.75235159e+07  2.34e+01 9.27e+01  5.25e+03     1s
  32  -1.33838593e+07 -3.75259990e+07  2.34e+01 6.08e+02  5.17e+03     1s
  33  -1.33975610e+07 -3.75155177e+07  2.34e+01 6.07e+02  5.16e+03     1s
  34  -1.33455171e+07 -3.75526333e+07  2.35e+01 3.35e+03  5.07e+03     1s
  35  -1.33456684e+07 -3.75526638e+07  2.35e+01 3.35e+03  5.01e+03     1s
  36  -1.33455906e+07 -3.75525721e+07  2.35e+01 3.37e+03  5.00e+03     1s
  37  -1.33454731e+07 -3.75523841e+07  2.35e+01 3.35e+03  4.97e+03     1s
  38  -1.38257314e+07 -3.71985564e+07  2.27e+01 3.24e+03  4.69e+03     1s
  39  -1.37832458e+07 -3.72272305e+07  2.28e+01 3.23e+03  4.69e+03     1s
  40  -1.37832458e+07 -3.72272305e+07  2.28e+01 3.23e+03  4.69e+03     1s
  41  -1.38304601e+07 -3.71926581e+07  2.27e+01 1.80e+04  4.58e+03     2s
  42  -1.72496921e+07 -3.56929441e+07  1.73e+01 1.92e+07  2.93e+03     2s
  43  -1.72495794e+07 -3.56926046e+07  1.73e+01 1.92e+07  2.91e+03     2s

Barrier performed 43 iterations in 1.57 seconds (1.95 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   52472   -3.2125351e+07   0.000000e+00   0.000000e+00      4s

Solved in 52472 iterations and 3.76 seconds (6.75 work units)
Optimal objective -3.212535129e+07

(CVXPY) May 02 08:55:33 PM: Problem status: optimal
(CVXPY) May 02 08:55:33 PM: Optimal value: -3.213e+07
(CVXPY) May 02 08:55:33 PM: Compilation took 1.037e+02 seconds
(CVXPY) May 02 08:55:33 PM: Solver (including time spent in interface) took 4.015e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 1/10 (start=3696) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:55:39 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 08:55:40 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:55:40 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:55:40 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:55:40 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:55:42 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:55:42 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:55:42 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 08:55:42 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:55:47 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 08:56:19 PM: Applying reduction GUROBI
(CVXPY) May 02 08:56:20 PM: Finished problem compilation (took 3.934e+01 seconds).
(CVXPY) May 02 08:56:20 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x67406b5c
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2801 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31722 columns, 83620 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.062e+04
 Factor NZ  : 8.440e+04 (roughly 23 MB of memory)
 Factor Ops : 5.328e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.94729118e+07 -3.78981951e+08  7.27e+05 1.23e+03  9.04e+05     0s
   1  -2.90971383e+07 -1.77502134e+08  5.80e+04 9.72e+01  7.66e+04     0s
   2  -1.61204008e+07 -6.13265174e+07  2.90e+03 5.96e+00  7.20e+03     0s
   3  -2.35400542e+07 -3.04436930e+07  1.58e+02 2.89e+00  6.12e+02     0s
   4  -2.61879340e+07 -2.85683079e+07  5.01e+01 1.88e+00  1.70e+02     0s
   5  -2.71566232e+07 -2.82805375e+07  2.35e+01 3.98e-01  7.53e+01     0s
   6  -2.76721822e+07 -2.81897028e+07  1.06e+01 1.93e-01  3.38e+01     0s
   7  -2.79235909e+07 -2.81527905e+07  4.58e+00 1.27e-01  1.48e+01     0s
   8  -2.80708132e+07 -2.81450859e+07  1.33e+00 2.25e-02  4.76e+00     0s
   9  -2.81045954e+07 -2.81416829e+07  6.51e-01 2.68e-02  2.37e+00     0s
  10  -2.81335228e+07 -2.81401628e+07  1.01e-01 1.39e-03  4.24e-01     0s
  11  -2.81377777e+07 -2.81392930e+07  2.30e-02 5.01e-03  9.68e-02     0s
  12  -2.81383940e+07 -2.81391138e+07  9.79e-03 3.61e-03  4.60e-02     0s
  13  -2.81385504e+07 -2.81390621e+07  6.59e-03 2.75e-03  3.27e-02     0s
  14  -2.81386622e+07 -2.81389907e+07  4.32e-03 1.65e-03  2.10e-02     0s
  15  -2.81387508e+07 -2.81389607e+07  2.49e-03 1.01e-03  1.34e-02     0s
  16  -2.81388015e+07 -2.81389257e+07  1.48e-03 5.69e-04  7.92e-03     0s
  17  -2.81388258e+07 -2.81389163e+07  9.95e-04 4.51e-04  5.77e-03     0s
  18  -2.81388410e+07 -2.81389070e+07  6.79e-04 3.41e-04  4.20e-03     0s
  19  -2.81388523e+07 -2.81389013e+07  4.63e-04 2.73e-04  3.12e-03     0s
  20  -2.81388640e+07 -2.81388922e+07  2.39e-04 1.80e-04  1.80e-03     0s
  21  -2.81388685e+07 -2.81388901e+07  1.58e-04 1.54e-04  1.37e-03     0s
  22  -2.81388703e+07 -2.81388893e+07  1.29e-04 1.45e-04  1.21e-03     0s
  23  -2.81388714e+07 -2.81388880e+07  1.09e-04 1.28e-04  1.05e-03     0s
  24  -2.81388742e+07 -2.81388862e+07  5.67e-05 1.04e-04  7.58e-04     0s
  25  -2.81388748e+07 -2.81388839e+07  4.71e-05 7.43e-05  5.74e-04     0s
  26  -2.81388753e+07 -2.81388829e+07  3.98e-05 6.50e-05  4.84e-04     0s
  27  -2.81388757e+07 -2.81388821e+07  3.31e-05 5.19e-05  4.05e-04     0s
  28  -2.81388762e+07 -2.81388809e+07  2.45e-05 3.31e-05  2.98e-04     0s
  29  -2.81388770e+07 -2.81388801e+07  9.87e-06 2.53e-05  1.95e-04     0s
  30  -2.81388772e+07 -2.81388790e+07  6.99e-06 1.65e-05  1.14e-04     1s
  31  -2.81388774e+07 -2.81388786e+07  4.80e-06 9.83e-06  7.33e-05     1s
  32  -2.81388777e+07 -2.81388779e+07  6.80e-07 8.90e-07  8.85e-06     1s
  33  -2.81388778e+07 -2.81388778e+07  2.54e-09 9.12e-08  4.12e-07     1s
  34  -2.81388778e+07 -2.81388778e+07  5.46e-11 1.64e-10  1.22e-08     1s
  35  -2.81388778e+07 -2.81388778e+07  1.09e-11 4.05e-10  3.20e-14     1s

Barrier solved model in 35 iterations and 0.56 seconds (0.50 work units)
Optimal objective -2.81388778e+07

Crossover log...

    4036 DPushes remaining with DInf 0.0000000e+00                 1s
       0 DPushes remaining with DInf 0.0000000e+00                 1s

       0 PPushes remaining with PInf 0.0000000e+00                 1s

  Push phase complete: Pinf 0.0000000e+00, Dinf 1.5306595e-11      1s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3327   -2.8138878e+07   0.000000e+00   0.000000e+00      1s

Solved in 3327 iterations and 0.69 seconds (0.67 work units)
Optimal objective -2.813887778e+07

(CVXPY) May 02 08:56:25 PM: Problem status: optimal
(CVXPY) May 02 08:56:25 PM: Optimal value: -2.814e+07
(CVXPY) May 02 08:56:25 PM: Compilation took 3.934e+01 seconds
(CVXPY) May 02 08:56:25 PM: Solver (including time spent in interface) took 4.679e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:56:31 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 08:56:33 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:56:33 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:56:33 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:56:33 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:56:36 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:56:36 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:56:36 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:56:42 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 08:56:53 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 08:58:19 PM: Applying reduction GUROBI
(CVXPY) May 02 08:58:20 PM: Finished problem compilation (took 1.064e+02 seconds).
(CVXPY) May 02 08:58:20 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x9f1c1728
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [8e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2801 columns
Presolve time: 0.11s
Presolved: 47001 rows, 55223 columns, 179717 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.859e+05
 Factor NZ  : 2.862e+05 (roughly 40 MB of memory)
 Factor Ops : 3.136e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.14679562e+08 -9.36312122e+08  1.65e+07 1.28e+01  8.10e+06     0s
   1   1.74294039e+08 -3.66779854e+08  1.22e+05 3.28e+00  4.54e+05     0s
   2   1.74294039e+08 -3.66779854e+08  1.22e+05 3.28e+00  4.54e+05     0s
   3   2.14679562e+08 -1.69621415e+11  1.65e+07 1.28e+01  1.53e+09     0s
   4   3.93478699e+08 -1.35554276e+11  2.32e+05 1.08e+02  2.66e+08     0s
   5   4.00878350e+08 -2.25808146e+10  4.59e+04 1.72e+01  4.26e+07     0s
   6   4.03801546e+08 -2.46126600e+09  3.74e+03 9.58e-01  8.56e+05     0s
   7   4.03801546e+08 -2.46126600e+09  3.74e+03 9.58e-01  8.56e+05     0s
   8   4.03801546e+08 -2.46126600e+09  3.74e+03 9.58e-01  8.56e+05     0s
   9   4.03801546e+08 -2.46126600e+09  3.74e+03 9.58e-01  8.56e+05     0s
  10   4.03801546e+08 -2.46126600e+09  3.74e+03 9.58e-01  8.56e+05     0s
  11   2.14679562e+08 -1.69621415e+11  1.65e+07 1.28e+01  1.53e+09     0s
  12   9.37056972e+07 -1.32253137e+10  2.80e+05 6.92e+01  5.54e+07     0s
  13   8.25628989e+07 -1.66596300e+09  1.92e+04 8.88e+00  3.77e+06     1s
  14   3.85289175e+07 -1.10325850e+08  2.90e+02 8.57e+01  1.94e+05     1s
  15   3.85292550e+07 -1.10326179e+08  2.90e+02 4.75e+02  1.94e+05     1s
  16   3.85292421e+07 -1.10326262e+08  2.90e+02 5.46e+02  1.93e+05     1s
  17   3.85294804e+07 -1.10325603e+08  2.90e+02 6.77e+07  1.92e+05     1s
  18   3.85304422e+07 -1.10315607e+08  2.90e+02 6.77e+07  1.92e+05     1s
  19   3.85294391e+07 -1.10318290e+08  2.90e+02 6.77e+07  1.91e+05     1s
  20  -8.48412523e+06 -3.85233004e+07  5.75e+01 1.36e+07  1.81e+04     1s
  21  -1.16864571e+07 -3.70369397e+07  4.80e+01 1.17e+07  1.41e+04     1s
  22  -1.16872611e+07 -3.70379735e+07  4.80e+01 1.17e+07  1.40e+04     1s
  23  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  24  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  25  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  26  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  27  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  28  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  29  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s
  30  -1.16889312e+07 -3.70374410e+07  4.80e+01 1.17e+07  1.40e+04     1s

Barrier performed 30 iterations in 1.06 seconds (1.22 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   53293   -3.0737893e+07   0.000000e+00   0.000000e+00      4s

Solved in 53293 iterations and 4.10 seconds (8.14 work units)
Optimal objective -3.073789264e+07

(CVXPY) May 02 08:58:25 PM: Problem status: optimal
(CVXPY) May 02 08:58:25 PM: Optimal value: -3.074e+07
(CVXPY) May 02 08:58:25 PM: Compilation took 1.064e+02 seconds
(CVXPY) May 02 08:58:25 PM: Solver (including time spent in interface) took 4.355e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 2/10 (start=8215) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:58:30 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 08:58:32 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:58:32 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:58:32 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:58:32 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:58:33 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:58:33 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:58:33 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 08:58:33 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:58:39 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 08:59:14 PM: Applying reduction GUROBI
(CVXPY) May 02 08:59:14 PM: Finished problem compilation (took 4.265e+01 seconds).
(CVXPY) May 02 08:59:14 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0xa27b2618
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2822 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31701 columns, 83557 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.056e+04
 Factor NZ  : 8.433e+04 (roughly 23 MB of memory)
 Factor Ops : 5.324e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.87890486e+07 -4.53384145e+08  7.27e+05 6.13e+02  5.48e+05     0s
   1  -2.70333208e+07 -2.03542231e+08  5.65e+04 4.11e+01  4.04e+04     0s
   2  -1.49927691e+07 -6.00403388e+07  1.73e+03 1.43e+00  3.08e+03     0s
   3  -2.31240255e+07 -2.97001681e+07  3.06e+01 3.43e+00  2.54e+02     0s
   4  -2.51701409e+07 -2.84276840e+07  1.60e+01 1.19e+00  1.13e+02     0s
   5  -2.66114134e+07 -2.82546284e+07  7.17e+00 8.39e-01  5.56e+01     0s
   6  -2.71249334e+07 -2.80781591e+07  4.29e+00 6.74e-01  3.12e+01     0s
   7  -2.71249334e+07 -2.80781591e+07  4.29e+00 6.74e-01  3.12e+01     0s
   8  -3.87955791e+07 -2.76347323e+10  7.27e+05 1.14e-13  3.53e+07     0s
   9  -1.33629788e+07 -2.41171714e+10  2.89e+04 3.16e+01  2.92e+06     0s
  10  -2.20535794e+06 -2.30133460e+09  3.87e+02 2.00e+00  8.69e+04     0s
  11  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s
  12  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s
  13  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s
  14  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s
  15  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s
  16  -1.39499184e+07 -9.31169390e+07  6.22e-01 4.87e+00  2.65e+03     0s

Barrier performed 16 iterations in 0.30 seconds (0.30 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10881   -2.7976570e+07   0.000000e+00   0.000000e+00      1s

Solved in 10881 iterations and 1.05 seconds (1.90 work units)
Optimal objective -2.797657011e+07

(CVXPY) May 02 08:59:16 PM: Problem status: optimal
(CVXPY) May 02 08:59:16 PM: Optimal value: -2.798e+07
(CVXPY) May 02 08:59:16 PM: Compilation took 4.265e+01 seconds
(CVXPY) May 02 08:59:16 PM: Solver (including time spent in interface) took 1.201e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 08:59:23 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 08:59:26 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 08:59:26 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 08:59:26 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 08:59:26 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 08:59:29 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 08:59:29 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 08:59:29 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 08:59:33 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 08:59:44 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:01:15 PM: Applying reduction GUROBI
(CVXPY) May 02 09:01:15 PM: Finished problem compilation (took 1.085e+02 seconds).
(CVXPY) May 02 09:01:15 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x924cbfdd
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [8e-05, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2822 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55202 columns, 179591 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.857e+05
 Factor NZ  : 2.859e+05 (roughly 40 MB of memory)
 Factor Ops : 3.133e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.43115794e+08 -1.43332840e+09  1.70e+07 1.28e+01  6.49e+06     0s
   1   1.98779533e+08 -5.56297178e+08  1.36e+05 4.10e+01  3.47e+05     0s
   2   1.98779533e+08 -5.56297178e+08  1.36e+05 4.10e+01  3.47e+05     0s
   3   2.43115794e+08 -3.38483136e+11  1.70e+07 1.28e+01  1.57e+09     0s
   4   4.57287352e+08 -2.76507273e+11  2.19e+05 1.07e+02  2.75e+08     0s
   5   4.65201708e+08 -4.03321699e+10  3.45e+04 1.48e+01  3.83e+07     0s
   6   4.65201159e+08 -4.03322247e+10  3.45e+04 4.61e+02  3.82e+07     0s
   7   6.72635514e+08 -4.84013539e+10  1.91e+04 4.49e+02  1.47e+07     0s
   8   6.72635514e+08 -4.84013539e+10  1.91e+04 4.49e+02  1.47e+07     0s
   9   6.72635514e+08 -4.84013539e+10  1.91e+04 4.49e+02  1.47e+07     0s
  10   6.72635514e+08 -4.84013539e+10  1.91e+04 4.49e+02  1.47e+07     0s
  11   2.43115794e+08 -3.38483136e+11  1.70e+07 1.28e+01  1.57e+09     0s
  12   1.07953292e+08 -2.39425776e+10  2.18e+05 6.63e+01  5.06e+07     0s
  13   9.55173847e+07 -2.71388281e+09  1.69e+04 7.55e+00  3.10e+06     0s
  14   2.66603143e+07 -1.03243588e+08  4.51e+01 2.94e+00  6.90e+04     1s
  15   2.66608861e+07 -1.03244278e+08  4.51e+01 9.33e+01  6.88e+04     1s
  16   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.27e+03     1s
  17   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  18   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  19   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  20   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  21   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  22   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  23   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  24   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  25   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s
  26   1.76414582e+06 -3.70001911e+07  2.03e+01 1.38e+01  8.25e+03     1s

Barrier performed 26 iterations in 0.95 seconds (1.09 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   50742   -3.0560469e+07   0.000000e+00   0.000000e+00      4s

Solved in 50742 iterations and 4.02 seconds (7.90 work units)
Optimal objective -3.056046879e+07

(CVXPY) May 02 09:01:20 PM: Problem status: optimal
(CVXPY) May 02 09:01:20 PM: Optimal value: -3.056e+07
(CVXPY) May 02 09:01:20 PM: Compilation took 1.085e+02 seconds
(CVXPY) May 02 09:01:20 PM: Solver (including time spent in interface) took 4.280e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 3/10 (start=8199) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:01:26 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:01:28 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:01:28 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:01:28 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:01:28 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:01:29 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:01:29 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:01:29 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:01:29 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:01:36 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:02:14 PM: Applying reduction GUROBI
(CVXPY) May 02 09:02:14 PM: Finished problem compilation (took 4.601e+01 seconds).
(CVXPY) May 02 09:02:14 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0xe548fc13
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [9e-02, 1e+05]
Presolve removed 46000 rows and 2217 columns
Presolve time: 0.07s
Presolved: 23501 rows, 32306 columns, 85372 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.237e+04
 Factor NZ  : 8.615e+04 (roughly 23 MB of memory)
 Factor Ops : 5.427e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.93518252e+07 -3.61402265e+08  8.61e+05 6.16e+02  5.22e+05     0s
   1  -2.71287729e+07 -1.83590305e+08  5.89e+04 2.79e+01  3.02e+04     0s
   2  -1.65396369e+07 -6.16105845e+07  3.25e+03 2.64e+00  3.22e+03     0s
   3  -2.41641225e+07 -3.15599189e+07  2.92e+02 3.31e+00  2.92e+02     0s
   4  -2.69448471e+07 -2.97026502e+07  9.83e+01 5.85e+00  9.50e+01     0s
   5  -2.81642363e+07 -2.94043202e+07  4.01e+01 2.89e+00  4.12e+01     0s
   6  -2.85746021e+07 -2.92611603e+07  2.21e+01 1.32e+00  2.24e+01     0s
   7  -2.88624085e+07 -2.92115570e+07  9.84e+00 7.63e-01  1.13e+01     0s
   8  -2.90247922e+07 -2.91655028e+07  3.66e+00 3.34e-01  4.49e+00     0s
   9  -2.90731132e+07 -2.91439027e+07  1.97e+00 6.72e-02  2.25e+00     0s
  10  -2.91289610e+07 -2.91385056e+07  1.42e-01 1.72e-02  3.01e-01     0s
  11  -2.91338701e+07 -2.91357320e+07  1.02e-02 3.99e-03  5.85e-02     0s
  12  -2.91340955e+07 -2.91351192e+07  5.75e-03 2.14e-03  3.22e-02     0s
  13  -2.91341907e+07 -2.91349522e+07  3.74e-03 1.83e-03  2.39e-02     0s
  14  -2.91342441e+07 -2.91348600e+07  2.46e-03 1.58e-03  1.93e-02     0s
  15  -2.91343075e+07 -2.91346975e+07  1.13e-03 1.04e-03  1.22e-02     0s
  16  -2.91343140e+07 -2.91346716e+07  9.97e-04 9.67e-04  1.12e-02     0s
  17  -2.91343231e+07 -2.91346057e+07  7.71e-04 7.97e-04  8.87e-03     0s
  18  -2.91343318e+07 -2.91345677e+07  5.05e-04 6.46e-04  7.40e-03     0s
  19  -2.91343350e+07 -2.91345399e+07  4.50e-04 5.81e-04  6.43e-03     0s
  20  -2.91343428e+07 -2.91344983e+07  2.96e-04 4.21e-04  4.88e-03     0s
  21  -2.91343515e+07 -2.91344447e+07  1.28e-04 2.30e-04  2.93e-03     0s
  22  -2.91343566e+07 -2.91344193e+07  5.79e-05 1.56e-04  1.97e-03     0s
  23  -2.91343574e+07 -2.91344093e+07  4.31e-05 1.26e-04  1.63e-03     0s
  24  -2.91343581e+07 -2.91343987e+07  3.05e-05 9.82e-05  1.27e-03     0s
  25  -2.91343590e+07 -2.91343877e+07  1.69e-05 6.91e-05  9.00e-04     0s
  26  -2.91343600e+07 -2.91343771e+07  6.79e-06 4.14e-05  5.36e-04     0s
  27  -2.91343607e+07 -2.91343686e+07  2.24e-06 2.02e-05  2.50e-04     0s
  28  -2.91343608e+07 -2.91343644e+07  1.39e-06 8.02e-06  1.12e-04     0s
  29  -2.91343609e+07 -2.91343611e+07  3.96e-07 4.54e-07  6.56e-06     0s
  30  -2.91343610e+07 -2.91343610e+07  1.93e-10 1.12e-08  3.26e-08     0s
  31  -2.91343610e+07 -2.91343610e+07  4.73e-11 4.98e-11  1.11e-13     0s

Barrier solved model in 31 iterations and 0.48 seconds (0.48 work units)
Optimal objective -2.91343610e+07

Crossover log...

    4036 DPushes remaining with DInf 0.0000000e+00                 0s
       0 DPushes remaining with DInf 0.0000000e+00                 1s

       0 PPushes remaining with PInf 0.0000000e+00                 1s

  Push phase complete: Pinf 0.0000000e+00, Dinf 1.6509797e-13      1s


Solved with barrier
Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3246   -2.9134361e+07   0.000000e+00   0.000000e+00      1s

Solved in 3246 iterations and 0.60 seconds (0.64 work units)
Optimal objective -2.913436100e+07

(CVXPY) May 02 09:02:15 PM: Problem status: optimal
(CVXPY) May 02 09:02:15 PM: Optimal value: -2.913e+07
(CVXPY) May 02 09:02:15 PM: Compilation took 4.601e+01 seconds
(CVXPY) May 02 09:02:15 PM: Solver (including time spent in interface) took 7.377e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:02:20 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:02:23 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:02:23 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:02:23 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:02:23 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:02:26 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:02:26 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:02:26 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:02:32 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:02:43 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:04:00 PM: Applying reduction GUROBI
(CVXPY) May 02 09:04:01 PM: Finished problem compilation (took 9.723e+01 seconds).
(CVXPY) May 02 09:04:01 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x3b1ca512
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [9e-02, 1e+05]
Presolve removed 69000 rows and 2217 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55807 columns, 183221 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.929e+05
 Factor NZ  : 2.868e+05 (roughly 40 MB of memory)
 Factor Ops : 2.985e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.05887714e+08 -1.23593815e+09  1.96e+07 1.28e+01  6.69e+06     0s
   1   2.47502108e+08 -5.39008349e+08  1.54e+05 4.45e+01  3.66e+05     0s
   2   2.47502108e+08 -5.39008349e+08  1.54e+05 4.45e+01  3.66e+05     0s
   3   3.05887714e+08 -3.23906377e+11  1.96e+07 1.28e+01  1.81e+09     0s
   4   5.53656198e+08 -2.88164597e+11  2.10e+05 1.06e+02  3.08e+08     0s
   5   5.59653908e+08 -4.86309954e+10  4.31e+04 1.62e+01  4.75e+07     0s
   6   5.61318820e+08 -1.27234889e+10  4.16e+03 4.29e+02  8.13e+06     0s
   7   5.61327695e+08 -1.27234994e+10  4.16e+03 1.08e+03  8.12e+06     0s
   8   5.61344324e+08 -1.27234930e+10  4.16e+03 4.19e+02  8.11e+06     0s
   9   5.61344324e+08 -1.27234930e+10  4.16e+03 4.19e+02  8.11e+06     0s
  10   5.61344324e+08 -1.27234930e+10  4.16e+03 4.19e+02  8.11e+06     0s
  11   3.05887714e+08 -3.23906377e+11  1.96e+07 1.28e+01  1.81e+09     0s
  12   1.13998216e+08 -2.60033594e+10  1.79e+05 6.14e+01  5.54e+07     0s
  13   1.01562600e+08 -2.92289768e+09  1.09e+04 6.90e+00  3.50e+06     0s
  14   6.82219304e+07 -1.50596467e+08  6.04e+02 1.30e+00  1.82e+05     1s
  15   6.82199585e+07 -1.50595233e+08  6.04e+02 3.95e+02  1.80e+05     1s
  16  -8.88781516e+06 -4.01930523e+07  7.16e+01 6.03e+01  1.01e+04     1s
  17  -8.88818285e+06 -4.01933788e+07  7.16e+01 2.01e+01  9.95e+03     1s
  18  -8.88818285e+06 -4.01933788e+07  7.16e+01 2.01e+01  9.95e+03     1s
  19  -8.88818285e+06 -4.01933788e+07  7.16e+01 2.01e+01  9.95e+03     1s
  20  -8.89154204e+06 -4.01967704e+07  7.16e+01 5.22e+01  9.76e+03     1s
  21  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s
  22  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s
  23  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s
  24  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s
  25  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s
  26  -8.89181497e+06 -4.01969433e+07  7.16e+01 5.23e+01  9.76e+03     1s

Barrier performed 26 iterations in 0.90 seconds (1.06 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   26274   -3.1734457e+07   0.000000e+00   0.000000e+00      4s

Solved in 26274 iterations and 3.74 seconds (8.23 work units)
Optimal objective -3.173445744e+07

(CVXPY) May 02 09:04:05 PM: Problem status: optimal
(CVXPY) May 02 09:04:05 PM: Optimal value: -3.173e+07
(CVXPY) May 02 09:04:05 PM: Compilation took 9.723e+01 seconds
(CVXPY) May 02 09:04:05 PM: Solver (including time spent in interface) took 3.983e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 4/10 (start=3155) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:04:18 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:04:20 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:04:20 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:04:20 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:04:20 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:04:21 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:04:21 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:04:21 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:04:21 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:04:25 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:05:00 PM: Applying reduction GUROBI
(CVXPY) May 02 09:05:00 PM: Finished problem compilation (took 4.063e+01 seconds).
(CVXPY) May 02 09:05:00 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x2d0c63ea
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2866 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31657 columns, 83425 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.042e+04
 Factor NZ  : 8.420e+04 (roughly 23 MB of memory)
 Factor Ops : 5.317e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.93979950e+07 -3.60952423e+08  7.27e+05 6.13e+02  4.35e+05     0s
   1  -2.89154100e+07 -1.70274971e+08  5.80e+04 4.64e+01  3.59e+04     0s
   2  -1.69547410e+07 -6.64006977e+07  3.48e+03 6.07e+00  5.22e+03     0s
   3  -2.27015581e+07 -2.97166561e+07  1.11e+02 3.57e+00  3.00e+02     0s
   4  -2.61455408e+07 -2.80229897e+07  2.57e+01 1.90e-01  6.13e+01     0s
   5  -2.61455408e+07 -2.80229897e+07  2.57e+01 1.90e-01  6.13e+01     0s
   6  -3.94066705e+07 -2.72988449e+10  7.27e+05 1.14e-13  3.53e+07     0s
   7  -1.34861699e+07 -2.38947834e+10  3.13e+04 3.43e+01  3.08e+06     0s
   8  -2.19460968e+06 -2.36645262e+09  4.32e+02 3.79e+00  9.10e+04     0s
   9  -1.35688924e+07 -9.77913746e+07  1.35e+00 4.65e+00  2.81e+03     0s
  10  -1.35688924e+07 -9.77913746e+07  1.35e+00 4.65e+00  2.81e+03     0s
  11  -1.35688924e+07 -9.77913746e+07  1.35e+00 4.65e+00  2.81e+03     0s
  12  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.20e+02     0s
  13  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  14  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  15  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  16  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  17  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  18  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  19  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  20  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  21  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s
  22  -8.49252100e+06 -3.73495568e+07  8.37e-10 1.08e+01  9.16e+02     0s

Barrier performed 22 iterations in 0.41 seconds (0.47 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11091   -2.7813337e+07   0.000000e+00   0.000000e+00      1s

Solved in 11091 iterations and 1.03 seconds (1.92 work units)
Optimal objective -2.781333661e+07

(CVXPY) May 02 09:05:06 PM: Problem status: optimal
(CVXPY) May 02 09:05:06 PM: Optimal value: -2.781e+07
(CVXPY) May 02 09:05:06 PM: Compilation took 4.063e+01 seconds
(CVXPY) May 02 09:05:06 PM: Solver (including time spent in interface) took 5.005e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:05:12 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:05:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:05:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:05:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:05:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:05:19 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:05:19 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:05:19 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:05:23 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:05:34 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:06:58 PM: Applying reduction GUROBI
(CVXPY) May 02 09:06:58 PM: Finished problem compilation (took 1.022e+02 seconds).
(CVXPY) May 02 09:06:58 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x4aee22e0
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2866 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55158 columns, 179327 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.851e+05
 Factor NZ  : 2.867e+05 (roughly 40 MB of memory)
 Factor Ops : 3.169e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.35665817e+08 -1.26469387e+09  1.74e+07 1.28e+01  5.90e+06     0s
   1   1.95350136e+08 -5.01495169e+08  1.72e+05 2.30e+01  3.11e+05     0s
   2   1.95350136e+08 -5.01495169e+08  1.72e+05 2.30e+01  3.11e+05     0s
   3   2.35665817e+08 -3.33995804e+11  1.74e+07 1.28e+01  1.60e+09     0s
   4   4.54642835e+08 -2.77114230e+11  2.38e+05 1.07e+02  2.80e+08     0s
   5   4.61947166e+08 -4.35776049e+10  3.55e+04 1.54e+01  4.07e+07     0s
   6   4.63237013e+08 -3.87864779e+09  2.31e+03 2.58e+00  4.75e+05     0s
   7   4.63190632e+08 -3.87876595e+09  2.31e+03 1.66e+02  4.73e+05     0s
   8   4.63190632e+08 -3.87876595e+09  2.31e+03 1.66e+02  4.73e+05     0s
   9   4.63190632e+08 -3.87876595e+09  2.31e+03 1.66e+02  4.73e+05     0s
  10   4.63190632e+08 -3.87876595e+09  2.31e+03 1.66e+02  4.73e+05     0s
  11   2.35665817e+08 -3.33995804e+11  1.74e+07 1.28e+01  1.60e+09     0s
  12   1.00370744e+08 -2.16636808e+10  2.60e+05 6.09e+01  4.53e+07     0s
  13   8.51941074e+07 -2.51196387e+09  2.16e+04 7.09e+00  2.72e+06     0s
  14   2.50496348e+07 -1.26018559e+08  7.97e+01 1.59e+00  7.89e+04     1s
  15   2.50502697e+07 -1.26018875e+08  7.97e+01 8.50e+01  7.87e+04     1s
  16   6.35222335e+06 -9.49954448e+07  2.50e+01 6.74e+01  4.68e+04     1s
  17   6.35173853e+06 -9.49973547e+07  2.50e+01 2.51e+02  4.66e+04     1s
  18   6.34944948e+06 -9.50119139e+07  2.50e+01 4.16e+02  4.62e+04     1s
  19   6.34944948e+06 -9.50119139e+07  2.50e+01 4.16e+02  4.62e+04     1s
  20   6.34944948e+06 -9.50119139e+07  2.50e+01 4.16e+02  4.62e+04     1s

Barrier performed 20 iterations in 0.70 seconds (0.81 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   32306   -3.0402913e+07   0.000000e+00   0.000000e+00      3s

Solved in 32306 iterations and 3.36 seconds (7.19 work units)
Optimal objective -3.040291342e+07

(CVXPY) May 02 09:07:03 PM: Problem status: optimal
(CVXPY) May 02 09:07:03 PM: Optimal value: -3.040e+07
(CVXPY) May 02 09:07:03 PM: Compilation took 1.022e+02 seconds
(CVXPY) May 02 09:07:03 PM: Solver (including time spent in interface) took 3.607e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 5/10 (start=7877) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:07:08 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:07:10 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:07:10 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:07:10 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:07:10 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:07:11 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:07:11 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:07:11 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:07:11 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:07:16 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:07:52 PM: Applying reduction GUROBI
(CVXPY) May 02 09:07:52 PM: Finished problem compilation (took 4.264e+01 seconds).
(CVXPY) May 02 09:07:52 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x34d5bfff
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 46000 rows and 2796 columns
Presolve time: 0.08s
Presolved: 23501 rows, 31727 columns, 83635 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.064e+04
 Factor NZ  : 8.441e+04 (roughly 23 MB of memory)
 Factor Ops : 5.329e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.90484956e+07 -3.75723475e+08  7.78e+05 1.23e+03  9.95e+05     0s
   1  -2.70087017e+07 -1.84616173e+08  5.06e+04 7.77e+01  7.02e+04     0s
   2  -1.60877978e+07 -5.70658743e+07  2.64e+03 5.70e+00  6.35e+03     0s
   3  -2.37857047e+07 -3.03643673e+07  2.81e+02 4.14e+00  5.54e+02     0s
   4  -2.64107815e+07 -2.89715790e+07  1.04e+02 2.39e+00  1.82e+02     0s
   5  -2.71250929e+07 -2.87380386e+07  6.73e+01 8.60e-01  1.10e+02     0s
   6  -2.76512959e+07 -2.86496751e+07  4.06e+01 4.19e-01  6.67e+01     0s
   7  -2.81408552e+07 -2.85927385e+07  1.72e+01 2.52e-01  2.97e+01     0s
   8  -2.84029900e+07 -2.85649528e+07  5.74e+00 5.82e-02  1.05e+01     0s
   9  -2.84985156e+07 -2.85604723e+07  2.06e+00 2.51e-02  4.01e+00     0s
  10  -2.85341627e+07 -2.85582027e+07  7.28e-01 5.48e-02  1.55e+00     0s
  11  -2.85441636e+07 -2.85576919e+07  3.91e-01 2.13e-02  8.73e-01     0s
  12  -2.85551321e+07 -2.85570073e+07  3.41e-02 4.02e-02  1.20e-01     0s
  13  -2.85556707e+07 -2.85567789e+07  1.96e-02 2.37e-02  7.09e-02     0s
  14  -2.85558885e+07 -2.85566623e+07  1.33e-02 1.53e-02  4.95e-02     0s
  15  -2.85561174e+07 -2.85565608e+07  7.29e-03 9.61e-03  2.83e-02     0s
  16  -2.85562137e+07 -2.85565024e+07  4.67e-03 6.66e-03  1.84e-02     0s
  17  -2.85562646e+07 -2.85564915e+07  3.27e-03 5.94e-03  1.45e-02     0s
  18  -2.85563057e+07 -2.85564650e+07  2.17e-03 4.28e-03  1.01e-02     0s
  19  -2.85563441e+07 -2.85564467e+07  1.19e-03 3.16e-03  6.53e-03     0s
  20  -2.85563595e+07 -2.85564398e+07  8.06e-04 2.75e-03  5.10e-03     0s
  21  -2.85563669e+07 -2.85564279e+07  6.24e-04 2.03e-03  3.88e-03     0s
  22  -2.85563716e+07 -2.85564197e+07  5.11e-04 1.52e-03  3.06e-03     0s
  23  -2.85563797e+07 -2.85564148e+07  3.13e-04 1.26e-03  2.23e-03     0s
  24  -2.85563835e+07 -2.85564078e+07  2.23e-04 8.80e-04  1.54e-03     0s
  25  -2.85563853e+07 -2.85564054e+07  1.82e-04 7.31e-04  1.27e-03     0s
  26  -2.85563876e+07 -2.85564049e+07  1.33e-04 6.99e-04  1.09e-03     0s
  27  -2.85563888e+07 -2.85564002e+07  1.07e-04 4.13e-04  7.25e-04     0s
  28  -2.85563899e+07 -2.85563984e+07  7.99e-05 3.00e-04  5.37e-04     0s
  29  -2.85563904e+07 -2.85563981e+07  6.99e-05 2.82e-04  4.90e-04     0s
  30  -2.85563916e+07 -2.85563970e+07  4.44e-05 1.97e-04  3.43e-04     0s
  31  -2.85563926e+07 -2.85563959e+07  2.21e-05 1.25e-04  2.06e-04     0s
  32  -2.85563931e+07 -2.85563954e+07  1.27e-05 9.74e-05  1.48e-04     0s
  33  -2.85563933e+07 -2.85563949e+07  9.22e-06 6.39e-05  1.01e-04     0s
  34  -2.85563935e+07 -2.85563944e+07  5.93e-06 3.15e-05  5.65e-05     0s
  35  -2.85563938e+07 -2.85563943e+07  9.07e-07 2.85e-05  3.49e-05     1s
  36  -2.85563938e+07 -2.85563941e+07  1.07e-05 1.69e-05  1.86e-05     1s
  37  -2.85563938e+07 -2.85563940e+07  3.26e-06 1.27e-05  1.28e-05     1s
  38  -2.85563938e+07 -2.85563940e+07  1.60e-06 9.88e-06  1.02e-05     1s
  39  -2.85563938e+07 -2.85563940e+07  1.30e-06 1.52e-05  9.51e-06     1s
  40  -2.85563938e+07 -2.85563939e+07  8.01e-08 1.36e-05  2.00e-06     1s
  41  -2.85563938e+07 -2.85563938e+07  7.85e-07 1.39e-06  4.57e-07     1s
  42  -2.85563938e+07 -2.85563938e+07  3.63e-07 3.74e-08  8.99e-08     1s
  43  -2.85563938e+07 -2.85563938e+07  1.16e-10 8.73e-11  5.33e-10     1s

Barrier solved model in 43 iterations and 0.59 seconds (0.60 work units)
Optimal objective -2.85563938e+07

Crossover log...

    4026 DPushes remaining with DInf 0.0000000e+00                 1s
       0 DPushes remaining with DInf 0.0000000e+00                 1s

       3 PPushes remaining with PInf 0.0000000e+00                 1s
       0 PPushes remaining with PInf 0.0000000e+00                 1s

  Push phase complete: Pinf 0.0000000e+00, Dinf 5.4079024e-03      1s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    3312   -2.8556394e+07   0.000000e+00   5.407902e-03      1s

Solved with barrier
    3313   -2.8556394e+07   0.000000e+00   0.000000e+00      1s

Solved in 3313 iterations and 0.71 seconds (0.77 work units)
Optimal objective -2.855639384e+07

(CVXPY) May 02 09:07:54 PM: Problem status: optimal
(CVXPY) May 02 09:07:54 PM: Optimal value: -2.856e+07
(CVXPY) May 02 09:07:54 PM: Compilation took 4.264e+01 seconds
(CVXPY) May 02 09:07:54 PM: Solver (including time spent in interface) took 8.555e-01 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:08:00 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:08:03 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:08:03 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:08:03 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:08:03 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:08:06 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:08:06 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:08:06 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:08:11 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:08:22 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:09:50 PM: Applying reduction GUROBI
(CVXPY) May 02 09:09:50 PM: Finished problem compilation (took 1.068e+02 seconds).
(CVXPY) May 02 09:09:50 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0xb8feecbb
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [5e-05, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 69000 rows and 2796 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55228 columns, 179747 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.860e+05
 Factor NZ  : 2.873e+05 (roughly 40 MB of memory)
 Factor Ops : 3.169e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.39102915e+08 -9.01405041e+08  1.79e+07 1.28e+01  8.88e+06     0s
   1   1.93882178e+08 -3.83485256e+08  1.14e+05 1.90e+01  5.12e+05     0s
   2   1.93882178e+08 -3.83485256e+08  1.14e+05 1.90e+01  5.12e+05     0s
   3   2.39102915e+08 -1.60979769e+11  1.79e+07 1.28e+01  1.65e+09     0s
   4   4.27119135e+08 -1.36786474e+11  2.15e+05 1.08e+02  2.84e+08     0s
   5   4.33196660e+08 -2.72517462e+10  4.94e+04 2.11e+01  5.64e+07     0s
   6   4.38416957e+08 -3.44036258e+09  2.78e+03 4.53e-01  1.63e+06     0s
   7   4.38416957e+08 -3.44036258e+09  2.78e+03 4.53e-01  1.63e+06     0s
   8   4.38416957e+08 -3.44036258e+09  2.78e+03 4.53e-01  1.63e+06     0s
   9   4.38416957e+08 -3.44036258e+09  2.78e+03 4.53e-01  1.63e+06     0s
  10   4.38416957e+08 -3.44036258e+09  2.78e+03 4.53e-01  1.63e+06     0s
  11   2.39102915e+08 -1.60979769e+11  1.79e+07 1.28e+01  1.65e+09     0s
  12   9.07474061e+07 -1.47311365e+10  2.26e+05 7.59e+01  6.21e+07     0s
  13   8.30044798e+07 -1.73015137e+09  1.10e+04 9.14e+00  4.17e+06     0s
  14   3.88989594e+07 -1.04073716e+08  2.08e+02 7.72e-01  2.10e+05     0s
  15  -9.96069849e+06 -3.36206124e+07  2.06e+01 1.75e+00  9.44e+03     1s
  16  -9.96109265e+06 -3.36209500e+07  2.06e+01 1.02e+02  9.38e+03     1s
  17  -9.95826814e+06 -3.36181292e+07  2.06e+01 6.49e+02  9.20e+03     1s
  18  -9.95696682e+06 -3.36168755e+07  2.06e+01 7.63e+02  9.03e+03     1s
  19  -9.95745637e+06 -3.36172240e+07  2.06e+01 1.11e+03  8.85e+03     1s
  20  -9.95681932e+06 -3.36166276e+07  2.06e+01 1.15e+03  8.71e+03     1s
  21  -9.95597370e+06 -3.36158062e+07  2.06e+01 1.16e+03  8.56e+03     1s
  22  -9.95607902e+06 -3.36158850e+07  2.06e+01 1.15e+03  8.55e+03     1s
  23  -9.95595604e+06 -3.36158695e+07  2.06e+01 1.14e+03  8.55e+03     1s
  24  -9.95595604e+06 -3.36158695e+07  2.06e+01 1.14e+03  8.54e+03     1s
  25  -9.95628927e+06 -3.36162489e+07  2.06e+01 9.16e+02  8.29e+03     1s
  26  -9.95628927e+06 -3.36162489e+07  2.06e+01 9.16e+02  8.28e+03     1s
  27  -9.95628927e+06 -3.36162489e+07  2.06e+01 9.16e+02  8.28e+03     1s
  28  -9.95625162e+06 -3.36162489e+07  2.06e+01 9.16e+02  8.28e+03     1s

Barrier performed 28 iterations in 0.94 seconds (1.15 work units)
Numerical trouble encountered


Solved with primal simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   52531   -3.1132784e+07   0.000000e+00   0.000000e+00      4s

Solved in 52531 iterations and 3.68 seconds (8.65 work units)
Optimal objective -3.113278427e+07

(CVXPY) May 02 09:09:55 PM: Problem status: optimal
(CVXPY) May 02 09:09:55 PM: Optimal value: -3.113e+07
(CVXPY) May 02 09:09:55 PM: Compilation took 1.068e+02 seconds
(CVXPY) May 02 09:09:55 PM: Solver (including time spent in interface) took 3.931e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 6/10 (start=6833) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:10:00 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:10:01 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:10:01 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:10:01 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:10:01 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:10:03 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:10:03 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:10:03 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:10:03 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:10:07 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:10:46 PM: Applying reduction GUROBI
(CVXPY) May 02 09:10:46 PM: Finished problem compilation (took 4.436e+01 seconds).
(CVXPY) May 02 09:10:46 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x4326b1cc
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-02, 1e+05]
Presolve removed 46000 rows and 2178 columns
Presolve time: 0.07s
Presolved: 23501 rows, 32345 columns, 85489 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.249e+04
 Factor NZ  : 8.627e+04 (roughly 23 MB of memory)
 Factor Ops : 5.434e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -5.13606179e+07 -4.04566280e+08  1.08e+06 6.16e+02  5.92e+05     0s
   1  -3.65114949e+07 -1.93647703e+08  7.74e+04 3.11e+01  3.66e+04     0s
   2  -1.45143088e+07 -7.25033454e+07  5.03e+03 2.79e+00  4.36e+03     0s
   3  -2.28372411e+07 -3.19995106e+07  5.03e+02 1.54e+01  3.88e+02     0s
   4  -2.28372411e+07 -3.19995106e+07  5.03e+02 1.54e+01  3.88e+02     0s
   5  -5.13713386e+07 -3.30144838e+10  1.08e+06 1.14e-13  5.23e+07     0s
   6  -1.44029475e+07 -2.98450615e+10  4.56e+04 3.06e+01  4.14e+06     0s
   7   5.54908113e+06 -6.02546731e+09  5.46e+02 2.51e+00  3.68e+05     0s
   8   1.61738969e+06 -9.86235013e+07  7.06e-01 8.03e-01  3.71e+03     0s
   9   1.61738969e+06 -9.86235013e+07  7.06e-01 8.03e-01  3.71e+03     0s
  10   1.61738969e+06 -9.86235013e+07  7.06e-01 8.03e-01  3.71e+03     0s
  11   1.61738969e+06 -9.86235013e+07  7.06e-01 8.03e-01  3.71e+03     0s
  12  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  13  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  14  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  15  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  16  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  17  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  18  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  19  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  20  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  21  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s
  22  -3.67022349e+06 -4.93668458e+07  2.51e-01 6.25e-02  1.42e+03     0s

Barrier performed 22 iterations in 0.45 seconds (0.48 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10399   -2.8711475e+07   0.000000e+00   0.000000e+00      1s

Solved in 10399 iterations and 1.02 seconds (1.82 work units)
Optimal objective -2.871147535e+07

(CVXPY) May 02 09:10:48 PM: Problem status: optimal
(CVXPY) May 02 09:10:48 PM: Optimal value: -2.871e+07
(CVXPY) May 02 09:10:48 PM: Compilation took 4.436e+01 seconds
(CVXPY) May 02 09:10:48 PM: Solver (including time spent in interface) took 1.167e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:10:54 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:10:58 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:10:58 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:10:58 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:10:58 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:11:00 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:11:00 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:11:00 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:11:04 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:11:15 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:12:44 PM: Applying reduction GUROBI
(CVXPY) May 02 09:12:44 PM: Finished problem compilation (took 1.064e+02 seconds).
(CVXPY) May 02 09:12:44 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x6b9b41a8
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [2e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-02, 1e+05]
Presolve removed 69000 rows and 2178 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55846 columns, 183455 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.934e+05
 Factor NZ  : 2.857e+05 (roughly 40 MB of memory)
 Factor Ops : 2.942e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.73642700e+08 -1.53298864e+09  2.47e+07 1.28e+01  8.03e+06     0s
   1   3.00854274e+08 -6.38405316e+08  1.86e+05 7.35e-01  4.14e+05     0s
   2   3.00854274e+08 -6.38405316e+08  1.86e+05 7.35e-01  4.14e+05     0s
   3   3.73642700e+08 -4.21784335e+11  2.47e+07 1.28e+01  2.28e+09     0s
   4   6.82698941e+08 -3.63081726e+11  2.51e+05 1.07e+02  3.89e+08     0s
   5   6.90940508e+08 -5.75998373e+10  6.99e+04 1.82e+01  6.70e+07     0s
   6   6.90940297e+08 -5.75999146e+10  6.99e+04 1.69e+03  6.69e+07     0s
   7   8.22745809e+08 -5.74842389e+10  5.02e+04 1.50e+03  7.27e+07     0s
   8   8.10007994e+08 -9.60174940e+09  3.31e+03 1.07e+02  6.61e+06     0s
   9   8.10007994e+08 -9.60174940e+09  3.31e+03 1.07e+02  6.61e+06     0s
  10   8.10007994e+08 -9.60174940e+09  3.31e+03 1.07e+02  6.61e+06     0s
  11   3.73642700e+08 -4.21784335e+11  2.47e+07 1.28e+01  2.28e+09     0s
  12   1.47802663e+08 -3.39626851e+10  2.36e+05 6.89e+01  7.36e+07     0s
  13   1.47184224e+08 -5.37245617e+09  1.67e+04 1.08e+01  6.91e+06     0s
  14   1.02869912e+08 -3.20668577e+08  7.11e+02 1.34e+00  3.99e+05     0s
  15   1.02867092e+08 -3.20662956e+08  7.11e+02 3.59e+02  3.96e+05     1s
  16   1.02839043e+08 -3.20713768e+08  7.11e+02 8.02e+02  3.93e+05     1s
  17   1.02822338e+08 -3.20771786e+08  7.11e+02 1.75e+02  3.86e+05     1s
  18   1.02826706e+08 -3.20783958e+08  7.11e+02 1.75e+02  3.75e+05     1s
  19   5.04615019e+07 -1.82751497e+08  3.28e+02 1.31e+02  1.53e+05     1s
  20   5.04360249e+07 -1.82830565e+08  3.28e+02 1.06e+03  1.52e+05     1s
  21   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  22   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  23   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  24   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  25   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  26   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  27   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  28   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s
  29   5.04347398e+07 -1.82830093e+08  3.28e+02 1.29e+03  1.51e+05     1s

Barrier performed 29 iterations in 0.97 seconds (1.14 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   29781   -3.1292810e+07   0.000000e+00   0.000000e+00      4s

Solved in 29781 iterations and 3.84 seconds (8.32 work units)
Optimal objective -3.129280982e+07

(CVXPY) May 02 09:12:49 PM: Problem status: optimal
(CVXPY) May 02 09:12:49 PM: Optimal value: -3.129e+07
(CVXPY) May 02 09:12:49 PM: Compilation took 1.064e+02 seconds
(CVXPY) May 02 09:12:49 PM: Solver (including time spent in interface) took 4.089e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 7/10 (start=5282) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:12:54 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:12:56 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:12:56 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:12:56 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:12:56 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:12:57 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:12:57 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:12:57 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:12:57 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:13:02 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:13:39 PM: Applying reduction GUROBI
(CVXPY) May 02 09:13:39 PM: Finished problem compilation (took 4.321e+01 seconds).
(CVXPY) May 02 09:13:39 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x3b9e0285
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 46000 rows and 2797 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31726 columns, 83632 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.063e+04
 Factor NZ  : 8.441e+04 (roughly 23 MB of memory)
 Factor Ops : 5.329e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.87275572e+07 -3.76502469e+08  7.73e+05 6.13e+02  5.00e+05     0s
   1  -2.67923188e+07 -1.86445491e+08  5.83e+04 4.13e+01  3.86e+04     0s
   2  -1.61560213e+07 -6.64716063e+07  2.01e+03 3.72e+00  4.26e+03     0s
   3  -2.30747961e+07 -3.06806588e+07  1.61e+02 3.37e+00  3.40e+02     0s
   4  -2.41135542e+07 -2.90069786e+07  1.28e+02 7.87e-01  1.73e+02     0s
   5  -2.41135542e+07 -2.90069786e+07  1.28e+02 7.87e-01  1.73e+02     0s
   6  -3.87349845e+07 -2.64915758e+10  7.74e+05 1.14e-13  3.75e+07     0s
   7  -1.20928579e+07 -2.48080211e+10  3.05e+04 3.18e+01  3.08e+06     0s
   8  -1.28020478e+06 -2.50075280e+09  4.18e+02 1.81e+00  9.36e+04     0s
   9  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s
  10  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s
  11  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s
  12  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s
  13  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s
  14  -1.32514884e+07 -8.93320474e+07  1.92e+00 4.03e+00  2.48e+03     0s

Barrier performed 14 iterations in 0.30 seconds (0.29 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10707   -2.8542171e+07   0.000000e+00   0.000000e+00      1s

Solved in 10707 iterations and 1.06 seconds (1.97 work units)
Optimal objective -2.854217080e+07

(CVXPY) May 02 09:13:41 PM: Problem status: optimal
(CVXPY) May 02 09:13:41 PM: Optimal value: -2.854e+07
(CVXPY) May 02 09:13:41 PM: Compilation took 4.321e+01 seconds
(CVXPY) May 02 09:13:41 PM: Solver (including time spent in interface) took 1.203e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:13:47 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:13:50 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:13:50 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:13:50 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:13:50 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:13:53 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:13:53 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:13:53 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:13:58 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:14:09 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:15:30 PM: Applying reduction GUROBI
(CVXPY) May 02 09:15:30 PM: Finished problem compilation (took 1.003e+02 seconds).
(CVXPY) May 02 09:15:30 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x7dd5078d
Coefficient statistics:
  Matrix range     [8e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e-02, 1e+05]
Presolve removed 69000 rows and 2797 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55227 columns, 179741 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.860e+05
 Factor NZ  : 2.873e+05 (roughly 40 MB of memory)
 Factor Ops : 3.170e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.40511488e+08 -8.90480496e+08  1.78e+07 6.40e+00  4.42e+06     0s
   1   2.26654177e+08 -8.50770462e+08  1.68e+07 9.38e+02  3.99e+06     0s
   2   2.02880891e+08 -4.12953019e+08  2.82e+05 3.49e+02  3.53e+05     0s
   3   2.02880891e+08 -4.12953019e+08  2.82e+05 3.49e+02  3.53e+05     0s
   4   2.40511488e+08 -3.18684172e+11  1.78e+07 6.40e+00  1.65e+09     0s
   5   3.83193233e+08 -2.76398849e+11  7.62e+05 2.12e+02  5.21e+08     0s
   6   3.89067706e+08 -5.62199413e+10  1.85e+05 3.30e+01  8.27e+07     0s
   7   4.14549975e+08 -1.25912611e+10  6.71e+03 5.58e+00  2.92e+06     0s
   8   4.14548632e+08 -1.25912473e+10  6.71e+03 6.21e+02  2.89e+06     0s
   9   4.14548632e+08 -1.25912473e+10  6.71e+03 6.21e+02  2.89e+06     0s
  10   4.14548632e+08 -1.25912473e+10  6.71e+03 6.21e+02  2.89e+06     0s
  11   2.40511488e+08 -3.18684172e+11  1.78e+07 6.40e+00  1.65e+09     0s
  12   9.12805380e+07 -2.94292121e+10  2.54e+05 7.53e+01  6.25e+07     0s
  13   8.23574548e+07 -3.53191878e+09  1.16e+04 9.10e+00  4.15e+06     0s
  14   4.87108845e+07 -1.71651571e+08  2.12e+02 7.26e-01  1.77e+05     1s
  15   2.51471366e+07 -9.19571820e+07  9.54e+01 1.92e+02  7.46e+04     1s
  16   2.51469379e+07 -9.19570591e+07  9.54e+01 2.06e+02  7.46e+04     1s
  17   2.51469379e+07 -9.19570591e+07  9.54e+01 2.06e+02  7.46e+04     1s
  18  -1.86453971e+07 -3.46656033e+07  1.34e+01 2.80e+01  3.96e+03     1s
  19  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.20e+02     1s
  20  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.20e+02     1s
  21  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.20e+02     1s
  22  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  23  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  24  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  25  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  26  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  27  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  28  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s
  29  -2.90033233e+07 -3.15315213e+07  2.41e+00 3.00e+00  2.19e+02     1s

Barrier performed 29 iterations in 1.04 seconds (1.27 work units)
Sub-optimal termination - objective -2.90033233e+07

Crossover log...

   46910 DPushes remaining with DInf 0.0000000e+00                 1s
       0 DPushes remaining with DInf 0.0000000e+00                 2s

   54214 PPushes remaining with PInf 0.0000000e+00                 2s
       0 PPushes remaining with PInf 0.0000000e+00                 2s

  Push phase complete: Pinf 0.0000000e+00, Dinf 1.7405019e+03      2s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   89278   -3.1103436e+07   0.000000e+00   1.740502e+03      2s

Solved with barrier
  105452   -3.1122236e+07   0.000000e+00   0.000000e+00      4s

Solved in 105452 iterations and 3.85 seconds (7.53 work units)
Optimal objective -3.112223616e+07

(CVXPY) May 02 09:15:35 PM: Problem status: optimal
(CVXPY) May 02 09:15:35 PM: Optimal value: -3.112e+07
(CVXPY) May 02 09:15:35 PM: Compilation took 1.003e+02 seconds
(CVXPY) May 02 09:15:35 PM: Solver (including time spent in interface) took 4.105e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 8/10 (start=6916) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:15:41 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:15:42 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:15:42 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:15:42 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:15:42 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:15:44 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:15:44 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:15:44 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:15:44 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:15:48 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:16:27 PM: Applying reduction GUROBI
(CVXPY) May 02 09:16:27 PM: Finished problem compilation (took 4.463e+01 seconds).
(CVXPY) May 02 09:16:27 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0xadc14120
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2662 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31861 columns, 84037 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.104e+04
 Factor NZ  : 8.481e+04 (roughly 23 MB of memory)
 Factor Ops : 5.351e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -4.15681806e+07 -3.68618443e+08  8.77e+05 6.13e+02  5.20e+05     0s
   1  -2.89597111e+07 -1.86006715e+08  5.83e+04 4.76e+01  4.01e+04     0s
   2  -1.58405823e+07 -7.84234294e+07  3.48e+03 1.12e+01  8.15e+03     0s
   3  -2.12905480e+07 -3.31618439e+07  4.50e+02 1.13e+00  8.26e+02     0s
   4  -2.33619256e+07 -2.97259074e+07  2.91e+02 2.00e+00  2.99e+02     0s
   5  -2.70035773e+07 -2.88468123e+07  5.39e+01 1.37e+00  6.86e+01     0s
   6  -2.70035773e+07 -2.88468123e+07  5.39e+01 1.37e+00  6.86e+01     0s
   7  -4.15764017e+07 -2.80881132e+10  8.78e+05 1.14e-13  4.24e+07     0s
   8  -7.31225546e+06 -2.62106259e+10  1.73e+04 1.28e+01  2.02e+06     0s
   9  -3.87144873e+04 -1.50238446e+09  2.13e+02 1.25e+00  5.33e+04     0s
  10  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s
  11  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s
  12  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s
  13  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s
  14  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s
  15  -1.71549222e+07 -5.27096527e+07  7.50e+00 5.61e+00  1.17e+03     0s

Barrier performed 15 iterations in 0.29 seconds (0.30 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10526   -2.8504140e+07   0.000000e+00   0.000000e+00      1s

Solved in 10526 iterations and 1.04 seconds (1.98 work units)
Optimal objective -2.850414014e+07

(CVXPY) May 02 09:16:29 PM: Problem status: optimal
(CVXPY) May 02 09:16:29 PM: Optimal value: -2.850e+07
(CVXPY) May 02 09:16:29 PM: Compilation took 4.463e+01 seconds
(CVXPY) May 02 09:16:29 PM: Solver (including time spent in interface) took 1.183e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:16:34 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:16:38 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:16:38 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:16:38 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:16:38 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:16:41 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:16:41 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:16:41 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:16:45 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:16:56 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:18:24 PM: Applying reduction GUROBI
(CVXPY) May 02 09:18:24 PM: Finished problem compilation (took 1.058e+02 seconds).
(CVXPY) May 02 09:18:24 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0x59b458cc
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 7e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2662 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55362 columns, 180551 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.876e+05
 Factor NZ  : 2.881e+05 (roughly 40 MB of memory)
 Factor Ops : 3.155e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.03083611e+08 -1.28645116e+09  1.99e+07 1.28e+01  6.67e+06     0s
   1   2.46911953e+08 -5.41281369e+08  1.46e+05 8.44e+00  3.51e+05     0s
   2   2.46895902e+08 -5.41282122e+08  1.46e+05 2.44e+02  3.51e+05     0s
   3   2.65548513e+08 -2.05574014e+08  6.13e+04 8.06e+01  1.08e+05     0s
   4   2.65548513e+08 -2.05574014e+08  6.13e+04 8.06e+01  1.08e+05     0s
   5   3.03083611e+08 -3.43759762e+11  1.99e+07 1.28e+01  1.84e+09     0s
   6   5.04502253e+08 -3.01805191e+11  5.91e+05 1.92e+02  5.20e+08     0s
   7   5.11219025e+08 -5.74025028e+10  1.23e+05 3.06e+01  8.36e+07     0s
   8   5.38128929e+08 -1.31419960e+10  4.38e+03 4.22e+00  3.61e+06     0s
   9   5.38129157e+08 -1.31419720e+10  4.38e+03 4.46e+02  3.57e+06     0s
  10   6.84479458e+08 -7.53181226e+09  2.54e+03 3.86e+01  1.06e+06     0s
  11   6.84479458e+08 -7.53181226e+09  2.54e+03 3.86e+01  1.06e+06     0s
  12   6.84479458e+08 -7.53181226e+09  2.54e+03 3.86e+01  1.06e+06     0s
  13   3.03083611e+08 -3.43759762e+11  1.99e+07 1.28e+01  1.84e+09     0s
  14   1.19257074e+08 -2.87415499e+10  2.38e+05 6.79e+01  6.18e+07     0s
  15   1.07116987e+08 -3.59307017e+09  1.43e+04 8.41e+00  4.32e+06     0s
  16   7.44768853e+07 -2.12931637e+08  6.42e+02 1.07e+00  2.54e+05     1s
  17   7.44724023e+07 -2.12928661e+08  6.42e+02 1.34e+02  2.53e+05     1s
  18   2.02713085e+06 -5.39812824e+07  9.47e+01 3.96e+01  2.49e+04     1s
  19   2.02552917e+06 -5.39827808e+07  9.47e+01 1.27e+02  2.45e+04     1s
  20   2.02488120e+06 -5.39829485e+07  9.47e+01 7.58e+02  2.41e+04     1s
  21   2.02130334e+06 -5.39863895e+07  9.47e+01 1.27e+03  2.34e+04     1s
  22   2.01792283e+06 -5.39895508e+07  9.47e+01 1.23e+03  2.31e+04     1s
  23   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s
  24   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s
  25   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s
  26   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s
  27   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s
  28   2.01665069e+06 -5.39903987e+07  9.47e+01 1.08e+03  2.28e+04     1s

Barrier performed 28 iterations in 0.90 seconds (1.05 work units)
Numerical trouble encountered


Solved with primal simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   55535   -3.1068866e+07   0.000000e+00   0.000000e+00      4s

Solved in 55535 iterations and 4.13 seconds (9.52 work units)
Optimal objective -3.106886582e+07

(CVXPY) May 02 09:18:29 PM: Problem status: optimal
(CVXPY) May 02 09:18:29 PM: Optimal value: -3.107e+07
(CVXPY) May 02 09:18:29 PM: Compilation took 1.058e+02 seconds
(CVXPY) May 02 09:18:29 PM: Solver (including time spent in interface) took 4.382e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 9/10 (start=6330) done.
the shapes of probs, mc_g_i, mv_d_j, g_i_bar, d_j_bar are (500,), (22,), (1,), (500, 22), (500, 1)

/opt/anaconda3/envs/csci2470/lib/python3.11/site-packages/cvxpy/problems/problem.py:167: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "

===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:18:35 PM: Your problem has 11523 variables, 23501 constraints, and 0 parameters.
(CVXPY) May 02 09:18:36 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:18:36 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:18:36 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:18:36 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:18:38 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:18:38 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:18:38 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 02 09:18:38 PM: Applying reduction Qp2SymbolicQp

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:18:43 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:19:22 PM: Applying reduction GUROBI
(CVXPY) May 02 09:19:22 PM: Finished problem compilation (took 4.567e+01 seconds).
(CVXPY) May 02 09:19:22 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 69501 rows, 34523 columns and 138023 nonzeros
Model fingerprint: 0x4c161103
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 46000 rows and 2889 columns
Presolve time: 0.07s
Presolved: 23501 rows, 31634 columns, 83356 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 23
 Free vars  : 23
 AA' NZ     : 6.036e+04
 Factor NZ  : 8.413e+04 (roughly 23 MB of memory)
 Factor Ops : 5.313e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.88917748e+07 -3.93598479e+08  7.27e+05 6.12e+02  4.71e+05     0s
   1  -2.82541469e+07 -1.80224813e+08  6.04e+04 4.14e+01  3.62e+04     0s
   2  -1.60009172e+07 -6.55436345e+07  1.59e+03 3.25e+00  3.94e+03     0s
   3  -2.28075149e+07 -2.95151134e+07  9.43e+01 5.13e+00  2.75e+02     0s
   4  -2.28075149e+07 -2.95151134e+07  9.43e+01 5.13e+00  2.75e+02     0s
   5  -3.88993685e+07 -2.76676562e+10  7.27e+05 1.14e-13  3.53e+07     0s
   6  -1.34165141e+07 -2.40513739e+10  3.13e+04 3.24e+01  3.00e+06     0s
   7  -1.99868573e+06 -3.22037166e+09  4.80e+02 1.67e+00  1.71e+05     0s
   8  -6.73621660e+06 -9.97926517e+07  1.20e-01 1.93e+00  3.67e+03     0s
   9  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s
  10  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s
  11  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s
  12  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s
  13  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s
  14  -2.18574127e+07 -3.25190178e+07  3.84e-03 2.61e-01  3.84e+02     0s

Barrier performed 14 iterations in 0.30 seconds (0.29 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10864   -2.7896521e+07   0.000000e+00   0.000000e+00      1s

Solved in 10864 iterations and 1.04 seconds (1.91 work units)
Optimal objective -2.789652141e+07

(CVXPY) May 02 09:19:24 PM: Problem status: optimal
(CVXPY) May 02 09:19:24 PM: Optimal value: -2.790e+07
(CVXPY) May 02 09:19:24 PM: Compilation took 4.567e+01 seconds
(CVXPY) May 02 09:19:24 PM: Solver (including time spent in interface) took 1.181e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.7.1
===============================================================================

(CVXPY) May 02 09:19:30 PM: Your problem has 12024 variables, 24001 constraints, and 0 parameters.
(CVXPY) May 02 09:19:33 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 02 09:19:33 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 02 09:19:33 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) May 02 09:19:33 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) May 02 09:19:35 PM: Compiling problem (target solver=GUROBI).
(CVXPY) May 02 09:19:35 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI
(CVXPY) May 02 09:19:35 PM: Applying reduction CvxAttr2Constr

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) May 02 09:19:41 PM: Applying reduction Qp2SymbolicQp
(CVXPY) May 02 09:19:52 PM: Applying reduction QpMatrixStuffing
(CVXPY) May 02 09:21:18 PM: Applying reduction GUROBI
(CVXPY) May 02 09:21:18 PM: Finished problem compilation (took 1.052e+02 seconds).
(CVXPY) May 02 09:21:18 PM: Invoking solver GUROBI  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
Set parameter OutputFlag to value 1
Set parameter QCPDual to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.6.0 24G325)

CPU model: Apple M3 Pro
Thread count: 11 physical cores, 11 logical processors, using up to 11 threads

Non-default parameters:
QCPDual  1

Optimize a model with 116001 rows, 58024 columns and 265523 nonzeros
Model fingerprint: 0xf0fc83b4
Coefficient statistics:
  Matrix range     [9e-01, 1e+03]
  Objective range  [1e-04, 8e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-02, 1e+05]
Presolve removed 69000 rows and 2889 columns
Presolve time: 0.08s
Presolved: 47001 rows, 55135 columns, 179189 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.01s

Barrier statistics:
 Dense cols : 24
 Free vars  : 24
 AA' NZ     : 1.849e+05
 Factor NZ  : 2.866e+05 (roughly 40 MB of memory)
 Factor Ops : 3.172e+06 (less than 1 second per iteration)
 Threads    : 9

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   2.43203764e+08 -1.34192395e+09  1.70e+07 1.28e+01  6.05e+06     0s
   1   1.99853433e+08 -5.15917171e+08  1.75e+05 1.50e+00  3.05e+05     0s
   2   1.99853433e+08 -5.15917171e+08  1.75e+05 1.50e+00  3.05e+05     0s
   3   2.43203764e+08 -3.39065550e+11  1.70e+07 1.28e+01  1.57e+09     0s
   4   4.60747459e+08 -2.76756762e+11  2.41e+05 1.07e+02  2.76e+08     0s
   5   4.68439265e+08 -4.33578382e+10  3.57e+04 1.53e+01  3.98e+07     0s
   6   4.70110804e+08 -3.94796790e+09  2.36e+03 1.07e+00  4.71e+05     0s
   7   4.70110804e+08 -3.94796790e+09  2.36e+03 1.07e+00  4.71e+05     0s
   8   4.70110804e+08 -3.94796790e+09  2.36e+03 1.07e+00  4.71e+05     0s
   9   4.70110804e+08 -3.94796790e+09  2.36e+03 1.07e+00  4.71e+05     0s
  10   4.70110804e+08 -3.94796790e+09  2.36e+03 1.07e+00  4.71e+05     0s
  11   2.43203764e+08 -3.39065550e+11  1.70e+07 1.28e+01  1.57e+09     0s
  12   1.10476196e+08 -2.39298832e+10  2.32e+05 6.64e+01  5.13e+07     0s
  13   9.44341182e+07 -2.78972210e+09  1.56e+04 7.79e+00  3.16e+06     0s
  14   2.82829036e+07 -1.05494602e+08  5.20e+01 1.63e+00  7.37e+04     1s
  15  -1.12044083e+07 -3.29821954e+07  5.59e+00 1.72e+00  3.63e+03     1s
  16  -1.12049925e+07 -3.29809943e+07  5.59e+00 2.89e+01  3.61e+03     1s
  17  -1.12049925e+07 -3.29809943e+07  5.59e+00 2.89e+01  3.61e+03     1s
  18  -1.12049925e+07 -3.29809943e+07  5.59e+00 2.89e+01  3.61e+03     1s
  19  -1.12049925e+07 -3.29809943e+07  5.59e+00 2.89e+01  3.61e+03     1s

Barrier performed 19 iterations in 0.69 seconds (0.81 work units)
Numerical trouble encountered


Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
   32532   -3.0471343e+07   0.000000e+00   0.000000e+00      3s

Solved in 32532 iterations and 3.47 seconds (7.27 work units)
Optimal objective -3.047134291e+07

(CVXPY) May 02 09:21:22 PM: Problem status: optimal
(CVXPY) May 02 09:21:22 PM: Optimal value: -3.047e+07
(CVXPY) May 02 09:21:22 PM: Compilation took 1.052e+02 seconds
(CVXPY) May 02 09:21:22 PM: Solver (including time spent in interface) took 3.727e+00 seconds

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
Instance 10/10 (start=8061) done.

In [11]:
# Aggregate and average
keys = list(results_list[0].keys())
means = {k: np.mean([r[k] for r in results_list]) for k in keys}
stds = {k: np.std([r[k] for r in results_list]) for k in keys}

print("============== Real-data results (averaged over {} instances) ================".format(NUM_INSTANCES))
print("Distortion (DA vs E[RT price]):")
print("  Stochastic:", means["stoch_distortion"], "±", stds["stoch_distortion"])
print("  CVaR:", means["cvar_distortion"], "±", stds["cvar_distortion"])
print("  Deterministic:", means["det_distortion"], "±", stds["det_distortion"])
print("E[Social Surplus]:")
print("  Stochastic:", means["stoch_ss"], "±", stds["stoch_ss"])
print("  CVaR:", means["cvar_ss"], "±", stds["cvar_ss"])
print("  Deterministic:", means["det_ss"], "±", stds["det_ss"])
print("Tail (5%) welfare (mean positive SS in worst tail):")
print("  Stochastic:", means["stoch_tail_welfare"], "±", stds["stoch_tail_welfare"])
print("  CVaR:", means["cvar_tail_welfare"], "±", stds["cvar_tail_welfare"])
print("  Deterministic:", means["det_tail_welfare"], "±", stds["det_tail_welfare"])
print("Tail (5%) price distortion:")
print("  Stochastic:", means["stoch_tail_distortion"], "±", stds["stoch_tail_distortion"])
print("  CVaR:", means["cvar_tail_distortion"], "±", stds["cvar_tail_distortion"])
print("  Deterministic:", means["det_tail_distortion"], "±", stds["det_tail_distortion"])
print("Probability feasible:", means["prob_feasible"], "±", stds["prob_feasible"])

============== Real-data results (averaged over 10 instances) ================
Distortion (DA vs E[RT price]):
  Stochastic: 0.23495772464848413 ± 0.08514227520689172
  CVaR: 110.30767710052905 ± 0.07247882792276175
  Deterministic: 409.4383138360469 ± 20.996367717203462
E[Social Surplus]:
  Stochastic: 28477803.19968434 ± 519196.7873900413
  CVaR: 28476091.32256646 ± 519429.51649425266
  Deterministic: 27744305.276541602 ± 497276.9641682862
Tail (5%) welfare (mean positive SS in worst tail):
  Stochastic: 25853219.159818698 ± 147836.57107726368
  CVaR: 25886943.37734922 ± 142249.59942015584
  Deterministic: 25825001.32107057 ± 147080.20330728992
Tail (5%) price distortion:
  Stochastic: 100.00000000000014 ± 6.036352236328737e-13
  CVaR: 7.742803977717687e-13 ± 4.362092182180069e-13
  Deterministic: 100.0 ± 0.0
Probability feasible: 0.020406302405131072 ± 0.009687976279932476

In [12]:
summary = pd.DataFrame({
    "Method": ["Stochastic", "CVaR", "Deterministic"] * 3,
    "Metric": ["Distortion", "Distortion", "Distortion", "E[SS]", "E[SS]", "E[SS]", "Tail welfare", "Tail welfare", "Tail welfare"],
    "Mean": [
        means["stoch_distortion"], means["cvar_distortion"], means["det_distortion"],
        means["stoch_ss"], means["cvar_ss"], means["det_ss"],
        means["stoch_tail_welfare"], means["cvar_tail_welfare"], means["det_tail_welfare"],
    ],
    "Std": [
        stds["stoch_distortion"], stds["cvar_distortion"], stds["det_distortion"],
        stds["stoch_ss"], stds["cvar_ss"], stds["det_ss"],
        stds["stoch_tail_welfare"], stds["cvar_tail_welfare"], stds["det_tail_welfare"],
    ],
})
summary["Std/Mean"] = summary["Std"] / summary["Mean"]
display(summary)

          Method        Metric          Mean            Std  Std/Mean
0     Stochastic    Distortion  2.349577e-01       0.085142  0.362373
1           CVaR    Distortion  1.103077e+02       0.072479  0.000657
2  Deterministic    Distortion  4.094383e+02      20.996368  0.051281
3     Stochastic         E[SS]  2.847780e+07  519196.787390  0.018232
4           CVaR         E[SS]  2.847609e+07  519429.516494  0.018241
5  Deterministic         E[SS]  2.774431e+07  497276.964168  0.017924
6     Stochastic  Tail welfare  2.585322e+07  147836.571077  0.005718
7           CVaR  Tail welfare  2.588694e+07  142249.599420  0.005495
8  Deterministic  Tail welfare  2.582500e+07  147080.203307  0.005695

In [13]:
from pathlib import Path

LOG_DIR = Path("outputs/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

print("\n=== Summary dataframe ===")
print(summary.to_string(index=False))

with open(LOG_DIR / "summary_dataframe.log", "w") as f:
    f.write(summary.to_string(index=False))
    f.write("\n")

=== Summary dataframe ===
       Method       Metric         Mean           Std  Std/Mean
   Stochastic   Distortion 2.349577e-01      0.085142  0.362373
         CVaR   Distortion 1.103077e+02      0.072479  0.000657
Deterministic   Distortion 4.094383e+02     20.996368  0.051281
   Stochastic        E[SS] 2.847780e+07 519196.787390  0.018232
         CVaR        E[SS] 2.847609e+07 519429.516494  0.018241
Deterministic        E[SS] 2.774431e+07 497276.964168  0.017924
   Stochastic Tail welfare 2.585322e+07 147836.571077  0.005718
         CVaR Tail welfare 2.588694e+07 142249.599420  0.005495
Deterministic Tail welfare 2.582500e+07 147080.203307  0.005695